cirq-core/cirq/transformers/align.py, cirq-core/cirq/transformers/align_test.py
- Adds support to recursively run `cirq.align_left` and `cirq.align_right` transformers on circuits wrapped inside a circuit operation by setting `deep=True` in transformer context.
=> Add support for deep=True to `cirq.align_left` and `cirq.align_right` transformers

cirq-core/cirq/transformers/eject_z.py, cirq-core/cirq/transformers/eject_z_test.py
- Adds support to recursively run `cirq.eject_z` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
=> Add support for deep=True to `cirq.eject_z` transformer

cirq-core/cirq/transformers/merge_k_qubit_gates.py, cirq-core/cirq/transformers/merge_k_qubit_gates_test.py
- Adds support to recursively run `cirq.merge_k_qubit_unitaries` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
- Note that we need to abstract out `_rewrite_merged_k_qubit_unitaries` step into a separate recursive function and cannot directly pass `deep=True` in `cirq.map_operations_and_unroll` primitive because the step needs to treat newly created circuit operations tagged with `merged_circuit_op_tag` differently (rewrite using rewriter as a single connected component) vs circuit operations that existed in the circuit before the transformation stage -- for which we need to ignore them in top level merging and recursively call the transformer on the encapsulated circuit. 
=> Add support for deep=True to `cirq.merge_k_qubit_unitaries` transformer

cirq-core/cirq/transformers/merge_single_qubit_gates.py, cirq-core/cirq/transformers/merge_single_qubit_gates_test.py
- Adds support to recursively run `cirq.merge_single_qubit_moments_to_phxz` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
- Also adds tests for `cirq.merge_single_qubit_gates_to_phxz` and `cirq.merge_single_qubit_gates_to_phased_x_and_z`, both of which automatically support deep=True flag after https://github.com/quantumlib/Cirq/pull/5122
=> Add support for deep=True to merge_single_qubit_gates* transformers

cirq-core/cirq/transformers/optimize_for_target_gateset.py, cirq-core/cirq/transformers/optimize_for_target_gateset_test.py
- Adds support for `deep=True` flag to `cirq.optimize_for_target_gateset` which enables optimizing circuits preserving the sub-circuit structure (i.e. without unrolling circuit operations).
=> Add support for deep=True to `cirq.optimize_for_target_gateset` transformer

cirq-core/cirq/transformers/merge_k_qubit_gates.py, cirq-core/cirq/transformers/merge_k_qubit_gates_test.py
- Fixes a bug in `cirq.merge_k_qubit_unitaries` due to which the transformer was applied recursively only on circuit operations satisfying `cirq.num_qubits(op) <= k and cirq.has_unitary(op)`.  Fixed the bug and added more tests. 
=> Bugfix in handling of deep=True flag in `cirq.merge_k_qubit_unitaries` transformer

cirq-google/cirq_google/engine/abstract_job.py, cirq-google/cirq_google/engine/abstract_job_test.py
- Add support for next() in AbstractJob
- Changes __iter__ to return a generator, which
will have support for iteration in for loops, as well as
next().
- Also improve the iteration tests to be more thorough and accurate.
Fixes: #5120
=> Add iterator support for AbstractJob

rtd_docs/requirements.txt
=> Pin Jinja2 version for build_docs CI.

cirq-aqt/cirq_aqt/_version.py, cirq-aqt/cirq_aqt/_version_test.py, cirq-core/cirq/_version.py, cirq-core/cirq/_version_test.py, cirq-core/cirq/ops/classically_controlled_operation_test.py, cirq-google/cirq_google/_version.py, cirq-google/cirq_google/_version_test.py, cirq-ionq/cirq_ionq/_version.py, cirq-ionq/cirq_ionq/_version_test.py, cirq-pasqal/cirq_pasqal/_version.py, cirq-pasqal/cirq_pasqal/_version_test.py, cirq-rigetti/cirq_rigetti/_version.py, cirq-rigetti/cirq_rigetti/_version_test.py, cirq-web/cirq_web/_version.py, cirq-web/cirq_web/_version_test.py
Bumps working version to v0.15.0
=> Bump cirq version to 0.15.0

cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/ops/clifford_gate_test.py
Looks like copy-pasta errors to me.
Also update a test to being parameterized and complete.
=> Fix broken caching in CliffordGate and add test

docs/noise.ipynb
- Part of docs cleanup effort in preparation of Cirq 1.0 launch. 
- Maybe @95-martin-orion can add more details about `NoiseProperties` and realistic device noise once the work is done.
=> Cleanup docs/noise.ipynb in preparation for Cirq 1.0 launch

cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_sqrt_iswap_test.py
This test was the slowest that we run, 45 seconds, so I cut down on the parameterized range.  @tanujkhattar
=> Speed up a slow transformer test

check/pylint, check/pylint-changed-files, dev_tools/bash_scripts_test.py
On my local machine this took pylint from 3 minutes to less than one.
=> Make pylint parallel

dev_tools/requirements/deps/format.txt
Version [22.1.0](https://black.readthedocs.io/en/latest/change_log.html#id1) is the first non-beta version of black and has a new [stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy). The last time we bumped the black version in https://github.com/quantumlib/Cirq/pull/4753 we did not actually reformat any code, so we could do that here and just rely on incremental formatting going forward, or we could do a global reformat to bring things up to date as we did when we originally switched to black in https://github.com/quantumlib/Cirq/pull/3516. I think the changes this time would be much less drastic than in the original switch. The main thing we've seen internally is tighter binding of the power operator, e.g. new black does `a**b + …
=> Upgrade black to stable version with format stability guarantees

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/moment.py, cirq-core/cirq/devices/named_topologies.py, cirq-core/cirq/experiments/qubit_characterizations.py, cirq-core/cirq/linalg/decompositions.py, cirq-core/cirq/ops/arithmetic_operation.py, cirq-core/cirq/ops/fourier_transform.py, cirq-core/cirq/ops/pauli_string_test.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap_test.py, cirq-core/cirq/protocols/decompose_protocol.py, cirq-core/cirq/qis/states.py, cirq-core/cirq/testing/deprecation.py, cirq-core/cirq/testing/equals_tester.py, cirq-core/cirq/testing/logs.py, cirq-core/cirq/testing/order_tester.py, cirq-core/cirq/value/measurement_key_test.py, cirq-core/cirq/vis/heatmap.py, cirq-google/cirq_google/engine/client/quantum_v1alpha1/gapic/transports/quantum_engine_service_grpc_transport.py, cirq-ionq/cirq_ionq/service.py, dev_tools/conf/.pylintrc, dev_tools/pylint_copyright_checker_test.py, dev_tools/requirements/deps/pylint.txt, dev_tools/shell_tools.py, examples/hhl.py
The new version of pylint support `--ignore-paths` (added in [pylint 2.9](https://pylint.pycqa.org/en/latest/whatsnew/2.9.html)) that allows specifying directories to ignore, which will make it easier to integrate generated code that we don't want to lint (see https://github.com/quantumlib/Cirq/pull/5139). Just a few minor changes were needed to get lint checks to pass with this new version, in particular the new version checks that `*args` and `**kwargs` include the `*` or `**` in the docstring.
=> Update to pylint 2.13

dev_tools/docs/build_api_docs.py
API Docs builds appear to be broken on some select symbols in Cirq-core. This disables them to allow builds to resume. Opened #5166
=> Disable broken symbols.

cirq-google/cirq_google/engine/engine_client_test.py
Previously we had `yapf: disable`/`yapf: enable` directives to exclude some large pytest parametrize expressions which the beta version of black had trouble with. These are handled fine by the new version, so we remove the directives and format the entire file.
=> Autoformat all of engine_client_test.py

cirq-ionq/cirq_ionq/sampler.py, cirq-ionq/cirq_ionq/sampler_test.py
This allows users of tensorflow quantum to use a high timeout and https://github.com/tensorflow/quantum/blob/f10d36b64761a003fd542392767fa079d57df0aa/tensorflow_quantum/python/quantum_context.py\#L82-L101 to run highly parallel workloads that may take very long times per-job without flakiness.
=> Allow specifying timeout_seconds when constructing an ionq Sampler

docs/circuits.ipynb
- Remove output
- Move import to top
- Minor changes to content (add `cirq.` prefix to many quoted words)
- Remove broken link to devices.ipynb
=> Fix docs/circuits.ipynb as part of docs cleanup for Cirq 1.0

docs/simulation.ipynb
Quick cleanup pass for simulator docs. Nontrivial changes:
- include note for `seed` parameter of simulator
- remove comments about modifying StepResult state (deprecated)
- clarify pure/mixed state behaviors and advantages
- external simulator focus: qsim++, qFlex--
Everything else is cleaning format and refreshing links.
=> Update simulator docs

docs/tutorials/_index.yaml
Removes broken link from cirq/tutorials as part of docs cleanup.
=> Fix broken link from cirq/tutorials page as part of docs cleanup

docs/start.ipynb
=> Link fix on start page.

examples/advanced/quantum_volume_errors.ipynb
=> Remove use of deprecated device behavior from quantum_volume_errors.

cirq-core/cirq/circuits/qasm_output.py, cirq-core/cirq/experiments/random_quantum_circuit_generation.py, cirq-core/cirq/ion/ion_decomposition_test.py, cirq-core/cirq/qis/clifford_tableau.py, cirq-core/cirq/sim/density_matrix_utils.py, cirq-google/cirq_google/calibration/engine_simulator.py, cirq-google/cirq_google/calibration/phased_fsim.py, examples/stabilizer_code.py
`np.array` is not a valid type, but rather a factory function for creating arrays. The actual type is `np.ndarray`. This change reduces the number of `check/mypy --next` errors by >60% from 244 to 96 on my machine.
=> Fix numpy annotations np.array -> np.ndarray

cirq-core/cirq/sim/act_on_density_matrix_args.py, cirq-core/cirq/sim/act_on_density_matrix_args_test.py, cirq-core/cirq/sim/act_on_state_vector_args.py, cirq-core/cirq/sim/act_on_state_vector_args_test.py, cirq-core/cirq/sim/clifford/act_on_stabilizer_ch_form_args.py, cirq-core/cirq/sim/density_matrix_simulator_test.py, cirq-core/cirq/sim/state_vector_simulator_test.py
A few simulators used either initial_state or target_tensor to initialize their ActOnArgs. We deprecated the latter in 0.15. This PR deletes those. Note that one follow-on change included here is that the repr functions needed to be changed to emit the field as `initial_state` too. (I wish I'd just called it `quantum_state` now, but oh well). @95-martin-orion
I also went ahead and removed the buffer from the repr, since it is just noise.
=> Delete the target_tensor parameter that was deprecated in 0.15

cirq-core/cirq/protocols/act_on_protocol_test.py, cirq-core/cirq/sim/act_on_args.py, cirq-core/cirq/sim/act_on_args_container_test.py, cirq-core/cirq/sim/act_on_args_test.py
Now that we have separated out the `QuantumStateRepresentation` from `ActOnArgs`, there is no need for the `_on_*` methods anymore. This PR deprecates those, adds deprecation tests, and updates any old test ActOnArgs to use the new QuantumStateRepresentation internally. @95-martin-orion
=> Deprecate the ActOnArgs._on_* methods

cirq-core/cirq/qis/states.py, cirq-core/cirq/qis/states_test.py, cirq-core/cirq/sim/act_on_density_matrix_args.py, cirq-core/cirq/sim/act_on_density_matrix_args_test.py
This changes how ActOnDensityMatrixArgs is constructed to allow specifying the initial state as a state vector or state tensor, or as a density matrix or density tensor. Some of this could perhaps be moved into `cirq.to_valid_density_matrix` if people think that is a better place. Currently `to_valid_density_matrix` only handles 1D state vectors or 2D density matrices, not 2x2x..2 tensors in either case, but if we have the qid_shape we can tell handle these unambiguously.
Fixes #3958
=> Allow specifying initial state vector in DensityMatrixSimulator

cirq-ionq/cirq_ionq/job.py, cirq-ionq/cirq_ionq/job_test.py
This will be used to notify users about deprecations and changes to the API without needing to update Cirq independently.
=> Allow server-side warnings from IonQ

cirq-core/cirq/circuits/circuit.py
Fixes #5150 (assuming this renders nicely on the docsite; how can I check that locally?)
This adds an underscore prefix to hide some type aliases and type vars that are not part of the public interface of the module. Also adds a docstring to the `CIRCUIT_TYPE` variable, which is used in a few other places.
=> Document CIRCUIT_TYPE and hide other typevars/aliases in circuits.py

cirq-core/requirements.txt, dev_tools/conf/mypy.ini
=> Unpin sympy and ignore sympy type errors

dev_tools/docs/build_api_docs.py, dev_tools/requirements/deps/tensorflow-docs.txt
Fixes #5166. My understanding is that previously we had some conflict with protobuf versions due to gapic generated code, but that was updated in #5139.
=> Bump tensorflow-docs version

cirq-core/cirq/contrib/quimb/mps_simulator.py, cirq-core/cirq/sim/act_on_args.py, cirq-core/cirq/sim/act_on_density_matrix_args.py, cirq-core/cirq/sim/act_on_state_vector_args.py, cirq-core/cirq/sim/clifford/act_on_stabilizer_args.py, cirq-core/cirq/sim/simulator_base_test.py
Makes the ActOnArgs generic on which quantum state type it contains. This allows us to delete the annoying `self._state: <State> = state` typehints. @95-martin-orion
=> Make the quantum state generic

.git-blame-ignore-revs
This adds a formatting commit to ignore when doing git blame.
=> Ignore skip-magic-trailing-comma formatting with git blame

cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/gate_operation_test.py
Fixes: https://github.com/quantumlib/Cirq/issues/5148
Reverts: https://github.com/quantumlib/Cirq/pull/4941
I'm willing to hear about making this code idiomatic while not breaking the newly added test.
=> Re-introduce less idiomatic code for `_group_interchangeable_qubits` implementation

.github/workflows/ci.yml
On closer examination, it appears that `github.head_ref` does not exist in the `push` action event context: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
This _should_ fix this.
=> Fix push event to fallback to run_id in ci

cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/protocols/json_serialization.py, cirq-core/cirq/protocols/json_serialization_test.py, cirq-core/cirq/protocols/json_test_data/datetime.datetime.json, cirq-core/cirq/protocols/json_test_data/datetime.datetime.repr
spun off from #5152 
It's super important when running experiments to keep track of when things happen.
cc @maffoo
=> Serialize datetime

cirq-core/cirq/sim/act_on_args.py, cirq-core/cirq/sim/act_on_args_container.py, cirq-core/cirq/sim/simulator.py, cirq-core/cirq/sim/simulator_base.py, cirq-core/cirq/sim/simulator_test.py
Removes the `simulator` package dependency on ActOnArgs, freeing up other simulators to implement SimulatesIntermediateState without needing specifically to implement ActOnArgs. @95-martin-orion
=> Bump types so that SimulatesIntermediateState isn't bound to ActOnArgs

cirq-core/cirq/work/observable_measurement.py, cirq-core/cirq/work/observable_measurement_data.py, cirq-core/cirq/work/observable_settings.py, cirq-core/cirq/work/observable_settings_test.py, cirq-core/cirq/work/sampler.py, cirq-core/cirq/work/sampler_test.py
Update all "circuit_params" members to allow complex scalar values. Update the hashing function also to handle these values by returning fixed-point `(real, imag)` tuples for complex numbers. Add a couple sanity checks that things still work.
Closes #5282
@tanujkhattar
=> Support complex params in `work` module

cirq-core/cirq/ops/gateset.py, cirq-core/cirq/ops/gateset_test.py, cirq-core/cirq/protocols/json_test_data/GateFamily.json, cirq-core/cirq/protocols/json_test_data/GateFamily.repr, cirq-core/cirq/protocols/json_test_data/Gateset.json, cirq-core/cirq/protocols/json_test_data/GridDeviceMetadata.json
Adding general validation of gate tags to GateFamily, as described in https://github.com/quantumlib/Cirq/pull/5063#discussion_r826415632
Replaces https://github.com/quantumlib/Cirq/pull/5063
@tanujkhattar
=> GateFamily: tag validation

docs/interop.ipynb
Minor patches to the interop doc.
Not super familiar with our QASM integration, but last I checked we hadn't changed it and don't intend to migrate to OpenQASM3.0 unless external contributors jump in on it.
=> docfixit: interop format

docs/tutorials/pasqal/getting_started.ipynb
- Update Pasqal documentation to use device validation
rather than devices attached to circuits.
- Clean up code so that repeated executions do not fail noise
model or validation.
- Clear output.
- Add a few code comments.
=> Update Pasqal Tutorial Documentation

cirq-google/cirq_google/json_resolver_cache.py, cirq-google/cirq_google/json_test_data/SycamoreTargetGateset.json, cirq-google/cirq_google/json_test_data/SycamoreTargetGateset.repr, cirq-google/cirq_google/json_test_data/spec.py, cirq-google/cirq_google/transformers/target_gatesets/sycamore_gateset.py, cirq-google/cirq_google/transformers/target_gatesets/sycamore_gateset_test.py
This makes it possible to fully serialize `GridDeviceMetadata`.
A repr/json with tabulation set is omitted because the repr of cirq.two_qubit_gate_product_tabulation() is very long.
@tanujkhattar
=> Add json serialization to SycamoreTargetGateset.

docs/gatezoo.ipynb
These appear to have come from a jupyter nbformat versioning issue.  "id" was added in the 4.5 schema.  Somehow these got saved into a 4.0 schema notebook.  
This breaks our nightly docs build right now.
=> Remove ids from notebooks

setup.py
The top level setup.py is virtual and only declares cirq-core,
cirq-google, and others as its dependencies.
Make sure it does not search for packages,
which would raise setuptools error.
Resolves https://github.com/quantumlib/Cirq/issues/5291
=> Prevent implicit package search from top level setup.py

examples/hhl.py
Added a parenthesis I think is required.
Fixed a sentence, I think the word "rotation" was missing.
=> Minor (cosmetic changes)

cirq-google/cirq_google/devices/calibrations/__init__.py
Lack of an `__init__.py` file prevented discovery of these files in `setup.py`.
=> __init__ for calibrations package

cirq-ionq/cirq_ionq/ionq_client.py, cirq-ionq/cirq_ionq/ionq_client_test.py
We were planning on making this arg optional, but it shouldn't hurt to also send it explicitly
=> IonQ: Explicitly select lang

cirq-ionq/cirq_ionq/job.py, cirq-ionq/cirq_ionq/job_test.py
We can't guarantee that shot * prob cleanly returns an integer, for example 0.0006*5000 does not return 3 due to an inability to represent 0.0006 perfectly. See https://docs.python.org/3/tutorial/floatingpoint.html
=> IonQ: Handle loss of precision in floats

cirq-google/cirq_google/__init__.py, cirq-google/cirq_google/calibration/__init__.py, docs/google/calibration_faq.md
- Correct names of a few references to provide correct linking.
- Expose the function name for a function used in this tutorial.
=> Minor updates to calibration_faq page

cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/ops/linear_combinations.py, cirq-core/cirq/protocols/json_test_data/PauliSum.json, cirq-core/cirq/protocols/json_test_data/PauliSum.repr, cirq-core/cirq/protocols/json_test_data/spec.py
Fixes #3071 
One approach to this would have been to serialize frozenset and tuple in Cirq, but this instead takes the approach of not relying on this but appropriately serializing and deserializing these.
=> Add json serialization for PauliSum

cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/ops/gate_operation_test.py, cirq-core/cirq/ops/pauli_interaction_gate.py, cirq-core/cirq/protocols/json_test_data/PauliInteractionGate.json, cirq-core/cirq/protocols/json_test_data/PauliInteractionGate.repr, cirq-core/cirq/protocols/json_test_data/spec.py
* also make a constant ALL_CAPS and use simpler type annotation
#5353
=> Add json serialization for PauliInteractionGate

cirq-core/cirq/study/resolver.py, cirq-core/cirq/study/resolver_test.py, cirq-google/cirq_google/api/v2/sweeps.py, cirq-google/cirq_google/api/v2/sweeps_test.py
- A ParamResolver resolves variables into values.
- Having non-trivial formulas as keys allows a significant
complexity and ambiguity into ParamResolvers, since it is
unclear how much is supported.  Prevent this case altogether
by raising an error if non-symbol formulas are used in ParamResolvers.
Fixes: #3550
=> Reject formulas as keys of ParamResolvers

cirq-core/cirq/transformers/drop_negligible_operations.py, cirq-core/cirq/transformers/drop_negligible_operations_test.py
Fixes https://github.com/quantumlib/Cirq/issues/5302
=> Ignore operations on more than 10 qubits in drop_negligible_operations transformer

cirq-core/cirq/testing/consistent_controlled_gate_op.py
Extends the test for dense pauli strings, which can be done after https://github.com/quantumlib/Cirq/issues/4508 is fixed.
=> Remove stale condition from assert_controlled_and_controlled_by_identical test

cirq-core/cirq/ops/classically_controlled_operation.py, cirq-core/cirq/ops/classically_controlled_operation_test.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py
Asserts that:
- `op.with_classical_controls() is op` : Returns self if set of conditions is empty. This is already true for other methods like `op.with_tags`, `op.controlled_by` etc.
- `tagged_op.with_classical_controls()` will now remove tags, which is consistent with the philosophy that tagged operations are immutable and tags should be removed if the underlying operation is mutated. Other methods, like `tagged_op.controlled_by`, already follow this pattern.
=> Fix CCO related nits in `cirq.Operation` and `cirq.TaggedOperation`

docs/tutorials/state_histograms.ipynb
Part of docs cleanup for Cirq 1.0
=> Fix typo in docs/tutorials/state_histograms.ipynb

docs/transform.ipynb
Part of docs cleanup for Cirq 1.0
=> Fix typos and nits in docs/transform.ipynb

.github/workflows/ci.yml, asv.conf.json, cirq-aqt/setup.py, cirq-core/cirq/__init__.py, cirq-core/cirq/_version.py, cirq-core/cirq/protocols/json_test_data/spec.py, cirq-core/cirq/sim/simulator.py, cirq-core/cirq/value/__init__.py, cirq-core/cirq/value/abc_alt.py, cirq-core/requirements.txt, cirq-core/setup.py, cirq-google/cirq_google/_version.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-web/setup.py, dev_tools/modules_test.py, dev_tools/modules_test_data/mod1/setup.py, pyproject.toml, setup.py
This is a step toward following the numpy python support schedule (https://github.com/quantumlib/Cirq/issues/3347). Note that according to the schedule we should be at 3.8+, but we cannot yet drop support for 3.7 since colab is still at 3.7.13.
=> Drop support for python 3.6

cirq-google/requirements.txt
I encountered an error in CI where pip was installing protobuf 4 (https://github.com/quantumlib/Cirq/runs/6606535751?check_suite_focus=true) and I think it was because the multiple version specifiers are supposed to be separated by a comma. Cleaned up the requirements file to add the comma as well as some whitespace for clarity (and consistency with the first line).
=> Fix protobuf version specifiers in cirq-google/requirements.txt

cirq-core/cirq/ops/common_gates.py, cirq-core/cirq/ops/common_gates_test.py, cirq-core/cirq/ops/phased_iswap_gate_test.py, cirq-core/cirq/ops/swap_gates_test.py, cirq-core/cirq/ops/three_qubit_gates.py, cirq-core/cirq/ops/three_qubit_gates_test.py
Fixes https://github.com/quantumlib/Cirq/issues/4275
=> Make all non-analytical gate decompositions respect global phase

cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/circuit_operation_test.py
=> Do not generate default repetition ids if use_repetition_ids=False

cirq-core/cirq/experiments/fidelity_estimation.py, cirq-core/cirq/experiments/fidelity_estimation_test.py
- These functions are inefficient and have been obsoleted
by vectorized versions in xeb_fitting.
This is part of the plan to deprecate redundant XEB functionality as
part of #3775.
=> Deprecate least_squares functions in fidelity_estimation

cirq-core/cirq/contrib/acquaintance/topological_sort_test.py, cirq-core/cirq/study/sweeps_test.py, cirq-core/cirq/testing/circuit_compare_test.py
I use python-repeat to check for flaky tests.  It allows you to pass in `--count XXX` to repeat a test multiple times.  Interestingly, for parameterized tests the decorator that creates the parameterized tests is run once globally, and then the tests are repeated.  This means that these tests can catch places where the parameterized values are mutated in some way during a test.  
This fixes the cases found from `check/pytest --count 100`.  In general mutating parameters called to functions without being very explicit about it is something we should try to avoid.
=> Fix tests that break python-repeat

docs/tutorials/rigetti/getting_started.ipynb
- I thought we could get away with testing this, but it looks
like the apt-get commands to install the forest SDK will not run
in the devsite infrastructure.
=> Add outputs back into rigetti getting started guide.

cirq-core/cirq/ops/pauli_measurement_gate_test.py, cirq-core/cirq/ops/pauli_string.py, cirq-core/cirq/ops/pauli_string_test.py
- The repr of pauli strings with coefficient of one
used to truncate the one.
- The old way is prettier but does not actually repr to the same thing,
ie.  type(eval('cirq.Z.on(cirq.LineQubit(0))')
!=   type(eval('1*cirq.Z.on(cirq.LineQubit(0))')
Fixes: #2771
=> Update repr of pauli strings

cirq-google/cirq_google/serialization/arg_func_langs.py, cirq-google/cirq_google/serialization/circuit_serializer_test.py, cirq-google/cirq_google/serialization/op_serializer.py, cirq-google/cirq_google/serialization/op_serializer_test.py
- Adds support for numpy types for CircuitSerializer and
deprecated GateOpSerializer.
- Also add checks for numpy floats and ints.
Fixes: #4010
=> Add numpy support for Google serialization

dev_tools/pr_monitor.py
Fixes #4412
Verified in my personal fork via curling the API directly.
@MichaelBroughton
cc @dabacon
=> pr_monitor: post empty string as commit message if PR body is empty

cirq-core/cirq/devices/thermal_noise_model.py
Keep import down by not importing scipy.
=> Lazily load scipy.linalg

cirq-core/cirq/study/resolver.py, cirq-core/cirq/study/resolver_test.py
- pass through None as a parameter if set.
Technically a breaking change, since this used to silently drop parameters that were set as None. 
Fixes: #4029
=> Pass through None during param resolution

cirq-core/cirq/protocols/decompose_protocol.py, cirq-core/cirq/protocols/pow_protocol.py, cirq-core/cirq/work/observable_settings.py
Also tightens some pylint exceptions, and uses a type annotation and not a cast to clean things in pow protocol a bit.
=> Union[None, X] is Optional[X]

cirq-core/cirq/protocols/json_serialization_test.py
https://github.com/quantumlib/Cirq/issues/2014 has been fixed and the following code snippet now works as expected.  
```python
>>> import cirq, sympy
>>> circuit = cirq.Circuit(cirq.rx(sympy.Symbol('theta')).on(cirq.NamedQubit("q")))
>>> cirq.testing.assert_json_roundtrip_works(circuit) # works.
```
=> Remove stale comment from json_serialization_test.py

cirq-google/cirq_google/serialization/arg_func_langs.py
Fixes #2384
Clarifies what sympy expressions are allowed when a user tries to serialize a circuit which contains unrecognized Sympy expressions.
@dstrain115
=> Update error message when invalid sympy arg is serialized

cirq-core/cirq/__init__.py, cirq-core/cirq/ion/__init__.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/analytical_decompositions/__init__.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_ms.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_ms_test.py
Part of https://github.com/quantumlib/Cirq/issues/2793
=> Move `two_qubit_matrix_to_ion_operations` to cirq/transformers/analytical_decompositions

cirq-core/cirq/contrib/quimb/mps_simulator_test.py
Resolves the "tests are failing" part of #5524.
=> Use new quimb TN string format

cirq-core/cirq/circuits/circuit_operation.py
Call the circuitop constructor with all the fields, rather than using `with...` for each field and repeating a potentially expensive validation at each step. @95-martin-orion 
Fixes #5516
=> Make CircuitOp.fromjson more efficient

cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_cz_test.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim_test.py
Fixes #5533
I don't feel great about this, because we don't have a principled way of choosing these tolerances, some of which already seem quite generous (1e-4 is not enough in one case). But this should upblock other PRs.
=> Increase test tolerances on some analytical decomposition tests

cirq-core/cirq/qis/__init__.py, cirq-core/cirq/qis/clifford_tableau.py, cirq-core/cirq/qis/quantum_state_representation.py
=> Move QuantumStateRepresentation to its own file

dev_tools/bash_scripts_test.py, dev_tools/notebooks/isolated_notebook_test.py, dev_tools/notebooks/notebook_test.py
Stop using shell_tools.run_shell which is slated for removal.
Partially implements https://github.com/quantumlib/Cirq/issues/4394
=> Replace shell_tools.run_shell --> shell_tools.run

cirq-google/cirq_google/engine/abstract_processor.py, cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/engine/engine_processor.py, cirq-google/cirq_google/engine/engine_processor_test.py, cirq-google/cirq_google/engine/engine_test.py, cirq-google/cirq_google/engine/simulated_local_processor.py, cirq-google/cirq_google/engine/util.py
* Migrate the different `processor.get_device()` methods and `Engine.get_engine_device()` to GridDevice
* Deprecate the `gate_sets` parameter in various `get_device()` methods, and remove `gate_sets` usages.
A dedicated deprecation decorator was added in order to handle `gate_sets` parameter being passed in as a positional argument.
Originally I had planned to do this after the 0.15 release, but because library code is not allowed to rely on deprecated code within tests, this is blocking SerializableDevice deprecation (https://github.com/quantumlib/Cirq/pull/5522).
@dstrain115 @MichaelBroughton
=> Move Engine interfaces to GridDevice

dev_tools/cloned_env_test.py, dev_tools/conftest.py, dev_tools/env_tools.py, dev_tools/git_env_tools.py, dev_tools/packaging/isolated_packages_test.py
Stop using shell_tools.run_cmd which is slated for removal.
Partially implements https://github.com/quantumlib/Cirq/issues/4394
=> Replace shell_tools.run_cmd --> shell_tools.run

cirq-core/cirq/ops/gateset.py, cirq-core/cirq/ops/gateset_test.py, cirq-google/cirq_google/devices/known_devices_test.py
Fixes https://github.com/quantumlib/Cirq/issues/5543
=> Treat default gate families with tags_to_ignore or tags_to_accept as custom gate families in Gatesets

docs/_book.yaml, docs/build/_index.yaml, docs/experiments/_index.yaml, docs/hardware/_index.yaml, docs/noise/_index.yaml, docs/simulate/_index.yaml, docs/transform/_index.yaml
Some small phrasing/style updates to the overview pages.
=> Overview updates

docs/start/install.md
=> Document policy for python version support.

cirq-google/cirq_google/devices/grid_device_test.py, cirq-google/cirq_google/devices/known_devices.py, cirq-google/cirq_google/devices/known_devices_test.py, cirq-google/cirq_google/devices/serializable_device_test.py
=> Deprecate create_device_proto_for_qubits

cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/ops/clifford_gate_test.py
This makes it easier to use any single-qubit Clifford gate in tests, including currently neglected order-3 Cliffords. See [context](https://github.com/quantumlib/Cirq/pull/5568#discussion_r904050802).
The PR also simplifies the construction of the gates. In particular, we don't need a simulator to get a gate's tableau.
=> All single-qubit Cliffords

docs/hardware/ionq/getting_started.ipynb
Fix typo in the link and align inline comments
=> review ionq/getting_started tutorial notebook

cirq-core/cirq/interop/quirk/cells/arithmetic_cells.py, cirq-core/cirq/ops/arithmetic_operation.py, cirq-core/cirq/ops/arithmetic_operation_test.py
https://github.com/quantumlib/Cirq/pull/4702 was started in November but did not get merged until May, which was after 14.1 went out. These deprecations need to be bumped to 0.16 instead of 0.15.
Once 0.15 goes out then I can reopen https://github.com/quantumlib/Cirq/pull/5579 and delete these.
=> Add a deprecation cycle for ArithmeticOp

cirq-google/cirq_google/devices/grid_device.py, cirq-google/cirq_google/devices/grid_device_test.py
=> Temporary GridDevice.qubits property

cirq-google/cirq_google/api/v2/program.proto, cirq-google/cirq_google/api/v2/program_pb2.py
Deprecating this field now that each device only has a single gateset and a single serializer.
Engine parsing logic will be updated to ignore other `gate_set` values other than the one corresponding to `CircuitSerializer` after 0.15, when global gatesets will be removed.
@dstrain115
=> Deprecate Program.language.gate_set proto field

cirq-google/cirq_google/__init__.py, cirq-google/cirq_google/devices/known_devices.py, cirq-google/cirq_google/devices/serializable_device_test.py, cirq-google/cirq_google/serialization/common_serializers.py, cirq-google/cirq_google/serialization/gate_sets.py, cirq-google/cirq_google/serialization/op_deserializer.py, cirq-google/cirq_google/serialization/op_deserializer_test.py, cirq-google/cirq_google/serialization/op_serializer.py, cirq-google/cirq_google/serialization/op_serializer_test.py, cirq-google/cirq_google/serialization/serializable_gate_set_test.py
This PR deprecates all serializers we plan to deprecate
* Deprecated GateOpSerializer, GateOpDeserializer, DeserializingArg, and SerializingArg using the class wrapper technique. 
* CircuitSerializer and serializer classes it depends on (`CircuitOp[De]Serializer`, `Serializer`) are left in place.
* Skipping deprecation of common serializers in `common_serializers.py` for now and remove them directly after the 0.15 release as it's very unlikely for users to access them directly. Most users interact with them via global gatesets, e.g.
https://github.com/quantumlib/Cirq/blob/abfc619bfe31e93573993c76cecfddc5689dea9b/cirq-google/cirq_google/serialization/gate_sets.py#L43-L64
But if time allows, I'll try to deprecate common serializers as well.
* Added mentions of serializer deprecations in …
=> Serializers deprecation

cirq-core/cirq/ops/gateset.py, cirq-core/cirq/protocols/json_test_data/CZTargetGateset.json, cirq-core/cirq/protocols/json_test_data/GateFamily.json, cirq-core/cirq/protocols/json_test_data/Gateset.json, cirq-core/cirq/protocols/json_test_data/GridDeviceMetadata.json, cirq-core/cirq/protocols/json_test_data/SqrtIswapTargetGateset.json, cirq-google/cirq_google/json_test_data/cirq.google.GridDevice.json
GateFamily has existed prior to the last release, while GateFamily tag support has not gone into a release yet. Removing empty lists in serialized JSON before the next release as recommended to ensure backward compatibility.
@95-martin-orion
=> GateFamily: do not serialize gates_to_accept and gates_to_ignore when empty

docs/_book.yaml, docs/build/gates.ipynb, docs/dev/rfc_process.md, docs/simulate/params.ipynb, docs/start/best_practices.md
- Add document under 'start' about some basic best practices,
like using 'cirq.X' instead of 'cirq.ops.X'.
- Also added sections about immutability of gates, operations, and
parameter resolvers.
- Removed name of former product manager.
Fixes:  #1373
=> Add user best practices documentation

docs/hardware/ionq/service.md
- Cleaning up some punctuation and defining the `remote_host` option
which was mentioned but not explained.
=> Minor updates for the IonQ Service page

cirq-core/cirq/protocols/measurement_key_protocol.py, cirq-core/cirq/work/observable_measurement.py, cirq-core/cirq/work/observable_measurement_data.py, cirq-core/cirq/work/observable_settings.py, cirq-core/cirq/work/sampler.py
=> Use mapping in cirq/work

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/moment.py, cirq-core/cirq/ops/classically_controlled_operation.py, cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/kraus_channel.py, cirq-core/cirq/ops/measurement_gate.py, cirq-core/cirq/ops/mixed_unitary_channel.py, cirq-core/cirq/ops/pauli_measurement_gate.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/measurement_key_protocol.py, cirq-core/cirq/value/condition.py, cirq-core/cirq/value/measurement_key.py
Fixes #5552.
Since this change only* affects type annotations, it is non-breaking. Any breakages due to `ParamResolver.param_dict` becoming immutable should instead refer to #5548, where this change was applied.
*Okay, it also removes some `dict` calls, but those were added in #5548.
=> Make with_measurement_key_mapping live up to its name

cirq-core/cirq/__init__.py, cirq-core/cirq/ops/__init__.py, cirq-core/cirq/ops/pauli_string_test.py, cirq-core/cirq/ops/swap_gates.py, cirq-core/cirq/ops/swap_gates_test.py, cirq-core/cirq/protocols/json_test_data/ISWAP_INV.json, cirq-core/cirq/protocols/json_test_data/ISWAP_INV.repr, cirq-google/cirq_google/serialization/common_serializers.py, cirq-google/cirq_google/serialization/common_serializers_test.py, docs/gatezoo.ipynb
Fixes #4615
#4624 has not been touched in a long time, so jumping in to fix this.
=> Add ISWAP_INV constant

cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_cz_test.py
And loosen the atol for the test.
=> Use more accurate complex128 for testing non-public method 

cirq-google/cirq_google/engine/engine_validator.py, cirq-google/cirq_google/engine/engine_validator_test.py, cirq-google/cirq_google/engine/simulated_local_processor.py, cirq-google/cirq_google/engine/virtual_engine_factory.py
Removing the notion of gate sets in engine validator.
@dstrain115 
cc @maffoo
=> Engine validator: rename validate_gate_set to validate_program

cirq-core/cirq/ops/pauli_interaction_gate.py, cirq-core/cirq/protocols/apply_channel_protocol.py, cirq-core/cirq/protocols/apply_mixture_protocol.py, cirq-core/cirq/protocols/apply_unitary_protocol.py, cirq-core/cirq/protocols/commutes_protocol.py, cirq-core/cirq/protocols/unitary_protocol.py, cirq-core/cirq/sim/sparse_simulator_test.py, cirq-google/cirq_google/ops/fsim_gate_family.py, cirq-google/cirq_google/optimizers/two_qubit_gates/example.py
The cast in `fsim_gate_family` could be done with an assert, but in this case I think it is more readable to just use the cast.
=> More fixes for next version of mypy

.github/workflows/ci.yml, check/pytest-and-incremental-coverage, dev_tools/bash_scripts_test.py
This remove the rigetti integration tests from the default of `pytest-and-incremental-coverage` and hence of `all`.  It keeps these tests in the CI workflow.  
The alternative to this would be to add the docker up and down to these scripts, but I'm hesitant to do this as these download external docker images.
Fixes #4660
=> Remove Rigetti from local checks

docs/dev/modules.md
The `modules.py` argument parser does not understand the argument
`--list`; it needs to be `list`.
=> Fix for issue #5637

cirq-core/cirq/contrib/paulistring/optimize_test.py
https://github.com/quantumlib/Cirq/issues/5546 was raised because the test diagram had to be changed from `─Z─` to  `─[Z]^1─`
This was caused because of precision issues caused by changing `np.complex128` to `np.complex64`. 
A recent PR (https://github.com/quantumlib/Cirq/commit/f904a09031b102a3ad5d7b55eff2c8efe565197f) rolled back the change and increased the precision back to `np.complex128`; thereby reverting the diagram to it's original form  `─Z─`.
We can remove the stale TODO and close the issue. 
Fixes https://github.com/quantumlib/Cirq/issues/5546
=> Remove stale TODO and fix #5546

dev_tools/requirements/deps/dev-tools.txt
Both qiskit-aer and its dependency qiskit-terra attempt to write
`qiskit/providers/__init__.py`.  If the version from qiskit-aer 0.9.1
wins it causes broken import of qiskit.providers.aer.
Here we update qiskit-aer to its latest version 0.10.4.
This fixes failing CI checks for Python 3.8 such as
https://github.com/quantumlib/Cirq/runs/7139878042.
=> Fix CI failure due to incompatible qiskit packages

cirq-rigetti/requirements.txt
Should fix CI breaks on mac. Matches rapidjson used here: https://github.com/rigetti/pyquil/blob/v3.0.0/poetry.lock
=> Pin python-rapidjson in cirq-rigetti.

docs/dev/development.md
- Change Foxtail to Sycamore since Foxtail is deprecated.
- Add some clarification that instructions are for linux.
=> Minor updates to development page

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/ops/kraus_channel.py, cirq-core/cirq/ops/mixed_unitary_channel.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_sqrt_iswap.py
- Fix type complaints for np.allclose arguments
- Fix complaint about float-to-int assignment
- Fix type-complaint about optional return value
=> Fix more numpy / mypy typing issues

cirq-core/cirq/protocols/resolve_parameters.py
One-liner to link this docstring on the website.
=> Link out to ParamResolver in resolve_parameters docstring

cirq-core/cirq/ops/common_channels.py
Indentation in matrix docstrings for channels is messing up the website display ([example](https://quantumai.google/reference/python/cirq/phase_damp)).
This PR simply de-indents those docstrings to prevent them from being interpreted as code blocks.
=> De-indent channel matrices

cirq-core/cirq/ops/fsim_gate.py
The \theta dependence was missing from lines 224-225
=> Fix the definition of PhasedFSimGate

cirq-core/cirq/sim/density_matrix_simulation_state_test.py, cirq-core/cirq/sim/simulation_state.py, cirq-core/cirq/sim/state_vector_simulation_state_test.py
Avoid contradictory use of the constructor `state` argument,
which is required for the SimulationState base class,
but unknown to its derived classes.
Closes #5721
=> Remove unused method SimulationState.with_qubits

docs/start/basics.ipynb
This is such a trivial PR, but I spotted them and figured I may as well offer to fix them very quickly.
This fixes a couple of very tiny grammar bugs, plus a few cases of cirq -> Cirq capitalization, and some missing periods at the ends of list items (to make all lists on the page follow the same convention).
=> Fix very trivial grammar issues & typos in docs/start/basics

cirq-aqt/cirq_aqt/aqt_device.py, cirq-aqt/cirq_aqt/aqt_device_metadata.py, cirq-aqt/cirq_aqt/aqt_device_metadata_test.py, cirq-aqt/cirq_aqt/aqt_device_test.py
Move AQTDevice specifications to a new dedicated AQTDeviceMetadata class.
Move `AQTDevice.gateset` and the `duration_of()` method to AQTDeviceMetadata.
Remove method `AQTDevice.decompose_circuit()`.
Pytestify tests for AQTDevice.
Fixes #5726
=> Add AQTDeviceMetadata and clean up AQTDevice

cirq-google/cirq_google/devices/grid_device.py
The device metadata returns durations as `Mapping`, so it's helpful to accept `Mapping` in `create_device_specification_proto` instead of requiring `Dict`.
=> Use Mapping instead of Dict in some grid device helper funcs

dev_tools/notebooks/isolated_notebook_test.py, docs/_book.yaml, docs/build/_index.yaml, docs/build/pauli_observables.ipynb, docs/hardware/qubit_picking.ipynb, docs/noise/_index.yaml, docs/noise/qcvv/coherent_vs_incoherent_xeb.ipynb, docs/noise/representing_noise.ipynb, docs/simulate/_index.yaml, docs/simulate/quantum_virtual_machine.ipynb, docs/simulate/qvm_basic_example.ipynb, docs/simulate/qvm_stabilizer_example.ipynb, docs/simulate/virtual_engine_interface.ipynb, docs/start/basics.ipynb, docs/start/intro.ipynb
Fix title sizing for XEB page
Fix links in other pages
Move Pauli observables to build, where it was intended to be in the first place. 
Move Representing Noise to noise.
=> Links and titles

dev_tools/triage-party/kubernetes/02_deployment/configmap.yaml
Reverts quantumlib/Cirq#4984
As it's no longer needed.
=> Revert "Add Cirq 1.0 tab to TP."

docs/start/basics.ipynb
Variable name on line 250 was `qiubits`
This is typo and correct variable name should be `qubits` as used in following lines of code.
This typo did not break code as `qubits` variable was previously declared on line 150 and hence this old variable was used here instead of the one which should be used.
=> Document fix

dev_tools/notebooks/notebook_test.py, docs/simulate/qvm_builder_code.ipynb
Hide some of the code behind a button in the builder notebook, use the same example shown in QSS, add an explanatory comment in notebook_test
=> Minor style changes to qvm builder code notebook

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/circuits/frozen_circuit.py, cirq-core/cirq/circuits/frozen_circuit_test.py
In our internal code almost all circuits are constructed with explicit moments rather than using an insertion strategy because we want to control the alignment of ops. Here we add a `from_moments` classmethod on `Circuit` and `FrozenCircuit` which takes any number of `OP_TREE` args and converts each one to a `Moment` in the resulting circuit. This gives a convenient way to construct circuits without cluttering the code with multiple calls to `Moment`.
Also adds special cases in both the `Circuit` and `FrozenCircuit` constructors to handle constructing from a single circuit or a sequence of moments.
=> Add `{Frozen}Circuit.from_moments` to construct circuit by moments.

cirq-core/cirq/ops/common_gates.py
=> No qudit Y gate

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py
Fixes: https://github.com/quantumlib/Cirq/issues/5819
=> Convert iterator to list to list before looping through moments in `def insert`

cirq-core/cirq/sim/simulator.py
=> Add binary literal example to methods of SimulatesAmplitudes class

cirq-core/cirq/devices/named_topologies.py, cirq-core/cirq/devices/named_topologies_test.py
Resolves #4710
Co-authored-by: Pavol Juhas <juhas@google.com>
=> Add nodes_to_linequbits method to LineTopology 

cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/routing_devices.py, cirq-core/cirq/testing/routing_devices_test.py
This PR is creates a fake device to be used only for testing qubit connectivity in routing procedures. It only creates grid (square) devices for now in the cirq-core/testing directory. Other device architectures like ring devices will be added in the future. 
For more context see,  http://tinyurl.com/cirq-qubit-routing
=> Creates fake grid device for testing qubit connectivity in routing

cirq-core/cirq/transformers/routing/mapping_manager.py
Changed implementation of computing distances and shortest path in MappingManager to use floyd warshall algorithm using NetworkX
=> Changed mapping manager to use floyd warshall

docs/_book.yaml, docs/experiments/_index.yaml
Minor addition to fix unclickable "Algorithms in ReCirq" heading in the "Experiments" tab sidebar. 
b/244171974
@wcourtney
=> Potential fix for unclickable sidebar heading

cirq-google/cirq_google/engine/engine_client.py
mypy tests on master are currently failing. See https://github.com/quantumlib/Cirq/runs/8237862866?check_suite_focus=true
This PR fixes the failing test.
google/api_core/exceptions defines `code: Union[None, int]`. See 
https://github.com/googleapis/python-api-core/blob/fe617c205918a3e4dfddeb06123e70540898032e/google/api_core/exceptions.py#L119
However, the derived classes can assign an enum to `code`. See 
https://github.com/googleapis/python-api-core/blob/fe617c205918a3e4dfddeb06123e70540898032e/google/api_core/exceptions.py#L222
This PR assumes that `code` can be `Union[None, int, enum.Enum]` and handles the 3 cases appropriately, thus getting rid of the mypy error.
=> Fix mypy error on master

cirq-core/cirq/ops/boolean_hamiltonian.py, cirq-core/cirq/ops/clifford_gate_test.py
Clean up TODO-s for fixed issues #4328 and #4532
=> Remove TODO markers for fixed issues

benchmarks/transformers/routing.py
Part of https://github.com/quantumlib/Cirq/issues/3840
Would be useful to track the improvements in runtime after https://github.com/quantumlib/Cirq/issues/5860 is fixed. 
Testing via `asv run --quick` locally gives the following output:
```
[ 25.00%] ··· transformers.routing.RouteCQC.time_circuit_routing                                                                                                                                                                                                                        ok
[ 25.00%] ··· ======== =============== =============== ================ ================ ================ =================
--                                      depth / op_density / grid_device_size                                
-------- …
```
=> Add performance benchmarks for CQC circuit routing

.gitignore, cirq-web/.gitignore
It is sufficient to have the pattern once in the top .gitignore.
=> Tell git to ignore build directories from distutils

cirq-core/cirq/devices/grid_device_metadata.py, cirq-core/cirq/devices/insertion_noise_model.py, cirq-core/cirq/devices/noise_model.py, cirq-core/cirq/devices/thermal_noise_model.py
=> Fix docstring typos in cirq.devices submodule

benchmarks/transformers/routing.py, docs/_book.yaml, docs/transform/_index.yaml, docs/transform/routing_transformer.ipynb
This PR adds a tutorial for using Cirq's new routing utilities as a transformer. Basic usage is covered as well as ways to build custom extensions on top of the existing utilities.
=> Adds tutorial ipynb for routing as a transformer

.github/workflows/ci.yml, check/pytest, check/pytest-and-incremental-coverage, check/pytest-changed-files, cirq-core/cirq/contrib/routing/initialization_test.py, cirq-core/cirq/ops/boolean_hamiltonian_test.py, cirq-core/cirq/sim/clifford/clifford_simulator_test.py, cirq-core/cirq/transformers/analytical_decompositions/controlled_gate_decomposition_test.py, conftest.py, dev_tools/bash_scripts_test.py, dev_tools/packaging/isolated_packages_test.py, dev_tools/requirements/deps/pytest.txt, examples/direct_fidelity_estimation_test.py
- Require pytest-randomly for the testing to ensure RNG-generated test
parameters are consistent across parallel test jobs.
- Remove check/pytest option --actually-quiet which disables pytest-randomly
hook for seeding parallel test jobs.
- Remove `CIRQ_TESTING_RANDOM_SEED` as it is not needed anymore.
- Remove RNG seeding in the tests where it seems redundant.
- Clean up one instance of unnecessary test parametrization.
This upholds #4787 and replaces #4788.
Reverts #1825 and obsoletes #1826.
=> Use pytest-randomly for reproducible random test parameters

dev_tools/requirements/deps/tensorflow-docs.txt
Avoid traffic throttling on GitHub due to too much cloning.
Fix https://github.com/quantumlib/Cirq/issues/5880
=> Use GitHub tarball for tensorflow-docs dependency

.github/workflows/ci.yml, check/pytest, cirq-google/cirq_google/engine/engine_job_test.py, cirq-google/cirq_google/engine/engine_processor_test.py, cirq-google/cirq_google/engine/engine_program_test.py, cirq-google/cirq_google/engine/engine_test.py, dev_tools/packaging/isolated_packages_test.py
- Avoid clashing test mocks of QuantumEngineServiceClient by limiting
mocking to the relevant test module.
- Enable test reordering by pytest-randomly.
Fixes #5870.
=> untangle entangled tests

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/circuits/frozen_circuit.py, cirq-core/cirq/circuits/moment.py, cirq-core/cirq/circuits/moment_test.py
- Make `cirq.Moment` resolvable, and don't allocate a new instance if nothing changes during resolution.
- Combine `_resolve_parameter_` implementations on `Circuit` and `FrozenCircuit`.
- Use `_from_moments` to avoid constructor overhead when creating resolved circuits.
- Return `self` if nothing has changed in circuit during resolution, to avoid unnecessary allocations.
=> Optimize circuit/moment resolution to reuse instances if possible

cirq-core/cirq/circuits/circuit.py
When the input is a list of moment, we can just assign that list to `self._moments` instead of using either `append` or `_load_contents_with_earliest_strategy`.  
* `Circuit.append`: This is already essentially `O(D)` if the the input is a list of moments because of the special case `isinstance` check: https://github.com/quantumlib/Cirq/blob/ff81f807bd00b8d0654466b0fdcb3224a687f877/cirq-core/cirq/circuits/circuit.py#L2102
* `Circuit._load_contents_with_earliest_strategy`: has complexity `O(D * Q)` instead of `O(D)`, even if input is all `Moment`s because it iterates on all the qubits that the moment acts on, for each moment; to keep track of the latest used index in case it encounters an operation which is not part of a moment and needs to be inserted using the earliest strategy. See …
=> Speed up circuit construction when contents are a list of moments

cirq-google/cirq_google/calibration/phased_fsim_test.py, cirq-google/cirq_google/calibration/test_data/xeb_calibration_layer.textproto
Problem: CI Pytest MacOS (3.10) fails because float value is output with
a lower precision than in the expected textproto,
https://github.com/quantumlib/Cirq/actions/runs/3192951160/jobs/5211002538.
Solution: Test with parameters that have exact decimal representation,
theta = 0.75,  fatol = xatol = 2**-7 = 0.0078125.
=> Fix test failure on differing precision of float in proto string

check/pytest
- Clean up special-casing for Python 3.6 as we require Python 3.7.
- Simplify handling of the parallel job count `-n COUNT` option in check/pytest.
Obey the `-n0` option on the command line in addition to `-n 0` to
request non-parallel testing.
=> Small housekeeping in check/pytest

docs/_book.yaml, docs/dev/versions.md
Cirq is now officially at v1.0 and we need an official policy for describing guidelines for version compatibility across cirq versions. 
This PR adds a document describing the new official policy. Please take a look and leave comments / give feedback. I'd be very interested to hear about use cases which are potentially unclear from the policy so we can make any necessary improvements.
cc @mpharrigan @dstrain115
=> Add version compatibility policy guidelines for Cirq

cirq-core/cirq/linalg/transformations.py, cirq-core/cirq/ops/common_channels.py, cirq-core/cirq/ops/common_channels_test.py, cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/gate_operation_test.py, cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/circuit_compare.py, cirq-core/cirq/testing/circuit_compare_test.py, cirq-core/cirq/transformers/measurement_transformers.py, cirq-core/cirq/transformers/measurement_transformers_test.py
Confusion matrix and reset channels both can be viewed as starting with a zero DM tensor and then copying (adding) in scaled slices from the original DM tensor. Thus we make a helper function that does this and add `_apply_channel_` optimizations to those gates.
Fixes #5901.
Starts #5900 though I haven't looked at all gates.
Also starts #4579 but there's likely more to do there as well. I didn't add the new test function to the primary test suite because creating superoperators is likely computationally expensive (granted most if not all gates that use this would be three or fewer qubits, which is still cheap), and the test not relevant for most gates.
=> Add _apply_channel_ optimizations for reset and confusion

cirq-google/cirq_google/experimental/ops/coupler_pulse.py, cirq-google/cirq_google/experimental/ops/coupler_pulse_test.py
Allows the hold time in `CouplerPulse` to be swept.
See https://github.com/quantumlib/Cirq/issues/5918
=> Remove checks so that `hold_time` is sweepable

cirq-ionq/cirq_ionq/ionq_native_gates.py, cirq-ionq/cirq_ionq/json_test_data/MSGate.json, cirq-ionq/cirq_ionq/serializer.py, cirq-ionq/cirq_ionq/serializer_test.py
ionq's native MSGate now supports an additional parameter for an arbitrary theta angle.
This angle defaults to 0.25, equivalent to a PI/2 rotation, which matches previous definition. The value is specified in fractions of 2PI, same as in phases.
=> Add support for arbitrary angles to IonQ native MS Gate

cirq-google/cirq_google/api/v2/result.proto, cirq-google/cirq_google/api/v2/result_pb2.py, cirq-google/cirq_google/api/v2/result_pb2.pyi, cirq-google/cirq_google/api/v2/results.py, cirq-google/cirq_google/api/v2/results_test.py
This is a first step toward supporting repeated keys in circuits run through quantum engine. I need to expand the tests to cover cases where instances > 1, but the main logic is ready for review.
=> Add support for repeated keys in result protos

cirq-google/cirq_google/experimental/ops/coupler_pulse.py, cirq-google/cirq_google/experimental/ops/coupler_pulse_test.py
This is something we use on our internal version of this gate.
=> Allow symbol for coupling_mhz in CouplerPulse gate

cirq-core/cirq/study/resolver.py, cirq-core/cirq/study/resolver_test.py
- Sympy will soon error out if an expression is not parsable by sympy.  It used to just ignore this.
- We have one test that exercises this (resolver_test.py:247). Modify code to handle this and print out a warning.
- This is breaking some internal google code and preventing sympy upgrade.
=> Fix sympy error

cirq-core/cirq/devices/grid_qubit.py, cirq-core/cirq/ops/pauli_string.py, cirq-core/cirq/study/flatten_expressions.py
Code block of cirq.PauliString is rendered incorrectly due to indentation. See https://quantumai.google/reference/python/cirq/PauliString#used-in-the-notebooks 
This PR changes the indentation to match the previous code block that gets rendered correctly.
=> Fix docstring indentation of cirq.PauliString

cirq-core/cirq/ops/matrix_gates.py, cirq-core/cirq/ops/matrix_gates_test.py
=> Add MatrixGate.with_name method.

cirq-core/cirq/ops/common_gates.py
Let t = 1.
Then the XPowGate matrix should be a phase factor times the Pauli X-matrix, 
which means that the first coefficient should equal 0. 
As written, the first coefficient is equal to a phase factor times \cos(\pi t), 
which does not equal 0.
=> fixed XPowGate matrix description

.github/workflows/ci.yml, check/shellcheck
- Add check/shellcheck for syntax checking of shell scripts
- Add CI job to run shellcheck on our shell scripts
Resolves #5923.
=> CI - add job for shellcheck

cirq-core/cirq/protocols/json_serialization.py
since they are for `json.dumps`, see https://docs.python.org/3/library/json.html#basic-usage
=> Mark to_json arguments as optional

.github/workflows/ci.yml
Make sure pip-compile can resolve direct and transient cirq dependencies.
Follow-up to #5929
=> CI - check consistency of requirements with pip-compile

cirq-core/cirq/ops/common_channels.py
=> Fix typos in LaTeX

cirq-core/requirements.txt
Part of fixing https://github.com/quantumlib/Cirq/issues/5967
=> Restrict numpy version to 1.23

benchmarks/serialization.py, benchmarks/transformers/transformer_primitives.py
This PR adds representative benchmarks for transformer primitives and circuit serialization, both of which are important use cases as we start dealing with larger circuits. 
@kjsatz Can you please take a look at the benchmarks and see if it captures our discussion? Would be also good to get your perspective on what should be the target timings these benchmarks should ideally run in? (cc @maffoo as well)
Tl;Dr is that the performance right now is too slow and we'd have to make sure we address the performance bottlenecks here so that these benchmarks can run significantly faster.
```text
$> asv run -b serialization.SerializeLargeExpandedCircuits -b transformers.transformer_primitives*
· Creating environments
· Discovering benchmarks
· Running 7 total benchmarks (1 commits * 1 environments * …
```
=> Add benchmarks for transformer primitives and json serialization

cirq-core/cirq/conftest.py, cirq-google/cirq_google/engine/calibration_test.py, conftest.py, examples/conftest.py
Problem: closefigures fixture is defined in the global conftest.py,
which is not included in cirq packages.  Package archives thus
contain tests with undefined fixture.
Solution: move closefigures definition to package conftest.py files.
Also add missing import of pyplot for `test_calibration_plot_histograms`.
=> Make sure the closefigures fixture is defined

cirq-google/cirq_google/engine/engine_client.py
This resolves issues in https://github.com/grpc/grpc/issues/25364.
=> Make AsyncioExecutor a shared resource across EngineClients 

cirq-core/cirq/ops/common_channels.py
Fixes https://github.com/quantumlib/Cirq/issues/5974
https://github.com/quantumlib/Cirq/pull/1545 updated the implementation and documentation for `PhaseFlipChannel` and `BitFlipChannel` classes but forgot to update the `phase_flip` and `bit_flip` factory methods. This PR fixes the bug.
=> Fix bug in documentation of phase_flip and bit_flip methods

docs/start/basics.ipynb
Fixes the following broken link on [basics page](https://quantumai.google/cirq/start/basics#virtual_machine_simulation):
> A set of [noise models](https://quantumai.google/cirq/start/cirq/noise/representing_noise) that try...
=> Fix link to noise models

cirq-core/cirq/circuits/moment.py
The 
```
else:
return None
```
was not needed as python will do this anyway.
=> Removing unnecessary return statement in cirq-core/cirq/circuits/moment.py

cirq-core/cirq/circuits/circuit.py
Reading through, I noticed some things could be combined to reduce reading and indentation.
=> Reducing some code by cleaning up some logic

cirq-ionq/cirq_ionq/ionq_client.py
This error occurred due to a cloudflare outage, and should be retried to avoid disrupting automated usage of the libs.
=> Retry bad_gateway in cirq-ionq

asv.conf.json, cirq-core/cirq/__init__.py, cirq-core/cirq/_compat.py, cirq-core/cirq/_compat_test.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py, cirq-core/requirements.txt
This is the first PR in a series of PRs to provide cirq users to conditionally disable validations in cirq to boost runtime performance. The proposal for adding a `__cirq_debug__` flag is presented in https://github.com/quantumlib/Cirq/issues/5988
This PR adds:
1) A `cirq.__debug__` flag, which is thread safe and implemented using contextvars. The default value is set to `__debug__` global constant in python. 
2) Conditions the qid shape validations in `Gate.validate_args()`, `Operation.validate_args` and `Gate.on_each` on the value of `cirq.__debug__` flag. 
Benchmarks on my laptop show improvement of about ~20%.
```bash
$> asv run --python=same --bench XOnAllQubitsCircuit
· Discovering benchmarks
· Running 2 total benchmarks (1 commits * 2 environments * 1 benchmarks)
[  0.00%] ·· …
```
=> Add `__cirq_debug__` flag and conditionally disable qid validations in gates and operations

docs/simulate/qvm_stabilizer_example.ipynb
The indexes for keys 'abcd' should be 1~4. The index 0 is for 'meas' key (line 377).
=> Fix an error in qvm_stabilizer_example.ipynb

.github/workflows/ci.yml
The previous Typescript checks were automatically picking the latest version of Node.
Fixes: https://github.com/quantumlib/Cirq/pull/5292#issuecomment-1439113744
=> Pin Node version

cirq-ionq/cirq_ionq/ionq_client.py, cirq-ionq/cirq_ionq/ionq_client_test.py
When these occur on GETs, they can be retried.
=> IonQ: Handle 409 errors that are injected by Cloudflare

cirq-core/cirq/circuits/frozen_circuit.py, cirq-core/cirq/circuits/moment.py, cirq-core/cirq/ops/pauli_sum_exponential.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/resolve_parameters.py, cirq-core/cirq/protocols/resolve_parameters_test.py
Fixes https://github.com/quantumlib/Cirq/issues/6001
cc @maffoo @zchen088 PTAL!
=> Speed up parameter resolution by checking if val is parameterized and caching the boolean

dev_tools/notebooks/__init__.py, dev_tools/notebooks/isolated_notebook_test.py, dev_tools/notebooks/notebook_test.py, dev_tools/notebooks/utils.py, dev_tools/notebooks/utils_test.py
Do not return the OS file descriptor as it was only used for
closing that file in `rewrite_notebook` callers.
Return only the filename of the rewritten notebook.
=> Simplify dev_tools.notebooks.utils.rewrite_notebook

check/format-incremental
The bug appears to be fixed in our required version of black per
https://github.com/psf/black/issues/1629
=> Remove outdated workaround for a bug in black formatter

dev_tools/notebooks/isolated_notebook_test.py
Keep numpy version in the isolated Python environment at 1.23 as
numpy-1.24 is incompatible with cirq and numba.
Fixes stuck notebook tests which import numba.
Related to #5967
=> Ensure compatible version of numpy in isolated_notebook_test.py

dev_tools/notebooks/notebook_test.py
`test_notebooks_against_released_cirq` should not change the installed
packages in the Python pytest environment.  Adjust OS environment
so that pip invoked from tested notebooks installs to a temporary directory.
Also add test for changed packages that catches downgrade to ply==3.4
caused by a test of interop.ipynb.
=> Prevent notebook tests from changing the pytest Python environment

docs/build/interop.ipynb
Keep users safe from downgrading their ply package installed with cirq.
Related to #6032
=> Install recent version of ply in interop.ipynb

cirq-core/cirq/experiments/xeb_simulation_test.py
CI is failing on master because pytest on Windows are failing. Upon some digging, it looks like a new release of Pandas 2.0 today broke us. See https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#other-api-changes
My rough guess is that the culprit is "_pandas.testing.assert_index_equal() with parameter exact="equiv" now considers two indexes equal when both are either a RangeIndex or Index with an int64 dtype. Previously it meant either a RangeIndex or a Int64Index (GH51098)_"
I'm not fully sure why it's failing only on Windows but the change is small enough that I feel comfortable unblocking the open PRs without spending more time in investigating the root cause.
=> Fix failing CI after Pandas 2.0 update

cirq-core/cirq/contrib/svg/svg.py, cirq-core/cirq/contrib/svg/svg_test.py
If we use the symbols `<` or `>` in the circuit diagram of any gate right now, `circuit_to_svg` would result in a string that leads to a parsing error because the less than / greater than symbols are not escaped correctly. 
This PR updates the svg generation logic to correctly escape the `<` and `>` characters.
=> Update cirq.contrib.svg to escape < and > characters

cirq-core/cirq/contrib/svg/svg.py, cirq-core/cirq/contrib/svg/svg_test.py
Also parametrize `test_gate_with_less_greater_str` so it is easier to
add checks for more wire symbols later.
=> Escape both `<>` characters in SVG test labels

.github/workflows/ci-weekly.yml, dev_tools/conftest.py, dev_tools/notebooks/isolated_notebook_test.py
Verified "changed notebooks" and "all notebooks" tests run when pytest is called with the respective mark and skipped otherwise.
I didn't find a good way to test the scheduled Action. Let me know if there's a good way.
Fixes #6037
=> Add weekly CI workflow to test all notebooks 

.github/workflows/ci.yml
I ran into some strange CI failures while trying to update mypy in https://github.com/quantumlib/Cirq/pull/6059 and tracked them down to a bad cache of python dependencies. While looking at this I realized that the way we compute a cache key for python dependencies in CI is broken, since it doesn't actually take all requirements files into account.
=> Use hash of all requirements files in cache keys for ci

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/moment.py, cirq-core/cirq/devices/grid_qubit.py, cirq-core/cirq/devices/line_qubit.py, cirq-core/cirq/ops/arithmetic_operation.py, cirq-core/cirq/ops/common_gates.py, cirq-core/cirq/ops/dense_pauli_string.py, cirq-core/cirq/ops/eigen_gate.py, cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/named_qubit.py, cirq-core/cirq/ops/parity_gates.py, cirq-core/cirq/ops/pauli_gates.py, cirq-core/cirq/ops/pauli_string_raw_types.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/act_on_protocol_test.py, cirq-core/cirq/protocols/circuit_diagram_info_protocol.py, cirq-core/cirq/protocols/phase_protocol.py, cirq-core/cirq/protocols/resolve_parameters.py, cirq-core/cirq/qis/quantum_state_representation.py, cirq-core/cirq/sim/simulation_state.py, cirq-core/cirq/sim/simulation_state_base.py, cirq-core/cirq/sim/simulator_base_test.py, cirq-core/cirq/value/classical_data.py, cirq-core/cirq/value/linear_dict.py, cirq-google/cirq_google/experimental/ops/coupler_pulse.py
As described in [PEP-673](https://peps.python.org/pep-0673/), the `Self` type can be used for methods that return the same type of `self`, even when used in subclasses. This replaces explicit annotations with typevars like `TSelf`.
=> Use PEP-673 Self type annotations

.github/workflows/ci-weekly.yml, dev_tools/notebooks/isolated_notebook_test.py
Also remove the intentional test failure as
it was correctly reported by the CI.
Finalizes #6037
Reverts #6060
=> Restore weekly cadence for the CI-weekly workflow

docs/dev/serialization.md
This PR adds a blurb to the serialization docs to specify usage of JSON namespaces.
Related to (but does not fix) #4377.
=> Document json_namespace usage

cirq-core/cirq/devices/grid_qubit.py
Using `self._row` and `self._col` attributes directly instead of properties in the internals of these classes provides a significant speedup, especially since these classes are heavily used. On an internal benchmark, this reduced the total time spent in `GridQubit.__eq__` from 20.8s down to 5.7s, a 3.6x speedup.
There are other optimizations we might be able to make in the future, for example by "de-virtualizing" more methods to not rely on generic implementations in the base class, as we have already done for `GridQubit.__eq__` itself, but for now this provides a welcome performance boost.
=> Access `_row` and `_col` attributes directly in `GridQubit` instead of using properties

cirq-core/cirq/circuits/moment.py, cirq-core/cirq/circuits/moment_test.py
This adds a new classmethod `cirq.Moment.from_ops` for constructing a moment from operations without calling `flatten_to_ops`. This can save a significant amount of time in workloads that construct a lot of circuits. For example, in one internal benchmark we spend almost 3% of the total runtime in the `cirq.Moment` construct (20s out of 676s total).
This also adds functions `cirq.m` and `cirq.c` as shorthands for `cirq.Moment.from_ops` and `cirq.FrozenCircuit.from_moments`, repsectively. These are similar to the `cirq.q` helper for constructing qubit types (https://github.com/quantumlib/Cirq/pull/5181) while trying to guide users to use cirq in the most performant way: avoiding the `OP_TREE` overhead associated with the default moment and circuit constructors, and preferring …
=> Add `Moment.from_ops` to more efficiently construct moments

cirq-core/cirq/contrib/quimb/state_vector.py, dev_tools/notebooks/isolated_notebook_test.py, dev_tools/notebooks/notebook_test.py
As of quimb-1.5.0 `TensorNetwork.contract(inplace=True)` returns
TensorNetwork instead of scalar.  Convert to scalar if needed.
=> Keep up with quimb-1.5.0

docs/experiments/fourier_checking.ipynb
`use_line_collection` is deprecated and defaults to `True` anyway.
Prevent deprecation messages from showing up at
https://quantumai.google/cirq/experiments/fourier_checking
=> Remove deprecated argument of pyplot.stem

cirq-core/cirq/study/resolver_test.py
The test is not expected to fail anymore.
Also fix CI failure due to xpassing test.
=> Unblock test that requires sympy-1.12

cirq-google/cirq_google/devices/grid_device.py, cirq-google/cirq_google/devices/grid_device_test.py, cirq-google/cirq_google/devices/known_devices.py
This refactor adds the `to_proto()` method to serialize `GridDevice` into `DeviceSpecification`. The convenience method to create a `DeviceSpecification` from partial gateset information, `_create_device_specification_proto()`, is also reimplemented as `GridDevice.from_device_information()` and returns a `GridDevice` instead. These features makes using server-side GridDevice viable - Server-side and client-side GridDevice instances should now be identical.
In addition, gateset serialization and deserialization mappings are reorganized into a shared data structure.
cc @maffoo @pavoljuhas
=> GridDevice serialization refactor

cirq-core/cirq/protocols/json_test_data/Linspace.json, cirq-core/cirq/protocols/json_test_data/Linspace.repr, cirq-core/cirq/protocols/json_test_data/Points.json, cirq-core/cirq/protocols/json_test_data/Points.repr, cirq-core/cirq/study/sweeps.py, cirq-core/cirq/study/sweeps_test.py
- Adds optional metadata attribute to Linspace and Points.
- This will be used to adjust device parameters via sweep.
See https://tinyurl.com/cirq-sweep-metadata-public for RFC.
=> Add metadata to sweeps

cirq-google/cirq_google/devices/grid_device.py, cirq-google/cirq_google/devices/grid_device_test.py
This was a regression - both `GridDeviceMetadata` and `DeviceSpecification` allow isolated qubits.
=> Accept all_qubits in GridDevice._from_device_information() to allow isolated qubits

cirq-core/requirements.txt
Fixes https://github.com/quantumlib/Cirq/issues/6047
=> Loosen `networkx`  requirements

check/mypy, cirq-core/cirq/ops/classically_controlled_operation.py, cirq-core/cirq/ops/controlled_gate.py, cirq-core/cirq/ops/controlled_operation.py, cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/decompose_protocol.py, cirq-core/cirq/protocols/decompose_protocol_test.py
This is a follow-up of https://github.com/quantumlib/Cirq/pull/6116
The goal is to make sure that if a gate or operation has a `_decompose_` defined such that operations are yielded one by one (i.e. the `_decompose_()` is a generator); then `cirq.decompose(op)`  protocol should recursively decompose the yielded operations one by one. 
This guarantee ensures that, if a user allocates / deallocates new qubits as part of the `_decompose_` protocol; then all operations yielded between an allocation / deallocation request are recursively decomposed in order after the initial allocation request and before the deallocation request. 
See the added test using mocks for more details. 
Note that the default recommendation to users would be to use a `SimpleQubitManager` so they do not need to worry …
=> Ensure that cirq.decompose traverses the yielded OP-TREE in dfs ordering

cirq-core/cirq/protocols/apply_unitary_protocol.py, cirq-core/cirq/protocols/apply_unitary_protocol_test.py, cirq-core/cirq/protocols/unitary_protocol.py, cirq-core/cirq/protocols/unitary_protocol_test.py, cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/sample_gates.py, cirq-core/cirq/testing/sample_gates_test.py
This is the simplest implementation to do this in order to unblock cirq-ft. 
This implementation only satisfies the first requirement of https://github.com/quantumlib/Cirq/issues/6101#issuecomment-1568686661
In followup PRs I will address other requirements.
=> Add support for allocating qubits in decompose to cirq.unitary

cirq-ft/LICENSE, cirq-ft/README.rst, cirq-ft/cirq_ft/__init__.py, cirq-ft/cirq_ft/_version.py, cirq-ft/cirq_ft/dropme_blank_test.py, cirq-ft/setup.py, dev_tools/requirements/deps/cirq-all-no-contrib.txt
- add empty bare bones cirq-ft package
- address pylint recommendation about opening files in setup.py
- include cirq-ft/requirements.txt in cirq-all-no-contrib.txt
Partially fixes #6119
=> Add new subpackage cirq-ft

cirq-core/cirq/protocols/has_stabilizer_effect_protocol.py
Minor fix, helps speed up `has_stabilizer_effect` protocol by not computing `has_unitary(val)` when `num_qubits(val) > 1`; which can be quite expensive because `has_unitary(val)` falls back to `_unitary_`
=> Fail early in `_strat_has_stabilizer_effect_from_unitary`

cirq-core/cirq/ops/matrix_gates_test.py, cirq-core/cirq/testing/circuit_compare.py, cirq-core/cirq/transformers/heuristic_decompositions/gate_tabulation_math_utils.py
=> Replace functions deprecated in NumPy 1.25

cirq-core/cirq/ops/three_qubit_gates.py, cirq-core/cirq/ops/three_qubit_gates_test.py
The `CSWAP` / `FREDKIN` gate is self inverse but currently `cirq.FREDKIN ** -1` returns a `_InverseCompositeGate(cirq.FREDKIN)`. This PR adds a `__pow__` method to `CSwapGate` so that `cirq.FREDKIN ** -1` returns a `cirq.FREDKIN`.
=> Make `cirq.FREDKIN` gate self-inverse

cirq-core/cirq/ops/measure_util.py, cirq-core/cirq/ops/measure_util_test.py
Previously we had a check to make sure the coefficient of the paulistring passed to measure_single_paulistring had a coefficient of 1 but we support +1 and -1. Check out https://github.com/quantumlib/Cirq/issues/6137 for context.
Fixes https://github.com/quantumlib/Cirq/issues/6137
=> Allow measure_single_paulistring to have negative coefficient

.github/workflows/ci-weekly.yml, .github/workflows/ci.yml, .github/workflows/release-master.yml
Use the latest versions of GitHub actions, namely
- update actions/checkout@v2 --> v3
- update actions/setup-python@v1 --> v4
Related to #6147
=> CI - update GitHub actions

cirq-core/cirq/transformers/transformer_primitives.py, cirq-core/cirq/transformers/transformer_primitives_test.py
`cirq.map_operations` raises an error right now in the case where you map more than one operation in the same moment to an op-tree that acts on overlapping qubits. A trivial example is the case where you map every `op` to `op.controlled_by(fixed_qubit)`. 
This PR fixes the bug. See the newly added test for more context, which fails in the current version and passes after the change in this PR.
=> BugFix in `cirq.map_operations`

cirq-ft/requirements.txt
The `info` arg for `cachetools.cached()` is introduced in cachetools 5.3.0.
=> Set cachetools min version to 5.3

.github/workflows/ci.yml, cirq-core/cirq/linalg/transformations_test.py, cirq-core/cirq/ops/linear_combinations_test.py, cirq-core/cirq/ops/pauli_string_test.py, dev_tools/requirements/deps/pylint.txt, dev_tools/requirements/pylint.env.txt
dill-0.3.6 is out and hopefully will not regress #5383
=> CI - run pylint checks with dependencies installed

cirq-core/requirements.txt, dev_tools/notebooks/isolated_notebook_test.py, pyproject.toml
- remove numpy version pinning, but require major version 1
- remove warning filters which are not relevant after numpy-1.24
Follow up to #5967
=> Clean up after compatibility with numpy-1.24

conftest.py
Verify that warning filter rules are not matched and then remove them.
Clean up after #4737 which does not bite anymore
=> Remove unused warnings filter for pytest

cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/consistent_decomposition.py, cirq-core/cirq/testing/consistent_decomposition_test.py, cirq-core/cirq/testing/consistent_protocols.py, cirq-core/cirq/testing/consistent_unitary.py, cirq-core/cirq/testing/consistent_unitary_test.py, cirq-core/cirq/testing/sample_gates.py
This PR:
1. Creates `assert_unitary_is_consistent` to check that the unitary computed by falling back to decompose in the presence of ancilla is correct.
1. Updates `assert_decompose_is_consistent_with_unitary` to support gates with ancillas.
1. Fixes the gates in `sample_gate` to actually use ancillas rather than named qubits.
This completes #6101 and #6182
=> Create consistency check for unitary with ancilla

cirq-ft/cirq_ft/algos/selected_majorana_fermion_test.py, cirq-ft/cirq_ft/algos/state_preparation_test.py, cirq-ft/cirq_ft/algos/unary_iteration_gate.py
Fixes https://github.com/quantumlib/Cirq/issues/6197
The two changes are
1) Use `cirq.Simulator` to simulate operations that can allocate new ancilla qubits
2) Update unary iteration implementation to proactively allocate all required ancillas so that a `GreedyQubitManager` is not required for an optimal ancilla allocation; and a `SimpleQubitManager` also works fine. This is useful because `cirq.Simulator` by default uses `SimpleQubitManager` to decompose operations and the trivial strategy results in all Unary Iteration based gates to allocate a LOT more ancillas than needed. 
As part of looking into this issue, I also identified a general improvement that we can make to Cirq simulators s.t. for simulating operations that can allocate ancilla qubits, the simulation is optimized by …
=> Simplify `StatePreparationAliasSampling` tests by relying on Cirq simulators to simulate operations allocating ancillas

cirq-core/cirq/_compat_test.py, cirq-core/cirq/qis/measures.py, cirq-core/cirq/qis/states.py, cirq-google/cirq_google/calibration/engine_simulator.py, cirq-google/cirq_google/engine/engine_program.py, cirq-google/cirq_google/serialization/op_serializer.py, dev_tools/modules.py, dev_tools/pr_monitor.py, dev_tools/requirements/deps/pytest.txt
- pr_monitor - convert to f-strings to satisfy pylint consider-using-f-string
- and clean up some redundant fixed strings concatenations
Finalizes #6171
=> Use f-strings in the pr_monitor tool

cirq-core/cirq/contrib/quimb/Cirq-to-Tensor-Networks.ipynb, cirq-core/cirq/contrib/quimb/Contract-a-Grid-Circuit.ipynb, cirq-core/cirq/work/observable_measurement_data_test.py, cirq-rigetti/cirq_rigetti/aspen_device_test.py, dev_tools/notebooks/notebook_test.py, docs/hardware/azure-quantum/access.md, docs/hardware/azure-quantum/getting_started_honeywell.ipynb, docs/hardware/azure-quantum/getting_started_ionq.ipynb, docs/start/install.md
* Avoid interference between notebook tests.
Use separate pip target directory for each notebook test that may
pip-install additional packages.  This prevents pip upgrade of numpy in one
notebook breaking another notebook.  Even if second notebook downgrades the
numpy package with `!pip install ...` command, the high version may be
already loaded in memory and effective until kernel restart.
* Quote brackets in pip shell arguments, prevent shell globing errors.
* Clean redundant parentheses after @pytest.fixture.
Fixes #6213
=> Fix notebook failure in CI tests

cirq-core/cirq/testing/consistent_qasm_test.py, dev_tools/requirements/deps/mypy.txt, dev_tools/requirements/deps/protos.txt
Fixes https://github.com/quantumlib/Cirq/issues/6223
=> Pin mypy-protobuf version and fix failing qasm test

cirq-ft/cirq_ft/infra/gate_with_registers.py
I often hit this assertion and have to poke around to figure out which register is missing. pe -> be.
=> [Cirq-FT] Fix typo and add more helpful assertion message.

cirq-core/cirq/ops/parity_gates.py, cirq-core/cirq/ops/parity_gates_test.py
fixes #6230 by adding a `value_equality` decorator to `XXPowGate`, `YYPowGate` and `ZZPowGate` in order to override the `distinct_child_types=True` configuration they inherit from `EigenGate`
this mimics what is [already done](https://github.com/quantumlib/Cirq/blob/701538c381b13479cf6ba09216b364b43b01d2ac/cirq-core/cirq/ops/common_gates.py#L70) for `cirq.XPowGate`, `cirq.ZPowGate`, and `cirq.ZPowGate`
=> fix ms gate equality

cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/engine/engine_client.py, cirq-google/cirq_google/engine/engine_client_test.py, cirq-google/cirq_google/engine/engine_job.py, cirq-google/cirq_google/engine/engine_job_test.py, cirq-google/cirq_google/engine/engine_processor_test.py, cirq-google/cirq_google/engine/engine_test.py
* Connects the user interface of engine circuit execution with the `StreamManager` introduced in https://github.com/quantumlib/Cirq/pull/6199.
* `QuantumRunStream` supports `CreateQuantumProgramAndJob` requests, so the implementation here bypasses `EngineProgram` altogether, which will continue to use unary RPCs. This also aligns with our eventual goal of removing programs as a resource.
* `ProcessorSampler`, the recommended interface to run circuits on QuantumEngine, uses `Engine.run_sweep()` under the hood.
*Note*: Previous review history is in [this PR](https://github.com/verult/Cirq/pull/17) against my own fork. I wanted to test something with GitHub's workflow, but it totally did not work :)
@dstrain115
cc @maffoo @wcourtney
=> Integrate StreamManager with run_sweep()

codecov.yml
Avoid spurious decreases of coverage because of varying code paths
being visited at different random seeds.
Ref: https://docs.codecov.com/docs/codecovyml-reference#coverageprecision
=> codecov - evaluate coverage at 0.1% resolution

cirq-core/cirq/ops/three_qubit_gates.py, cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/consistent_controlled_gate_op.py, cirq-core/cirq/testing/consistent_controlled_gate_op_test.py, cirq-core/cirq/testing/consistent_protocols.py
Fixes https://github.com/quantumlib/Cirq/issues/6235
Also adds a consistency test `assert_controlled_unitary_consistent` to the standard suite of `assert_implements_consistent_protocols` to make sure unitaries of `gate.controlled()` and `ControlledGate()` are identical. This consistency test would have caught the bug in the original PR.
=> Fix bug in controlled() method of CCX and CCZ gates

cirq-core/cirq/circuits/circuit_operation_test.py, cirq-core/cirq/transformers/heuristic_decompositions/two_qubit_gate_tabulation.py, codecov.yml, examples/bernstein_vazirani.py, examples/deutsch.py, examples/shor.py
The `coverage` tool understands `# pragma: no cover` markup comments to exclude
code lines from coverage analysis.    The previous syntax `# coverage: ignore`
had no effect and resulted in spurious coverage changes for a different code
paths taken.
Removing the codecov.yml file, because coverage precision had no effect on
codecov complaints about decreased coverage.
=> codecov - fix syntax for excluding code lines from coverage

cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/engine/engine_client.py, cirq-google/cirq_google/engine/engine_client_test.py, cirq-google/cirq_google/engine/engine_job.py, cirq-google/cirq_google/engine/engine_job_test.py, cirq-google/cirq_google/engine/engine_processor_test.py, cirq-google/cirq_google/engine/engine_test.py
This reverts commit 86479ae738454a2e6b88f30124a4e699ce22f302.
Temporarily reverting the swap from unary to stream calls, since streaming is not yet ready on server side.
=> Revert "Integrate StreamManager with run_sweep() (#6233)"

cirq-ft/cirq_ft/algos/qrom_test.py, dev_tools/conf/pip-install-minimal-for-pytest-changed-files.sh
Problem: cirq-ft/cirq_ft/algos/qrom_test.py::test_notebook fails when
executed from `Changed files test` CI because of missing dependencies.
Solution: Install notebook-testing requirements for this CI job.
=> Fix CI requirements for Changed files test

cirq-ft/cirq_ft/algos/select_swap_qrom.py, cirq-ft/cirq_ft/algos/select_swap_qrom_test.py, cirq-ft/cirq_ft/infra/decompose_protocol.py, cirq-ft/cirq_ft/infra/decompose_protocol_test.py
This PR fixes two bugs in Cirq-FT
1) `SelectSwapQROM` is now hashable
2) `cirq_ft.t_complexity(gate)` failed for some corner cases like `cirq_ft.SwapWithZeroGate(0,4,1)**-1)` because if a gate has an empty decomposition (i.e. it's a no-op) the `_decompose_once_considering_known_decomposition` method would return a `None` instead of an empty list. The former implies we don't know the decomposition whereas the latter means the T-complexity is all 0.
=> Fix bug in cirq-ft due to which T-complexity fails for gates with an empty decomposition / no-op

cirq-core/cirq/vis/heatmap_test.py, dev_tools/cloned_env_test.py, dev_tools/notebooks/isolated_notebook_test.py, dev_tools/packaging/isolated_packages_test.py
* remove temporary isolated venv after isolated notebook/packaging test done
* remove temporary venv after cloned env test done
* remove temporary directories for figures after heatmap testings
Fix pytest and TMPDIR housekeeping (#6036)
=> Remove temporary directories after test done

check/doctest, check/pytest, check/pytest-and-incremental-coverage, check/pytest-changed-files, check/pytest-changed-files-and-incremental-coverage, dev_tools/pypath
Problem: dev_tools/pypath does not work when `python` command does
not exist causing a failure in `check/pytest` (PYTHONPATH not set).
Solution: Require that `python` starts Python 3.
Bail out from the check scripts otherwise.
=> Check if python starts python3

cirq-core/cirq/protocols/json_serialization.py
[Minor Update] First contribution. Updating documentation
=> Update documentation to prevent markdown rendering of underscores as italics.

cirq-core/cirq/vis/heatmap_test.py
Eliminate random decreases of coverage.
Make codecov coverage check happy.
=> Coverage - avoid skipping code lines on different random seeds

cirq-ionq/cirq_ionq/ionq_client.py, cirq-ionq/cirq_ionq/ionq_client_test.py, cirq-ionq/cirq_ionq/ionq_devices_test.py
changes from `User-Agent: User-Agent: cirq/1.2.0 (python/3.11.4)` to `User-Agent: cirq/1.2.0 (python/3.11.4)`
=> remove extra User-Agent

cirq-ft/cirq_ft/algos/qrom.py, cirq-ft/cirq_ft/algos/qrom_test.py, cirq-ft/cirq_ft/algos/unary_iteration_gate.py, cirq-ft/cirq_ft/infra/qubit_manager.py, cirq-ft/cirq_ft/infra/qubit_manager_test.py
Updates the unary iteration framework to allow "early termination" and uses this trick to apply the variable-spacing optimization to QROM circuits described in https://arxiv.org/pdf/2007.07391.pdf
As a drive-by fix, the PR also fixes a flaky bug in `GreedyQubitManager` where the free'd qubits were added to the pool of managed qubits in a non-deterministic order due to finding unique elements via `set(qubits)`. Replaced with an order-preserving way of finding unique elements.
=> Apply variable-spaced optimization to QROM circuits

cirq-core/cirq/sim/density_matrix_simulation_state.py, cirq-core/cirq/sim/simulation_state_test.py
For #6081.
`add/remove_qubit()` was added in #6108 and removed in #6127. I've added back the functions and updated `remove_qubit()` to `self.factor()` **inplace** to make the test (`simulation_state_test.test_delegating_gate_channel()`) pass.
The test was failing because the final density matrices were different for the control and test circuit. The `simulate(test_circuit).final_density_matrix.shape` was (2, 2, 2, 2) while `simulate(control_circuit).final_density_matrix.shape` was (2, 2). My guess was that the adding qubit was working fine but `remove_qubit()` was not able to remove the qubit. After debugging, I found that remove qubit was also working fine but `self.factor()` was not being done **inplace** and the density matrix was not getting updated during the removal of the qubit.
=> add back add/remove_qubit to density matrix sim state

cirq-google/cirq_google/cloud/quantum/__init__.py, cirq-google/cirq_google/cloud/quantum_v1alpha1/__init__.py, cirq-google/cirq_google/cloud/quantum_v1alpha1/types/__init__.py, cirq-google/cirq_google/cloud/quantum_v1alpha1/types/quantum.py, cirq-google/cirq_google/engine/engine_client.py, cirq-google/cirq_google/engine/engine_client_test.py
The update is no longer a breaking change.  Note that I force pushed (because the refactor was quite heavy), so most comments from the first round are outdated.
=> Support the new quantum engine processor_selector in engine_client

codecov.yml
Ref: https://docs.codecov.com/docs/ignoring-paths
=> codecov - exclude protobuf-generated sources from coverage analysis

cirq-core/cirq/study/resolver.py, cirq-core/cirq/value/duration.py, cirq-core/cirq/value/duration_test.py
Fixes https://github.com/quantumlib/Cirq/issues/6269
cc https://github.com/quantumlib/Cirq/issues/6097
=> Speed up parameter resolution for `cirq.Duration`

cirq-google/cirq_google/engine/abstract_processor.py, cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/engine/engine_client.py, cirq-google/cirq_google/engine/engine_processor.py, cirq-google/cirq_google/engine/engine_program.py, cirq-google/cirq_google/engine/engine_test.py, cirq-google/cirq_google/engine/processor_sampler.py, cirq-google/cirq_google/engine/processor_sampler_test.py, cirq-google/cirq_google/engine/simulated_local_processor.py
This pull request (PR) adds two new parameters to the run methods of `EngineProgram`, `Engine`, and `EngineProcessor`: `run_name` and `device_configuration_name`. These parameters allow users to select a specific configuration for the processor when running the circuit. They are also added to the `init` function of `ProcessorSampler` (and the `get_sampler` methods within `Engine` and `EngineProcessor`).
Additionally, the run methods of `EngineProgram` and `Engine` now include a parameter called `processor_id`. This parameter can be used to specify a specific processor for the run, and will substitute the deprecated parameter `processor_ids` , because allowing multiple candidate processors was not useful in practice.
=> Add new processor selector parameters in cirq-google/engine run methods

cirq-core/cirq/ops/dense_pauli_string.py, cirq-core/cirq/ops/linear_combinations.py, cirq-core/cirq/value/value_equality_attr.py
Fixes https://github.com/quantumlib/Cirq/issues/6272
cc https://github.com/quantumlib/Cirq/issues/6097
Benchmarks can be seen by running
```python
>>> gate = cirq.PhasedXZGate.from_matrix(cirq.testing.random_unitary(2))
>>> %timeit hash(gate)
```
Before
```
2.67 µs ± 52.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
After
```
159 ns ± 2.75 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
A more real world example would be QROM in Cirq-FT, where `value_equality_values` returns all the data to be loaded by the QROM. Benchmarks as follows
```python
>>> qrom = cirq_ft.QROM.build([1, 2, 3, 4, 5] * 10_000)
>>> %timeit cirq_ft.t_complexity(qrom)
```
Before
```
```
After
```
```
=> Add caching to `value_equality_values` decorator for auto generated methods.

cirq-ft/cirq_ft/algos/qrom.py, cirq-ft/cirq_ft/algos/qrom_test.py
Fixes https://github.com/quantumlib/Cirq/issues/6279
=> Variable spacing QROM should depend upon structure of different data sequences and not exact elements

cirq-google/cirq_google/engine/stream_manager.py, cirq-google/cirq_google/engine/stream_manager_test.py
This PR builds on top of https://github.com/quantumlib/Cirq/pull/6253 . Please review the last two commits.
This fix stemmed from the issue that requests were not sent after a stream breaks and reopens. The root cause is that the request iterator from the previous stream is still running, and although the Quantum Engine client doesn't actively yield from the iterator, the iterator still dequeues from the request queue behind the scenes.
This PR adds a dedicated stop signal to be sent to the request queue to signal that the iterator should stop. In addition to the issue above, this also addresses the TODO that the request iterator should be closed upon stream closing in order to send a half close to the server.
To make this fix work, I also made the request queue local to the execution and …
=> StreamManager: Add mechanism to close the request iterator

cirq-core/cirq/devices/insertion_noise_model.py, cirq-core/cirq/devices/insertion_noise_model_test.py, cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/protocols/json_test_data/InsertionNoiseModel.json, cirq-core/cirq/protocols/json_test_data/InsertionNoiseModel.repr
1. Add ```_json_dict``` and ```_from_json_dict_``` magic functions to support
2. Add InsertionNoiseModel in resolver cache
Fixes quantumlib/Cirq#6249
=> Add serialization support for InsertionNoiseModel

cirq-core/cirq/ops/fsim_gate.py
In the docstring for the FSimGate, the unitary is reported to be:
```python
a = cos(theta)
b = -1j*sin(theta)
c = exp(+1j*phi)
[
[1, 0, 0, 0],
[0, a, b, 0],
[0, b, a, 0],
[0, 0, 0, c],
]
```
However, the actual unitary produced by the gate is slightly different. Specifically, the term `c` is exp(-1j*phi). The snippet below demonstrates:
```python
import numpy as np
import cirq
theta = np.pi/4
phi = np.pi/6
cirq.unitary(cirq.FSimGate(theta, phi))
actual_c = cirq.unitary(cirq.FSimGate(theta, phi))[3,3]
doc_c = np.exp(1j*phi)
print(f"FSimGate element (3,3) is {actual_c:.4f}, Documentation is {doc_c:.4f}")
```
The snippet reports that the value of `c` is `0.8660-0.5000j` while the documentation indicates it should be `0.8660+0.5000j`.
I believe the gate definition is correct and the …
=> Correct unitary in the docstring of the FSimGate

cirq-core/cirq/contrib/svg/svg.py, cirq-core/cirq/devices/named_topologies.py, cirq-core/cirq/experiments/qubit_characterizations.py, cirq-core/cirq/linalg/decompositions.py, cirq-core/cirq/vis/heatmap.py, cirq-core/cirq/vis/heatmap_test.py, cirq-core/cirq/vis/histogram.py, cirq-core/cirq/vis/state_histogram.py, cirq-core/cirq/vis/state_histogram_test.py, cirq-google/cirq_google/engine/calibration.py, cirq-google/cirq_google/engine/virtual_engine_factory.py, docs/experiments/textbook_algorithms.ipynb, docs/start/intro.ipynb, examples/two_qubit_gate_compilation.py
matplotlib 3.8.0 was released this week and included typing hints. This fixes the resulting CI breakages.
=> Fix matplotlib typing

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/interop/quirk/url_to_circuit.py, cirq-core/cirq/protocols/apply_channel_protocol.py
- quirk_url_to_circuit and quirk_json_to_circuit had weird HTML in them.
- concat_ragged had a bunch of pre tags in the output.
I believe these changes fix the markdown generation.
=> Apply some minor doc fixes

cirq-google/cirq_google/ops/internal_gate.py, cirq-google/cirq_google/ops/internal_gate_test.py
Currently `InternalGate` includes a dict in `_value_equality_values_`, so it is never hashable even if all gate args are hashable. Change to use a frozenset of items instead to make it hashable. We also change to store constructor kwargs directly instead of copying the kwargs dict, since `**kwargs` passed in to a function is always a unique dictionary which won't alias a caller's dict.
=> Make InternalGate hashable if all gate args are hashable

cirq-core/cirq/ops/common_channels.py
Docstring does not render correctly on the website: https://quantumai.google/reference/python/cirq/GeneralizedAmplitudeDampingChannel
Maybe putting this equation on one line will fix it?
=> Try to make docstring render correctly

cirq-ft/cirq_ft/algos/swap_network.py, cirq-ft/cirq_ft/infra/gate_with_registers.ipynb, cirq-ft/cirq_ft/infra/gate_with_registers.py, cirq-ft/cirq_ft/infra/gate_with_registers_test.py
Adds back the `bitsize` field to Cirq-FT registers. This brings the Cirq-FT registers another step closer to Qualtran registers and makes the interop easier. 
This PR follows a brute force approach where the special meaning of `bitsize` is lost. In general, a qubit register with `bitsize=K`  should behave like a `2 ** K` dimension Qudit, instead of a K-qubit register. However, Cirq currently does not provide any way to express decomposition of gates acting on qudits in terms of other "simpler" gates that act on individual qubits. In Qualtran, this is expressed using `Split` and `Join` operations, but Cirq does not have an analogous concept. 
In future, we can consider extending the Cirq infrastructure to support gates acting on Qudits with decompositions that manipulate the 2 dimensional …
=> Add `bitsize` field to Cirq-FT Registers

cirq-ft/cirq_ft/algos/and_gate.py, cirq-ft/cirq_ft/algos/apply_gate_to_lth_target.py, cirq-ft/cirq_ft/algos/prepare_uniform_superposition.py, cirq-ft/cirq_ft/algos/qrom.py, cirq-ft/cirq_ft/algos/selected_majorana_fermion.py, cirq-ft/cirq_ft/algos/state_preparation.py, cirq-ft/cirq_ft/infra/gate_with_registers.py, cirq-ft/cirq_ft/infra/gate_with_registers_test.py
Registers with bitsize 0 are ambiguous since they you are not really passing any qubits to instantiate those registers. They also complicate the interop with Qualtran. This PR removes this workflow by adding an explicit validation that `bitsize` should always be a positive integer. 
cc @mpharrigan
=> Do not allow creating registers with bitsize 0

cirq-ft/cirq_ft/algos/and_gate.py, cirq-ft/cirq_ft/algos/and_gate_test.py, cirq-ft/cirq_ft/algos/hubbard_model.py, cirq-ft/cirq_ft/algos/multi_control_multi_target_pauli.py, cirq-ft/cirq_ft/algos/prepare_uniform_superposition.py, cirq-ft/cirq_ft/algos/qrom.py, cirq-ft/cirq_ft/algos/unary_iteration_gate.py, cirq-ft/cirq_ft/infra/jupyter_tools_test.py, cirq-ft/cirq_ft/infra/testing_test.py
After https://github.com/quantumlib/Cirq/pull/6300, Cirq-FT registers can now be directional (LEFT / RIGHT). This PR changes the signature of `And` gate to use directional registers s.t. it matches the signature of `And` Bloq in `Qualtran`.  This is the only gate right now that should use directional signatures in Cirq-FT. 
cc @fdmalone @mpharrigan
=> Change signature of `cirq_ft.And` gate to use directional registers like Qualtran

cirq-ft/cirq_ft/algos/arithmetic_gates.py, cirq-ft/cirq_ft/algos/arithmetic_gates_test.py
Fixes https://github.com/quantumlib/Qualtran/issues/388
cc @fdmalone
=> Make `SingleQubitCompare` output registers directional

cirq-ft/cirq_ft/algos/arithmetic_gates.py
Similar fix as #6312 and fixes quantumlib/qualtran#389
=> Make ancilla for BiQubitsMixer sided too.

cirq-core/cirq/__init__.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/analytical_decompositions/__init__.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_state_preparation.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_state_preparation_test.py
this PR adds a version of the 'prep_two_qubit_state' methods but for a full iswap instead of a sqrt_iswap
=> Adds 2q prep for iswap instead of sqrt_iswap

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/circuits/frozen_circuit_test.py
Preserving subcircuits is very useful internally because we use subcircuit identity when compiling to hardware to guide waveform reuse. Note that previously if a circuit was passed to `from_moments` it would be passed to `Moment` which would fail for any circuit that had multiple moments with gates on the same qubit, because those could not be collapsed into a single moment. Single-moment circuits would've worked in the past and they will continue to work but will now being contained in a circuit operation.
Here's an example of a single-moment circuit:
```python
circuit = Circuit.from_moments(
FrozenCircuit(Moment(X(q0), X(q1)))
)
circuit == Circuit(
Moment(X(q0), X(q1))
)
circuit == Circuit(
Moment(
CircuitOperation(
FrozenCircuit(Moment(X(q0), X(q1)))
)
)
)
```
Here's an example of a …
=> Preserve subcircuits passed to `[Frozen]Circuit.from_moments`

.github/workflows/ci-daily.yml, cirq-ft/cirq_ft/algos/qrom_test.py, cirq-ft/cirq_ft/algos/qubitization_walk_operator_test.py, cirq-ft/cirq_ft/algos/reflection_using_prepare_test.py, cirq-ft/cirq_ft/algos/select_swap_qrom_test.py, cirq-ft/cirq_ft/algos/selected_majorana_fermion_test.py, cirq-ft/cirq_ft/algos/state_preparation_test.py, cirq-ft/cirq_ft/algos/unary_iteration_gate_test.py
* Add slow marks to the unit tests with over 20 second duration.
* Adjust ci-daily job so it runs all slow tests.
* And add ci-daily jobs for Windows and MacOS operating systems
so that slow tests get tested on those platforms too.
Refs: 
* https://github.com/quantumlib/Cirq/issues/6211#issuecomment-1780471939
* https://github.com/quantumlib/Cirq/issues/6211#issuecomment-1784412539
Resolves #6211
=> ci - skip slow tests on PR, run them in daily ci instead

.github/workflows/ci.yml
No change in the test execution, just a bit more output for the
`Pytest Ubuntu`, `Pytest Windows`, and `Pytest MacOS` jobs.
Related to #6211
=> ci - show 20 slowest tests on Linux, Windows and Mac

.github/workflows/ci-daily.yml, cirq-ft/cirq_ft/algos/and_gate_test.py, cirq-ft/cirq_ft/algos/apply_gate_to_lth_target_test.py, cirq-ft/cirq_ft/algos/generic_select_test.py, cirq-ft/cirq_ft/algos/hubbard_model_test.py, cirq-ft/cirq_ft/algos/qrom_test.py, cirq-ft/cirq_ft/algos/qubitization_walk_operator_test.py, cirq-ft/cirq_ft/algos/state_preparation_test.py, cirq-ft/cirq_ft/algos/swap_network_test.py, cirq-ft/cirq_ft/algos/unary_iteration_gate_test.py, cirq-ft/cirq_ft/infra/gate_with_registers_test.py, cirq-ft/cirq_ft/infra/t_complexity_protocol_test.py, dev_tools/notebooks/notebook_test.py, dev_tools/packaging/isolated_packages_test.py
* Fix requirements installation for Windows
* Run notebook tests only on Linux platform
* Run test_isolated_packages on POSIX platforms only
Temporary workaround for #6336
=> Fix ci-daily pytest failure

cirq-web/cirq_web/widget_test.py
Exercise the `open_in_browser` argument in the
`test_generate_html_file_with_browser` test, but
do not open a new tab or steal UI focus for the browser.
=> Run unit tests without affecting browser session

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/circuits/frozen_circuit.py
This simplifies working with frozen circuits and circuit identity by storing the `FrozenCircuit` instance returned by `Circuit.freeze()` and returning the same instance until it is "invalidated" by any mutations of the Circuit itself. Note that if we make additional changes to the Circuit implementation, such as adding new mutating methods, we will need to remember to add `self._frozen = None` statements to invalidate the frozen representation in those places as well. To make this easier to audit, I have put these invalidation statements immediately after any mutation operations on `self._moments`, even in places where some invalidations could be elided or pushed to the end of a method; it seems safer to keep these close together in the source code. I have also added an implementation …
=> Cache `Circuit` properties between mutations

cirq-core/cirq/experiments/fidelity_estimation_test.py
Increase tolerance for fidelities calculated with and without state
vector amplitudes.  Avoid flaky, random-seed dependent test failures
on a slightly excessive difference.
Example: https://github.com/quantumlib/Cirq/actions/runs/6726576064/job/18283075054#step:6:598
=> Fix flaky behavior of test_xeb_fidelity

cirq-core/cirq/ops/parity_gates.py, cirq-core/cirq/ops/parity_gates_test.py, cirq-core/cirq/ops/pauli_gates_test.py
part of https://github.com/quantumlib/Cirq/issues/5906#issuecomment-1791466853
=> Increase coverage of clifford protocols to parity_gates

cirq-google/cirq_google/engine/stream_manager.py, cirq-google/cirq_google/engine/stream_manager_test.py
This PR fixes a race condition that occurred roughly every 10-15min by adding a retry with `GetQuantumResultRequest` when `StreamManager` receives a program or job already exists error. The sequence is as follows:
1. The client sends a CreateProgramAndJobRequest
1. The client's stream disconnects
1. The client retries with a new stream and a GetResultRequest
1. The job doesn't exist yet, and the client receives a "job not found" error
1. Scheduler creates the program and job.
1. The client retries with a CreateJobRequest and fails with a "job already exists" error
This would cause issues when a user specifies a `program ID` or `job ID` in `Engine.run_sweep()` or `EngineProcessor.run_sweep()` rather than letting the client generate the ID, because there could be a real ID conflict. …
=> StreamManager: retry with get result request on already exist errors

cirq-core/cirq/sim/simulator_test.py, cirq-core/cirq/study/resolver.py, cirq-core/cirq/study/resolver_test.py, cirq-ionq/cirq_ionq/sampler_test.py
This cleans up the logic in `ParamResolver.value_of` and makes a few optimizations:
- Throughout `ParamResolver`, refer to `self._param_dict` instead of the `self.param_dict` property.
- In `ParamResolver.value_of`, handle the cases of resolving a string or symbol in a more straightforward way by checking for their presence in the param dict (when resolving a string we check for both a str and symbol, and similarly when resolving a symbol). If the str or symbol is not found, we can immediately return the symbol without calling through to sympy substitution logic, which was being invoked previously. If the value is found, we check whether it is a "pass through" resolvable value and whether it needs to be resolved recursively and then return.
These changes ensure that sympy substitution …
=> Optimize ParamResolver.value_of

cirq-core/cirq/devices/grid_qubit.py, cirq-core/cirq/devices/grid_qubit_test.py, cirq-core/cirq/devices/line_qubit.py, cirq-core/cirq/ops/named_qubit.py
This speeds up hashing on `GridQubit`, `GridQid`, `LineQubit`, and `LineQid`. Instead of using `_compat.cached_method`, we store an explicit `self._hash` property to cache computing the hash. We also make the constructors explicit in the concrete classes with no need to call a subperclass constructor. We did some basic benchmarks to compare performance with current master. On this branch `GridQubit.__hash__` dropped from 1.3us to 488ns (2.66x speedup), while repeated hashing of the same grid qubit dropped from 150ns to 121ns (1.24x speedup). Similarly, `LineQubit.__hash__` dropped from 685uns to 453ns (1.51x speedup), while repeated hashing of the same line qubit dropped from 142ns to 124ns (1.15x speedup).
On master:
```python
In [2]: gq = cirq.GridQubit(1, 2)
In [3]: %timeit hash(gq) …
```
=> Speed up hashing for GridQubit, LineQubit, and NamedQubit

cirq-core/cirq/circuits/qasm_output_test.py, cirq-core/cirq/contrib/paulistring/clifford_target_gateset_test.py, cirq-core/cirq/experiments/xeb_fitting_test.py, cirq-core/cirq/experiments/xeb_sampling.py, cirq-core/cirq/ops/clifford_gate_test.py, cirq-core/cirq/ops/common_channels_test.py, cirq-core/cirq/ops/common_gates_test.py, cirq-core/cirq/ops/gate_features_test.py, cirq-core/cirq/ops/pauli_string_raw_types_test.py, cirq-core/cirq/ops/pauli_string_test.py, cirq-core/cirq/ops/random_gate_channel_test.py, cirq-core/cirq/ops/raw_types_test.py, cirq-core/cirq/protocols/act_on_protocol_test.py, cirq-core/cirq/protocols/apply_unitary_protocol_test.py, cirq-core/cirq/protocols/equal_up_to_global_phase_protocol_test.py, cirq-core/cirq/protocols/unitary_protocol_test.py, cirq-core/cirq/sim/simulation_state_test.py, cirq-core/cirq/sim/simulator_test.py, cirq-core/cirq/testing/gate_features_test.py, cirq-core/cirq/transformers/expand_composite_test.py, cirq-core/cirq/transformers/merge_k_qubit_gates_test.py, cirq-core/cirq/transformers/stratify.py, cirq-core/cirq/transformers/target_gatesets/compilation_target_gateset_test.py, cirq-core/cirq/transformers/target_gatesets/cz_gateset_test.py, cirq-core/cirq/work/observable_measurement_test.py, cirq-core/cirq/work/zeros_sampler.py
- Latest best practice advice is to remove all mentions of the word 'dummy' as it is problematic terminology.
=> Remove dummy from cirq-core

cirq-google/cirq_google/engine/processor_sampler.py, cirq-google/cirq_google/engine/processor_sampler_test.py
This is part of deprecating support for Quantum Engine batch programs, while keeping the `cirq.Sampler.run_batch()` interface.
cc @eliottrosenberg @wcourtney
=> ProcessorSampler: route run_batch to run_sweep

docs/start/install.md
To install the mactex cask with the current version of Homebrew, the command should be changed.
See also https://github.com/orgs/Homebrew/discussions/902
=> Fix brew cask install mactex command in macOS tutorial.

cirq-aqt/cirq_aqt/aqt_sampler_test.py, cirq-ft/cirq_ft/algos/mean_estimation/complex_phase_oracle_test.py, cirq-ft/cirq_ft/infra/jupyter_tools_test.py, cirq-google/cirq_google/calibration/engine_simulator_test.py, cirq-google/cirq_google/workflow/processor_record_test.py
Follow up to #6356.  Replace non-inclusive terminology.
=> Remove leftover dummy terms from Cirq sources

cirq-core/cirq/_compat_test.py, cirq-core/cirq/testing/_compat_test_data/__init__.py, cirq-core/cirq/testing/_compat_test_data/module_a/__init__.py
Fixes #6373.
Note that using multiprocessing with "spawn" is significantly slower than either "fork" or "forkserver", but it ensures that the subprocesses are isolated so is significantly safer. We can switch back in the future to improve performance if we can work out the issues, but for now I think using spawn is more robust.
=> Use spawn in _compat_test.py to avoid fork problems

cirq-core/cirq/_compat_test.py, cirq-core/cirq/value/value_equality_attr.py
We often reuse instances of objects with value semantics, and in such cases equality checking can be short-circuited by first checking for object identity before falling back to actually comparing the values of two objects. This is particular beneficial if we actually take care to reuse instances, which is something we should consider doing more generally to avoid object allocation and repeated computation of various properties such as hashes (see https://github.com/quantumlib/Cirq/pull/6371).
=> Short-circuit value equality with an identity check

cirq-core/cirq/_compat.py
Previously, the first time a no-arg cached method was called the decorator would make three calls: `hasattr`, `object.__setattr__`, `getattr`, and when called subsequently it would make two calls: `hasattr`, `getattr`. Here we refactor the implementation to use a sentinel value so that on the first call we only make two calls: `getattr`, `object.__setattr__`, and when called subsequently we only make a single `getattr` call.
=> Optimize cached_method when wrapping no-arg methods

cirq-core/cirq/devices/grid_qubit.py, cirq-core/cirq/devices/line_qubit.py, cirq-core/cirq/ops/named_qubit.py
Qid comparison turns out to be a very common operation when manipulating circuits, for example when computing the hash of a moment we sort operations by qubits in order to have a canonical order for hashing. Here we optimize the comparison of common qid types for grid, line, and named qubits.
=> Optimize qid comparisons

cirq-core/cirq/experiments/qubit_characterizations.py, cirq-core/cirq/experiments/qubit_characterizations_test.py
Adds exponential fitting in order to extract the single-qubit error rates from the measured data.
=> Add exponential fitting to RandomizedBenchMarkResult

cirq-core/cirq/circuits/circuit.py
Add identity check to short-circuit exact and approximate equality checks on `cirq.AbstractCircuit` and subclasses. Also change the implementation of `__eq__` to avoid creating new tuples of moments; instead we check the length and then zip over the moments.
=> Check value equality first when comparing circuits

cirq-core/cirq/circuits/moment.py
Same optimization as done for circuits in #6375.
=> Check identity first when comparing moments

cirq-core/cirq/ops/raw_types.py
The value received from `*qubits` is a tuple, and `GateOperation.__init__` would immediately convert the passed-in list back to a tuple anyway, so we can save on lots of small allocations by just passing the tuple of args through to `GateOperation`.
=> Don't create a new list of qubits in `Gate.on`

rtd_docs/requirements.txt
As of alabaster-0.7.14 the alabaster theme package requires sphinx 3.4
which conflicts with the current sphinx requirement.
As a quick fix we pin to alabaster-0.7.13 here.
Temporary workaround for #6400
=> Fix "Build docs" CI job by temporarily pinning alabaster to 0.7.13

cirq-core/cirq/experiments/qubit_characterizations.py, cirq-core/cirq/experiments/qubit_characterizations_test.py, cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/qis/clifford_tableau.py
SingleQubitCliffordGates represents the 24 gates in the single qubit clifford group. Some of the operations this class implements are expensive computation but at the same time are properties of each of the 24 operators.
turning those expensive computations into cached properties is benificial for performance but for that the objects need to be immutable.
one of the places that heavily relies on single qubit cliffords is `qubit_characterizations.py` which implemented the single qubit clifford algebra from scratch by falling on to the matrix representation and doing matrix multiplication and inversion (for computing the adjoint) this led to a bottleneck while creating circuits (e.g. for example _create_parallel_rb_circuit for 50 qubits and a 1000 gates takes $3.886s$). using …
=> make SingleQubitCliffordGate immutable singletons and use it in qubit_characterizations for a 37% speedup

rtd_docs/requirements.txt
=> Pin sphinx dependencies that require Sphinx 5.0 or later

cirq-core/cirq/experiments/qubit_characterizations.py, cirq-core/cirq/experiments/qubit_characterizations_test.py
SingleQubitCliffordGates fail the gateset check of the grid device https://github.com/quantumlib/Cirq/blob/a3eed6b97490556cf1dda82928a0aa9ea8798da1/cirq-google/cirq_google/devices/grid_device.py#L43-L64. while the objects fail the check the operations themselves are supported but after coversion to a supported format like phased xz
this was missed from #6420
=> convert identity to phased xz in qubit characterization

cirq-core/cirq/contrib/requirements.txt, dev_tools/requirements/deps/notebook.txt
fixes https://github.com/quantumlib/Cirq/issues/6437
older versions of quimb use a numbda decorator that no longer exists. the recent release of quimb fixes that https://github.com/jcmgray/quimb/blob/0f9db3f7b81e50375b5001296bfc2b767a7e557d/docs/changelog.md however it breaks tests in `/contrib/quimb` so will pin the versions for now.
=> pin quimb and numba versions to fix CI

cirq-core/cirq/contrib/svg/svg.py
As per https://matplotlib.org/3.5.0/api/font_manager_api.html#matplotlib.font_manager.FontProperties `Arial` is not a valid font family with the only options being ` 'sans-serif' (default), 'serif', 'cursive', 'fantasy', or 'monospace'`
The invalid input doesn't raise an error and instead fails silently with a warning message which is visible [in the notebooks](https://quantumai.google/cirq/noise/qcvv/xeb_theory#random_circuit) 
As per https://github.com/matplotlib/matplotlib/blob/f0c4c41d1a08bc3f53824cddc8fef7f88fc52a43/lib/matplotlib/mpl-data/stylelib/seaborn-v0_8.mplstyle#L18 Arial is part of the `sans-serif` family which is the default
=> Fix font family for svg

cirq-core/cirq/transformers/optimize_for_target_gateset.py, cirq-core/cirq/transformers/optimize_for_target_gateset_test.py, cirq-core/cirq/transformers/target_gatesets/compilation_target_gateset.py, cirq-core/cirq/transformers/target_gatesets/cz_gateset.py
fixes https://github.com/quantumlib/Cirq/issues/6422 as suggested by @tanujkhattar https://github.com/quantumlib/Cirq/issues/6422#issuecomment-1915363510
calling `optimize_for_target_gateset` with `gateset=cirq.CZTargetGateset(preserve_moment_structure=True)` and `max_num_passes` equal a value >= 2 or None) produces the desired result
=> Add an optional CompilationTargetGateset postprocessor to contract the circuit

.github/workflows/ci-daily.yml, .github/workflows/ci-weekly.yml, .github/workflows/ci.yml, .github/workflows/release-main.yml
Address deprecation warnings in CI workflow annotations at
https://github.com/quantumlib/Cirq/actions/runs/7792545465
Namely update to
* actions/cache@v4 per https://github.com/actions/cache/releases/tag/v4.0.0
* actions/checkout@v4 per https://github.com/actions/checkout/blob/main/CHANGELOG.md
* actions/setup-node@v4 per https://github.com/actions/setup-node/releases/tag/v4.0.0
* actions/setup-python@v5 per https://github.com/actions/setup-python/releases/tag/v5.0.0
=> CI - update GitHub actions to node20

.github/workflows/ci-daily.yml, dev_tools/requirements/deps/notebook.txt
Use common version specification for quimb and numba as defined in
contrib/requirements.txt.  And install notebook dependencies for all CI platforms.
Avoid incompatible versions of quimb and numba in notebook environments.
Example failure: https://github.com/quantumlib/Cirq/actions/runs/7792626671/job/21250976788#step:6:580
Fix verified at https://github.com/quantumlib/Cirq/actions/runs/7805446772
Related to #6336
=> Fix ci-daily notebook failures on Mac OS X

cirq-core/cirq/experiments/__init__.py, cirq-core/cirq/experiments/two_qubit_xeb.py, cirq-core/cirq/experiments/two_qubit_xeb_test.py
This way the notebook https://quantumai.google/cirq/noise/qcvv/parallel_xeb becomes
```py3
>>> res = cirq.experiments.parallel_two_qubit_xeb(sampler)
>>> res.plot_heatmap()
```
=> Combine 2q parallel XEB into one methods to simplify the XEB workflow

pyproject.toml
This is an intended behavior in tests.
=> Suppress matplotlib warnings on non-interactive use of pyplot.show

cirq-core/requirements.txt
Duet is up to 0.3.0.dev and we'd like to continue to be able to use this internally with cirq.
=> Relax version requirement on duet

.github/workflows/ci.yml
Ref: https://docs.codecov.com/docs/adding-the-codecov-token
This should fix `Codecov: Failed to properly create commit`
warnings in the CI output.
=> Specify CODECOV_TOKEN for uploading coverage reports

cirq-core/cirq/experiments/__init__.py, cirq-core/cirq/experiments/two_qubit_xeb.py, cirq-core/cirq/experiments/two_qubit_xeb_test.py
This PR:
- Adds the option to specify the qubits to the XEB workflow
- Adds pauli error computation for 2q XEB
- Adds `InferredXEBResult` class which
- computes inferred errors: pauli, XEB, and decay constant
- has a convenience method to plot heatmap for each of the errors
- has a convenience method to plot histogram of each of the erros.
=> Combine RB and XEB to compute inferred errors

cirq-core/cirq/contrib/quimb/Contract-a-Grid-Circuit.ipynb, dev_tools/notebooks/isolated_notebook_test.py
Enable Contract-a-Grid-Circuit.ipynb in notebook tests
Fixes #6088
=> Enable testing of quimb-dependent notebook

cirq-core/cirq/protocols/has_stabilizer_effect_protocol.py, cirq-core/cirq/protocols/has_stabilizer_effect_protocol_test.py
Fixes https://github.com/quantumlib/Qualtran/issues/665
@NoureldinYosri Do you remember why you added the following check? 
```python
qid_shape = qid_shape_protocol.qid_shape(val, default=None)
if qid_shape is None or len(qid_shape) <= 3:
return None
```
=> Bugfix in `_strat_has_stabilizer_effect_from_decompose`

cirq-core/cirq/study/result.py, cirq-core/cirq/study/result_test.py
- ResultDict will now print out repeated measurements on each line, as opposed to throwing ValueError
Fixes: #6447
=> Change str of ResultDict to print out repeated measurements

cirq-core/requirements.txt
The `1.3.*` pattern is invalid in `install_requires` context.
The `mpmath<1.4` spec prohibits pre-releases of 1.4 such as 1.4.0a0.
Related to #6475
=> Fix maximum version limit for mpmath

dev_tools/docker_test.py
=> Enable test_docker_pre after pinning the mpmath transitive dependency

cirq-core/cirq/experiments/t1_decay_experiment.py, cirq-core/cirq/experiments/t1_decay_experiment_test.py
Makes two changes to the $T_1$ experiment in Cirq:
1.  Changes the fit function to $f(t) = A e^{-t/T_1} + B$ instead of just $f(t) = e^{-t/T_1}$ to capture the effects of SPAM errors.
2. Makes the wait times logarithmically spaced instead of linearly spaced, which is more suitable since we expect an exponential decay.
=> Update T1 experiment

.github/workflows/ci-daily.yml, .github/workflows/ci-weekly.yml, .github/workflows/ci.yml, .github/workflows/release-main.yml, Dockerfile, asv.conf.json, benchmarks/README.md, dev_tools/packaging/packaging_test.sh, dev_tools/pr_monitor/Dockerfile, docs/dev/development.md, docs/start/install.md, release.md
first step towards dropping py3.9 in cirq1.4 https://github.com/quantumlib/Cirq/issues/6463
=> Remove python3.9 from CI tests

.zenodo.json, README.rst, dev_tools/notebooks/notebook_test.py, docs/dev/rfc_process.md, docs/dev/triage.md, docs/experiments/_index.yaml, docs/simulate/virtual_engine_interface.ipynb
- Saw an old PR to replace Github with proper capitalization of GitHub.
- This PR does this on a more consistent basis and updates that PR.
- Replaces #5961
=> Fix capitalization of GitHub in docs

cirq-core/cirq/__init__.py, cirq-core/cirq/protocols/json_test_data/spec.py, cirq-core/cirq/study/__init__.py, cirq-core/cirq/study/sweeps.py, cirq-core/cirq/study/sweeps_test.py
Since this is a singleton, it should use constant naming. Since it should also stay consistent with other Sweeps (and for backwards compatibility), we will keep the old name as well.
Fixes: #5617
=> Add UNIT_SWEEP as an alias for UnitSweep

.github/workflows/ci-daily.yml
Install development version of cirq, but with stable dependencies.
Avoid using the pip-install `--pre` option because it installs
pre-release of every direct and transitive dependency.
Example failure: https://github.com/quantumlib/Cirq/actions/runs/8444592307/job/23130415923
Pass with this change: https://github.com/quantumlib/Cirq/actions/runs/8460206027/job/23179852811
Related to #6336
=> Fix ci-daily workflow failures on Mac OS X

cirq-core/requirements.txt
Version limit on mpmath is unnecessary after #6534 because
cirq pre-releases are now installed with stable dependencies.
This reverts commit e11132e391c5c13377416b62af6a9aad8861f839 (#6477).
Related to #6475
=> Undo temporary version pin of mpmath

cirq-google/cirq_google/__init__.py, cirq-google/cirq_google/json_resolver_cache.py, cirq-google/cirq_google/json_test_data/FSimViaModelTag.json, cirq-google/cirq_google/json_test_data/FSimViaModelTag.repr, cirq-google/cirq_google/ops/__init__.py, cirq-google/cirq_google/ops/fsim_via_model_tag.py, cirq-google/cirq_google/ops/fsim_via_model_tag_test.py
The motivation of creating this tag is for the qcc/translate part. We can use this tag to control which implementation gate we want to translate it into.
CC: @maffoo @eliottrosenberg
=> Add FSimViaModelTag

cirq-core/cirq/sim/simulation_state.py, cirq-core/cirq/sim/state_vector_simulation_state.py
- These simulators do not use density matrices.
Fixes: #6225
=> Fix density matrix references in other simulators

cirq-core/requirements.txt
context: https://github.com/quantumlib/Cirq/issues/6543
=> pin scipy to ~1.12.0 to temporarily fix ci

.github/workflows/ci-daily.yml, .github/workflows/ci.yml, dev_tools/conf/apt-list-dev-tools.txt, docs/dev/development.md
Recent GHA runner images require docker-compose v2.
Refs:
https://github.com/actions/runner-images/blob/ubuntu20/20240401.4/images/ubuntu/Ubuntu2004-Readme.md
https://docs.docker.com/compose/migrate/
Fixes #6546
=> CI - migrate to docker compose v2

cirq-core/requirements.txt
In order to avoid the conflict of dependency with pyle
```
SolverProblemError
Because pyle depends on cirq-core (1.4.0.dev20240404120310) which depends on scipy (>=1.12.0,<1.13.0), scipy is required.
So, because pyle depends on scipy (~1.9.2), version solving failed.
```
Previous context for scipy ~=1.12 see #6545
=> Loosen the scipy condition in requirements.txt

cirq-core/cirq/ops/qubit_manager.py, cirq-core/cirq/ops/qubit_manager_test.py
Quote the prefix string in repr of `_BaseAncillaQid` classes.
Follow up to #6554.
=> Improve repr of `_BaseAncillaQid` classes with prefix

check/all
And also show a status summary of the executed checks.
=> check/all - exit with error status if any of checks failed

cirq-google/cirq_google/engine/stream_manager.py, cirq-google/cirq_google/engine/stream_manager_test.py
Users have reported intermittent errors where requests are halted due to a timeout. Within a provided stacktrace, I found:
```
<AioRpcError of RPC that terminated with:
status = StatusCode.UNKNOWN
details = "408:Request Timeout"
debug_error_string = "<...>"
>
```
The stack trace also indicated that the [`_is_retryable_error`](https://github.com/quantumlib/Cirq/blob/2eb6d63880a4cc96f96ee764da79df70442aca0c/cirq-google/cirq_google/engine/stream_manager.py#L264) check failed and so raised the exception.
This change adds the `UNKNOWN` error code to retry in these cases.
=> Add UNKNOWN status code to retryable Quantum Engine errors

cirq-core/cirq/study/sweeps.py, cirq-core/cirq/study/sweeps_test.py
An empty `cirq.Product()` sweep yields one empty param resolver, but was reporting a length of 0 when calling `__len__`. This fixes the `__len__` computation so it agrees with the actual length of the sweep when iterating.
=> Fix `__len__` of empty Product sweep to match actual length

cirq-core/cirq/contrib/svg/svg.py, cirq-core/cirq/contrib/svg/svg_test.py
We have bloqs in Qualtran that use `&` on one of the output wires. The corresponding SVG diagram fails. This PR fixes it.
=> Escape `&` in SVG diagrams

cirq-google/cirq_google/cloud/quantum_v1alpha1/services/quantum_engine_service/transports/grpc.py, cirq-google/cirq_google/cloud/quantum_v1alpha1/services/quantum_engine_service/transports/grpc_asyncio.py, cirq-google/cirq_google/engine/stream_manager.py
We want to prevent overwhelming the engine tasks with too many requests.
Setting a maxsize does not reject requests that happen after the queue is full. Instead, when a request is to be put into the queue it will wait until a [free slot](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue.put) is available before adding.
We also limit the size of the request messages sent to prevent overloading the server with very large requests.
=> Set maxsize of request queue to Quantum Engine

cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/qis/clifford_tableau.py
Implements binary exponentiation as described in https://github.com/quantumlib/Cirq/issues/6327
This change does not include the feature of exponentiation for non-integer exponents. This still needs to be discussed, since $\frac{5}{2}$ might be supported ( i.e. the square root is clear ), but other values might not. Knowing which non-integers to support needs to be discussed
=> Optimize Clifford.__pow__ by using binary exponentiation

cirq-core/cirq/contrib/quimb/state_vector.py
Problem: Python 3.12 requires quimb-1.8.0, but quimb-1.8.0 cannot
evaluate path-info for TensorNetwork consisting of a scalar Tensor.
Solution: Skip path-info evaluation for scalar TensorNetwork.
Path-info is used for RAM estimation only which is not a problem
for scalar TensorNetwork-s.
This fixes unit test failure for
cirq-core/cirq/contrib/quimb/grid_circuits_test.py::test_tensor_expectation_value
Ref: https://github.com/jcmgray/quimb/issues/231
=> Avoid DivisionByZero error when TensorNetwork simplifies to a scalar

.github/workflows/ci.yml, cirq-core/cirq/contrib/requirements.txt, cirq-google/cirq_google/api/v1/operations_pb2.py, cirq-google/cirq_google/api/v1/params_pb2.py, cirq-google/cirq_google/api/v1/program_pb2.py, cirq-google/cirq_google/api/v2/device_pb2.py, cirq-google/cirq_google/api/v2/metrics_pb2.py, cirq-google/cirq_google/api/v2/program_pb2.py, cirq-google/cirq_google/api/v2/result_pb2.py, cirq-google/cirq_google/api/v2/run_context_pb2.py, cirq-google/cirq_google/engine/engine_test.py, dev_tools/cloned_env_test.py, dev_tools/notebooks/notebook_test.py, dev_tools/requirements/deps/dev-tools.txt, dev_tools/requirements/deps/protos.txt, dev_tools/requirements/deps/pytest.txt
- Fix attribute error in `engine_test.py::test_create_context`
- Adjust package presence assertion in `test_isolated_env_cloning`
- Bump up to virtualenv>=20.23, filelock~=3.1, pylatex~=1.4
- Bump up to grpcio-tools~=1.59.0 and recompile protos
- Relax qiskit-aer requirement to qiskit-aer~=0.12.0.  Allow qiskit-aer-0.12.0
which has source archive on PyPI and can be installed for Python 3.12.
- Bump up to quimb~=1.7 which installs correctly with Python 3.12
Remove quimb-only dependencies from our requirements, let
quimb sort out its dependencies itself.
- CI - add pytest jobs with Python 3.12
- Skip mysteriously failing test of Contract-a-Grid-Circuit.ipynb
Fixes #6460
=> Support Python 3.12

cirq-aqt/setup.py, cirq-core/cirq/_version.py, cirq-core/cirq/ops/qid_util.py, cirq-core/cirq/protocols/json_serialization_test.py, cirq-core/requirements.txt, cirq-core/setup.py, cirq-ft/setup.py, cirq-google/cirq_google/_version.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-rigetti/setup.py, cirq-web/setup.py, dev_tools/modules_test.py, dev_tools/modules_test_data/mod1/setup.py, dev_tools/snippets_test.py, setup.py
- Raise exception if running with Python <= 3.9.x
- Clean up checks and notes relevant for old Pythons
- Bump up to numpy~=1.22 which is effectively the minimum version
that works with Python 3.10.  We are a bit more permissive than
NEP 29 which suggests numpy-1.23+.
Fixes: #6463
Ref: https://numpy.org/neps/nep-0029-deprecation_policy.html
=> NEP-29 - enforce minimum Python version 3.10

.github/workflows/ci.yml, dev_tools/packaging/isolated_packages_test.py
Problem: `test_isolated_packages` may run clashing parallel builds
of a local `cirq_core` wheel.
Solution: Run pip-install with the `--no-clean` option so parallel
builds do not delete active files.
Also invoke isolated_packages_test.py with `--enable-slow-tests` in CI
to include non-slow tests if ever added to that file.
=> CI - deflake `Isolated pytest Ubuntu`

cirq-core/cirq/linalg/decompositions.py, cirq-core/cirq/linalg/diagonalize.py, cirq-core/cirq/linalg/predicates.py, cirq-core/cirq/linalg/transformations.py, cirq-core/cirq/testing/lin_alg_utils.py, cirq-core/cirq/transformers/analytical_decompositions/controlled_gate_decomposition.py
- On MacOS, with numpy ~1.26, np.linalg.det gives spurious warnings when passed a complex array.
- Suppress these warnings, as they are just annoying and do not signify anything.
=> Suppress superfluous warnings from numpy

dev_tools/bash_scripts_test.py, dev_tools/requirements/deps/pytest.txt
Remove top-version limits on the pytest-related package.
These pins were introduced a while ago and are hopefully
not needed anymore.
=> Release pins from all pytest-related packages

docs/_book.yaml, docs/build/_index.yaml, docs/experiments/_index.yaml, docs/hardware/_index.yaml, docs/noise/_index.yaml, docs/simulate/_index.yaml, docs/transform/_index.yaml
- Fix syntax error in `docs/noise/_index.yaml`
- Stop including deleted yaml file
- Format with the yaml_format Google tool
Fixes #6587
=> Fix nightly build of the staging cirq website

check/all, check/build-changed-protos, check/format-incremental, check/pylint-changed-files, check/pytest-and-incremental-coverage, check/pytest-changed-files, check/pytest-changed-files-and-incremental-coverage, cirq-core/cirq/contrib/svg/svg_test.py, dev_tools/conf/mypy.ini
- Avoid passing an empty string argument to `check/format-incremental`
when invoked from `check/all`
- Improve validation of the git-revision argument in check scripts by
allowing git tags that resolve to a commit
- Fix invalid use of `?` in egrep pattern
- Make check/mypy pass in the dev.env.txt virtual environment
=> Fix spurious failure of the check/all script

cirq-google/cirq_google/__init__.py, cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/engine/engine_processor.py, cirq-google/cirq_google/engine/engine_processor_test.py, cirq-google/cirq_google/engine/engine_test.py, cirq-ionq/cirq_ionq/__init__.py, cirq-ionq/cirq_ionq/ionq_devices.py, docs/google/devices.md, docs/google/engine.md
* Remove deprecated constants from cirq_google module.
Long past the `v0.16` deprecation deadline, constants
were invalid for almost 2 years after #5762.
* Remove deprecated method `cirq_google.Engine.sampler()`
Long past the `v1.0` deprecation deadline.
* Purge deprecated arguments to `EngineProcessor.list_calibrations`
`earliest_timestamp_seconds` and `latest_timestamp_seconds` are
long past the `v1.0` deadline.
* Remove deprecated function `cirq_ionq.ionq_devices.decompose_to_device`.
Long past the `v0.16` deadline.
Ref: https://github.com/quantumlib/Cirq/blob/main/release.md#before-you-release-flush-the-deprecation-backlog
=> Flush deprecations before minor release

dev_tools/modules.py, dev_tools/modules_test.py, dev_tools/modules_test_data/mod1/pack1/_version_test.py, dev_tools/modules_test_data/mod2/pack2/_version_test.py, dev_tools/packaging/produce-package.sh
- Make `dev_tools/modules.py replace_version` update also the
version expected in unit tests
- Skip type check in the new test-only source files
- Update `dev_tools/packaging/produce-package.sh` to use the `replace_version`
utility when building development wheels
=> Improve replace_version tool and development wheels

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py
When constructing circuits with `Circuit.from_moments` we often want to conditionally include a moment and we often end up with awkward expressions like:
```python
Circuit.from_moments(prepare_ops, *([flip_ops] if flip else []), measure_ops)
```
This PR would allow us to pass `None` as an arg to `from_moments` in which case that arg would be skipped and not included in the circuit (not even as an empty moment). The above code can then be written more clearly as:
```python
Circuit.from_moments(prepare_ops, flip_ops if flip else None, measure_ops)
```
=> Allow passing `None` to `AbstractCircuit.from_moments`

cirq-core/cirq/experiments/xeb_sampling.py
XEB sampling creates threads inorder to speed sampling up. however this leads to a race condition when the sampler itself uses threads in its internal implementation. This PR removes the implicit behaviour 
In a follow up PR I'll make passing a threading pool possible but optional
cc: @eliottrosenberg
=> Remove implicit thread creation in XEB sampling

cirq-google/requirements.txt, dev_tools/requirements/deps/mypy.txt, dev_tools/requirements/deps/protos.txt
* Pin `protobuf` to version 4 to fix "Lint check" CI failure such as
https://github.com/quantumlib/Cirq/actions/runs/9654153610/job/26627844188
* Also bump `types-protobuf` `mypy-protobuf` for consistency with protobuf-4.x
=> Fix CI lint failure by pinning to protobuf-4

cirq-google/cirq_google/engine/abstract_processor.py, cirq-google/cirq_google/engine/engine_processor.py, cirq-google/cirq_google/engine/engine_processor_test.py, cirq-google/cirq_google/engine/engine_program.py, cirq-google/cirq_google/engine/engine_program_test.py, cirq-google/cirq_google/engine/engine_test.py, cirq-google/cirq_google/engine/simulated_local_processor_test.py, cirq-google/cirq_google/engine/virtual_engine_factory_test.py, cirq-google/cirq_google/workflow/processor_record_test.py
Removes default values and enforces specifying `run_name` and `device_config_name`
Special note that this does not disrupt the workflow
```
sampler = processor.get_sampler(  
run_name="run_name", device_config_name="config_alias"
)
sampler.run_batch([circuit] * 20, repetitions=500) 
sampler.run_sweep(circuit, params=[...], repetitions=500) 
```
=> Enforces specifying run_name and device_config_name on Engine interfaces

docs/hardware/pasqal/getting_started.ipynb
This is a workaround to allow execution of getting_started.ipynb
notebook as a part of documentation build.
Here we manually convert optimized circuit to have 1 operation per moment
so it passes validation w/r to the PasqalVirtualDevice.
Related to #6655
=> docs - unblock execution of cirq_pasqal getting_started notebook

cirq-core/cirq/experiments/readout_confusion_matrix.py, cirq-core/cirq/experiments/readout_confusion_matrix_test.py
This adds the method `readout_mitigation_pauli_uncorrelated` to `cirq.experiments.readout_confusion_matrix.TensoredConfusionMatrices`, which allows one to scalably perform readout error mitigation on arbitrarily long Pauli strings without having to construct any exponentially large matrices. For now, this is restricted to the case when the confusion matrix is a tensor product of single-qubit confusion matrices but could be generalized if desired. The test illustrates its usage. It is a reimplementation of work that I did in grad school (a special case of https://github.com/eliottrosenberg/correlated_SPAM).
=> Add uncorrelated readout error mitigation for arbitrarily long Pauli strings

cirq-core/cirq/transformers/target_gatesets/compilation_target_gateset.py
- This doc had an incorrect name for the function. Changed to the correct one.
=> Change to optimize_for_target_gateset in docs

cirq-core/cirq/experiments/two_qubit_xeb.py, cirq-core/cirq/experiments/xeb_fitting.py, cirq-core/cirq/experiments/xeb_fitting_test.py
This PR supports creating FSim calibration options for arbitary FSim like gates. It also split the XEB function in two in prerpartion for implmenting XEB calibration for arbitary gates.
part of breaking https://github.com/quantumlib/Cirq/pull/6568 into smaller PRs.
=> Support creating XEB calibration options for arbitary FSim like gates

cirq-core/cirq/transformers/noise_adding.py, cirq-core/cirq/transformers/noise_adding_test.py
Adds a tool for adding depolarizing noise after the specified gate, which can be used on hardware for probabilistic error amplification and zero noise extrapolation.
=> Add noise amplification transformer

docs/start/start.ipynb
Problem: Documentation build converts root-anchored reference /REF
in notebook markdown to https://quantumai.google/cirq/REF
but education page is at https://quantumai.google/resources.
Solution: Use absolute URL to the education page.
Fixes: #6646
=> Use absolute URL for Cirq education resources

cirq-core/cirq/ops/common_gates_test.py, cirq-core/cirq/ops/eigen_gate.py
Problem: In sympy-1.13.0 the expressions `sympy.S.One == 1.0` and
`sympy.S.Half == 0.5` evaluate to False which causes
inequality between `cirq.cphase(sympy.pi)` and `cirq.CZ`.
Solution: Check equality with parametrized exponents converted to float.
Fixes: #6663
=> Fix equality of cphase gates initialized from sympy constants

cirq-core/cirq/experiments/xeb_simulation.py, cirq-core/cirq/experiments/xeb_simulation_test.py
Fixes a bug where, for deep XEB circuits (depth=300), the simulator complains that the statevector is not normalized.
=> Use np.complex128 for simulating xeb circuits

cirq-core/cirq/transformers/randomized_measurements.py, cirq-core/cirq/transformers/randomized_measurements_test.py
Working from Seneca's last PR that provided `class RandomizedMeasurements`, I
1. added an additional argument to the `__call__` function to include `unitary_ensemble: str = "pauli"` which can be set to either `"pauli"`, `"clifford"` or `"cue"`
2. added functions for generating random single-qubit Clifford and cue gates. 
3. replaced `unitaries_to_moment` function with `random_single_qubit_unitary_moment` to incorporate all three unitary ensembles instead of just Pauli
=> Added random single-qubit CUE and Clifford gates

cirq-rigetti/requirements.txt
Pin qcs-sdk-python <= 0.19.0 for Windows
Temporary workaround for #6684.
=> work around ci build failure on windows

cirq-google/cirq_google/serialization/arg_func_langs_test.py, cirq-google/requirements.txt, dev_tools/requirements/deps/mypy.txt
Fixes #6651
I've updated `arg_func_lang_test.py` to pass the new or old kwarg to `json_format.MessageToDict` based on inspecting the function signature, so it works with old and new versions of protobuf. This will unblock upgrades that we need to do internally to work with python 3.12.
=> Allow using protobuf version 5 and later

dev_tools/conf/mypy.ini
setup.py files define distributions of cirq and cirq subpackages.
There is no much value to enforce type annotations in their code.
Also clean up ineffective exclusion pattern for cirq-rigetti (related to #6661).
Fixes #6687
=> Exclude all setup.py files from typecheck

docs/dev/development.md
Fixes https://github.com/quantumlib/Cirq/issues/6686
=> Remove `v` in `git remote` command in dev installation

cirq-ionq/cirq_ionq/ionq_native_gates.py
Make documented unitary expressions equal to the code below.
Fixes #6639
=> Fix docstrings for the ionq GPIGate and GPI2Gate

cirq-core/cirq/ops/eigen_gate.py
Problem: The `sympy.Expr.is_constant()` introduced in #6669 is very
slow causing glacial-speed equality checks of parameterized gates.
Solution: Check if expression is sympy.Number instead which still
satisfies the equality fix added in #6669.
Timing of
check/pytest --numprocesses=0 --randomly-seed=0 \
cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_sqrt_iswap_test.py
Before: 945 s   After: 18 s,  Before #6669: 18 s.
=> Eliminate awful slowdown of `EigenGate._value_equality_values_`

cirq-google/cirq_google/devices/grid_device.py, cirq-google/cirq_google/devices/grid_device_test.py
- Adds validation to `GridDevice` for Coupler Qid objects.
=> Add validation for couplers

cirq-rigetti/requirements.txt
The last release of qcs-sdk-python 0.19.2 includes binary wheels
for Windows so the CI should pass with the last package version.
This reverts commit c8f799e6e87ecc66a66a488bd101a09312ca2f1a,
"Pin qcs-sdk-python to 0.19.0 for Windows (#6685)".
Fixes #6684
=> Drop version pin of qcs-sdk-python on Windows

cirq-core/cirq/ops/linear_combinations.py, cirq-core/cirq/protocols/hash_from_pickle_test.py
ProjectorSum stores data in a mutable LinearDict which is not hashable.
LinearDict also does not pickle, because by default it has a
lambda-function attribute.
This excludes ProjectorSum from the `test_hash_from_pickle` test.
Resolves #6674
=> Mark ProjectorSum class as unhashable

cirq-core/cirq/linalg/decompositions_test.py, cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/pytest_randomly_utils.py, cirq-core/cirq/testing/pytest_randomly_utils_test.py, cirq-core/cirq/transformers/analytical_decompositions/controlled_gate_decomposition_test.py
Add testing decorator `retry_once_with_later_random_values` to repeat
test once with subsequent random values.
This reduces CI failures for random seed choices by pytest-randomly, e.g.,
```
check/pytest --numprocesses=0 --randomly-seed=1783995880 \
cirq-core/cirq/transformers/analytical_decompositions/controlled_gate_decomposition_test.py::test_decompose_random_unitary
check/pytest --numprocesses=0 --randomly-seed=1454822943 \
cirq-core/cirq/linalg/decompositions_test.py::test_num_two_qubit_gates_required
```
=> Avoid CI flakes due to random-seed-dependent unit tests

cirq-core/cirq/transformers/dynamical_decoupling.py, cirq-core/cirq/transformers/dynamical_decoupling_test.py
Enable adding dynamical decoupling in single qubit gate moments only.
Adding mechanism is described in the code. In short:
```
For each qubit:
For moments in (first_active_moment, last_active_single_qubit_moment):
Insert
Absorb the inverse to the last_active_single_qubit_moment
```
2 test cases added for single qubit gates moments insertion mode:
Test case 1: add dd preserves the circuit.
```
0: ───────────────────────────────H───@───
│
1: ───────────────────────H───@───H───X───
│
2: ───────────────H───@───H───X───────────
│
3: ───H───────@───H───X───────────────────
│
4: ───H───@───X───────────────────────────
│
5: ───H───X───────H───@───────────────────
│
6: ───────────────H───X───H───@───────────
│
7: ───────────────────────H───X───H───@───
│
8: ───────────────────────────────H───X─── …
```
=> Enable pulling through Clifford operations, also add an option of only applying dd to single qubit gate moments

pyproject.toml
Cirq now supports Python >=3.10 and <=3.12. This PR aligns the target versions of the `black` tool to Cirq supported Python versions.  Unless I am missing something, this is a leftover from https://github.com/quantumlib/Cirq/pull/6591/files.
Tested with `black==24.3.0` from https://github.com/cosenal/Cirq/blob/black-target-versions/dev_tools/requirements/deps/format.txt
=> Align Black target versions with supported Python versions

cirq-core/cirq/experiments/xeb_fitting_test.py, cirq-core/cirq/experiments/xeb_simulation_test.py
Problem: `multiprocessing.Pool()` uses all available cores which can
cause problems on hardware with many cores.
Solution: Limit the maximum pool size to 4.
=> Limit maximum multiprocessing pool size in xeb tests

cirq-rigetti/cirq_rigetti/aspen_device.py, cirq-rigetti/cirq_rigetti/aspen_device_test.py, cirq-rigetti/requirements.txt
* Sync with new API for checking device family in qcs-sdk-python,
Ref: https://github.com/rigetti/qcs-sdk-rust/pull/463 in isa.pyi
* Require qcs-sdk-python-0.20.1 which introduced the new family API
Fixes #6732
=> Fix Rigetti check for Aspen family device kind

pyproject.toml
In the current version of pytest (8.3.3) with the pytest-asyncio module version 0.24.0, we see the following warnings at the beginning of a pytest run:
```
warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
..../lib/python3.10/site-packages/pytest_asyncio/plugin.py:208:
PytestDeprecationWarning: The configuration option
"asyncio_default_fixture_loop_scope" is unset. The event loop scope for
asynchronous fixtures will default to the fixture caching scope. Future
versions of pytest-asyncio will default the loop scope for asynchronous
fixtures to function scope. Set the default fixture loop scope explicitly in
order to avoid unexpected behavior in the future. Valid fixture loop scopes
are: "function", "class", "module", "package", "session"
```
A [currently-open issue …
=> Silence pytest warnings about asyncio fixture scope

dev_tools/incremental_coverage.py
Avoid spurious CI failure due to missing coverage of changed conftest.py lines.
conftest.py configures the pytest session.  It is tricky and not worthwhile to
ensure it is test-covered.
=> Exclude conftest.py files from enforcing changed-code coverage

.github/workflows/ci.yml
Note cirq-rigetti is excluded, because it is not yet NumPy-2 compatible.
The test is only run on Ubuntu for the sake of speed and simplicity.
Related to #6706
=> CI - add temporary job pytest-numpy-2 to test with NumPy-2 on Ubuntu

cirq-core/cirq/vis/heatmap.py
Avoid `Incompatible types in assignment` error by providing explicit
cast of the value returned from `get_facecolor()`.
The failure is flaky and more likely to happen if run without mypy cache
This fix was verified using:
for i in {1..50}; do check/mypy --cache-dir=/dev/null || break; done
=> CI - fix flaky type check failure in `cirq.vis.heatmap`

dev_tools/pylint_copyright_checker.py, dev_tools/requirements/deps/pylint.txt
- Bump up to the latest pylint-3.3.1 allowing patch-level updates.
- Adjust `pylint_copyright_checker` for the pylint-3 API.
Follow the `examples/custom_raw.py` in the pylint repository.
Fixes #6351
=> Update copyright checker and switch to pylint-3

Dockerfile, cirq-rigetti/requirements.txt, dev_tools/conf/.coveragerc
Only used within mypy type checking session.
=> coverage - exclude code guarded by `if TYPE_CHECKING`

cirq-google/cirq_google/engine/engine_job.py
For simple circuits RT time from our hardware is:
```
1. Engine without stream: 3.3s
2. Engine with streaming: 1.14s
```
Increasing our polling rate to 1s enables sending 2x simultaneous jobs without explicitly increasing our quota, with minimal increase to RT latency (250ms)
Fixes: b/372751875
=> decrease polling rate for `QuantumJob`

cirq-core/cirq/transformers/analytical_decompositions/quantum_shannon_decomposition.py, cirq-core/cirq/transformers/analytical_decompositions/quantum_shannon_decomposition_test.py
This PR:
- fixes how `_single_qubit_decomposition` handles global phase and reduces the number of operations it returns when possible.
- Makes the eigendecomposition  part resilient to numerical precision issues by:
1. resorting to the more accurate`eigh` instead of `eig` when the unitary is hermitian.
2. if the unitary is not hermitian then use Gram–Schmidt to make sure the eigenvectors are orthonormal (mathematically they should but we could get non orthognoal vectors either because of numerical precision or because an eigenvector is repeated and as a result the the eigenvector spanning that subspace are arbitary) 
- Reduce the number of operations by removing operations equaivalent to identity (e.g. rz($\phi$) with $\phi \approx 0$)
- Adds tests for the reported failures making sure …
=> Fix Quantum Shannon Decomposition

cirq-core/cirq/experiments/xeb_fitting_test.py, cirq-core/cirq/experiments/xeb_simulation_test.py
Direct Pool executions causes flaky test outcomes in internal test
framework.  This change makes it easier to work around the problem.
No change in the effective test code.
=> Use pytest fixture for multiprocessing Pool in XEB tests

cirq-core/cirq/transformers/analytical_decompositions/quantum_shannon_decomposition.py, cirq-core/cirq/transformers/analytical_decompositions/quantum_shannon_decomposition_test.py
=> Mark QSD QFT5 with xfail

Dockerfile, cirq-rigetti/requirements.txt
* Unpin the quil package
The latest release quil-0.13.1 includes binary wheels.
Wheels were omitted unintentionally before due to a CI error at 
the quil project.
* Update to pyquil>=4.14.3 as it requires good qcs-sdk-python,
and remove now unnecessary version spec of qcs-sdk-python.
Fixes: #6754
=> Update pyquil dependency and remove workaround pinning of quil

cirq-core/cirq/work/sampler.py, cirq-core/cirq/work/sampler_test.py
Related to b/372751875
Throttle in-flight requests which otherwise would cause a `Quota exceeded exception`
Where as before sending `50 circuits` to `sampler.run_batch` would cause an exception, now it completes in `~31s`, `100 jobs in ~61s`, and `500 jobs in ~276s` for longer circuits.
=> add request limiter when polling for results

cirq-core/cirq/work/sampler.py
Follow up to [#6774](https://github.com/quantumlib/Cirq/pull/6774) 
For large circuits ~200 circuits with 100 layers, `run_batch` will still encounter the Quota Exceeded exception.
The original chunk size is too large, but through testing I found that `CHUNK_SIZE=5` for circuits of a similar size will not encounter the issue.
=> Throttle run_batch requests

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/circuits/qasm_output.py, cirq-core/cirq/circuits/qasm_output_test.py, cirq-core/cirq/ops/classically_controlled_operation.py, cirq-core/cirq/ops/common_channels.py, cirq-core/cirq/ops/common_gates.py, cirq-core/cirq/ops/identity.py, cirq-core/cirq/ops/matrix_gates.py, cirq-core/cirq/ops/measurement_gate.py, cirq-core/cirq/ops/phased_x_gate.py, cirq-core/cirq/ops/swap_gates.py, cirq-core/cirq/ops/three_qubit_gates.py
- This supports changing the version and the obvious changes in outputting to OpenQASM 3.0
- This PR does not cover imports from OpenQASM 3.0
=> Preliminary support for outputting to OpenQASM 3.0

.github/dependabot.yml
The default label added by Dependabot is `dependencies`, which doesn't align with our use of `area/dependencies`. This config file makes it use `area/dependencies` instead, plus adds some other labels that make sense to add at the same time:
* Docker items:
- `area/dependencies`
- `area/docker`
- `kind/health`
* GitHub Actions items:
- `area/dependencies`
- `area/github`
- `kind/health`
* Python items:
- `area/dependencies`
- `area/python`
- `kind/health`
* JavaScript items:
- `area/dependencies`
- `area/javascript`
- `kind/health`
=> Adjust labels added to PRs by Dependabot

cirq-core/cirq/contrib/qasm_import/_lexer.py, cirq-core/cirq/contrib/qasm_import/_parser.py, cirq-core/cirq/contrib/qasm_import/_parser_test.py
- This adjusts the lexer and parser to handle programs from OpenQASM 3.0.
=> Preliminary support for parsing OpenQASM 3.0

cirq-core/cirq/protocols/qasm.py, cirq-core/cirq/protocols/qasm_test.py
- OpenQASM 2.0 grammar requires decimal points in scientific notation.  For instance, 1e-10 is not allowed according to a strict interpretation of the grammar.
- This PR forces the formatter to use a decimal when printing out scientific notation.
Fixes: #6550
=> Force decimals in scientific notation for OpenQASM 2.0

cirq-core/cirq/circuits/qasm_output.py, cirq-core/cirq/circuits/qasm_output_test.py
- Previously, if there was a measurement with the same key but two differently sized registers, then the qasm output might select the wrong key and size the register incorrectly.
- This PR examines all the measurements first, and selects the biggest one, so to correctly size the classical register.
- Adds unit test t demonstrate.
Fixes: #6508
=> Allow measurement keys with differing qubits in OpenQASM

cirq-core/cirq/experiments/two_qubit_xeb.py
Allows the user to specify the batch size in order to optimize the runtime.
=> Parallel XEB: Add option to specify batch size

cirq-core/cirq/work/sampler.py, cirq-google/cirq_google/engine/validating_sampler.py
We get a ~3x speedup if `run_batch` diverts to `run_batch_async`. Shown in this [colab](https://colab.sandbox.google.com/drive/1K4VXZ9bHOBuOjgJNVrn3xPQwhTPoo-up?resourcekey=0-PLrhiL2AFfNuZeySAQseWA#scrollTo=7bO66-ILOzoC), it benchmarks using a child class of `cirq.Sampler` which does not implement it's own `run_batch` methods.
=> Divert cirq.Sampler's run_batch to run_batch_async

cirq-google/cirq_google/engine/engine.py
Now user's don't need to manually disable streaming. Will flip this once there's a fix.
=> disable streaming by default

.github/dependabot.yml
After PR #6822 made Dependabot work again, it also revealed multiple other issues with the configuration file. This PR attempts to fix all the known issues so far:
* Changes Python versioning strategy to be `widen`. Per the GitHub docs: "Widen the allowed version requirements to include both the new and old versions, when possible. Typically, this only increases the maximum allowed version requirement."
* Fixes the pip/Python case to look for requirements files in all the places where we have them.
* Fixes the npm case to look for `package.json` in the right place.
=> Multiple fixes and enhancements to dependabot.yml

dev_tools/conftest.py
Prevent tested notebooks from connecting to cloud services with
local user credentials.  Tell gcloud to use empty configuration
directory instead of user configuration within pytest session.
This makes the test of docs/tutorials/google/start.ipynb notebook
use virtual hardware engine unconditionally.
=> Disable local Google Cloud credentials in tests

cirq-core/cirq/sim/density_matrix_utils.py, cirq-core/cirq/sim/simulation_utils.py
due to numerical instabilities the probabilities might be slightly outside the range $[0, 1]$ ... this issue is annoying and shows up with medium to large circuits even with `dtype=np.complex128`
fixes: https://github.com/quantumlib/Cirq/issues/6719
=> make DensityMatrixSimulator more numerically stable

cirq-web/cirq_ts/package-lock.json, cirq-web/cirq_ts/package.json
- Bump tsc-watch from 4.6.2 to 6.2.1 in /cirq-web/cirq_ts
- Bump webpack-dev-server from 4.15.2 to 5.2.0 in /cirq-web/cirq_ts
- Bump ts-mocha from 9.0.2 to 10.0.0 in /cirq-web/cirq_ts
=> Combine passing dependabot updates for cirq-web

cirq-core/cirq/transformers/gauge_compiling/cz_gauge.py, cirq-core/cirq/transformers/gauge_compiling/cz_gauge_test.py, cirq-core/cirq/transformers/gauge_compiling/gauge_compiling.py, cirq-core/cirq/transformers/gauge_compiling/gauge_compiling_test.py, cirq-core/cirq/transformers/gauge_compiling/gauge_compiling_test_utils.py, cirq-core/cirq/transformers/gauge_compiling/gauge_compiling_test_utils_test.py
Support run sweep output in gauge compiling.
Enables output parameterized circuit with sweepable parameters for CZ Gauge.
**Usage**:
Users can create a parameterized circuit with N set of parameters associated with it similar to:
```
parameterized_circuit, N_params = self.gauge_transformer.as_sweep(input_circuit, N=5)
```
Then, with the following input circuit
```
0: ───H───Y───@───M───
│
1: ───Y───X───┼───M───
│
2: ───────────@───M───
```
the outputs are similar to
```
circuit:
0: ───H───Y───PhXZ(a=a1,x=x1,z=z1)───@───PhXZ(a=a3,x=x3,z=z3)───M───
│
1: ───Y───X──────────────────────────┼──────────────────────────M───
│
2: ───────────PhXZ(a=a0,x=x0,z=z0)───@───PhXZ(a=a2,x=x2,z=z2)───M───
5 set of parameters:
Parameter set 0: {'x0': 1, 'z0': 0, 'a0': 0.5, 'x1': 0.0, 'z1': 0.0, 'a1': 0.0, …
```
=> Support run_sweep in GaugeTransformer. Pioneered in the CZ Gauge.

cirq-google/cirq_google/devices/grid_device.py, cirq-web/README.rst, dev_tools/conf/.pylintrc, dev_tools/triage-party/README.md, release.md
Not all cases can be replaced; some refer to repositories where the main branch is still called master. This changes all the ones that I could find and that can be done.
=> Replace references to "master" branch with "main"

cirq-core/cirq/ops/classically_controlled_operation.py, cirq-core/cirq/ops/classically_controlled_operation_test.py
The original implementation seems to have assumed the classical conditions were prepended to the wire symbols, not appended.
fixes #6814
=> Fix exponent location on classically controlled diagrams

cirq-core/cirq/protocols/qasm.py, cirq-core/cirq/protocols/qasm_test.py
- Qubits is an optional parameter, only used for certain types (usually `cirq.Gate`), and, if supplied elsewhere, can raise an error.
- Print out a more informative message.
Fixes: #6016
=> Add more informative message for improper cirq.qasm arguments.

cirq-core/cirq/ops/pauli_string_phasor.py, cirq-core/cirq/ops/pauli_string_phasor_test.py
This fixes problems created when diagramming a PauliSumExponential on an `I`, which gets stripped out.
Fixes #5944
=> Return NotImplemented for diagram info for empty PauliStringPhasors

dev_tools/notebooks/isolated_notebook_test.py, docs/build/interop.ipynb
- This PR adds documentation for OpenQASM export, and also shows how to change version of OpenQASM output.
It also clarifies which versions are supported.
Fixes: #6185
=> Add documentation for QASM export

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/ops/raw_types.py
- Adds a simple example for Circuit.transform_qubits and Operation.transform_qubits
Fixes: #4014
=> Add examples for transform_qubits function

cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/circuit_operation_test.py, cirq-core/cirq/ops/classically_controlled_operation_test.py, cirq-core/cirq/protocols/json_test_data/CircuitOperation.json, cirq-core/cirq/protocols/json_test_data/CircuitOperation.repr_inward
This changes `CircuitOperation` so that `use_repetition_ids` defaults to False rather than True. If explicit `repetition_ids` are provided (to the constructor or to the `replace` method), we set `repetition_ids` to True automatically. The motivation for this is that internally we have never used repetition_ids and in fact we have helper methods for creating looped circuit operations since it is easy to forget to pass `use_repetition_ids=False` to override the default. The history here is that we started implementing repetition_ids at about the same time as we started implementing support for repeated measurement keys, and unfortunately I think we picked the wrong default for the keys. All of our internal experiments such as QEC and looped sampling experiments have set …
=> CircuitOperation: change use_repetition_ids default to False

cirq-core/cirq/transformers/gauge_compiling/gauge_compiling.py, cirq-core/cirq/transformers/gauge_compiling/iswap_gauge.py, cirq-core/cirq/transformers/gauge_compiling/iswap_gauge_test.py, cirq-core/cirq/transformers/gauge_compiling/spin_inversion_gauge.py, cirq-core/cirq/transformers/gauge_compiling/spin_inversion_gauge_test.py, cirq-core/cirq/transformers/gauge_compiling/sqrt_iswap_gauge.py, cirq-core/cirq/transformers/gauge_compiling/sqrt_iswap_gauge_test.py
This is a followup pr of https://github.com/quantumlib/Cirq/pull/6852 to enable as_sweep() for 3 more gauges.
The only remaining gauge is sqrt_cz_gauge, which requires additional parameters for the 2-qubit gates to reflect the swap behavior.
=> Apply as_sweep for iswap_gauge, spin_inversion_gauge, sqrt_iswap_gauge

cirq-core/cirq/experiments/xeb_fitting.py
The test function `test_calibrate_z_phases()` in the file `cirq-core/cirq/experiments/z_phase_calibration_test.py` eventually ends up calling `fit_exponential_decays()` in `xeb_fitting.py`. That function uses SciPy's `curve_fit()` to fit an exponential function to data. For some unlucky combination of random seed and problem cases, `curve_fit()` can fail to find a solution, and raises `RuntimeError` when that happens.
This PR simply changes the call to `curve_fit()` to use a higher number for the maximum function evaluations. The following is a test case that fails without the change and succeeds with it:
```bash
./check/pytest -v --randomly-seed=3258636985 \
cirq-core/cirq/experiments/z_phase_calibration_test.py::test_calibrate_z_phases_no_options
```
Fixes #6906.
=> Fix flaky curve fitting tests

cirq-google/cirq_google/engine/engine.py
Streaming is again working on the service. Re-enabling this feature as the default interaction method.
Fixes #6817.
=> Re-enable streaming Engine interface by default

cirq-aqt/setup.py, cirq-core/setup.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-rigetti/setup.py, cirq-web/setup.py, dev_tools/modules_test.py, dev_tools/modules_test_data/mod1/setup.py, setup.py
The `setup.py` files (at the top level as well as the various Cirq modules) currently define the `author` and `author_email` fields. The set of authors of Cirq, and the set of maintainers of Cirq at any given time, are somewhat overlapping but not identical. The [Python Packaging User Guide](https://packaging.python.org/en/latest/specifications/core-metadata/#maintainer) defines `maintainer` and `maintainer_email` fields to identify the maintainer contact info. This PR adds the values to the `setup.py` files.
=> Add maintainer and maintainer_email fields to setup.py

cirq-aqt/setup.py, cirq-core/setup.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-rigetti/setup.py, cirq-web/setup.py, setup.py
This adds classifier terms to improve software discoverability and findability on PyPI.
=> Add PyPI Trove classifiers to setup.py files

cirq-aqt/setup.py, cirq-core/setup.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-rigetti/setup.py, cirq-web/setup.py, setup.py
PyPI rejected the new Trove classifier term that was added a couple of days ago. I [opened an issue in pypi/warehouse](https://github.com/pypi/warehouse/issues/17379) to report the situation.
Reverting this change so that more workflows don't fail.
=> Revert "Add PyPI Trove classifiers to setup.py files"

cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/ops/gate_operation_test.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/json_test_data/_InverseCompositeGate.json, cirq-core/cirq/protocols/json_test_data/_InverseCompositeGate.repr
Response to issue #6769
Running the code snippet provided in #6769 now yields correct result:
```
0: ───[0>0]──────
│
1: ───[1>1]──────
│
2: ───[2>2]^-1───
{
"cirq_type": "Circuit",
"moments": [
{
"cirq_type": "Moment",
"operations": [
{
"cirq_type": "GateOperation",
"gate": {
"cirq_type": "_InverseCompositeGate",
"val": {
"cirq_type": "QubitPermutationGate",
"permutation": [
0,
1,
2
]
}
},
"qubits": [
{
"cirq_type": "LineQubit",
"x": 0
},
{
"cirq_type": "LineQubit",
"x": 1
},
{
"cirq_type": "LineQubit",
"x": 2
}
]
}
]
}
]
}
0: ───[0>0]──────
│
1: ───[1>1]──────
│
2: ───[2>2]^-1───
```
=> Support inverse gate JSON seralization

cirq-core/cirq/experiments/qubit_characterizations.py, cirq-core/cirq/ops/common_channels.py, cirq-core/cirq/ops/phased_x_z_gate.py, cirq-core/cirq/testing/sample_gates.py
Avoid spurious one-character subscripts and superscripts in HTML docs.
Follow-up to #6870
=> Adjust some more TeX expressions for rendering in web docs

.github/workflows/ci.yml
Per instructions on the following pages, adding a `merge_group` trigger is needed to use merge queues.
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group
=> Add support for merge queues

cirq-core/cirq/contrib/quimb/state_vector.py
The workaround is not needed after upstream fixes in quimb and
our upgraded requirements for a later quimb version.
This reverts commit bfba9653a058af975289a96e1572f97305ea165b.
=> Revert "#6586 - Avoid DivisionByZero error when TensorNetwork simplifies to a scalar"

cirq-google/cirq_google/engine/engine_client_test.py
Split initial `test_create_job` test into:
- Four successful tests:
- `test_create_job_with_all_parameters`
- `test_create_job_without_labels`
- `test_create_job_without_description`
- `test_create_job_without_specified_job_id`
- One failure test:
- `test_create_job_with_invalid_priority`
*Note: Splitting successful tests to stay consistent with existing tests:*
- *`test_create_job_with_invalid_processor_and_device_config_arguments_throws`*
- *`test_create_job_with_run_name_and_device_config_name_succeeds`*
EDIT: Also refactored the test cases to use pytest fixtures for `default_run_context` and `default_engine_client` for consistency and to reduce redundancy.
Fixes #6761
=> Refactor engine client `test_create_job` test names for better clarity and consistency

.github/dependabot.yml
This PR is in response to issue #6966.
It seems like the greatest number of Dependabot PR spam comes from the JavaScript dependencies for cirq-web. This change to the "npm" Dependabot config to make it group minor and/or patch version updates into a single PR if they are not security-related changes; all other updates (meaning, any security updates, and any major version updates) will be handled using the default method, which is separate PRs.
This `groups` configuration is based on [an example in the Dependabot documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#example-3-individual-pull-requests-for-major-updates-and-grouped-for-minorpatch-updates).
With respect to this week's Dependabot activity, this …
=> Make Dependabot ignore patch updates to JS dependencies

cirq-core/requirements.txt, dev_tools/requirements/deps/ipython.txt
Choose wider compatibility window when NEP-29 and SPEC-0
guidance differ.
- Drop numpy-1.24 per NEP-29 and SPEC-0
- Drop scipy-1.10 per SPEC-0
- Drop matplotlib-3.6 per SPEC-0
- Drop pandas-1 per SPEC-0
- Drop networkx-3.0 per SPEC-0
- Drop ipython-8.9 per SPEC-0
Refs:
- https://numpy.org/neps/nep-0029-deprecation_policy.html
- https://scientific-python.org/specs/spec-0000
=> Update scientific Python core dependencies per NEP-29 and SPEC-0

cirq-core/cirq/devices/grid_qubit.py, cirq-core/cirq/devices/grid_qubit_test.py, cirq-core/cirq/devices/line_qubit.py, cirq-core/cirq/devices/line_qubit_test.py
=> Support numpy qid indexes

cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/equal_up_to_global_phase_protocol_test.py
- This will add a default fallback for cirq.Gate instances to use their unitary decomposition for the equal_up_to_global_phase protocol.
Fixes: #6574
=> Add a default fallback for the equal_up_to_global_phase protocol

.github/workflows/ci.yml, cirq-google/cirq_google/engine/engine_processor_test.py, dev_tools/requirements/dev-np2.env.txt
The pytest-numpy-2 job excludes cirq-rigetti which is not yet compatible with
Python 3.13.  This activates Python 3.13 testing for other Cirq packages.
Related to #6932
=> CI - run the pytest-numpy-2 job also with Python 3.13

.github/workflows/ci.yml, dev_tools/pypath, dev_tools/requirements/dev-np2.env.txt
Add missing `setuptools` dependency when testing with Python 3.13.
Fixes #6995
=> CI - fix failing test with Python 3.13

check/nbformat, dev_tools/requirements/deps/tensorflow-docs.txt, docs/build/interop.ipynb, docs/google/internal_gates.ipynb, docs/hardware/aqt/getting_started.ipynb, docs/noise/qcvv/parallel_xeb.ipynb, docs/tutorials/google/start.ipynb
- Fail early if tensorflow-docs installation is broken.
- Use exit status from the nbfmt tool to decide if the format is good.
- Bump up tensorflow-docs to be compatible with protobuf-4
- Reformat notebooks which slipped through broken check/nbformat.
Fixes #7002
=> Fix check/nbformat installation and execution

dev_tools/docs/run_doctest.py
`cirq-web` tests may store external Python sources in node_modules.
Exclude them from the doctest test.
Also remove obsolete pattern for 'cirq-google/cirq_google/engine/client/'
as that directory does not exist anymore.
=> doctest - exclude third-party sources in node_modules

.github/workflows/ci.yml, dev_tools/requirements/deps/dev-tools.txt
Recent documentation updates converted rst files to markdown.
Remove rstcheck execution in the CI and drop it from requirements.
=> CI - remove rstcheck as there are no rst files left

cirq-core/cirq/transformers/analytical_decompositions/controlled_gate_decomposition_test.py
This prevents test failure for
```
check/pytest --numprocesses=0 --randomly-seed=1589095746 \
cirq-core/cirq/transformers/analytical_decompositions/controlled_gate_decomposition_test.py::test_decompose_random_special_unitary
```
=> Avoid CI flake due to random-seed-dependent test

cirq-core/cirq/contrib/quimb/Contract-a-Grid-Circuit.tst, dev_tools/notebooks/notebook_test.py
- Enable Contract-a-Grid-Circuit.ipynb quimb notebook
- Test it with a smaller grid circuit to prevent OOM on GitHub actions
Fixes #6590
=> Enable test of the Contract-a-Grid-Circuit.ipynb notebook

cirq-rigetti/requirements.txt
The wheel installation fails on Windows Python 3.12 with
`Bad CRC-32 for file 'qcs_sdk/qcs_sdk.cp312-win_amd64.pyd'`
Revert after the fix of https://github.com/rigetti/qcs-sdk-rust/issues/531
=> Avoid broken wheel for qcs-sdk-python on Windows

.github/dependabot.yml
The only JavaScript dependencies are in the cirq-web package, which isn't installed in a public-facing location anywhere. The frequency of Dependabot updates and PRs has been too high to justify the maintenance cost. Per internal discussions, we want to move to a monthly schedule for the npm/JavaScript checks.
=> Change npm schedule to monthly

cirq-aqt/setup.py, cirq-core/setup.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-rigetti/setup.py, cirq-web/setup.py
=> Specify `long_description_content_type` so that PyPI accepts wheels

cirq-rigetti/requirements.txt
The installation of `qcs-sdk-python==0.21.11` fails on Linux Python 3.12
with `zlib.error: Error -3 while decompressing data: invalid block type`.
Block new versions of qcs-sdk-python until this gets sorted out.
Ref: https://github.com/rigetti/qcs-sdk-rust/issues/531
=> Avoid broken wheels for qcs-sdk-python

cirq-core/cirq/qis/clifford_tableau.py, cirq-core/cirq/qis/clifford_tableau_test.py
Came across this and figure improve the readability could potentially be helpful in future developments.
=> Improve the readability of CliffordTableau _full_str_ function

cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/ops/clifford_gate_test.py
Remove one space to align output CliffordTableau correctly.
Before:
```
Clifford Gate with Tableau:
stable | destable
-------+----------
- Z0   | + Y0
```
After:
```
Clifford Gate with Tableau:
stable | destable
-------+----------
- Z0   | + Y0
```
=> Fix the format of CliffordGate repr.

.github/workflows/stale.yml
Google is about to change the security settings on all repositories. One of the changes is this:
> [Workflow permissions](https://docs.github.com/en/enterprise-cloud@latest/admin/enforcing-policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#workflow-permissions) will be changed from "Read and write permissions" to "Read repository contents and packages permissions." With this change the `GITHUB_TOKEN` will only have read access for the contents and packages scopes by default. The more permissive setting **cannot** be chosen as the default for individual organizations or repositories.
This PR sets the job permission as suggested by the [documentation for `actions/stale`](https://github.com/actions/stale?tab=readme-ov-file#recommended-perm …
=> Set permissions for CI job

cirq-google/cirq_google/engine/virtual_engine_factory.py, dev_tools/conf/mypy.ini
Avoid `[unused-ignore]` error from `check/mypy` when qsimcirq is installed.
=> Make mypy pass regardless if qsimcirq is installed or not

cirq-rigetti/requirements.txt
The recent release qcs-sdk-python-0.21.12 should be fixed per
https://github.com/rigetti/qcs-sdk-rust/issues/531.
This rolls back #7056 and #7026
=> Unpin the qcs-sdk-python dependency

.github/workflows/ossf-scorecard.yaml
Scorecard (https://github.com/ossf/scorecard) is an automated tool that assesses a number of checks associated with software security and assigns each check a score of 0-10. Once installed, it will create a report at https://scorecard.dev/viewer/?uri=github.com/quantumlib/Cirq
The use of Scorecard is suggested in Google's internal GitHub guidance (go/github-docs).
An example of a Scorecard report for OpenFermion can be seen here: https://scorecard.dev/viewer/?uri=github.com/quantumlib/OpenFermion
=> Add workflow for OpenSSF Scorecard

dev_tools/snippets_test.py
A regex in this file (on line 143) triggered a code scan security warning:(https://github.com/quantumlib/Cirq/security/code-scanning/97):
```python
def find_rst_code_snippets(content: str) -> List[Tuple[str, int]]:
snippets = find_code_snippets(
r'\n.. code-block:: python\n(?:\s+:.*?\n)*\n(.*?)(?:\n\S|\Z)', content
^^^
```
> This part of the regular expression may cause exponential
> backtracking on strings starting with '\naa code-block:: python\n :'
> and containing many repetitions of '\n :'.
This was in code for testing reStructuredText files. Since we no longer have any `.rst` files in the code base, it seemed more sensible to remove all the rST-specific code in here. Doing that not only resolves the code scan warning – it also reduces the maintenance burden going forward.
=> Remove rST-specific code in snippets_test.py

cirq-core/requirements.txt
The Python tqdm package prior to version 4.11.2 has a vulnerability that could allow attackers to execute arbitrary code, as documented in this security advisory:
- https://osv.dev/vulnerability/PYSEC-2017-74
Increasing the minimum version to 4.12 or higher seems like the easiest solution.
=> Increase min version of Python tqdm for security advisory PYSEC-2023-74

cirq-aqt/requirements.txt, cirq-ionq/requirements.txt, cirq-pasqal/requirements.txt, dev_tools/pr_monitor/requirements.txt, dev_tools/requirements/deps/mypy.txt, dev_tools/requirements/isolated-base.env.txt
The Requests library has several vulnerabilities in older versions. The following security advisories can all be remedied by increasing the minimum version of the package `requests` to 2.32 or higher:
- https://osv.dev/vulnerability/PYSEC-2018-28
- https://osv.dev/vulnerability/PYSEC-2023-74
- https://osv.dev/vulnerability/GHSA-9wx4-h78v-vm56
These vulnerabilities were flagged by the Scorecard scanning workflow.
=> Increase min version of Python Requests for multiple security advisories

cirq-aqt/cirq_aqt/aqt_device_metadata.py, cirq-aqt/cirq_aqt/aqt_target_gateset.py, cirq-core/cirq/contrib/acquaintance/strategies/quartic_paired.py, cirq-core/cirq/contrib/json.py, cirq-core/cirq/interop/quirk/cells/parse_test.py, cirq-core/cirq/ops/__init__.py, cirq-core/cirq/ops/op_tree.py, cirq-core/cirq/sim/clifford/clifford_simulator.py, cirq-core/cirq/sim/clifford/clifford_tableau_simulation_state.py, cirq-core/cirq/study/sweepable.py, cirq-core/cirq/transformers/analytical_decompositions/cphase_to_fsim.py, cirq-core/cirq/transformers/dynamical_decoupling.py, cirq-core/cirq/transformers/optimize_for_target_gateset_test.py, cirq-google/cirq_google/api/v2/run_context.py, cirq-google/cirq_google/engine/__init__.py, cirq-google/cirq_google/engine/engine_processor.py, cirq-google/cirq_google/engine/simulated_local_processor.py, cirq-google/cirq_google/workflow/__init__.py, cirq-rigetti/cirq_rigetti/circuit_transformers_test.py, cirq-rigetti/cirq_rigetti/sampler_parametric_circuit_test.py, cirq-rigetti/cirq_rigetti/sampler_readout_reassigned_qubits_test.py, cirq-rigetti/cirq_rigetti/sampler_readout_separate_memory_regions_test.py, cirq-rigetti/cirq_rigetti/service_parametric_circuit_test.py, examples/bb84.py, examples/shors_code.py
When I run `check/format-incremental`, it reports two trivial formatting errors as shown below. This commit fixes that.
```diff
Comparing against revision 'upstream/main'.
Running the black formatter... (version: black, 25.1.0 (compiled: yes)
Python (CPython) 3.10.14)
--- cirq-core/cirq/ops/op_tree.py	2025-01-30 20:52:25.721992+00:00
+++ cirq-core/cirq/ops/op_tree.py	2025-02-23 18:32:17.923984+00:00
@@ -10,12 +10,11 @@
-"""A recursive type describing trees of operations, and utility methods for it.
-"""
+"""A recursive type describing trees of operations, and utility methods for it."""
from typing import Callable, Iterable, Iterator, NoReturn, Union, TYPE_CHECKING
from cirq._doc import document
from cirq._import import LazyLoader
would reformat cirq-core/cirq/ops/op_tree.py
--- …
```
=> Fix format issues flagged by black

pyproject.toml
Enable formatting of all Python sources using `black .`
=> Exclude proto-generated Python files from black formatter

README.md
Resolves https://github.com/quantumlib/Cirq/security/code-scanning/399
(A bit annoying to get a code scanning alert for a missing badge. OTOH, it helps highlight that the Cirq project strives to meet open-source community standards.)
Also added a missing logo to the DOI badge.
=> Add badge for OpenSSF score

dev_tools/conf/apt-list-dev-tools.txt
pandoc is not used since #3587, but we do use shellcheck.
Also sort package names.
=> Remove apt package pandoc and add shellcheck

.github/workflows/ci-daily.yml, .github/workflows/ci-weekly.yml, .github/workflows/ci.yml, .github/workflows/pytest-debug.yaml, .github/workflows/release-main.yml
Best practices dictate that workflows should use the minimum permissions they need. This commit resolves the following code-scanning alerts:
https://github.com/quantumlib/Cirq/security/code-scanning/255 https://github.com/quantumlib/Cirq/security/code-scanning/257 https://github.com/quantumlib/Cirq/security/code-scanning/258 https://github.com/quantumlib/Cirq/security/code-scanning/259 https://github.com/quantumlib/Cirq/security/code-scanning/260 https://github.com/quantumlib/Cirq/security/code-scanning/263 https://github.com/quantumlib/Cirq/security/code-scanning/264 https://github.com/quantumlib/Cirq/security/code-scanning/265 https://github.com/quantumlib/Cirq/security/code-scanning/268 https://github.com/quantumlib/Cirq/security/code-scanning/270 …
=> Set CI workflow permissions

release.md
Per discussion on issue #6970, this adds a brief note about the approximate release cadence of Cirq.
=> Fix #6970: mention release cadence

cirq-core/cirq/ops/controlled_gate.py, cirq-core/cirq/ops/controlled_gate_test.py, cirq-core/cirq/ops/controlled_operation.py, cirq-core/cirq/ops/global_phase_op.py, cirq-core/cirq/ops/global_phase_op_test.py
Fixes #6488.
Fixes #6517.
Fixes the way global phase is handled in decomposition of controlled CZ gates (which are an intermediate step for many decompositions). This PR removes the phase from the Z sub-gate where the existing code had erroneously placed it. Instead, it creates a new, independent controlled-global-phase op as part of the decomposition, with the correct control values, and adds that into the decomposition to compensate. 
The PR also adds a handler to allow the controlled global phase op to be further decomposed into Rz's and Y's, via an equivalent diagonal gate, as desired. (`decompose` will do this automatically by default, as is checked by the `should_decompose_to_target` in tests).
Finally, it hardens the consistency check in the controlled-gate consistency tests, to …
=> Fix decompose for controlled CZ gates with phase shift

cirq-google/cirq_google/serialization/circuit_serializer.py, cirq-google/cirq_google/serialization/circuit_serializer_test.py
- Put in a special case for fsimgate deserialization so that sycamore gates are serialized to that representation.
- This will avoid potential floating point errors when deserializing.
=> Ensure SycamoreGate instances are preserved over serialization

cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/ops/pauli_string.py, cirq-core/cirq/ops/pauli_string_test.py, cirq-core/cirq/ops/swap_gates.py
Rewrite PauliString.conjugated_by.
Context: previous conjugated_by relies on _decompose_into_cliffords_ which crashes in for some cliffords: #6946.
Followup: note `pass_operations_over()` and `inplace_after()` still rely on `_decompose_into_cliffords_ `and `_pass_operation_over_`, I will clean them up in the followup PRs. (tried to clean them up in the same pr, but too many nit updates are needed in both the class itself and the tests)
=> Fix conjugated_by of PauliString.

cirq-core/cirq/transformers/dynamical_decoupling.py
Context: #7065 fixed `PauliString`'s `conjugated_by`, `before` and `after`. Now dd could use a more reliable `after()` in pulling Paulis through Cliffords.
Also read through dynamical_decoupling.py and did a couple of nit fixes.
=> Use fixed PauliString.after() in dynamical decoupling.

cirq-core/cirq/devices/grid_qubit.py, cirq-core/cirq/devices/grid_qubit_test.py, cirq-core/cirq/devices/line_qubit.py, cirq-core/cirq/devices/line_qubit_test.py
Fixes #7102. No longer coerces x/row/col to int. Wraps hash expression with `hash` instead.
On my laptop it's also a _tiny_ bit faster. It creates 10,000,000 LineQubits in 2.1s; old code took 2.5s.
Also, note that I left all the type annotations `int`, which is what they have always been. I looked into changing these into `numbers.Rational` or `SupportsFloat` or something, but it's too invasive. Lots of code seems to assume integral x/row/col values, and mypy blows up when you try to expand it.
=> [Bugfix] Re-allow non-integral line/grid qubits

examples/README.md, examples/magic_square.py, examples/magic_square_test.py
Add the Mermin-Peres magic square game described in https://en.wikipedia.org/wiki/Quantum_pseudo-telepathy#The_magic_square_game
=> Add magic square game

cirq-core/cirq/transformers/gauge_compiling/__init__.py, cirq-core/cirq/transformers/gauge_compiling/cphase_gauge.py, cirq-core/cirq/transformers/gauge_compiling/cphase_gauge_test.py
Add gauge compiling for arbitrary-angle cphase gates. Tested in [this](https://colab.sandbox.google.com/drive/15rBv6Zl5iDUDETpd-Kas50_O21fVhbwB) colab. Note that this contains the cz and sqrt_cz gauges as special cases.
=> Add cphase_gauge

cirq-google/cirq_google/engine/calibration_to_noise_properties.py
This adds 3 new CZ-gate calibration metrics to be translated from
`cirq_google.Calibration` to `cirq_google.GoogleNoiseProperties`
- two_qubit_parallel_cz_gate_xeb_pauli_error_per_cycle (gate_pauli_errors)
- two_qubit_parallel_cz_gate_xeb_entangler_theta_error_per_cycle (fsim_errors)
- two_qubit_parallel_cz_gate_xeb_entangler_phi_error_per_cycle (fsim_errors)
=> cirq-google - get CZ gate noise properties from engine calibration data

cirq-core/cirq/transformers/gauge_compiling/cphase_gauge_test.py, cirq-core/cirq/transformers/gauge_compiling/cz_gauge_test.py, cirq-core/cirq/transformers/gauge_compiling/spin_inversion_gauge_test.py, cirq-core/cirq/transformers/gauge_compiling/sqrt_cz_gauge_test.py
sweep_must_pass var in test class was used during the multi-pr implementations of as_sweep for different gauges. Now all the gauges have been supported by as_sweep, so, we can safely remove the flag here as by default sweep is tested for gauges.
=> Remove sweep_must_pass in gauge_compiling tests

dev_tools/notebooks/isolated_notebook_test.py
Pre-install a working version of qcs-sdk-python package.
Ref: https://github.com/rigetti/qcs-sdk-rust/issues/531
Ref: https://github.com/quantumlib/Cirq/pull/7126
=> Fix isolated notebooks tests against stable Cirq

.github/workflows/first-interaction.yaml
This adds a workflow that triggers on new issues and PRs. If the author has not contributed to this repository before, the workflow will add a comment with an informative welcome message to the issue or PR. The goal is to try to be welcoming of contributions and simultaneously steer people towards information they may have missed.
=> Add workflow to welcome first-time contributors

cirq-google/cirq_google/api/v1/program.proto, cirq-google/cirq_google/api/v2/batch.proto, cirq-google/cirq_google/api/v2/calibration.proto, cirq-google/cirq_google/api/v2/metrics.proto, cirq-google/cirq_google/api/v2/ndarrays.proto, cirq-google/cirq_google/api/v2/ndarrays_pb2.pyi, cirq-google/cirq_google/api/v2/program.proto, cirq-google/cirq_google/api/v2/program_pb2.pyi, cirq-google/cirq_google/api/v2/result.proto, cirq-google/cirq_google/api/v2/result_pb2.pyi, cirq-google/cirq_google/api/v2/run_context.proto, cirq-google/cirq_google/api/v2/run_context_pb2.pyi
No change in the effective content.
- Adjust comments to be more readable after formatting
- Format proto sources using
```
protofmt --remove_unused_imports --in_place $(git ls-files "*.proto")
```
=> Format proto files

cirq-core/cirq/contrib/qasm_import/_parser_test.py
The `qiskit.qasm2` submodule needs to be imported explicitly.
Also simplify test-skipping when qiskit is not installed.
Fixes failure of the CI `Coverage check` job.
=> Add missing import of qiskit.qasm2 in unit test

cirq-google/cirq_google/serialization/circuit_serializer.py, cirq-google/cirq_google/serialization/circuit_serializer_test.py
- If dimensions is missing, it should be set to 2.
- However, the previous code passed 2 to arg_from_proto.
- 2 is not a proto, it's a number, so this did not work.
=> Fix deserialization of reset gates when dimensions missing.

cirq-core/cirq/linalg/decompositions.py, cirq-core/cirq/linalg/decompositions_test.py
* Remove unused code.
* Actual raise in kron 4x4 to 2x2s (raise was in docstring, but not actualized). Update related tests as well.
* Other nit fixes.
=> Small fixes of linalg.decompositions

cirq-google/requirements.txt
Unit tests pass with protobuf-5.29.3 (latest in the 5.x series).
Python protobuf sources are still generated with protobuf-4
so cirq-google can be used in environments with protobuf-4 too.
Related to #7145
=> Allow cirq-google installation with protobuf-5

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/frozen_circuit.py
When freezing or unfreezing circuits, we have a list or tuple of `Moment` objects so we can call the `_from_moments` classmethod on the relevant target type which avoids the `isinstance` typechecks that are needed when calling `from_moments` as we do currently.
See below for a microbenchmark of this change. On main, freezing an example circuit with 10_001 moments takes something like 550us, while on this branch the same freeze operation takes about 40us (note that we have to copy the circuit before freezing because we cache the result of `freeze` if a circuit has not been mutated).
With main:
```profile
In [1]: import cirq; q = cirq.q(0); c = cirq.Circuit([cirq.X(q)] * 10_000, cirq.M(q))
In [2]: %timeit c.copy()
25.6 μs ± 135 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
In …
```
=> Avoid Moment typechecks when (un)freezing circuits

.github/workflows/first-interaction.yaml
This will hopefully solve the problem that external contributors get a "resource is not accessible by integration" error.
=> Add additional permissions to the job definition

dev_tools/requirements/isolated-base.env.txt
The dependency seems to be redundant.
=> Drop "requests" package from the isolated-base.env

.github/dependabot.yml, dev_tools/requirements/deps/cirq-all-no-contrib.txt
Having multiple directories listed is probably the reason why Dependabot sometimes opens multiple PRs for the same thing (e.g., #7142 (comment)). The requirements files include each other, and Dependabot is probably finding the same file by different paths.
Changing this to use only dev_tools/requirements/deps because the requirements in there are the basis for all the other requirements.txt files.
=> Update directories searched by Dependabot for pip case

.github/dependabot.yml
Updating chai and pixelmatch seems to cause the ts checks to fail. Based on [this comment](https://github.com/chaijs/chai/issues/1568#issuecomment-1873883627) and others in an issue thread in the Chai project repo, version 5.0.0 and higher of chai requires the use of a certain type of JavaScript modularization/packaging, and this may not be what other modules use. Perhaps this is the reason why the tests fail for us -- I can't tell without looking more closely. Right now, though, this is not an essential update to do. We need to stop Dependabot trying to update these two dependencies every time it runs.
=> Tell Dependabot to ignore higher versions of chai and pixelmatch

dev_tools/requirements/deps/packaging.txt
Problem: setuptools-77 requires packaging>=24.2, but pyquil requires
packaging~=23.1.  setuptools-77 and packaging-23 do not work together.
Solution: Temporarily pin setuptools to 76.x.
=> Fix broken development environment

cirq-google/cirq_google/serialization/circuit_serializer.py, cirq-google/cirq_google/serialization/circuit_serializer_test.py, cirq-google/cirq_google/serialization/tag_deserializer.py, cirq-google/cirq_google/serialization/tag_serializer.py
- This adds custom tag serializers for serializing tags.
- This allows greater flexibility and a much easier way to specify a serializer to serialize and deserialize internal tags.
=> Add ability to add custom tag (de)serializers

examples/README.md
The statement about everyone being free to copy, publish, etc., was ambiguous; after discussion with @dstrain, we settled on adding mention of the Apache license.
While I was at it, I got rid of my previous hacky solution for formatting the note, in favor of using GFM's simple markup for info boxes.
=> Clarify the license statement for examples/

.github/workflows/stale.yml
We deleted or renamed a couple of tags, but I forgot to update this
file. Also, we decided to allow the use of `triage/discuss` for PRs
too, so I added it to the pr-labels-list.
=> Update tags in stale issue handling GitHub Actions workflow

cirq-pasqal/cirq_pasqal/conftest.py, cirq-rigetti/cirq_rigetti/conftest.py, cirq-web/cirq_web/conftest.py
Problem: Deprecation helpers in `cirq._compat` need to detect
if they are used in a test session, but that did not work in
some sub-packages.
Solution: Make every cirq-subpackage set `CIRQ_TESTING`.
=> Let all sub-packages indicate when testing is in progress

cirq-core/cirq/protocols/hash_from_pickle_test.py, cirq-rigetti/README.md, cirq-rigetti/cirq_rigetti/aspen_device.py, cirq-rigetti/cirq_rigetti/aspen_device_test.py, cirq-rigetti/cirq_rigetti/circuit_sweep_executors.py, cirq-rigetti/cirq_rigetti/circuit_sweep_executors_test.py, cirq-rigetti/cirq_rigetti/circuit_transformers.py, cirq-rigetti/cirq_rigetti/circuit_transformers_test.py, cirq-rigetti/cirq_rigetti/conftest.py, cirq-rigetti/cirq_rigetti/deprecation.py, cirq-rigetti/cirq_rigetti/json_resolver_cache.py, cirq-rigetti/cirq_rigetti/json_test_data/spec.py, cirq-rigetti/cirq_rigetti/qcs_sampler_and_service_test.py, cirq-rigetti/cirq_rigetti/quil_input.py, cirq-rigetti/cirq_rigetti/quil_input_test.py, cirq-rigetti/cirq_rigetti/quil_output.py, cirq-rigetti/cirq_rigetti/quil_output_test.py, cirq-rigetti/cirq_rigetti/sampler.py, cirq-rigetti/cirq_rigetti/sampler_bell_circuit_test.py, cirq-rigetti/cirq_rigetti/sampler_parametric_circuit_test.py, cirq-rigetti/cirq_rigetti/sampler_readout_reassigned_qubits_test.py, cirq-rigetti/cirq_rigetti/sampler_readout_separate_memory_regions_test.py, cirq-rigetti/cirq_rigetti/sampler_test.py, cirq-rigetti/cirq_rigetti/service.py, cirq-rigetti/cirq_rigetti/service_bell_circuit_test.py, cirq-rigetti/cirq_rigetti/service_parametric_circuit_test.py, cirq-rigetti/cirq_rigetti/service_test.py, cirq-rigetti/setup.py, dev_tools/docs/run_doctest.py
- Add helper module `cirq_rigetti.deprecation`
- Add deprecation warnings for public functions and classes
- Let deprecation wrappers detect `cirq_rigetti` tests
- Suppress Cirq-Rigetti deprecation warnings in `cirq_rigetti` tests
- Add deprecation note to the Cirq-Rigetti README
Partially implements #7058
=> Deprecate Cirq-Rigetti

.github/workflows/stale.yml
The comment on GitHub are ending up without a break between paragraphs. I seems to require two blank lines in YAML.
=> Fix tiny misformatting of comments by Stale issue handler

cirq-core/cirq/experiments/readout_confusion_matrix.py, cirq-core/cirq/linalg/transformations.py, cirq-core/cirq/qis/states.py
Clean redundant type-ignores in np.einsum calls.
Fixes #5757
=> Fix np.einsum type annotations

cirq-aqt/cirq_aqt/_version.py, cirq-aqt/cirq_aqt/_version_test.py, cirq-aqt/setup.py, cirq-core/cirq/_version.py, cirq-core/cirq/_version_test.py, cirq-core/setup.py, cirq-google/cirq_google/_version.py, cirq-google/cirq_google/_version_test.py, cirq-google/setup.py, cirq-ionq/cirq_ionq/_version.py, cirq-ionq/cirq_ionq/_version_test.py, cirq-ionq/setup.py, cirq-pasqal/cirq_pasqal/_version.py, cirq-pasqal/cirq_pasqal/_version_test.py, cirq-pasqal/setup.py, cirq-rigetti/cirq_rigetti/_version.py, cirq-rigetti/cirq_rigetti/_version_test.py, cirq-rigetti/setup.py, cirq-web/cirq_web/_version.py, cirq-web/cirq_web/_version_test.py, cirq-web/setup.py, dev_tools/modules.py, dev_tools/packaging/generate-dev-version-id.sh, dev_tools/packaging/packaging_test.sh, release.md, setup.py
- Remove conditional dev-release note from package description as
PyPI makes it clear enough when user visits development release.
- Make setup.py independent of `CIRQ_PRE_RELEASE_VERSION`.
- Validate dev-version value in packaging_test.sh
- Use `runpy` instead of `exec` to obtain version value.
Make it less mysterious how is the `__version__` obtained.
- Clean up calls to io.open() which is an alias to open().
- Normalize `.dev` version value to `.dev0` per setuptools notice.
=> Simplify python package description

cirq-google/cirq_google/serialization/circuit_serializer.py, cirq-google/cirq_google/serialization/circuit_serializer_test.py
- WaitGate operations with multiple qubits need to specify the `num_qubits` parameter.
- This PR fixes this and adds an appropriate test case.
=> Fix WaitGate for multiple qubits in cirq_google proto

cirq-core/cirq/contrib/routing/greedy_test.py
On my MacOS 15.x Apple M1 laptop, I frequently get a test failure in `cirq-core/cirq/contrib/routing/greedy_test.py`:
```
[gw2] darwin -- Python 3.11.9 /Users/mhucka/.pyenv/versions/cirq-py311-np1/bin/python3
def test_router_hanging():
"""Run a separate process and check if greedy router hits timeout (5s)."""
circuit, device_graph = create_circuit_and_device()
process = Process(target=create_hanging_routing_instance, args=[circuit, device_graph])
process.start()
process.join(timeout=5)
try:
>           assert not process.is_alive(), "Greedy router timeout"
E           AssertionError: Greedy router timeout
E           assert not True
E            +  where True = is_alive()
E            +    where is_alive = <Process name='Process-1' pid=58097 parent=56380 started>.is_alive …
```
=> Avoid frequent test failure in greedy_test.py by increasing timeout

check/format-incremental
The `check/format-incremental` needs more work.
isort invocation should skip `__init__.py` files, but it does not.
Related to #7181
=> CI - skip sorting of imports with isort

check/format-incremental
- Exclude `__init__.py` files from isort targets.
Skip isort execution altogether if only `__init__.py` files changed.
- Make files in `cirq-google/cirq_google/cloud` subject to formatting.
They were already formatted by black.
Follow up to #7190, #7181
Fixes #4863
=> Fix isort invocation in format-incremental

release.md
Change:
- Update info about the Zenodo process
- Fix a reference to a slightly incorrect variable name
- Add some missing backticks to references to `main`
=> Update Zenodo info & correct a small typo

dev_tools/bash_scripts_test.py
Set the `CI` environment variable to get the `--color` option unconditionally.
Also check if `isort` is invoked.
Follow-up to #7181
=> Improve check of expected shell commands in check/format-incremental

cirq-core/cirq/contrib/paulistring/pauli_string_measurement_with_readout_mitigation.py
=> fix minor typos in docstring

README.md
Changes:
- Add mention of the list of good first issues at /contribute
- Try to shorten the text everywhere
- Tweak the size of the contributors badge
=> Revise Community section

README.md, cirq-aqt/README.md, cirq-core/README.md, cirq-core/cirq/contrib/quimb/Cirq-to-Tensor-Networks.ipynb, cirq-core/cirq/contrib/quimb/Contract-a-Grid-Circuit.ipynb, cirq-google/README.md, cirq-ionq/README.md, cirq-pasqal/README.md, cirq-rigetti/README.md, cirq-web/README.md, dev_tools/docs/build_api_docs.py, dev_tools/notebooks/isolated_notebook_test.py, docs/build/classical_control.ipynb, docs/build/interop.ipynb, docs/dev/notebooks.md, docs/gatezoo.ipynb, docs/noise/qcvv/parallel_xeb.ipynb, docs/noise/qcvv/xeb_calibration_example.ipynb, docs/simulate/qvm_stabilizer_example.ipynb, docs/tutorials/google/colab.ipynb, docs/tutorials/google/start.ipynb, docs/tutorials/google/visualizing_calibration_metrics.ipynb, release.md
Use `pip install --upgrade` to ensure the latest development version.
Adjust test of pip-install commands in notebooks.
=> Improve cirq-dev installation command

cirq-core/cirq/protocols/resolve_parameters.py
=> Clarify docstring of `is_parameterized`

docs/dev/style.md
Revise coding-style advice to prefer unquoted annotations which are
enabled by `from __future__ import annotations`
Ref: https://peps.python.org/pep-0563/
Related to #1999
=> Recommend use of unquoted annotations in coding style guide

.github/pr-size-labels.yaml, .github/workflows/pr-labeler.yaml
The previous GitHub Actions used as the labeling action was buggy. Switching to a different action that looks more promising.
=> Use a different action for size labeler GHA

cirq-core/cirq/ops/clifford_gate.py
classmethod was removed from Python as of 3.13, so this comment no longer applies.
=> Remove classmethod comment

cirq-core/cirq/contrib/qcircuit/qcircuit_pdf.py, cirq-core/cirq/contrib/qcircuit/qcircuit_pdf_test.py
Let us avoid test-only argument in `circuit_to_pdf_using_qcircuit_via_tex`.
Mock `Document.generate_pdf` instead so we can test without the `latexmk` program.
Related to #7220
=> Test qcircuit pdf generation without extra `prepare_only` argument

.github/workflows/ci-daily.yml
cirq-rigetti is not included in cirq metapackage anymore.
Make sure to install an exactly matching dev version.
Related to #7058, #7170
=> ci-daily - explicitly install cirq-rigetti for the tests

cirq-core/cirq/devices/device.py
The default value of the `edges` argument will change.  Here we
future-proof the code by providing the current default value.
This fixes  pytest -Werror cirq-core/cirq/devices/device_test.py
=> Address warning about node_link_data, node_link_graph defaults

cirq-google/cirq_google/engine/asyncio_executor.py
When using grpc with asyncio from multiple threads, spurious `PollerCompletionQueue` errors are printed due to multiple event loops listening a socket to be notified of grpc events. More than one event loop may be woken when the completion queue writes a byte to the notification socket, but only one of the loops receives the data and the others raise a `BlockingIOError`. This doesn't actually cause a problem in the grpc still works with asyncio in multiple threads, but lots of spurious error messages are printed by the default exception handler. (See https://github.com/grpc/grpc/issues/25364 for discussion of the issue.)
This configures the asyncio event loop used for grpc with an exception handler that ignores these `BlockingIOError`s from the `PollerCompletionQueue` so that we don't …
=> Ignore spurious PollerCompletionQueue errors in AsyncioExecutor

cirq-core/cirq/experiments/xeb_fitting.py
The current default is to pass grouping columns to the apply function,
which in our case does not use them at all.  Here we exclude them with
`include_groups=False` adopting the new behavior.
This fixes DataFramgeGroupBy.apply warning in
```
$ check/pytest -Werror:DataFrameGroupBy cirq-core/cirq/experiments
...
FAILED cirq-core/cirq/experiments/xeb_fitting_test.py::test_parallel_full_workflow[True] - DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated,...
```
=> Address pandas warning about deprecated DataFrameGroupBy.apply default

Dockerfile
Need to use `pip install --upgrade` to get the latest dev-release
of cirq especially if stable cirq was already installed before.
Follow-up to #7213
=> Fix docker installation for cirq_pre_release image

.github/workflows/ci.yml, dev_tools/requirements/deps/packaging.txt
Upgrade setuptools and wheel before installing the dev.env requirements
for the CI.  The Python environments in GHA comes with old setuptools
which makes the installation of dev.env fail.
Same for Python environment used in the Packaging Test CI.
=> Fix failing CI tests due to old setuptools

.github/workflows/release-main.yml
Upgrade setuptools before creating wheel archives.
Follow-up of #7249
=> CI - fix failing pre-release workflow

.github/workflows/ci.yml, conftest.py
numpy had a warnings helper for that which got removed in numpy-2.2.
Also remove the custom pytest option `--warn-numpy-data-promotion`.
Fixes numpy-2 test failure due to use of removed function.
=> Drop temporary warnings about changed data promotion in numpy-2

cirq-core/cirq/ops/clifford_gate.py
Address `DeprecationWarning: NotImplemented should not be used in a boolean context`
This fixes
```
check/pytest -Werror:"NotImplemented should":DeprecationWarning
```
=> Avoid using NotImplemented as a boolean

cirq-google/cirq_google/serialization/circuit_serializer.py
- If empty, invert_mask is converted to an empty tuple object.
- This is not yet supported server-side.
=> Fix serialization error in cirq_google.

cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/circuit_operation_test.py, cirq-core/cirq/ops/classically_controlled_operation_test.py, cirq-core/cirq/protocols/json_test_data/CircuitOperation.json, cirq-core/cirq/protocols/json_test_data/CircuitOperation.repr_inward
Revert "Flip back to default `use_repetition_ids=True` in CircuitOperation (#7237)"
This reverts commit 58d9619a2a420c1a0a721b28e7d784bcc0a8ec81.
This also finalizes #7232
=> Roll forward #6910 - CircuitOperation: change use_repetition_ids default to False

release.md
- update twine authentication arguments
- when installing from Test PyPI pass it via `--extra-index-url`
so that standard index remains in use for cirq dependencies
=> Clarify instructions for release process

cirq-google/cirq_google/serialization/circuit_serializer_test.py
Let `test_unknown_tag_is_ignored` be the one that warns about
`Unknown tag` and `test_unrecognized_tag_is_ignored` about
`Unrecognized Tag`.
No change in the effective code.
=> Flip test names to match expected warnings

.github/workflows/pr-labeler.yaml
Required per https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#add-labels-to-an-issue
=> Put back the issues-write permission for pr-labeler

cirq-core/cirq/ops/matrix_gates.py, cirq-core/cirq/protocols/circuit_diagram_info_protocol_test.py
Fixes #7243 
This PR corrects the way Cirq prints a controlled 1×1 MatrixGate in ASCII/Unicode circuit diagrams and tidies up the underlying protocol behavior. Previously, attempting to draw a 1×1 controlled gate raised a TypeError. Now it will render correctly, and a unit test has been created to verify the output.
matrix_gates.py
Early‑return NotImplemented for zero‑qubit MatrixGate, deferring to the fallback renderer.
circuit_diagram_info_protocol_test.py
Updated test_controlled_1x1_matrixgate_diagram_error to assert the exact rendered string:
0: ───C[[0.+1.j]]───  
Ran pytest cirq/protocols/circuit_diagram_info_protocol_test.py — all relevant tests pass.
=> Fixes crash when printing circuit with controlled MatrixGate

cirq-core/cirq/protocols/decompose_protocol.py
Hopefully it is more informative as to why decomposition failed.
Also correct a typo in the if condition.
Resolves #6667
=> Clarify error message for `decompose_once(X(q))`

cirq-core/cirq/study/sweeps.py, cirq-core/cirq/study/sweeps_test.py
- cirq.Zip param_tuples was doing a sum of tuples, which was creating n^2 tuples over the course of the calculations.
- Use itertools to do this correctly.
Using a zip of 1000 different values of 10000 different values: Before: 110 seconds.  After: 5.6 seconds
```
%timeit sum(values, ())
111 ms ± 3.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit tuple(itertools.chain.from_iterable(values))
431 µs ± 3.98 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
=> Make cirq.Zip twenty times faster

.github/workflows/ci-daily.yml, .github/workflows/ci.yml
This should prevent failures of pip-install due to incompatibility
between cached Python environment and active pip tool.
See https://github.com/quantumlib/Cirq/pull/7302 for example failures.
Ref: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
=> CI - replace actions/cache with setup-python package caching

cirq-core/cirq/contrib/acquaintance/gates.py, cirq-core/cirq/ops/boolean_hamiltonian_test.py, cirq-core/cirq/study/sweeps.py, cirq-core/cirq/transformers/analytical_decompositions/controlled_gate_decomposition.py
Such summations create many temporary lists or tuples which is slow.
Instantiate just one list or tuple instead.
=> Rewrite inefficient `sum(..., [])` and `sum(..., ())`

dev_tools/requirements/mypy.env.txt
Problem: Type checking fails in an environment with numpy-2.
Solution: Unblock the ci by pinning to numpy-1.  Fix annotations for numpy-2 ASAP.
Partially resolves #7323
=> CI - fix type check with a temporary pin to numpy-1

cirq-core/cirq/contrib/paulistring/clifford_optimize.py, cirq-core/cirq/contrib/paulistring/recombine.py, cirq-core/cirq/contrib/paulistring/separate.py, cirq-core/cirq/ops/pauli_string.py, cirq-core/cirq/ops/pauli_string_phasor.py, cirq-core/cirq/ops/pauli_string_phasor_test.py, cirq-core/cirq/ops/pauli_string_test.py
Starts deprecating all pass_operations_over().
pass_operations_over class function for PauliString* Classes is supposed to be replaced by conjuaged_by(), after(), before(). And the function itself is confusing and misleading in terms of the input order (see #2351).
Context: #7123 and #2351.
=> Start deprecating pass_operations_over for PauliString and PauliStringPhasor

docs/tutorials/google/identifying_hardware_changes.ipynb
- This fixes the simple errors in the identifying_hardware_changes notebook from #5588.
- I am not sure this notebook is runnable though, as we no longer use sqrt ISWAP and the two-qubit metrics are missing.
=> Fix qubit metadata in identifying_hardware_changes

.github/workflows/ci-daily.yml, .github/workflows/ci-weekly.yml, .github/workflows/ci.yml, .github/workflows/ossf-scorecard.yaml, .github/workflows/pr-labeler.yaml, .github/workflows/stale.yml
Avoid spending users GHA resources on our CI jobs in GitHub forks.
Downstream Cirq forks can remove the if-guard if they really want
to run workflows.
Ref: https://github.com/orgs/community/discussions/26704
=> Disable all GitHub Actions jobs in forks

cirq-core/cirq/contrib/qasm_import/_parser_test.py, cirq-core/cirq/testing/random_circuit_test.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_cz_test.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim_test.py, cirq-core/cirq/transformers/routing/line_initial_mapper_test.py
Follow up to #7327, related to #4393.
=> Add few more return-type annotations to tests

cirq-core/cirq/contrib/requirements.txt
- The cotengra developer has quickly fixed the bug in 0.7.3 and released 0.7.4, so we should be okay to unpin this requirement.
=> Unpin cotengra requirement

docs/google/concepts.ipynb, docs/google/devices.md, docs/tutorials/google/spin_echoes.ipynb
- The function cirq_google.optimized_for_sycamore has been replaced by the transformer paradigm and can be implemented using the appropriate CompilationTargetGateset for the device.
- This PR removes the last references to them in the documentation.
=> Remove documentation references to optimized_for_sycamore

cirq-core/cirq/__init__.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/symbolize.py, cirq-core/cirq/transformers/symbolize_test.py
Symbolizes single qubit gates by tags.
Example:
Input:
```
0: ───X[phxz_0]───@───Y[phxz_1]───X───
│
1: ───────────────@───────────────────
```
`$  cirq.symbolize_single_qubit_gates_by_indexed_tags(c, tag_prefix="phxz")`
Output:
```
0: ───PhXZ(a=a0,x=x0,z=z0)───@───PhXZ(a=a1,x=x1,z=z1)───X───
│
1: ──────────────────────────@──────────────────────────────
```
where, a0,x0,z0,a1,x1,z1 are symbols.
Context: to be used in https://github.com/quantumlib/Cirq/issues/6994.
=> Add a symbolize transformer

dev_tools/requirements/deps/packaging.txt
This was added as a workaround in #7168, but the problem
appears to be fixed upstream in pyquil.
=> Unpin upper bound on setuptools requirement

cirq-google/cirq_google/engine/__init__.py, cirq-google/cirq_google/engine/virtual_engine_factory.py, cirq-google/cirq_google/engine/virtual_engine_factory_test.py
Convenience function for constructing GoogleNoiseProperties from available
specifications for known QVM devices.
Related to b/395705720
=> Add QVM factory function load_device_noise_properties

cirq-core/requirements.txt
As of #7234 we use the `edges` argument to `node_link_data` which
was added in networkx-3.4.
=> Bump networkx to minimum version 3.4

cirq-core/cirq/ops/control_values_test.py, cirq-core/cirq/ops/pauli_gates_test.py, cirq-core/cirq/ops/raw_types_test.py, cirq-core/cirq/ops/state_preparation_channel_test.py, cirq-core/cirq/protocols/qasm.py, cirq-core/cirq/sim/clifford/clifford_simulator_test.py, cirq-core/cirq/sim/simulator_test.py, cirq-core/cirq/value/abc_alt.py, cirq-core/cirq/value/linear_dict_test.py, cirq-core/cirq/value/measurement_key_test.py, cirq-core/cirq/value/timestamp_test.py, dev_tools/conf/.pylintrc
Activate pylint rules used in pyle and fix flagged issues.
Added pylint rules:
- abstract-class-instantiated
- assignment-from-no-return
- bad-chained-comparison
- bad-mcs-classmethod-argument
- bad-mcs-method-argument
- deprecated-decorator
- method-hidden
- raising-bad-type
- raising-format-tuple
- redefined-slots-in-subclass
- self-cls-assignment
- shadowed-import
- simplifiable-condition
- unneeded-not
- use-maxsplit-arg
- using-constant-test
Related to #7371
=> pylint - sync with rules used in internal codes

cirq-core/cirq/transformers/merge_single_qubit_gates_test.py
This fixes a minor issue I found while working on #7291 
The test case names don't match the method being tested. This is confusing because there is another method called `merge_single_qubit_moments_to_phxz`, but it's not the one tested here.
=> Fix test case names.

dev_tools/notebooks/isolated_notebook_test.py, docs/hardware/qubit_picking.ipynb, docs/simulate/noisy_simulation.ipynb, docs/simulate/quantum_virtual_machine.ipynb, docs/simulate/qvm_basic_example.ipynb
Replace calls of `noise_properties_from_calibration` with
`load_device_noise_properties` so users do not need to pass
the `gate_times_ns` argument.
Updated notebooks need to install development cirq and be listed in
`NOTEBOOKS_DEPENDING_ON_UNRELEASED_FEATURES`.
Related to b/395705720
=> Prefer load_device_noise_properties in example notebooks

cirq-core/cirq/_compat.py, cirq-core/cirq/contrib/quantum_volume/quantum_volume.py, cirq-core/cirq/experiments/random_quantum_circuit_generation.py, cirq-core/cirq/experiments/xeb_sampling.py, cirq-core/cirq/ops/classically_controlled_operation.py, cirq-core/cirq/sim/density_matrix_simulator_test.py, cirq-core/cirq/sim/simulator_base.py, cirq-core/cirq/sim/sparse_simulator_test.py, cirq-google/cirq_google/engine/asyncio_executor.py, cirq-rigetti/cirq_rigetti/circuit_transformers.py, dev_tools/requirements/deps/mypy.txt
- Bump mypy to 1.16.0
- Remove redundant cast and ignore comments
- Add casts and ignores for typing flagged by mypy-1.16.0
- Fix annotations of simulator step results
Replaces #7404
=> Bump mypy to 1.16.0

cirq-core/cirq/transformers/analytical_decompositions/three_qubit_decomposition.py, cirq-core/cirq/transformers/analytical_decompositions/three_qubit_decomposition_test.py
We require scipy>=1.11 so any special code for earlier scipy is dead.
=> Remove dead code for scipy<=1.5

cirq-core/cirq/transformers/dynamical_decoupling.py
Context: Constructing circuit using Circuit.from_moment instead of passing all the moments to Circuit() can improve the construction performance of Circuit as being suggested by NoureldinYosri@.
Also did some minor improvements of imports.
=> Update dd with faster circuit construction

cirq-google/cirq_google/experimental/analog_experiments/__init__.py, cirq-google/cirq_google/experimental/analog_experiments/analog_trajectory_util.py, cirq-google/cirq_google/experimental/analog_experiments/analog_trajectory_util_test.py, cirq-google/cirq_google/experimental/analog_experiments/symbol_util.py, cirq-google/cirq_google/ops/analog_detune_gates.py, cirq-google/cirq_google/study/symbol_util.py, cirq-google/cirq_google/study/symbol_util_test.py
Add FreqMap and AnalogTrajectory into cirq_google.experiments.
In this PR, two major differences compared with Trond did before.
1. `AnalogTrajectory` initialized with classmethod so that the class member is always full_trajectory
2. Add the resolving ability in the `FreqMap` so that we can provide the symbol into it and plot it with resolver like `pulse_plot` 
New usage example
```py
traj1 = (20 * tu.ns, {"q0_1": 5 * tu.GHz}, {})
traj2 = (sympy.Symbol("t1"), {"q0_2": 8 * tu.GHz}, {})
traj3 = (
40 * tu.ns,
{"q0_0": 8 * tu.GHz, "q0_1": None, "q0_2": None},
{("q0_0", "q0_1"): 5 * tu.MHz, ("q0_1", "q0_2"): 8 * tu.MHz},
)
trajs = [traj1, traj2, traj3]
analog_traj = AnalogTrajectory.from_sparse_trajecotry(trajs)
analog_traj.plot(resolver={"t1": 50*tu.ns})
```
=> Add AnalogTrajectory and FreqMap

cirq-aqt/setup.py, cirq-core/cirq/_version.py, cirq-core/setup.py, cirq-google/cirq_google/_version.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-rigetti/setup.py, cirq-web/setup.py, dev_tools/modules_test_data/mod1/setup.py, setup.py
Problem: Internal documentation build does not support python3.11 yet.
Solution: Allow installation for Python 3.10 so that docs build can
use latest development releases.
Related to #6648
=> Permit installation for Python 3.10 (docs build only)

dev_tools/requirements/deps/mypy.txt
- Bump mypy from 1.16.0 to 1.16.1 in /dev_tools/requirements/deps
- Let us unify version specs for types-requests and requests
=> Combine mypy version updates

cirq-core/cirq/contrib/paulistring/pauli_string_measurement_with_readout_mitigation.py, cirq-core/cirq/contrib/paulistring/pauli_string_measurement_with_readout_mitigation_test.py
Avoid possible KeyError in `test_process_pauli_measurement_results_raises_error_on_missing_calibration`
Problem: Random Pauli strings generated in the test may not contain all qubits
as is assumed in the `empty_calibration_result_dict` key.
Solution: Make dictionary with the qubits present in Pauli strings.
Fixes spurious test failure
```
pytest --randomly-seed=532866775 \
cirq-core/cirq/contrib/paulistring/pauli_string_measurement_with_readout_mitigation_test.py \
-k test_process_pauli_measurement_results_raises_error_on_missing_calibration
```
Also fix
- unnecessarily repeated list construction
- unintentional dropping of circuits in a loop
- Nit - sync docstring with function arguments
=> Fix test flake in pauli_string_measurement_with_readout_mitigation_test

cirq-core/cirq/transformers/align.py, cirq-core/cirq/transformers/dynamical_decoupling.py, cirq-core/cirq/transformers/dynamical_decoupling_test.py, cirq-core/cirq/transformers/expand_composite_test.py, cirq-core/cirq/transformers/measurement_transformers.py, cirq-core/cirq/transformers/merge_single_qubit_gates.py, cirq-core/cirq/transformers/merge_single_qubit_gates_test.py, cirq-core/cirq/transformers/noise_adding.py, cirq-core/cirq/transformers/optimize_for_target_gateset.py, cirq-core/cirq/transformers/qubit_management_transformers.py, cirq-core/cirq/transformers/randomized_measurements.py, cirq-core/cirq/transformers/stratify.py, cirq-core/cirq/transformers/symbolize.py, cirq-core/cirq/transformers/tag_transformers.py, cirq-core/cirq/transformers/transformer_api.py, cirq-core/cirq/transformers/transformer_primitives.py, docs/build/classical_control.ipynb
I came across a couple of typos in transformers, so I ask the code assistant to help identify more of them and update all here.
=> Fix a couple of typos in transformers

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/circuits/frozen_circuit.py, cirq-core/cirq/circuits/frozen_circuit_test.py
First step towards fixing https://github.com/quantumlib/Cirq/issues/7454. This PR just adds the `tags` attribute to `AbstractCircuit`, along with some of the logic (e.g. `__eq__`, `_json_dict_`, etc). After this we have to add support in the proto serialization itself.
Partially implements #7454
=> Promote FrozenCircuit.tags to AbstractCircuit

.github/CODEOWNERS
=> CODEOWNERS - remove owner specifications for cirq-rigetti

cirq-core/requirements.txt, dev_tools/requirements/deps/ipython.txt
* drop numpy-1.25 per NEP-29 and SPEC-0
* drop scipy-1.11 per SPEC-0
* drop matplotlib-3.7 per SPEC-0
* drop pandas-2.0 per SPEC-0
* drop ipython-8.14 and allow ipython-9 per SPEC-0
Refs:
* https://numpy.org/neps/nep-0029-deprecation_policy.html
* https://scientific-python.org/specs/spec-0000
Resolves b/392641425
=> Update Scientific Python dependencies per NEP-29 and SPEC-0

cirq-aqt/setup.py, cirq-core/cirq/_version.py, cirq-core/setup.py, cirq-google/cirq_google/_version.py, cirq-google/setup.py, cirq-ionq/setup.py, cirq-pasqal/setup.py, cirq-web/setup.py, dev_tools/modules_test_data/mod1/setup.py, setup.py
NEP-29 require minimum Python version 3.11
Roll forward of #7338 because internal documentation build can now
run with Python 3.11.  A few capitalization fixups are here too.
Revert "Permit installation for Python 3.10 (docs build only) (#7445)"
This reverts commit 609d93dbc51a6608a0d0c3f5d50d51325052e027.
Fixes #6648
=> NEP-29 - require minimum Python version 3.11

cirq-core/cirq/study/sweeps.py, cirq-core/cirq/study/sweeps_test.py
Reverts quantumlib/Cirq#7490
See b/433265888
=> Revert "Expand parameters for product sweeps iteratively instead of recursively"

cirq-core/cirq/devices/grid_qubit.py
- An internal bug noted that there could be confusion if you assumed that GridQubit.neighbors() returned only the neighbors on a specific device layout.
- This changes only the documentation to point out that this function is device-agnostic.
=> Add clarification to GridQubit neighbors function

cirq-core/cirq/study/sweeps.py, cirq-core/cirq/study/sweeps_test.py
The new unit test assertion involving a product of 1025 sweeps crashes the current implementation with a "max recursion depth exceeded" error, but passes with the new implementation. This is particularly relevant when dict_to_product_sweep is called with a large input dictionary.
This re-introduces the change reverted in https://github.com/quantumlib/Cirq/pull/7522 and addresses the issue which caused the failure:
`itertools.chain.from_iterable` produces an `Iterator` as its output, meaning the output object can only be iterated through once before it is exhausted. However, `Params` is a type alias for `Iterable[tuple['cirq.TParamKey', 'cirq.TParamVal']]`, meaning it is expected for a given `Params` to be iterated through repeatedly. This is also necessary in order for the `Params` …
=> Expand product sweep parameters iteratively rather than recursively

docs/_book.yaml
The removal of some documents in a previous PR left the left-side TOC panel with an extra heading. Now, it also turns out that none of the other sections in the Cirq docs use an accordion, so we can feed two birds with one scone by getting rid of the accordion and moving the contents up one level. This should result in a properly-structured panel.
<div align="center">
</div>
=> Fix sidepanel contents for section on noise

cirq-google/cirq_google/engine/stream_manager.py
https://github.com/quantumlib/Cirq/pull/7500 modified the `quantum_run_stream` method definition by changing the `timeout` argument from `timeout: float | None = None` to `timeout: float | object = gapic_v1.method.DEFAULT`. Setting `timeout=None` is interpreted as having no timeout at all, whereas `timeout=gapic_v1.method.DEFAULT` uses the framework-supplied default value of 60s. For bidirectional streams, the `timeout` is used to set the lifetime of the entire stream, causing batches of jobs which cumulatively take more than 60s to fail with `DEADLINE_EXCEEDED` errors. This change sets `timout=None` explicitly, restoring the behavior previously obtained via the default argument.
=> Restore behavior which persists `quantum_run_stream`s indefinitely

cirq-core/cirq/circuits/moment_test.py, cirq-core/cirq/protocols/kraus_protocol.py, cirq-core/cirq/protocols/kraus_protocol_test.py
- There were a few issues with the new strategy to fall back to super-operator calculations using apply_channels.
- First, the super_operator_to_kraus function is generally not precise or numerically stable enough to support an atol of 1e-10 so loosened this to 1e-6 and also allowed the ability to specify this as a parameter.
- Next, some operators define decomposition, so cirq.kraus should try to decompose and get a unitary before falling back to using apply_channel.
Fixes: #7536
=> Fix kraus channels for fallbacks to super-operators

cirq-core/cirq/ops/fsim_gate.py, cirq-core/cirq/value/condition.py, cirq-google/cirq_google/line/placement/anneal.py, cirq-google/cirq_google/ops/analog_detune_gates.py, cirq-google/cirq_google/serialization/arg_func_langs.py, cirq-ionq/cirq_ionq/results.py
- These are typos identified by running the CommonTypos internal tool on api reference docs for cirq.
=> Fix typos in reference docs

cirq-core/cirq/transformers/dynamical_decoupling.py, cirq-core/cirq/transformers/dynamical_decoupling_test.py
To prevent undesired transformations, dd no longer merges adjacent moments automatically for those added moments. For instance, the previous behavior could incorrectly merge single-qubit gates into two-qubit moments. If merging is required, please call `merge_moments` or `merge_single_qubit_gates` explicitly after dd.
=> Remove the merge moments logic in dd

cirq-google/cirq_google/api/v2/sweeps.py, cirq-google/cirq_google/api/v2/sweeps_test.py
Adding an option in the `run_context_to_proto` so that only one of the float32 or float64 will be written into proto. Default to be float 32 so that the behavior is unchanged. 
When we update the Cirq version internally to include this CL, we need to make sure all  swithcing into `v2.run_context_to_proto(.., use_float64=True)`
=> Add option and set the default float encoding as float32

docs/build/interop.ipynb
Since recent changes have added supports for multiple statements, update the description in the OpenQASM compatibility table accordingly. 
#6917: added "gate" support
#6710: added "reset" support
#4738: added "if" support
Fixes: #7525
=> Update OpenQASM compatibility table

dev_tools/notebooks/isolated_notebook_test.py, docs/hardware/qubit_picking.ipynb, docs/simulate/noisy_simulation.ipynb, docs/simulate/quantum_virtual_machine.ipynb, docs/simulate/qvm_basic_example.ipynb, docs/simulate/qvm_builder_code.ipynb, docs/simulate/qvm_stabilizer_example.ipynb, docs/simulate/virtual_engine_interface.ipynb
Make all notebook tests use stable cirq after the 1.6.0 release.
Ref: https://github.com/quantumlib/Cirq/blob/main/docs/dev/notebooks.md#lifecycle
Fixes #7556
=> Test all notebooks vs stable Cirq after the release

cirq-core/cirq/interop/quirk/cells/parse.py, cirq-core/cirq/study/resolver.py, cirq-google/cirq_google/serialization/arg_func_langs.py, pyproject.toml
- enable rule RUF027 - missing-f-string-syntax
- fix f-strings without the f-prefix
Partially implements #7505
=> ruff - enable and fix RUF027 - missing-f-string-syntax

cirq-core/cirq/ops/gateset.py, cirq-core/cirq/ops/gateset_test.py
Gate Families have two main modes of operations: 'type' gate families that check containment versus a type of gate and 'instance' gate families which check whether the operation matches a specific instantiation of the gate.  'instance' checking is much slower.
- This PR switches the order of checking gate families.  It now checks "type" gate families before "instance" gate families.
- Type gate family checks are simple `isinstance` checks and should be fast.
- Instance gate families check instance equality, which is a lot slower, since it has to compare value equality for every operation for containment.
This speeds up the validation of a sample circuit with 400 moments of 18 single-qubit operations from 1.5 seconds to 0.11 seconds.
=> Change order of checking containment within a gateset

cirq-core/cirq/study/sweeps.py
- This change improves the performance of _check_duplicate_keys.
- Rather than check each sweep individually, this adds the keys of all the sweeps to the set and checks the total size. The total size of the set should be the sum of the sizes of the sweep, otherwise there are duplicates.
- This is a relatively minor performance improvement, but I saw it while trying to optimize something else, and it is self-contained.
This speeds checking a large sweep (the example I have is a Zip of 700k sweeps) from 300ms to 150ms.
=> Performance improvement in _check_duplicate_keys

cirq-google/cirq_google/api/v2/sweeps.py, cirq-google/cirq_google/api/v2/sweeps_test.py
- This function was building the Const message twice.
- Instead, write directly to the proto message.
- This speeds up run contexts with Const values up by about 40%.
=> Improve performance of _build_sweep_const

.github/workflows/ci.yml, dev_tools/packaging/generate-dev-version-id.sh, dev_tools/packaging/packaging_test.sh, dev_tools/packaging/produce-package.sh
Produce timestamp string with respect to the UTC time zone.
Also ensure the working repository is in a pristine state.
Partially implements #6502
=> Generate reproducible dev-versions from the last commit time

cirq-google/cirq_google/cloud/README.md, dev_tools/conf/mypy.ini, pyproject.toml
The cirq-google/cirq_google/cloud contains only generated code.
=> Add linting and type checking overrides for cirq-google/cirq_google/cloud, which contains only generated code

cirq-core/cirq/contrib/paulistring/pauli_string_measurement_with_readout_mitigation_test.py
This PR updates the tolerance of the np.isclose assertion used to validate the mitigated expectation value against its ideal value. The tolerance is being increased from 4 * mitigated_stddev to 10 * mitigated_stddev. 
The nature of calculating a Pauli expectation is to statistically estimate the value by sampling from measurement outcomes a finite number of times, which by chance can lead to a small probability of the result deviate from the ideal value by > 4 * standard deviations. Increasing the tolerance to 10  * mitigated_stddev can makes the test much more robust against these statistical fluctuations.
Fixes #7612
=> Increase np.isclose tolerance for mitigated expectation value assertion

cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/linear_combinations.py, cirq-core/cirq/ops/pauli_string_test.py
Allow PauliString-like gates to be used in PauliSum expressions.
Fixes #7280
=> Allow PauliString-like gates to be used in PauliSum

cirq-core/cirq/transformers/gauge_compiling/__init__.py, cirq-core/cirq/transformers/gauge_compiling/idle_moments_gague.py, cirq-core/cirq/transformers/gauge_compiling/idle_moments_gauge.py, cirq-core/cirq/transformers/gauge_compiling/idle_moments_gauge_test.py
Adding a gauge compiler that surrounds empty sequences by randomly chosen gates ... this gauge is technically half way between a gauge and dynmical decoupling
=> Create a gauge for idle moments

cirq-core/cirq/ops/arithmetic_operation.py, cirq-core/cirq/ops/common_gates.py, cirq-core/cirq/ops/pauli_string_phasor.py
In the docstring of [ArithmeticGate.apply](https://quantumai.google/reference/python/cirq/ArithmeticGate),
two exponentiation `**` accidentally combine to a bold text syntax.
Here we add backtick quotes to avoid this, and also fix a few other
similar instances.
=> Fix unexpected markdown syntax in docstring

dev_tools/requirements/mypy.env.txt
Type check fails for numpy-2.3.3.  Add temporary pin
to numpy-2.2.x to let it pass.
Workaround for #7657
=> CI - unblock type check with a temporary pin to numpy-2.2

cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/engine/engine_processor.py, cirq-google/cirq_google/engine/processor_sampler.py
Increases default throughput for Quantum Engine users.
=> Increase default max_concurrent_jobs to 100

cirq-core/cirq/linalg/transformations.py, cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/sim/clifford/stabilizer_state_ch_form.py, cirq-core/cirq/sim/state_vector_simulation_state.py, cirq-core/cirq/testing/lin_alg_utils.py, cirq-core/cirq/transformers/heuristic_decompositions/two_qubit_gate_tabulation.py, dev_tools/requirements/mypy.env.txt
- revert "CI - unblock type check with a temporary pin to numpy-2.2 (#7658)"
- purge unused "type: ignore" comments
- fix small issues showing for numpy-2.3.3
- allow convertible types for the dtype argument of `StateVectorSimulationState`
Fixes #7657
=> Fix type-checking issues for numpy-2.3.3

cirq-core/cirq/contrib/paulistring/clifford_optimize.py
This adds a basic documentation string to the function `clifford_optimized_circuit()` in the file `cirq-core/cirq/contrib/paulistring/clifford_optimize.py`.
=> Fix #2961: add basic docstring to clifford_optimized_circuit()

cirq-core/cirq/ops/wait_gate.py, cirq-core/cirq/value/duration.py
- Noticed some inefficiencies in the creation of WaitGate where it is doing unnecessary object boxing.
- This removes (slow) comparisons between Duration objects.
This improves creation of WaitGate objects (e.g. from cirq.wait(nanos=10)) from about 27 micros to about 16 micros. While not a huge effect, this could have measurable savings for certain T1 and similar experiments that involve creation of lots of wait gates.
=> Micro-optimizations to WaitGate

cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/gauge_compiling/__init__.py, cirq-core/cirq/transformers/gauge_compiling/multi_moment_cphase_gauge.py, cirq-core/cirq/transformers/gauge_compiling/multi_moment_cphase_gauge_test.py, cirq-core/cirq/transformers/gauge_compiling/multi_moment_gauge_compiling.py
Support multi moment gauge transformation, where target moments will be gauged with new moments, e.g., 
```
q₀: ... ───LG0───╭───────────╮────RG0───...
│           │
q₁: ... ───LG1───┤  moments  ├────RG1───...
│   to be   │
q₂: ... ───LG2───┤ gauged on ├────RG2───...
│           │
q₃: ... ───LG3───╰───────────╯────RG3───...
```
* A common `MultiMomentGaugeTransformer` class is defined.
* Implemented the CPhase multi moment gauge `CPhaseGaugeTransformerMM`.
* A moment is a target moment if it contains at least one target op (CZPowGate) and all its operations are supported by this transformer.
* A couple of single qubit gates are supported for `CPhaseGaugeTransformerMM`, e.g., Pauli Gates, ZPowGate etc. If these gates are detected, gauge will be calculated accordingly. Users can tweak their …
=> Support multi moment gauge compiling
