README.rst

just a suggestion if you like the aesthetics. Don't merge if you don't like it! I like it because it links to pypi and shows the most recent release version number. But you might hate it!

pypi badge

---

docs/requirements.txt

Not necessary for ReadTheDocs since it installs cirq first.

Remove .. package install for docs build

---

cirq/contrib/paulistring/pauli_string_phasor.py
cirq/ops/pauli_string.py
cirq/ops/pauli_string_test.py

Add PauliString method to_z_basis_ops()

---

cirq/contrib/paulistring/__init__.py
cirq/contrib/paulistring/convert_gate_set.py
cirq/contrib/paulistring/convert_gate_set_test.py
cirq/contrib/paulistring/pauli_string_phasor.py
cirq/contrib/paulistring/pauli_string_phasor_test.py
cirq/ops/clifford_gate.py
cirq/ops/clifford_gate_test.py

Also:
- Add pass_operations_over() method to PauliStringPhasor
- Add parenthesis around CliffordGate text diagram output if not drawn as a single symbol

Conversion to Clifford+PauliStringPhasor gate set

---

continuous-integration/.pylintrc
dev_tools/check_pylint.py
dev_tools/shell_tools.py
docs/development.md

- Move pylint config from command line flags into config file

Add instructions for running check commands directly

---

cirq/contrib/paulistring/__init__.py
cirq/contrib/paulistring/separate.py
cirq/contrib/paulistring/separate_test.py

Add circuit separation into non-Clifford and Clifford halves

---

cirq/__init__.py
cirq/contrib/jobs/job.py
cirq/contrib/jobs/job_test.py
cirq/google/engine/engine.py
cirq/google/params.py
cirq/google/params_test.py
cirq/ops/__init__.py
cirq/ops/common_gates_test.py
cirq/ops/partial_reflection_gate_test.py
cirq/ops/pauli_interaction_gate_test.py
cirq/schedules/schedule_test.py
cirq/schedules/schedulers_test.py
cirq/study/__init__.py
cirq/study/sweeps.py
cirq/study/sweeps_test.py
cirq/testing/random_circuit_test.py

- Rename sweeps.Unit into UnitSweep and fix it not being exported from cirq
- Fix PartialReflectionGate not being exported from cirq

Use 'import cirq' in test imports (Part 1)

---

cirq/circuits/circuit_test.py
cirq/contrib/paulistring/pauli_string_phasor.py
cirq/contrib/paulistring/pauli_string_phasor_test.py
cirq/contrib/quirk/export_to_quirk_test.py
cirq/ops/common_gates_test.py
cirq/ops/eigen_gate.py
cirq/ops/eigen_gate_test.py
cirq/ops/gate_features.py
cirq/ops/gate_operation.py
cirq/ops/matrix_gates.py
cirq/ops/matrix_gates_test.py
cirq/ops/partial_reflection_gate.py
cirq/value/symbol.py
cirq/value/symbol_test.py

- Enables ** notation when creating operations

Add identity arithmetic operations to Symbol

---

check/mypy
check/pylint
check/pytest
check/pytest-and-incremental-coverage
check/pytest2
dev_tools/run_pytest_and_incremental_coverage.py

Fixes https://github.com/quantumlib/Cirq/issues/784

Fix check/ tools not going to repo root

---

cirq/contrib/paulistring/__init__.py
cirq/contrib/paulistring/clifford_optimize.py
cirq/contrib/paulistring/clifford_optimize_test.py

This optimizer could be used in optimized_for_xmon() to res​olve #756.

Add Clifford circuit optimizer

---

cirq/contrib/paulistring/__init__.py
cirq/contrib/paulistring/optimize.py
cirq/contrib/paulistring/optimize_test.py

Uses the Pauli string and Clifford optimizers.

Add an overall circuit optimizer

---

cirq/contrib/paulistring/clifford_optimize.py
cirq/contrib/paulistring/clifford_optimize_test.py
cirq/contrib/paulistring/optimize.py

Also adds a test that would fail before this fix.

Fix bug in Clifford optimizer

---

docs/tutorial.md

Fix typo (anstaz -> ansatz) in tutorial.md

---

docs/circuits.md
docs/development.md
docs/extensions.md
docs/gates.md
docs/simulation.md
docs/tutorial.md

" ansatz" has been fixed by https://github.com/quantumlib/Cirq/pull/883

Fix minor typos

---

CONTRIBUTING.md
cirq/circuits/qasm_output_test.py
cirq/contrib/paulistring/convert_to_pauli_string_phasors.py
cirq/ops/common_gates.py
cirq/ops/common_gates_test.py

Addressing: https://github.com/quantumlib/Cirq/issues/872

cirq.H with EigenGate implementation Fixes #872

---

cirq/circuits/circuit_dag.py
cirq/contrib/paulistring/pauli_string_optimize.py

Fix 2 small issues with networkx that cause backwards compatibility issues if you only have networkx 1.10.

Fix 2 backwards compatibility issues with networkx

---

README.rst

Here: https://github.com/quantumlib/Cirq/issues/955

Add link to quantum stack overflow for questions. Fixes #955

---

cirq/ops/pauli_interaction_gate.py
cirq/ops/pauli_interaction_gate_test.py

Modify cirq.PauliInteractionGate's __repr__  to output valid python

---

dev_tools/auto_merge.py

- Detect if merge is blocked due to absent required status checks
- Add a fallback if the merge is blocked for some unknown reason
- Query the 'checks' API for check runs (which are not listed by the statuses API)

Fix auto_merge failing to understand checks that aren't status checks

---

cirq/ops/pauli_string.py

Fixes https://github.com/quantumlib/Cirq/issues/966

Change types for PauliString.get()

---

cirq/circuits/circuit.py
cirq/circuits/circuit_test.py

Fixes: https://github.com/quantumlib/Cirq/issues/1003

Remove Circuit.__deepcopy__

---

cirq/__init__.py
cirq/circuits/circuit.py
cirq/circuits/circuit_test.py
cirq/contrib/paulistring/convert_to_clifford_gates.py
cirq/contrib/paulistring/pauli_string_phasor.py
cirq/contrib/paulistring/pauli_string_phasor_test.py
cirq/decompositions.py
cirq/google/xmon_gates.py
cirq/ops/__init__.py
cirq/ops/clifford_gate.py
cirq/ops/common_gates.py
cirq/ops/common_gates_test.py
cirq/ops/controlled_gate.py
cirq/ops/controlled_gate_test.py
cirq/ops/eigen_gate.py
cirq/ops/gate_features.py
cirq/ops/gate_features_test.py
cirq/ops/gate_operation.py
cirq/ops/reversible_composite_gate.py
cirq/ops/reversible_composite_gate_test.py
cirq/protocols/inverse.py
cirq/protocols/inverse_test.py
docs/gates.md

Part of https://github.com/quantumlib/Cirq/issues/943

Remove cirq.ReversibleEffect in favor of cirq.inverse and __pow__

---

cirq/circuits/circuit_test.py
cirq/circuits/qasm_output_test.py
cirq/contrib/jobs/depolarizer_channel.py
cirq/contrib/jobs/depolarizer_channel_test.py
cirq/contrib/qcircuit/qcircuit_diagrammable.py
cirq/contrib/quirk/quirk_gate.py
cirq/google/__init__.py
cirq/google/eject_full_w.py
cirq/google/eject_full_w_test.py
cirq/google/eject_z.py
cirq/google/eject_z_test.py
cirq/google/engine/engine_test.py
cirq/google/programs.py
cirq/google/programs_test.py
cirq/google/sim/xmon_simulator.py
cirq/google/sim/xmon_simulator_test.py
cirq/google/xmon_device.py
cirq/google/xmon_device_test.py
cirq/google/xmon_gate_extensions.py
cirq/google/xmon_gates.py
cirq/google/xmon_gates_test.py
cirq/testing/circuit_compare_test.py
dev_tools/profiling/benchmark_simulators.py
docs/gates.md

Part of https://github.com/quantumlib/Cirq/issues/952

Merge cirq.google.ExpZGate into cirq.RotZGate

---

cirq/__init__.py
cirq/circuits/circuit.py
cirq/circuits/circuit_test.py
cirq/google/xmon_gates.py
cirq/google/xmon_gates_test.py
cirq/ops/clifford_gate.py
cirq/ops/clifford_gate_test.py
cirq/ops/controlled_gate.py
cirq/ops/controlled_gate_test.py
cirq/ops/eigen_gate.py
cirq/ops/eigen_gate_test.py
cirq/ops/gate_operation.py
cirq/ops/gate_operation_test.py
cirq/ops/matrix_gates.py
cirq/ops/matrix_gates_test.py
cirq/ops/three_qubit_gates.py
cirq/ops/three_qubit_gates_test.py
cirq/protocols/__init__.py
cirq/protocols/unitary.py
cirq/protocols/unitary_test.py

Add has_unitary to SupportsUnitary protocol to support cirq.has_unitary
Add _has_unitary_ to each gate / class that has _unitary_ and add tests for each of these classes.

Add _has_unitary_ magic method

---

cirq/ops/common_gates.py
cirq/testing/consistent_decomposition.py

Fixes #1159. Includes the fix for the gate and for the unit test.

Make HPowGate's _decompose_ preserve global phase

---

cirq/__init__.py
cirq/protocols/__init__.py
cirq/sim/simulator.py
cirq/sim/simulator_test.py
cirq/sim/sparse_simulator.py
cirq/sim/sparse_simulator_test.py

- Also fix SupportsChannel not being exposed at top level
Fixes https://github.com/quantumlib/Cirq/issues/1158

Fix sparse simulator not decomposing composite gates

---

cirq/ops/common_gates.py

* Reorder so that single qubit gates come first.
* Group instances at bottom of file.

Add documentation to common gates

---

cirq/testing/consistent_qasm.py

Use QASM protocol in QASM tests

---

cirq/google/__init__.py
cirq/google/programs.py
cirq/google/programs_test.py

 Add a is_native_xmon_gate function along with tests and documentation.

---

cirq/_version.py

Comes after https://github.com/quantumlib/Cirq/pull/1210

Start dev version 0.5.0.dev

---

cirq/ops/common_gates.py
cirq/ops/phased_x_gate_test.py

Add phase_exponent to XPowGate and YPowGate

---

cirq/circuits/circuit.py
cirq/circuits/circuit_test.py

Fixes: https://github.com/quantumlib/Cirq/issues/1131

Render empty moments

---

cirq/contrib/acquaintance/__init__.py
cirq/contrib/acquaintance/bipartite.py
cirq/contrib/acquaintance/bipartite_test.py
cirq/contrib/acquaintance/devices.py
cirq/contrib/acquaintance/devices_test.py
cirq/contrib/acquaintance/executor.py
cirq/contrib/acquaintance/executor_test.py
cirq/contrib/acquaintance/gates.py
cirq/contrib/acquaintance/gates_test.py
cirq/contrib/acquaintance/inspection_utils.py
cirq/contrib/acquaintance/inspection_utils_test.py
cirq/contrib/acquaintance/mutation_utils.py
cirq/contrib/acquaintance/mutation_utils_test.py
cirq/contrib/acquaintance/permutation.py
cirq/contrib/acquaintance/permutation_test.py
cirq/contrib/acquaintance/shift.py
cirq/contrib/acquaintance/shift_test.py
cirq/contrib/acquaintance/strategies/__init__.py
cirq/contrib/acquaintance/strategies/complete.py
docs/conf.py

* added BipartiteSwapNetworkGate
* added device attribute to execution strategy
* added acquaintance_size=None option to SwapNetworkGate
* made strategies submodule
* added acquaintance DAG
* made CircularShiftGate decompose into SwapPermutationGate

reorganized and augmented acquaintance module

---

dev_tools/env_tools.py

Fixes: https://github.com/quantumlib/Cirq/issues/1270
@Ashalynd  Please review.

Nonhardcode python location in dev_tools/env_tools.py

---

cirq/contrib/acquaintance/gates_test.py

Problem was that there are only 26 letters of the alphabet.

[fixes #1361] switched from NamedQubit to LineQubit

---

cirq/__init__.py
cirq/sim/__init__.py
cirq/sim/density_matrix.py
cirq/sim/density_matrix_test.py
cirq/sim/wave_function.py

Similar to method in wave_function.y

Add method to get valid density matrix from possible inputs

---

cirq/__init__.py
cirq/circuits/qasm_output.py
cirq/google/programs.py
cirq/google/sim/xmon_simulator.py
cirq/google/xmon_device.py
cirq/ops/common_gates.py
cirq/ops/common_gates_test.py
cirq/ops/gate_features_test.py
cirq/ops/gate_operation.py
cirq/ops/gate_operation_test.py
cirq/protocols/__init__.py
cirq/protocols/measurement_key.py
cirq/protocols/measurement_key_test.py
cirq/protocols/unitary.py
cirq/sim/density_matrix_simulator.py
cirq/sim/sparse_simulator.py

Also adds channel to measurement.  
See #1356 and #1357

Add measurement_key protocol.

---

cirq/circuits/circuit.py
cirq/circuits/circuit_test.py
cirq/ops/gate_features.py
cirq/ops/gate_features_test.py
cirq/protocols/decompose_test.py
cirq/sim/sparse_simulator_test.py
examples/bernstein_vazirani.py
examples/grover.py
examples/phase_estimator.py

Make SingleQubitGate.on_each use *targets

---

cirq/linalg/decompositions_perf_test.py
cirq/linalg/decompositions_test.py
examples/examples_perf_test.py

Move benchmark tests to _perf_ files

---

cirq/ops/gate_features.py

Remove unused import

---

cirq/ops/three_qubit_gates.py

Pauli expansion for Fredkin and Toffoli gates

---

setup.py

Fixes https://github.com/quantumlib/Cirq/issues/1427

Except 3.5.0 and 3.5.1 in setup.py

---

docs/tutorial.md

Assuming that matrix is represented like in numpy, the example looks confusing. (Unless I am overlooking something.)

Should this example be corrected?

---

examples/examples_perf_test.py
examples/examples_test.py
examples/superdense_coding.py

Very simplistic Superdense Coding example that might serve as an instructive file.

Add Superdense Coding to examples.

---

cirq/testing/__init__.py
cirq/testing/random_superposition_test.py
cirq/value/linear_dict.py
setup.py

Add random_superposition to cirq.testing

---

cirq/value/linear_dict.py
cirq/value/linear_dict_test.py

Use composition instead of inheritance in LinearDict

---

cirq/protocols/apply_channel.py

Missed a comment on review of #1459

Minor fix to apply_channel

---

cirq/ion/ion_device.py
docs/snippets_test.py

Add raw strings to snippets test

---

dev_tools/auto_merge.py

- Have been watching it long enough that I expect to have seen situations where this would cause continuous havoc, but haven't seen them

Make automerge script keep going when an error is encountered

---

.travis.yml
check/format-incremental
dev_tools/conf/pip-list-dev-tools.txt
dev_tools/incremental_coverage.py

Fixes https://github.com/quantumlib/Cirq/issues/1445

Add check/format-incremental, add travis-ci formatting check

---

cirq/__init__.py
cirq/linalg/__init__.py
cirq/linalg/transformations.py
cirq/linalg/transformations_test.py
cirq/sim/density_matrix_simulator.py

Uses this in density matrix simulator.

Add method to conjugate a tensor by another tensor

---

cirq/sim/wave_function.py
cirq/sim/wave_function_test.py

- Remove redundant parens
- Inline negation into the summation (a - b instead of a + -b)
- Zero vector case

Polish dirac_notation

---

cirq/testing/equals_tester.py

The latter is deprecated, and will not work in 3.8.

Use collections.abc.Hashable instead of collections.Hashable

---

cirq/__init__.py
cirq/ops/__init__.py
cirq/ops/common_gates.py
cirq/ops/common_gates_test.py
cirq/ops/three_qubit_gates.py

Fixes: https://github.com/quantumlib/Cirq/issues/1625

Define CCNOT AND CX

---

cirq/__init__.py
cirq/linalg/__init__.py
cirq/linalg/states.py
cirq/linalg/states_test.py
cirq/sim/wave_function.py

- Creates a state vector with a single non-zero entry

Add cirq.one_hot method

---

cirq/ops/parallel_gate_operation.py
cirq/ops/parallel_gate_operation_test.py

Fix consistency of ParallelGateOperation

---

cirq/ops/pauli_string.py
cirq/sim/density_matrix_simulator_test.py
cirq/sim/sparse_simulator_test.py

Fixes https://github.com/quantumlib/Cirq/issues/1631

Implement PauliString._decompose_

---

cirq/ops/gate_features.py
cirq/ops/gate_features_test.py

on_each of SingleQubitGate takes list of Qid of arbitrary depth as input

---

cirq/google/sim/xmon_simulator.py
cirq/sim/simulator.py
cirq/sim/simulator_test.py
cirq/sim/wave_function.py

xref https://github.com/quantumlib/Cirq/pull/1678#issuecomment-500966950

Add qubit_map to SimulationTrialResult

---

cirq/testing/asynchronous.py

Remove pytest as dependency from asynchronous.py

---

cirq/contrib/qasm_import/_parser.py
cirq/contrib/qasm_import/_parser_test.py

qasm parser docstring + code simplification

---

.travis.yml

- Gives us more version coverage

Bump one of the linux pytests to 3.7

---

cirq/contrib/qasm_import/_lexer.py
cirq/contrib/qasm_import/_lexer_test.py
cirq/contrib/qasm_import/_parser.py
cirq/contrib/qasm_import/_parser_test.py

Adds measurement statements of qubits and quantum registers. 
This is the 5th PR of the piecemeal reimplementation of #1602.

[QASM import] measurement

---

README.rst

Fixes: https://github.com/quantumlib/Cirq/issues/1773

Mention gitter cirqdev in readme

---

cirq/ops/qubit_order.py
cirq/ops/qubit_order_test.py

Fix QubitOrder.explicit

---

cirq/api/google/v2/BUILD
cirq/api/google/v2/metrics.proto
cirq/api/google/v2/metrics_pb2.py
cirq/api/google/v2/program_pb2.py
cirq/api/google/v2/result_pb2.py
cirq/api/google/v2/run_context_pb2.py

Updated package for metrics.proto from v1 to v2 and re-ran proto compiler on the directory, which updated some of the generated code for other protos as well.

s/v1/v2 for metrics proto.

---

cirq/ops/display.py
cirq/ops/display_test.py

This one was a real head scratcher!

Make displays respect PauliString coefficient

---

.travis.yml

- Too flaky (and too easy to bypass) to be a blocker on submission
Fixes https://github.com/quantumlib/Cirq/issues/1813

Remove perf test continuous integration

---

cirq/__init__.py
cirq/ops/__init__.py
cirq/ops/gate_operation.py
cirq/ops/gate_operation_test.py

Implements `cirq.op_gate_isinstance`.  I thought this already existed but I couldn't find it.

Add GateOperation gate instance test

---

.travis.yml

Was supposed to be in a previous PR, but appears to have been lost in a merge conflict with the removal of the perf tests.

Add doctest to .travis.yml

---

check/all

Me bash foo is poor, so please tell me how to bash better.
Also made some choices about what is default, not sure if I got this correct.
#1760

Add check/all to run tests close to CI

---

cirq/contrib/acquaintance/permutation_test.py

Currently unable to validate a dev package build because these tests fail.

Fix pytest.raises calls in permutation_test.py

---

cirq/contrib/contrib-requirements.txt

Bump ply version

---

cirq/ops/eigen_gate.py
cirq/ops/pauli_gates.py
cirq/ops/pauli_gates_test.py
cirq/ops/pauli_string.py
cirq/ops/pauli_string_test.py

Fix type of Pauli powers

---

cirq/ops/fsim_gate.py
cirq/ops/fsim_gate_test.py

Fixes #1882.
We've decided to accept the inconsistency, so the fix merely documents what is implemented. Also adds a unit test to confirm and improves existing documentation.

Document relationship between fSim, iSWAP and CPhase

---

cirq/ops/pauli_string.py
cirq/ops/pauli_string_test.py

 Filter out Identities from PauliString constructor

---

cirq/optimizers/eject_z.py
cirq/optimizers/eject_z_test.py

Eject Zs through SWAP

---

cirq/__init__.py
cirq/linalg/__init__.py
cirq/linalg/operator_spaces.py
cirq/linalg/operator_spaces_test.py
cirq/ops/linear_combinations.py
cirq/ops/linear_combinations_test.py

Fixes #1037. This is one of the last useful bits mined from #1299.
Follow-up: use the new algorithm in other classes.

Efficient integer powers of Pauli combinations

---

cirq/__init__.py
cirq/ops/__init__.py
cirq/ops/common_channels.py
cirq/ops/common_channels_test.py
docs/api.rst

Add ResetChannel

---

cirq/ops/phased_x_gate.py
cirq/ops/phased_x_gate_test.py

For integer `phase_exponent`.
Fixes #1933.

Fix PhasedXPowGate circuit diagram

---

check/pytest
cirq/ops/phased_x_gate.py
cirq/ops/phased_x_gate_test.py

Fix error code output for check/pytest

---

.travis.yml

Fix Travis deploy condition

---

cirq/circuits/circuit_dag.py
cirq/circuits/circuit_dag_test.py

Docstring says it is, but it wasn't.

makes circuit DAG transitive closure

---

.travis.yml

Pushing to quantumlibdev so that there is no possibility of corrupting quantum lib repos.

Move over to uploading cirq-dev to quantumlibdev pypi on prod

---

cirq/ops/three_qubit_gates.py
cirq/ops/three_qubit_gates_test.py

Equality for CSwapGate

---

cirq/__init__.py
cirq/google/api/v1/programs.py
cirq/ops/common_gates.py
cirq/ops/eigen_gate.py
cirq/ops/eigen_gate_test.py
cirq/ops/pauli_gates.py
cirq/ops/pauli_interaction_gate.py
cirq/ops/three_qubit_gates.py
cirq/optimizers/eject_phased_paulis.py
cirq/study/resolver.py
cirq/testing/consistent_protocols.py
cirq/value/__init__.py
cirq/value/angle.py
cirq/value/type_alias.py

Closes #1987 
Replaced all `Union[float, sympy.Basic]` and `Union[sympy.Basic, float]` I could find.

Add TParamVal alias

---

cirq/sim/density_matrix_simulator.py
cirq/sim/density_matrix_simulator_test.py
cirq/sim/mux.py
cirq/sim/mux_test.py
cirq/sim/sparse_simulator.py
cirq/sim/sparse_simulator_test.py

My only worry is that changing seeds between calls on numpy can bork things.

Add seed to simulators

---

docs/development.md

Update development docs for check/all script

---

cirq/__init__.py
cirq/circuits/circuit.py
cirq/devices/grid_qubit.py
cirq/devices/line_qubit.py
cirq/devices/unconstrained_device.py
cirq/ops/eigen_gate.py
cirq/ops/fsim_gate.py
cirq/ops/gate_operation.py
cirq/ops/global_phase_op.py
cirq/ops/moment.py
cirq/ops/named_qubit.py
cirq/ops/pauli_string.py
cirq/ops/phased_x_gate.py
cirq/ops/raw_types.py
cirq/protocols/__init__.py
cirq/protocols/json.py

This better reflects the intent of this function.
Fixes #2040 
Fixes #2053

Rename to_json_dict to obj_to_dict_helper

---

cirq/optimizers/decompositions_test.py

Closes #2034 
Before it failed 6/10000 times, now it failed 0/200000.

Fix flaky optimizer test

---

.travis.yml

Deploy was not happening. #2067

Fix indentation in Travis yaml file

---

cirq/experiments/n_qubit_tomography.py
cirq/experiments/n_qubit_tomography_test.py
cirq/experiments/qubit_characterizations.py

N qubit tomography code written with @maffoo.  Supports arbitrary rotations before measurement.   Designed to be modular to allow for data preprocessing.

Add n qubit tomography experiment

---

cirq/linalg/predicates.py
cirq/linalg/predicates_test.py
cirq/sim/density_matrix_utils.py
cirq/sim/simulator.py
cirq/sim/sparse_simulator.py
cirq/sim/sparse_simulator_test.py
cirq/sim/wave_function.py
cirq/sim/wave_function_simulator.py
cirq/sim/wave_function_simulator_test.py
cirq/sim/wave_function_test.py

[Qudits] Support wave function/sparse simulator

---

cirq/__init__.py
cirq/ops/__init__.py
cirq/ops/common_channels.py
cirq/ops/common_channels_test.py
cirq/protocols/json_test.py
cirq/sim/density_matrix_simulator.py
cirq/sim/density_matrix_simulator_test.py
cirq/sim/density_matrix_utils.py
cirq/sim/density_matrix_utils_test.py
cirq/sim/simulator.py
cirq/sim/wave_function.py
cirq/sim/wave_function_simulator.py

[Qudits] Support density matrix simulator, ResetChannel

---

cirq/ops/controlled_gate.py
cirq/ops/controlled_gate_test.py
cirq/ops/controlled_operation.py
cirq/ops/controlled_operation_test.py
cirq/ops/matrix_gates.py
cirq/ops/matrix_gates_test.py
cirq/ops/raw_types.py

Part of #933.
Also allows controlled gates/operations on values other than |1>.

[Qudits] Support ControlledGate, ControlledOperation, SingleQubitMatrixGate

---

cirq/circuits/circuit.py
cirq/circuits/circuit_test.py

Add Circuit.with_noise

---

cirq/google/engine/engine.py
cirq/google/engine/engine_test.py

Add `sampler` method to `cirq.google.Engine`

---

cirq/contrib/paulistring/__init__.py

Added a docstring to paulistring module.

---

cirq/contrib/acquaintance/topological_sort.py
cirq/contrib/routing/device.py
cirq/contrib/routing/greedy.py
cirq/contrib/routing/router.py
cirq/contrib/routing/utils.py

Cleanup unused type imports

---

cirq/ops/pauli_string.py
cirq/sim/density_matrix_utils.py
cirq/sim/density_matrix_utils_test.py
cirq/sim/wave_function.py
cirq/testing/random_circuit.py

Add atol parameter to wavefunction and density matrix utils

---

cirq/experiments/fidelity_estimation_test.py
cirq/sim/mux_test.py
cirq/sim/simulator.py
cirq/sim/simulator_test.py
cirq/study/trial_result.py

Allow repetitions=0 in cirq.sample

---

cirq/sim/sparse_simulator_test.py
cirq/sim/wave_function.py
cirq/sim/wave_function_test.py

Fix initial state possibly being modified in simulation

---

.travis.yml

Not sure why these kept working for one day longer than the other line...
Part of #2283

Additional workaround for Windows builds failing

---

cirq/contrib/svg/__init__.py
cirq/contrib/svg/example.ipynb
cirq/contrib/svg/svg.py
cirq/contrib/svg/svg_test.py

I opened #2313 in the hopes that someone else would do it and I would reap the benefits. Unfortunately, I ended up nerd sniping myself and threw this together last night.
It's rough-and-ready but I think looks pretty serviceable in the end.

SVG Circuit Representations

---

cirq/ops/common_gates.py

fixes https://github.com/quantumlib/Cirq/pull/2205#issuecomment-539260440
I need this. Feel free to take an add the rest of the moved classes

Compatibility shim for common gate

---

cirq/ops/linear_combinations.py
cirq/ops/linear_combinations_test.py
cirq/ops/pauli_string.py
cirq/ops/pauli_string_test.py

Add check_preconditions flag to PauliSum and PauliString expectation functions

---

cirq/conftest.py

Use headless matplotlib backend in tests

---

requirements.txt

Set networkx version to 2.3

---

cirq/google/__init__.py
cirq/google/common_serializers.py
cirq/google/gate_sets.py
cirq/google/gate_sets_test.py
cirq/protocols/json_test.py

- Adds a serializable gateset with ISWAP ** 0.5 aka FSIM(pi/4,0)

Add SQRT_ISWAP_GATESET

---

dev_tools/auto_merge.py

- Specify a `per_page` argument of 100 (the maximum) (default was 30)
E.g. this made the difference in https://github.com/quantumlib/Cirq/pull/2308

Raise auto_merge script's ability to see an approving review

---

cirq/optimizers/decompositions_test.py

Use testing assert function for more readable output

---

examples/qaoa.py

Computes the objective function values using vectorized numpy operations. As written the example only uses 6 qubits and already the improvement is from ~7 seconds to ~2 seconds. This makes the code actually practical at larger qubit numbers where the speed up is astronomical.

Speed up QAOA example

---

cirq/contrib/svg/svg.py
cirq/contrib/svg/svg_test.py

- Vertical spacing
- Color qubit lines blue (note: this requires a hack / assumption)
- Add xmlns so images show up when notebooks are rendered with nbsphinx
(it is a miracle I figured out this was the problem...)

SVG circuit drawing updates

---

.travis.yml

Fixes: https://github.com/quantumlib/Cirq/issues/2446

Skip install step in misc check

---

cirq/sim/clifford/clifford_simulator.py
cirq/sim/density_matrix_simulator.py
cirq/sim/density_matrix_utils.py
cirq/sim/mux.py
cirq/sim/simulator.py
cirq/sim/sparse_simulator.py
cirq/sim/wave_function.py

- Changes `prng` to a hidden attribute `_prng` in Simulator and DensityMatrixSimulator

Use RANDOM_STATE_LIKE in simulators

---

.travis.yml

Fixes https://github.com/quantumlib/Cirq/issues/2565

Turn off flaky build-protos check

---

cirq/work/sampler.py
cirq/work/sampler_test.py

- Was causing bugs due to code not being thread safe by default
- Instead default to running synchronously on await

Don't run async methods on other threads by default

---

cirq/circuits/circuit.py
cirq/circuits/qasm_output.py
cirq/circuits/qasm_output_test.py
cirq/google/optimizers/convert_to_xmon_gates_test.py
cirq/neutral_atoms/convert_to_neutral_atom_gates_test.py
cirq/ops/fsim_gate.py
cirq/ops/phased_iswap_gate.py
cirq/ops/phased_x_gate.py
cirq/protocols/circuit_diagram_info_protocol.py
cirq/protocols/circuit_diagram_info_protocol_test.py

- Also fix the qasm UGate not having a decomposition or a correct repr

Add CircuitDiagramInfoArgs.format_real

---

cirq/ops/common_gates.py
cirq/ops/common_gates_test.py

Respect Z.controlled(a).controlled(b) === Z.controlled(b+a)

Update ZPow.controlled specialization

---

cirq/google/engine/engine.py
cirq/google/engine/engine_test.py

Lengthen randomly generated program id

---

cirq/google/gate_sets.py
cirq/google/gate_sets_test.py

- Adds WaitGate to SYC_GATESET and SQRT_ISWAP_GATESET

Add WaitGate to gate sets

---

cirq/contrib/qasm_import/_parser.py
cirq/contrib/qasm_import/_parser_test.py

Fixes: https://github.com/quantumlib/Cirq/issues/2607

Add support for u1(lambda) gate

---

cirq/contrib/routing/greedy.py
cirq/contrib/routing/greedy_test.py
cirq/contrib/routing/router_test.py

Controls how many steps to go without making any new logical gates possible. (Equivalent to #2619 when set to 1, and equivalent to prior code when set to infinity.)

adds max_num_empty_steps parameter

---

cirq/google/common_serializers.py
cirq/google/common_serializers_test.py
cirq/google/devices/known_devices_test.py

Add PhasedXZ gate to standard single qubit (de)serializers

---

cirq/google/optimizers/convert_to_sqrt_iswap.py
cirq/google/optimizers/convert_to_sqrt_iswap_test.py

- Shortens length from 13 moments to 7 moments.
- Decomposition courtesy of mpharrigan.
Fixes #2635

Better decomposition of SWAP into ISWAP ** 0.5

---

.travis.yml
cirq/google/optimizers/convert_to_sqrt_iswap.py
cirq/google/optimizers/convert_to_sqrt_iswap_test.py
cirq/ops/moment.py
cirq/ops/moment_test.py
setup.py

Update this branch with latest commits from master

V0.7.0 dev

---

.travis.yml

Fixes: https://github.com/quantumlib/Cirq/issues/2656

Update osx check from 3.6 to 3.7

---

requirements.txt

This should stop tests from failing until #2723 is fixed.

Pin pandas

---

cirq/experiments/qubit_characterizations.py

Draw ket labels for both real and imaginary parts of density matrix

---

examples/QAOA_Demo.ipynb
examples/Rabi_Demo.ipynb

Added introductory notebooks for Rabi and QAOA.

Added QAOA and Rabi Demo notebooks.

---

dev_tools/auto_merge.py

Make auto_merge script use new update-branch API call

---

docs/development.md

- Added line for installing developer tools for local development
Fixes: #2791

Updated Dev Documentation

---

cirq/circuits/circuit.py
cirq/circuits/circuit_test.py
cirq/ops/moment.py
cirq/ops/moment_test.py

Add support for indexing circuits and moments by qubits

---

cirq/google/engine/engine_processor.py
cirq/google/engine/engine_processor_test.py

- Remove error thrown
- Update tests

Implement filtering by time slot type

---

cirq/google/common_serializers.py
cirq/google/common_serializers_test.py

- Only serializes CZ gate and not any other powers of CZPowGate

Add CZ serializer

---

docs/index.rst
docs/studies/variational_algorithm.ipynb
docs/tutorial.ipynb

- Adds a new tutorial that just explains the basic features of cirq
without trying to go into variational algorithms.
- Sections are:
- Qubits
- Gates and Operations
- Circuits and Moments
- Simulation
- Unitary Matrices and Decomposition
Moves the Variational Algorithm into case studies
- Also updates it to remove Schedules and use newer methods

Add new tutorial

---

cirq/experiments/t1_decay_experiment.py
requirements.txt

Fix axis rename and unpin pandas

Fix column axis rename in pandas 1.0

---

cirq/contrib/acquaintance/bipartite.py
cirq/contrib/acquaintance/devices.py
cirq/contrib/acquaintance/gates.py
cirq/contrib/acquaintance/permutation.py
cirq/contrib/acquaintance/shift.py
cirq/contrib/acquaintance/shift_swap_network.py
cirq/contrib/routing/swap_network.py
cirq/experiments/cross_entropy_benchmarking.py
cirq/experiments/random_quantum_circuit_generation.py
cirq/experiments/single_qubit_readout_calibration.py
cirq/experiments/t1_decay_experiment.py
cirq/google/devices/known_devices.py
cirq/google/devices/xmon_device.py
cirq/google/engine/engine_job.py
cirq/google/engine/engine_processor.py
cirq/google/engine/engine_program.py
cirq/google/line/placement/sequence.py
cirq/google/ops/physical_z_tag.py
cirq/neutral_atoms/neutral_atom_devices.py

Also, replace calls to `format` with format strings.

Add some missing type annotations

---

cirq/circuits/insert_strategy.py
cirq/contrib/qasm_import/_lexer.py
cirq/google/line/placement/anneal.py
cirq/study/resolver.py

Cleaning up a vestige of python 2.

Remove explicit object superclass

---

cirq/circuits/_bucket_priority_queue.py
cirq/circuits/circuit.py
cirq/circuits/circuit_dag.py
cirq/circuits/insert_strategy.py
cirq/circuits/optimization_pass.py
cirq/devices/grid_qubit.py
cirq/devices/line_qubit.py
cirq/devices/noise_model.py
cirq/devices/unconstrained_device.py
cirq/study/flatten_expressions.py
cirq/study/resolver.py
cirq/study/sweeps.py
cirq/study/sweeps_test.py
cirq/study/trial_result.py

More type annotations and format strings

---

cirq/ops/clifford_gate.py
cirq/ops/common_channels.py
cirq/ops/common_gates.py
cirq/ops/controlled_gate.py
cirq/ops/controlled_operation.py
cirq/ops/dense_pauli_string.py
cirq/ops/eigen_gate.py
cirq/ops/fourier_transform.py
cirq/ops/fsim_gate.py
cirq/ops/gate_operation.py
cirq/ops/global_phase_op.py
cirq/ops/identity.py
cirq/ops/linear_combinations.py
cirq/ops/matrix_gates.py
cirq/ops/matrix_gates_test.py
cirq/ops/measurement_gate.py
cirq/ops/moment.py
cirq/ops/named_qubit.py
cirq/ops/parallel_gate_operation.py
cirq/ops/parity_gates.py
cirq/ops/pauli_interaction_gate.py
cirq/ops/pauli_string.py
cirq/ops/pauli_string_phasor.py
cirq/ops/phased_iswap_gate.py
cirq/ops/phased_x_gate.py
cirq/ops/phased_x_z_gate.py
cirq/ops/raw_types.py
cirq/ops/swap_gates.py
cirq/ops/tags.py
cirq/ops/wait_gate.py

Add more type annotations and f-strings

---

cirq/google/devices/known_devices.py
cirq/google/devices/known_devices_test.py
cirq/google/devices/serializable_device_test.py

Fixes #791 
Numbers thanks to @JulianSKelly see #791.

Update xmon gate times

---

cirq/_version.py

In preparation of 0.8.0 release.

Bump version of master to 0.9.0.dev

---

cirq/aqt/aqt_device.py
cirq/aqt/aqt_sampler.py
cirq/contrib/paulistring/clifford_optimize.py
cirq/contrib/quantum_volume/quantum_volume.py
cirq/devices/noise_model.py
cirq/google/devices/known_devices.py
cirq/google/devices/serializable_device.py
cirq/google/engine/calibration.py
cirq/google/line/placement/anneal.py
cirq/google/optimizers/convert_to_sqrt_iswap.py
cirq/ops/moment.py
cirq/protocols/json_serialization.py
cirq/protocols/json_serialization_test.py
cirq/sim/density_matrix_simulator.py
cirq/sim/sparse_simulator.py
cirq/vis/heatmap_test.py
dev_tools/incremental_coverage.py
examples/direct_fidelity_estimation.py
examples/hhl.py

This includes making all TODOs refer to github issues.  I've also audited all of these github issues to make sure they include enough information about the issues.

Cleanup TODOs and corresponding Github issues

---

examples/examples_test.py
examples/quantum_teleportation.py

This should fix the flakey tests in #2064

Pipe seed into quantum teleportation example

---

requirements.txt

Update protobuf version

---

cirq/_compat.py

Set __dict__ when wrapping module

---

cirq/_compat.py
cirq/_compat_test.py

Also makes sure module doc is preserved.

Add tests for module wrapping in _compat

---

CONTRIBUTING.md
docs/dev/development.md

* Also add virtualenv command to work in environment.

Update contributing markdown links

---

docs/circuits.ipynb

DropNegligible was described but missing.
✅ I signed a new CLA.

Fixes obvious typo

---

cirq/__init__.py
cirq/ops/tags.py
cirq/ops/tags_test.py
cirq/protocols/json_serialization.py
cirq/protocols/json_test_data/VirtualTag.json
cirq/protocols/json_test_data/VirtualTag.repr
docs/api.rst

Fixes #3006 and repr and adds serialization.

Fix VirtualTag

---

cirq/google/engine/engine_job.py
cirq/google/engine/engine_processor.py
cirq/google/engine/engine_program.py

A bit more compact than creating a message and calling `ParseFromString` in a separate statement.

Use FromString classmethod for protos

---

docs/simulation.ipynb

This copies changes from #2811 into the Jupyter notebook.

Preserve external simulator recommendations.

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Version per recommendation of Google's open source team.

Add a code of conduct

---

cirq/ion/convert_to_ion_gates_test.py
cirq/ops/common_gates.py
cirq/ops/common_gates_test.py
cirq/ops/phased_x_gate.py
cirq/ops/phased_x_gate_test.py
cirq/ops/random_gate_channel.py
cirq/optimizers/decompositions_test.py
cirq/protocols/mixture_protocol_test.py
docs/api.rst

- Also fix ZPowGate and PhasedXPowGate not supporting approximate equality
- Also fix some tests using deprecated methods

Fix some test incompatibilities with latest numpy

---

cirq/devices/grid_qubit.py
cirq/devices/grid_qubit_test.py

Support adding numpy arrays to GridQubits

---

cirq/google/arg_func_langs_test.py
requirements.txt

Bump protobuf requirement to 3.12.x

---

docs/google/best_practices.md
docs/google/engine.md

- Add documentation under Google docs for
batching circuits together using engine.run_batch()

Add docs for circuit batching

---

cirq/sim/clifford/clifford_simulator.py
cirq/sim/clifford/clifford_simulator_test.py

fix bug in deprecated collapse_wavefunction

---

cirq/sim/clifford/clifford_simulator.py

Skip unitary in Clifford check

---

docs/examples.md

Made correction in the file name of variational algorithms for fixing the broken link

Fixed Issue #3178

---

cirq/study/resolver.py
cirq/study/resolver_test.py

- sympy is soooooooooooo slow
- Change parameter resolver to handle basic sympy cases
- Speeds parameter resolution up by ~10x in common cases.
Fixes #1899

Rewrite sympy in 20 lines

---

dev_tools/auto_merge.py

Mypy asks for a hint:
```
$ ./check/all
Running misc
No issues.
Running pylint
Running mypy
dev_tools/auto_merge.py:154: error: Need type annotation for 'results'
Running incremental format                                             
```

Give mypy a hint

---

cirq/__init__.py
cirq/protocols/__init__.py
cirq/protocols/json_serialization_test.py
cirq/protocols/pauli_expansion_protocol.py
rtd_docs/api.rst

Add SupportsPauliExpansion

---

cirq/google/engine/engine.py
cirq/google/engine/engine_client.py
cirq/google/engine/engine_client_test.py
cirq/google/engine/engine_test.py
docs/tutorials/google/start.ipynb

Exposes the listing of quantum programs on the Engine API.
One half of #3302.

List programs

---

cirq/__init__.py
cirq/protocols/json_serialization_test.py
cirq/study/resolver.py
cirq/study/sweepable.py
cirq/study/sweeps.py
cirq/value/__init__.py
cirq/value/type_alias.py
rtd_docs/api.rst

This is part of the suggestion in https://github.com/quantumlib/Cirq/pull/3256#pullrequestreview-474013593.

Improve parameter-related types and documentation

---

cirq/__init__.py
cirq/ops/__init__.py
cirq/ops/common_gates.py
cirq/ops/common_gates_test.py
rtd_docs/api.rst

Implement cphase

---

cirq/__init__.py
cirq/protocols/json_serialization_test.py
cirq/sim/__init__.py
cirq/sim/clifford/__init__.py
cirq/sim/clifford/act_on_stabilizer_ch_form_args.py
cirq/sim/clifford/act_on_stabilizer_ch_form_args_test.py
rtd_docs/api.rst

Split out from #3203
#2948 #2423

Add ActOnStabilizerCHFormArgs

---

cirq/ops/common_channels.py
cirq/ops/common_channels_test.py
cirq/protocols/json_test_data/MultiDepolarizingChannel.json
cirq/protocols/json_test_data/MultiDepolarizingChannel.repr

Add symmetric depol

---

cirq/ops/common_channels.py
cirq/ops/common_channels_test.py

Execute TODO to have the prob mass auto added

---

docs/google/engine.md

Adds documentation for listing jobs and programs.
Fixes #3302.

Docs for listing jobs and programs

---

cirq/_doc.py
dev_tools/docs/build_api_docs.py
rtd_docs/conf.py

I need a Dictionary mapping from `int -> str`. The current way `int -> NamedTuple` which doesn't work for other projects.

Add extensions to document public constants

---

cirq/optimizers/two_qubit_to_fsim.py

Un-invert B gate

---

cirq/study/resolver.py

Fixing sympy imports.
This fixes breakages on sympy 1.2.

Fixing sympy imports

---

cirq/_version.py

The release is out, we need to bump the dev version on master.

Bump master version to 0.10.0.dev

---

cirq/_compat.py

Removes an accidental print statement.

remove accidental print

---

cirq/experiments/cross_entropy_benchmarking.py
cirq/ops/common_channels.py
docs/google/devices.md

- Adjust duration of physical Z to 20ns.
- Add disclaimer and pointer to gate duration docs
- Fix other random indenting that sphinx is complaining about.
Fixes: #3354

Fix duration documentation for Physical Z

---

cirq/experiments/qubit_characterizations_test.py

Follow-up to #3414. Sorry, couldn't resist.

Verify that Cliffords fix Pauli group

---

docs/citation.md
rtd_docs/conf.py

Adding citation doc for devsite.

Adding citation doc for devsite

---

cirq/protocols/json_serialization.py
cirq/protocols/json_serialization_test.py
cirq/protocols/json_test_data/InitObsSetting.json
cirq/protocols/json_test_data/InitObsSetting.repr
cirq/protocols/json_test_data/_MeasurementSpec.json
cirq/protocols/json_test_data/_MeasurementSpec.repr
cirq/value/product_state.py
cirq/work/__init__.py
cirq/work/observable_settings.py
cirq/work/observable_settings_test.py

Observable Measurement - 1 - Settings

---

docs/_book.yaml
docs/aqt/access.md

Fix AQT access & authentication nav to be the same structure as Google's.

fix AQT access & authentication nav

---

docs/tutorials/google/start.ipynb

Small fixes to comments, spelling, etc.

Fix typos in quantum computing service start guide

---

cirq/google/api/v2/program.py
cirq/google/arg_func_langs.py
cirq/google/line/placement/line_test.py
dev_tools/incremental_coverage.py

Fixes cirq.google coverage issues that came up as I was extracting cirq.google into a separate package (#3433).

fix some cirq.google missing coverage issues

---

cirq/ops/common_gates.py
cirq/sim/clifford/stabilizer_state_ch_form.py

related `type: ignore`s can now be removed

Fix StabilizerStateChForm omega data type

---

docs/tutorials/basics.ipynb

s/comnsideration/consideration

Fix a typo in basics.ipynb

---

dev_tools/conf/pip-list-dev-tools.txt
requirements.txt

Moves freezegun dependency to dev dependencies.

moving freezegun dependency to dev dependencies

---

cirq/__init__.py
cirq/ionq/__init__.py
cirq/ionq/ionq_client.py
cirq/ionq/ionq_client_test.py
cirq/ionq/job.py
cirq/ionq/job_test.py
cirq/ionq/results.py
cirq/ionq/results_test.py
cirq/ionq/serializer.py
cirq/ionq/serializer_test.py
cirq/ionq/service.py
cirq/ionq/service_test.py

Contents
* Supports create_job and get_job
* Does some minimal serialization
#3479 has list of further features to be added.

Initial IonQ service

---

docs/_book.yaml

Adding missing ecosystem nav

---

cirq/ops/fsim_gate.py
cirq/ops/fsim_gate_test.py

Fixes an issue found by @mrwojtek in #3505.

Fix symmetry of PhasedFSimGate under qubit exchange

---

cirq/google/common_serializers.py
cirq/google/common_serializers_test.py

Follow up to comment from @dstrain in #3514: https://github.com/quantumlib/Cirq/pull/3514#issuecomment-731578973

Fix WAIT_GATE_SERIALIZER to work with multi-qubit waits

---

.github/CODEOWNERS
dev_tools/codeowners_test.py

Adds alfrisch to AQT codeowners.

Adds alfrisch to AQT codeowners

---

cirq/optimizers/decompositions_test.py
cirq/study/sweepable_test.py
cirq/value/linear_dict_test.py
cirq/value/product_state_test.py

Found one in my test and thought to check others.

Remove print debugs from tests

---

docs/_book.yaml
docs/install.md
docs/tutorials/rabi_oscillations.ipynb
docs/tutorials/variational_algorithm.ipynb

More docs nits. 
- python version in install.md
- rabi oscillation link issue
- variational algo title to match nav 
- remove reservations notebook from nav

[docs] Fixes in install.md, rabi tutorial, variational algo and reservations tutorial

---

cirq/ionq/ionq_client.py
cirq/ionq/ionq_client_test.py
cirq/ionq/service.py
cirq/ionq/service_test.py

Add list jobs to IonQ service

---

cirq/circuits/circuit.py
cirq/ops/moment.py
cirq/ops/moment_test.py

Fixes https://github.com/quantumlib/Cirq/issues/3278.

Refactor cirq.Moment to support efficiently finding operations by qubit

---

cirq/ionq/ionq_client.py
cirq/ionq/ionq_client_test.py
cirq/ionq/service.py
cirq/ionq/service_test.py

Refactors out list code, and move private methods for client lower.

Add list calibrations to IonQ service

---

cirq/ops/pauli_string.py
cirq/ops/pauli_string_test.py

- Increases consistency with cirq.PauliString

Add transform_qubits/__neg__/__pos__ to MutablePauliString

---

cirq/ops/parallel_gate_operation.py
cirq/protocols/json_serialization.py
cirq/protocols/json_serialization_test.py
cirq/protocols/json_test_data/ParallelGateOperation.json
cirq/protocols/json_test_data/ParallelGateOperation.repr

add JSON serialization to ParallelGateOperation

---

cirq/ionq/__init__.py
cirq/ionq/sampler.py
cirq/ionq/sampler_test.py
cirq/ionq/service.py
cirq/ionq/service_test.py

Add sampler to IonQ Service

---

cirq/circuits/circuit_operation.py
cirq/circuits/circuit_operation_test.py

Validate that CircuitOperation is provided a FrozenCircuit

---

cirq/value/product_state.py
cirq/value/product_state_test.py

Fixes: https://github.com/quantumlib/Cirq/issues/3691

Copy instead of assign input state for ProductState multiplication

---

cirq/ops/common_channels.py
cirq/ops/identity.py
cirq/ops/raw_types.py

Remove unused imports

---

cirq/study/result.py

- This is really really expensive compared to looking up the value more directly like this

Fix Result constructing a pandas dataframe to compute repetitions

---

cirq/circuits/circuit.py
cirq/circuits/frozen_circuit_test.py

circuit = circuit.freeze()

---

cirq/_version.py
dev_tools/notebooks/isolated_notebook_test.py
docs/qcvv/isolated_xeb.ipynb
docs/qcvv/parallel_xeb.ipynb
docs/qcvv/xeb_coherent_noise.ipynb
docs/qcvv/xeb_theory.ipynb
docs/tutorials/google/floquet.ipynb
docs/tutorials/ionq/getting_started.ipynb

- Modifies notebooks depending on unreleased features to install released version of cirq.
- Bumps up the devel version to 0.11.0

Version bump 0.11.0

---

dev_tools/codeowners_test.py

Update codeowners test following #3877

Update codeowners test following #3877

---

cirq/circuits/circuit.py
cirq/circuits/circuit_operation_test.py
cirq/circuits/circuit_test.py

Propagate global phase in diagram from sub circuits

---

requirements.txt

Cirq is broken for pandas version < 1.1.4

Pin pandas version to >= 1.1.4

---

cirq/ops/wait_gate.py

Fix docstring for wait helper function

---

docs/tutorials/educators/intro.ipynb

Fix Rounding error while printing solution of "Exercise: Custom Controlled Rx gate" in docs/tutorials/educators/intro.ipynb

---

cirq-core/cirq/ops/phased_x_z_gate.py
cirq-core/cirq/ops/three_qubit_gates.py
docs/gates.ipynb

Some documentation format cleanup led to me seeing an extra $ which led to me adding some documentation for some three qubit gates which led to me adding a few more gates for the gates page.

Add and cleanup some gate docs

---

cirq-core/cirq/contrib/quimb/mps_simulator_test.py

This was create 288 circuits and running 4 simulations per circuit.  The test took >9 seconds.  I've replaced this with random circuits and reduced the number to of circuits to 5 to get this to around 2 seconds.
I don't think this test was testing anything special about the two qubit circuit, but if so then this won't be a good fix so you should yell.

Speed up MPS simulator test

---

cirq-google/cirq_google/arg_func_langs_test.py
cirq-google/cirq_google/engine/engine_program_test.py
cirq-google/cirq_google/op_serializer_test.py

A few more numpy warning squashes

---

docs/qcvv/isolated_xeb.ipynb

Adds a missing networkx import in a notebook.

import networkx

---

docs/tutorials/google/floquet.ipynb

Wouldn't this work just as well?
@mrwojtek @rmlarose

floquet.ipynb - idiomatic numpy indexing

---

cirq-aqt/README.rst

fix AQT link + logo

---

cirq-core/cirq/circuits/circuit.py
cirq-core/cirq/circuits/circuit_test.py
cirq-core/cirq/ops/clifford_gate.py
cirq-core/cirq/ops/moment.py
cirq-core/cirq/ops/pauli_string.py
cirq-core/cirq/optimizers/merge_interactions.py
cirq-core/cirq/protocols/circuit_diagram_info_protocol.py
cirq-core/cirq/testing/equals_tester.py
cirq-google/cirq_google/devices/serializable_device.py
cirq-google/cirq_google/engine/engine.py
cirq-google/cirq_google/engine/engine_client.py
cirq-google/cirq_google/engine/engine_job.py
cirq-google/cirq_google/engine/engine_processor.py
cirq-google/cirq_google/engine/engine_program.py

Refactor private static methods to module functions. 
Related to #3324.

Refactor private static methods to module functions.

---

cirq-aqt/cirq_aqt/_version.py
cirq-core/cirq/_version.py
cirq-google/cirq_google/_version.py
cirq-ionq/cirq_ionq/_version.py
cirq-pasqal/cirq_pasqal/_version.py
cirq-rigetti/cirq_rigetti/_version.py
cirq-web/cirq_web/_version.py

0.12.0 is released. Bumping dev version to 0.13.0.

Bump dev version to v0.13.0.dev.

---

dev_tools/packaging/verify-published-package.sh
release.md

Script changes and general tidying from our 0.12.0 release @balopat .

Updates release.md and verification scripts.

---

dev_tools/pr_monitor.py

Fix XL size labeling everywhere.

Fix XL size labeling everywhere.

---

cirq-web/bloch_sphere_example.ipynb
cirq-web/circuit_example.ipynb
dev_tools/notebooks/isolated_notebook_test.py
docs/noise.ipynb
docs/operators_and_observables.ipynb
docs/protocols.ipynb
docs/tutorials/rigetti/getting_started.ipynb

Post v0.12 notebook cleanup: pre-release notebooks -> stable.

pre-release notebooks -> stable

---

cirq-core/cirq/ops/fsim_gate.py

Fix docstring for fsim gate

---

cirq-core/cirq/sim/act_on_density_matrix_args.py
cirq-core/cirq/sim/act_on_state_vector_args.py
cirq-core/cirq/sim/clifford/act_on_clifford_tableau_args.py
cirq-core/cirq/sim/clifford/act_on_stabilizer_ch_form_args.py

This seems to be broken at head.

Fix lint bugs with unused imports

---

cirq-core/cirq/contrib/acquaintance/executor.py
cirq-core/cirq/contrib/acquaintance/shift.py
cirq-core/cirq/contrib/acquaintance/strategies/complete.py
cirq-core/cirq/contrib/qcircuit/qcircuit_pdf.py
cirq-core/cirq/contrib/quimb/mps_simulator.py
cirq-core/cirq/contrib/routing/router.py
cirq-core/cirq/ion/ion_gates.py
cirq-core/cirq/ops/matrix_gates.py
cirq-core/cirq/ops/permutation_gate.py
cirq-core/cirq/ops/qubit_order.py
cirq-core/cirq/ops/wait_gate.py
cirq-core/cirq/optimizers/three_qubit_decomposition.py
cirq-core/cirq/optimizers/two_qubit_to_fsim.py
cirq-core/cirq/study/resolver_test.py
cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py
cirq-google/cirq_google/serialization/circuit_serializer.py
cirq-google/cirq_google/serialization/serializable_gate_set.py
cirq-google/cirq_google/serialization/serializable_gate_set_test.py
cirq-web/cirq_web/bloch_sphere/bloch_sphere.py
dev_tools/incremental_coverage.py
examples/hhl.py
examples/quantum_fourier_transform.py

Continuing the battle versus #3388

More lint documentation fixes.

---

cirq-core/cirq/contrib/routing/utils.py
cirq-core/cirq/experiments/t2_decay_experiment.py
cirq-core/cirq/ion/ion_decomposition.py
cirq-core/cirq/study/sweepable.py
cirq-core/cirq/testing/logs.py
cirq-core/cirq/value/angle.py
cirq-core/cirq/work/observable_measurement_data.py
cirq-google/cirq_google/api/v2/sweeps.py
cirq-pasqal/cirq_pasqal/pasqal_sampler_test.py
examples/bell_inequality.py

Even more documentation lint

---

cirq-aqt/cirq_aqt/aqt_sampler.py
cirq-core/cirq/contrib/acquaintance/permutation.py
cirq-core/cirq/contrib/paulistring/separate.py
cirq-core/cirq/interop/quirk/cells/testing.py
cirq-core/cirq/ion/convert_to_ion_gates.py
cirq-core/cirq/ops/moment.py
cirq-core/cirq/sim/sparse_simulator_test.py
cirq-core/cirq/testing/equivalent_repr_eval.py
cirq-google/cirq_google/optimizers/convert_to_sqrt_iswap.py
cirq-google/cirq_google/serialization/op_deserializer.py
cirq-pasqal/cirq_pasqal/pasqal_noise_model.py
cirq-web/cirq_web/circuits/circuit.py

What do you do every night?  Fix more documentation lint errors pinky.

More documentation fixes

---

docs/dev/development.md

Small clarification in development.md

---

cirq-core/cirq/ops/pauli_string_test.py

More tests that were failing due to precision.  See #4379

Fix test that are failing on aarch64-linux due to precision

---

cirq-core/cirq/contrib/quimb/state_vector.py
cirq-core/cirq/linalg/decompositions.py
cirq-core/cirq/ops/common_channels.py
cirq-core/cirq/ops/identity.py
cirq-core/cirq/ops/linear_combinations.py
cirq-core/cirq/ops/pauli_string.py
cirq-core/cirq/protocols/apply_unitary_protocol.py
cirq-core/cirq/sim/act_on_args_container.py
cirq-core/cirq/vis/heatmap.py
cirq-google/cirq_google/optimizers/optimize_for_sycamore.py
cirq-rigetti/cirq_rigetti/aspen_device.py

Removes more todos from codebase.

Documentation fixes continue

---

check/mypy

Broken here: https://github.com/quantumlib/Cirq/commit/fd257e6c228a0b4c8839ad6ac3d30467476f195e#diff-8cceb31ef3d58deea4a1c9df3e3177ce3aa6a18be536905e60d4b14e230e3150
cc #3767 @dabacon

Fix check/mypy-next

---

cirq-core/cirq/circuits/qasm_output_test.py
cirq-core/cirq/contrib/qasm_import/_parser.py
cirq-core/cirq/ops/common_gates.py

Add sxdg, now that it is supported by qiskit

---

cirq-web/cirq_ts/package-lock.json

Upgrade Ansi-Regex to 5.0.1

---

cirq-web/cirq_ts/package-lock.json

Another dependabot warning fix.

Upgrade glob-parent to 5.1.2

---

cirq-core/cirq/experiments/t2_decay_experiment.py
cirq-core/requirements.txt

Experiment with latest CI break.

Fix backwards incompatible pandas usage.

---

cirq-core/cirq/ion/ion_device.py
cirq-core/cirq/ion/ion_device_test.py
cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
cirq-core/cirq/neutral_atoms/neutral_atom_devices_test.py

Deprecate {ion,neutral_atom}.decompose_operation.

---

dev_tools/requirements/deps/pytest.txt

Remove codeowners windows.

---

cirq-core/cirq/testing/deprecation.py
cirq-core/cirq/testing/logs.py
cirq-core/cirq/testing/logs_test.py

Use contextlib.contextmanager for assert_logs and assert_deprecated

---

cirq-core/cirq/transformers/transformer_primitives.py
cirq-core/cirq/transformers/transformer_primitives_test.py

- As requested in #4923
- Should also be useful to simplify #4933, cc @daxfohl

Add `deep=True` flag to recursively apply transformer primitives to subcircuits.

---

cirq-core/cirq/study/result.py

Move default implementation of Result.data into base class

---

dev_tools/profiling/benchmark_serializers.py
dev_tools/profiling/benchmark_simulators.py
examples/bb84.py

Recent run of `./check/increment-format --all`

Minor formatting fixes

---

cirq-core/cirq/json_resolver_cache.py
cirq-core/cirq/ops/permutation_gate.py
cirq-core/cirq/protocols/json_test_data/QubitPermutationGate.json
cirq-core/cirq/protocols/json_test_data/QubitPermutationGate.repr
cirq-core/cirq/protocols/json_test_data/spec.py

Serialize QubitPermutationGate.

---

cirq-google/cirq_google/workflow/quantum_executable.py
cirq-google/cirq_google/workflow/quantum_executable_test.py

Add to_dict() to KeyValueExecutableSpec

---

docs/install.md

* Corrected virtual environment link.
* Replaced Foxtail with Sycamore.

Cleaning up cirq/install docs

---

docs/tutorials/educators/neutral_atom.ipynb

Updates neutral atom tutorial to remove uses of deprecated device behavior.

Neutral atom update

---

cirq-google/cirq_google/calibration/workflow.py
cirq-google/cirq_google/calibration/workflow_test.py
cirq-google/cirq_google/engine/abstract_engine.py
cirq-google/cirq_google/engine/abstract_local_engine.py
cirq-google/cirq_google/engine/abstract_processor.py
cirq-google/cirq_google/engine/engine.py
cirq-google/cirq_google/engine/engine_processor.py
cirq-google/cirq_google/engine/engine_processor_test.py
cirq-google/cirq_google/engine/engine_sampler.py
cirq-google/cirq_google/engine/engine_sampler_test.py
cirq-google/cirq_google/engine/simulated_local_processor.py
cirq-google/cirq_google/engine/util.py

Deprecate `gate_set` parameter on engine classes.

---

cirq-core/cirq/ops/arithmetic_operation.py

Unquote example code in ArithmeticOperation

---

.github/workflows/ci.yml

Enable CI checks on master push event.

---

README.rst

Update readme file to use new build badge.

---

cirq-core/cirq/ops/gateset.py
cirq-core/cirq/ops/gateset_test.py

Gateset: fix invalid repr when gateset is empty

---

cirq-ionq/cirq_ionq/ionq_client.py
cirq-ionq/cirq_ionq/ionq_native_gates.py
cirq-ionq/cirq_ionq/ionq_native_gates_test.py

Also snuck in a 'log post body on error' change

Fix (and test) Diagramming IonQ native circuits

---

docs/aqt/access.md

- Change one link that doesn't work.
- Change to 80 character lines for my own sanity
- Add some commas and a few minor grammatical changes.

Minor aqt doc fixes

---

cirq-core/cirq/circuits/circuit_test.py
cirq-core/cirq/devices/device.py
cirq-core/cirq/ion/ion_device_test.py
cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
cirq-core/cirq/neutral_atoms/neutral_atom_devices_test.py
cirq-google/cirq_google/devices/xmon_device.py
cirq-google/cirq_google/devices/xmon_device_test.py
cirq-pasqal/cirq_pasqal/pasqal_device.py
cirq-pasqal/cirq_pasqal/pasqal_device_test.py

Yet more v0.15 device deprecation reomvals.

Remove can_add_operation_into_moment deprecation.

---

release.md

Update release instructions to include Zenodo citation update

---

docs/circuits.ipynb

A whole bunch of nits, some wording and context changes. 
Most code changes were due to running the black code formatter.

Phrasing pass for Circuits

---

docs/google/specification.md

Fix minor grammar issue on specification page.

---

docs/_template.ipynb
docs/dev/notebooks.md

- Also minor fix to the notebook template.
Fixes: #3803

Add clarification to notebook external deps in docs

---

cirq-core/cirq/ops/wait_gate.py
cirq-core/cirq/ops/wait_gate_test.py

Fix WaitGate parameter resolution with multiple qubits

---

docs/dev/rfc_process.md

- Product suggested a slight change in phrasing
for this page.  This only changes a few sentences in
the RFC page about new vendor integrations.

Phrasing updates to new vendor doc

---

dev_tools/bash_scripts_test.py

pytest TempdirFactory was moved, adjust type specification accordingly.

Fix mypy --next complaint on pytest.TempdirFactory

---

cirq-core/cirq/ops/common_gates.py

Use LaTeX for r(x|y|z)

---

cirq-core/cirq/ops/measure_util.py

String or MeasurementKey in measure

---

cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim.py
cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim_test.py

Make transformers use higher precision

---

docs/gatezoo.ipynb

Had to wait for #5613 to be done before adding to zoo (chicken, meet egg.  Egg, chicken)

Add ISWAP_INV to zoo

---

docs/start/basics.ipynb

Fix incomplete sentences

---

cirq-core/cirq/sim/density_matrix_simulation_state.py
cirq-core/cirq/sim/density_matrix_simulator_test.py

**Breaking Change**
Fixes #5778

Remove unused qid_shape param from DMSimState.init

---

docs/hardware/pasqal/getting_started.ipynb

- Tutorial was using PasqalConverter which was removed.
- Also added a section on how to insert so each operation
is in its own moment.

Update pasqal getting started tutorial to 1.0

---

.github/workflows/ci.yml
README.rst
docs/start/install.md
docs/start/intro.ipynb
release.md

Remove alpha notice.

---

cirq-core/cirq/circuits/circuit_operation.py
cirq-core/cirq/ops/dense_pauli_string.py
cirq-core/cirq/ops/pauli_string.py
cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim.py

Fixes https://github.com/quantumlib/Cirq/issues/5835

Fix mypy type check errors due to sympy update

---

setup.py

Fixes: https://github.com/quantumlib/Cirq/issues/5880

Generalize filtration of dev requirements that can't be uploaded to pypi

---

benchmarks/randomized_benchmarking.py

Follow up on https://github.com/quantumlib/Cirq/pull/5866

Address nits in Single Qubit Randomized Benchmarking benchmarks:

---

cirq-core/cirq/transformers/synchronize_terminal_measurements.py
cirq-core/cirq/transformers/synchronize_terminal_measurements_test.py

Fixes https://github.com/quantumlib/Cirq/issues/5934

Fix bug in synchronize_terminal_measurements transformer

---

cirq-aqt/cirq_aqt/_version.py
cirq-aqt/cirq_aqt/_version_test.py
cirq-core/cirq/_version.py
cirq-core/cirq/_version_test.py
cirq-google/cirq_google/_version.py
cirq-google/cirq_google/_version_test.py
cirq-ionq/cirq_ionq/_version.py
cirq-ionq/cirq_ionq/_version_test.py
cirq-pasqal/cirq_pasqal/_version.py
cirq-pasqal/cirq_pasqal/_version_test.py
cirq-rigetti/cirq_rigetti/_version.py
cirq-rigetti/cirq_rigetti/_version_test.py
cirq-web/cirq_web/_version.py
cirq-web/cirq_web/_version_test.py

Bump cirq version to 1.2.0

---

cirq-core/cirq/ops/matrix_gates.py
cirq-core/cirq/ops/matrix_gates_test.py

MatrixGate names don't survive serialization

---

.github/workflows/ci.yml

Pin python version on MacOS to 3.7.16 and see if that fixes the _bz2 issue.  Fingers crossed!

Try to fix _bz2 issue.

---

cirq-google/cirq_google/engine/engine_client.py
cirq-google/cirq_google/engine/engine_client_test.py

They are unused on server side.
@wcourtney

Remove overwrite_existing fields in CreateQuantumProgramRequest and CreateQuantumJobRequest

---

cirq-ionq/cirq_ionq/ionq_native_gates.py

Fix LaTeX formatting for arbitrary-angle MS gate, which affects the documentation.

Fix LaTeX formatting for arbitrary-angle MS gate

---

examples/advanced/quantum_utility_sim_4a.ipynb
examples/advanced/quantum_utility_sim_4b.ipynb

This PR adds two new colabs to the `examples/advanced` directory.
These changes have already been reviewed internally.

Add example colabs

---

dev_tools/notebooks/isolated_notebook_test.py
dev_tools/notebooks/notebook_test.py

Don't run 28+ qubit simulations in CI. Should have been part of #6169.

Skip utility sims

---

cirq-core/cirq/sim/state_vector_simulator.py
cirq-core/cirq/sim/state_vector_simulator_test.py

Fixes https://quantumcomputing.stackexchange.com/a/33145/362

Handle qudits in the `__str__` of  StateVectorTrialResult

---

cirq-aqt/cirq_aqt/_version.py
cirq-aqt/cirq_aqt/_version_test.py
cirq-core/cirq/_version.py
cirq-core/cirq/_version_test.py
cirq-ft/cirq_ft/_version.py
cirq-ft/cirq_ft/_version_test.py
cirq-google/cirq_google/_version.py
cirq-google/cirq_google/_version_test.py
cirq-ionq/cirq_ionq/_version.py
cirq-ionq/cirq_ionq/_version_test.py
cirq-pasqal/cirq_pasqal/_version.py
cirq-pasqal/cirq_pasqal/_version_test.py
cirq-rigetti/cirq_rigetti/_version.py
cirq-rigetti/cirq_rigetti/_version_test.py
cirq-web/cirq_web/_version.py
cirq-web/cirq_web/_version_test.py

Part of releasing Cirq v.1.2.0

Bump cirq version to 1.3.0

---

codecov.yml

Do not fail codecov coverage checks for small changes in coverage.
Ref: https://docs.codecov.com/docs/commit-status#threshold

codecov - tolerate small decrease in coverage

---

cirq-google/cirq_google/engine/engine_test.py

This PR splits relevant tests to a unary and stream mode. This was done also in https://github.com/quantumlib/Cirq/pull/6285, but tests in `engine_test.py` were mistakenly skipped.

Create separate unary and streaming RPC tests in engine_test.py

---

cirq-google/cirq_google/engine/stream_manager.py

StreamManager: make function params explicit

---

codecov.yml

Temporarily disabled in order to modify build tools.

Restore code coverage

---

cirq-google/cirq_google/engine/engine.py

This reverts commit 39bd9269b1d8cbc26e33871da9e4418ab38b1e6d.

Revert "Change default for streaming feature flag to false (#6310)"

---

.github/workflows/release-main.yml
dev_tools/packaging/create_pypirc.sh

fixes https://github.com/quantumlib/Cirq/issues/6405

use token to upload to pypi

---

.github/workflows/ci-weekly.yml
.github/workflows/ci.yml

Ref: https://github.com/actions/upload-artifact/issues/444#issuecomment-1856410599
Finalize #6445

CI - update GitHub actions to node20

---

README.rst
docs/dev/support.md

Remove doc references to stale gitter channel

---

cirq-core/cirq/ops/qubit_manager.py
cirq-core/cirq/ops/qubit_manager_test.py

Fixes https://github.com/quantumlib/Cirq/issues/6553

Bugfix in `comparison_key` and nicer `with_dimension` of `_BaseAncillaQid`

---

cirq-core/cirq/experiments/two_qubit_xeb.py
docs/noise/qcvv/parallel_xeb.ipynb

Also changes default depths to better see the exponential tail of the fit.

Fix bug that caused XEB to fail when requesting depth > 100.

---

cirq-core/cirq/work/collector.py

np.infty no longer supported in NumPy 2.0

---

cirq-google/cirq_google/api/v2/program.py
cirq-google/cirq_google/api/v2/program_test.py

- Adds serialization for coupler Qids to change them into a qubit string and back.

Add serialization for Coupler Qids

---

cirq-core/cirq/experiments/qubit_characterizations.py
cirq-core/cirq/linalg/decompositions.py
cirq-core/cirq/vis/heatmap.py
cirq-core/cirq/vis/state_histogram.py
cirq-google/cirq_google/engine/calibration.py
docs/dev/plotting.md

Fix failure of the mypy (Type check) job in ci.yml. 
Help mypy detect when optional argument has been provided.
No change in the code function.

Fix recent type check failure in the CI

---

cirq-google/cirq_google/cloud/quantum_v1alpha1/services/quantum_engine_service/async_client.py
cirq-google/cirq_google/cloud/quantum_v1alpha1/services/quantum_engine_service/client.py
cirq-google/cirq_google/cloud/quantum_v1alpha1/services/quantum_engine_service/transports/base.py
dev_tools/requirements/deps/mypy.txt

Use the builtin importlib.metadata instead.
Also pick up pylint issues and remove unnecessary
dependency on setuptools typing stubs.

Stop using deprecated module pkg_resouces

---

cirq-core/cirq/__init__.py
cirq-core/cirq/json_resolver_cache.py
cirq-core/cirq/protocols/json_test_data/Concat.json
cirq-core/cirq/protocols/json_test_data/Concat.repr
cirq-core/cirq/study/__init__.py
cirq-core/cirq/study/sweeps.py
cirq-core/cirq/study/sweeps_test.py

A follow up PR will add Concat to cirq google sweep proto like in #6815

Add Concat to Sweeps

---

.github/dependabot.yml

Turns out the "widen" strategy is not available for pip.
Switch to "increase-if-necessary".

Use strategy "increase-if-necessary" in dependabot.yml

---

cirq-core/cirq/ops/measurement_gate.py
cirq-core/cirq/ops/measurement_gate_test.py

Fixes https://github.com/quantumlib/Cirq/issues/6093

Consider all-false invert_mask equal to no invert_mask

---

.github/workflows/ci-daily.yml
.github/workflows/ci.yml
dev_tools/notebooks/isolated_notebook_test.py

- #6577 was closed as wontfix
- #3577 was closed as wontfix

Clean up obsolete TODO comments

---

cirq-core/cirq/study/sweeps.py
docs/dev/rfc_process.md

- typo - consider
- typo - replace `if` --> `is`

Fix a couple of spelling typos before release

---

.github/workflows/ci-daily.yml
.github/workflows/ci-weekly.yml
.github/workflows/ci.yml
.github/workflows/pytest-debug.yaml
.github/workflows/release-main.yml
.github/workflows/stale.yml

Google's security practices for GitHub Actions states the following:
> When using a third-party action (one not hosted in a [Google-managed org](http://go/github/orgs)), a fixed version of the action MUST be used by [specifying a specific commit](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses), rather than a branch like "main", or a tagged release, which can be overwritten by any maintainer of the action.
This commit adds sha hash numbers to all `uses:` directives that didn't have one already. This was done by running the tool [frizbee](https://github.com/stacklok/frizbee?README) over the files.
This also fixes the following code-scanning alerts:
- …

Fix #7055: pin versions of actions in GHA workflows

---

.git-blame-ignore-revs

Ignore proto code formatting in git blame

---

.github/workflows/first-interaction.yaml

This fixes the formatting of messages. It also prevents running when the actor is Dependabot.

Tweak the first-interaction workflow

---

.git-blame-ignore-revs

Ignore isort code formatting in git blame

---

.editorconfig
cirq-web/cirq_ts/e2e/bloch_sphere/bloch_sphere_e2e_test.ts
cirq-web/cirq_ts/e2e/circuit/circuit_e2e_test.ts
cirq-web/cirq_ts/src/bloch_sphere/bloch_sphere.ts
cirq-web/cirq_ts/src/bloch_sphere/bloch_sphere_test.ts
cirq-web/cirq_ts/src/bloch_sphere/components/meridians.ts
cirq-web/cirq_ts/src/bloch_sphere/components/meridians_test.ts
cirq-web/cirq_ts/src/bloch_sphere/components/scene.ts
cirq-web/cirq_ts/src/bloch_sphere/components/sphere.ts
cirq-web/cirq_ts/src/bloch_sphere/components/sphere_test.ts
cirq-web/cirq_ts/src/bloch_sphere/components/state_vector.ts
cirq-web/cirq_ts/src/bloch_sphere/main.ts
cirq-web/cirq_ts/src/circuit/components/grid_qubit.ts
cirq-web/cirq_ts/src/circuit/components/grid_qubit_test.ts
cirq-web/cirq_ts/src/circuit/components/meshes.ts
cirq-web/cirq_ts/src/circuit/components/types.ts
cirq-web/cirq_ts/src/circuit/components/types_test.ts
cirq-web/cirq_ts/src/circuit/grid_circuit.ts
cirq-web/cirq_ts/src/circuit/grid_circuit_test.ts
cirq-web/cirq_ts/src/circuit/main.ts

- Enable `max_line_length=100` for typescript files in editorconfig
- Format typescript sources to address `check/ts-lint`
Executed  check/npm run fix

Format typescript sources at max_line_length=100

---

.github/workflows/pr-labeler.yaml

Can't seem to get permisssions working using GITHUB_TOKEN. Let's try using a PAT added as a secret to the org.

Try using a PAT

---

docs/build/ecosystem.md
docs/citation.md
docs/dev/style.md

Fix a few capitalization typos

---

docs/google/best_practices.ipynb
docs/noise/qcvv/coherent_vs_incoherent_xeb.ipynb
docs/noise/qcvv/xeb_calibration_example.ipynb

The calibration notebook was deleted in #6580.

Fix issue #7245: update docs referring to calibration_api.ipynb

---

cirq-google/cirq_google/serialization/circuit_serializer.py
cirq-google/cirq_google/serialization/circuit_serializer_test.py

- This removes the USE_CONSTANTS_FOR_MOMENTS and USE_CONSTANTS_FOR_OPERATIONS flags and makes them the default.
- This has been confirmed to be working server-side and can significantly reduce size and speed up deserialization.
- This also fixes all the tests that rely on specific proto structure, since all the operations and moments now move into the constants table.

Remove USE_CONSTANTS flags and make them the default

---

cirq-core/cirq/ops/raw_types.py

This updates the documentation on `Gate` so that it explains what to implement.  Note that docs/build/custom_gates.ipnyb already explains this.
Fixes: #5520

Update documentation about num_qubits protocol

---

cirq-google/cirq_google/__init__.py
cirq-google/cirq_google/json_resolver_cache.py
cirq-google/cirq_google/json_test_data/WILLOW.json
cirq-google/cirq_google/json_test_data/WILLOW.repr
cirq-google/cirq_google/json_test_data/WillowGate.json
cirq-google/cirq_google/json_test_data/WillowGate.repr
cirq-google/cirq_google/ops/__init__.py
cirq-google/cirq_google/ops/sycamore_gate.py
cirq-google/cirq_google/ops/willow_gate.py
cirq-google/cirq_google/ops/willow_gate_test.py

- On Willow processors, the parasitic c-phase parameter for iswap-like gates has changed from the Sycamore processors.
- Update the parameter and add a new gate for simulation purposes.

Add Willow gate

---

cirq-core/cirq/contrib/requirements.txt

- New version 0.7.3 released yesterday breaks CI

Pin Cotengra version

---

cirq-core/cirq/experiments/qubit_characterizations.py
cirq-core/cirq/experiments/z_phase_calibration.py
cirq-core/cirq/linalg/operator_spaces.py
cirq-core/cirq/ops/arithmetic_operation_test.py
cirq-core/cirq/ops/controlled_operation.py
cirq-core/cirq/ops/linear_combinations.py
cirq-core/cirq/qis/entropy.py
cirq-core/cirq/sim/clifford/stabilizer_state_ch_form.py
cirq-core/cirq/sim/simulation_utils.py
cirq-core/cirq/sim/simulation_utils_test.py
cirq-core/cirq/work/observable_measurement_data.py
cirq-google/cirq_google/api/v1/programs.py
dev_tools/requirements/mypy.env.txt

- Address type annotations errors found for numpy-2
- Let CI perform type checking with numpy-2
Fixes #7323

Adjust type annotations for numpy-2

---

.git-blame-ignore-revs

Ignore notebook formatting in git blame

---

cirq-core/cirq/transformers/dynamical_decoupling.py
cirq-core/cirq/transformers/dynamical_decoupling_test.py

Update dd at "pulled-throughs meet non-cliffords".
* Add an extra logic of merge if it is possible as being described in the comment.
* Also update the tests with an extra test case that would not generate the desired output with previous code.

Update dd at "pulled-throughs meet non-cliffords"

---

cirq-core/cirq/circuits/circuit_operation.py
cirq-core/cirq/circuits/circuit_operation_test.py

Otherwise every time `CircuitOperation.has_unitary` is called, `has_unitary_protocol` [decomposes the circuit into operations](https://github.com/quantumlib/Cirq/blob/609d93dbc51a6608a0d0c3f5d50d51325052e027/cirq-core/cirq/protocols/has_unitary_protocol.py#L98) and calls `has_unitary` on each. This is inefficient, especially if `repetitions > 1`, because `has_unitary_protocol` looks at the circuit with repetitions.
To ensure this change is correct, I wrote the tests first, and then made the change.

Cache the result of CircuitOperation.has_unitary

---

docs/build/classical_control.ipynb
docs/tutorials/google/identifying_hardware_changes.ipynb

- Typos identified by CommonTypos internal Google check.

Fix two typos
