quantumlib/Cirq

docs/tutorial.md
`common_gates.py` seems to be located in `ops` not `circuits`.
=> Fixed broken link in tutorial

cirq/circuits/circuit_test.py, cirq/circuits/qasm_output_test.py, cirq/google/sim/xmon_simulator_test.py, cirq/linalg/transformations_test.py, cirq/ops/clifford_gate_test.py, cirq/ops/common_gates_test.py, cirq/ops/gate_operation_test.py, cirq/ops/pauli_interaction_gate_test.py, cirq/ops/three_qubit_gates_test.py, cirq/testing/lin_alg_utils.py, cirq/testing/lin_alg_utils_test.py, cirq/value/angle_test.py
This should make the tests robust to numerical error.
=> Fix tests using assert_allclose without setting atol

cirq/__init__.py, cirq/circuits/circuit.py, cirq/linalg/__init__.py, cirq/linalg/transformations.py, cirq/linalg/transformations_test.py
- Moved from `cirq/circuits/circuit.py:_apply_unitary_operation` to `cirq/linalg/transformations.py:targeted_left_multiply`
- Added some tests of the method
- Fixed `reflection_matrix_pow` not being exported.
- Made `out` optional.
If anyone can think of a better name I'd be happy to hear it.
=> Expose cirq.targeted_left_multiply

cirq/google/merge_interactions.py
MergeInteractions was not always merging an entire series of operations on two qubits.  It would stop prematurely at any moment with no operation on one of the qubits.
=> Fix MergeInteractions treating empty space as a break point

CONTRIBUTING.md, docs/development.md
Added links from CONTRIBUTING to development and eliminated duplicated information.  Moved some of the redundant information to development.md.  
Let me know if you have an alternate preference for where any of the information should live.
=> Make CONTRIBUTING.md reference development.md

docs/install.md
Fix broken anchor links on [docs/install](https://cirq.readthedocs.io/en/latest/install.html).
=> Fix links in docs/install.md

cirq/__init__.py, cirq/circuits/__init__.py, cirq/circuits/circuit_dag.py, cirq/circuits/circuit_dag_test.py, continuous-integration/mypy.ini, python2.7-runtime-requirements.txt, runtime-requirements.txt
Resolves #547.
Add networkx as a dependency.
=> Add CircuitDag class

README.rst
Change the Cirq logo to an absolute URL so it isn't a broken link on PyPI.
=> Fix logo on PyPI

cirq/google/sim/mem_manager.py
- See https://github.com/numpy/numpy/issues/11636
Fixes https://github.com/quantumlib/Cirq/issues/746
=> Work around array shape being lost in SharedMemManager during np.ctypeslib.as_ctypes, np.ctypeslib.as_array round trip

cirq/decompositions_test.py
- The decomposition tolerance was looser than the asserted tolerance
=> Fix a flaky test in cirq/decompositions_test.py

cirq/ops/three_qubit_gates.py, cirq/ops/three_qubit_gates_test.py
- Improve CCZ and Toffoli's two-cost from 10 to 8
- Improve CSWAP's two-cost from 14 to 9 for outside controls and 12 for inside controls
- Check all qubit permutations when testing matrix equivalence
=> Optimize three qubit gate decompositions

cirq/google/engine/engine.py, cirq/google/engine/engine_test.py
Addressing: https://github.com/quantumlib/Cirq/issues/776. I was thinking about implementing an `__str__`, but  I don't know what that would look like. I think `__repr__` is enough for this class.
=> Implement repr() for JobConfig

cirq/circuits/circuit_dag.py, cirq/circuits/circuit_dag_test.py
Resolves #846.
networkx.is_isomorphic() seems to require that nodes have a total ordering.  Right now I have only implemented `__lt__` for Unique.
Testing the ordering operators on Unique will be much easier once #568 is finished.
=> Support CircuitDag equality

docs/gates.md, docs/tutorial.md, python2.7-requirements.txt
Addressing: https://github.com/quantumlib/Cirq/issues/823 and https://github.com/quantumlib/Cirq/issues/857. While we are at it, should we update both versions to the latest numpy (1.15)?
=> Update numpy version for python2 from 1.13 to 1.14 and remove "docs/" path for relative links.

.travis.yml, python2.7-generate.sh, setup.py
This is the version included in Ubuntu 16.04, so a fairly common thing
that we should support if possible. See #710.
=> Reduce minimum required python version to 3.5.2

cirq/ops/pauli.py, cirq/ops/pauli_test.py
Equality test was passing because it was falling back to object equals and equality groups only had one element.
=> Add eq, ne, and hash to Pauli

cirq/contrib/acquaintance/executor_test.py
Addresses #880.
The costly test was creating two 8-qubit unitaries to compare. Would using the simulator (and comparing only a sample of states) be significantly faster (i.e. fast enough)?
=> Removes expensive executor test

cirq/decompositions_test.py, docs/tutorial.md
This test is flaky in the google repository, since the matrix decomposition could be something not exactly 0.5 (such as 0.500001).  Changed the test to use an allclose method rather than test equality.
=> Fix precision in decomposition_test.py

cirq/ops/eigen_gate.py
Background:
https://docs.scipy.org/doc/numpy/release.html#numpy-1-15-0-release-notes
"Giving a generator to numpy.sum is now deprecated. This was undocumented behavior, but worked. Previously, it would calculate the sum of the generator expression. In the future, it might return a different result. Use np.sum(np.from_iter(generator)) or the built-in Python sum instead."
=> Fix deprecation warning for np.sum with generator.

cirq/circuits/circuit_dag_test.py, cirq/circuits/circuit_test.py, cirq/contrib/paulistring/clifford_optimize_test.py, cirq/contrib/paulistring/convert_gate_set_test.py, cirq/contrib/paulistring/convert_to_clifford_gates_test.py, cirq/contrib/paulistring/convert_to_pauli_string_phasors_test.py, cirq/contrib/paulistring/optimize_test.py, cirq/contrib/paulistring/pauli_string_optimize_test.py, cirq/contrib/paulistring/pauli_string_phasor_test.py, cirq/contrib/paulistring/pauli_string_raw_types_test.py, cirq/google/convert_to_xmon_gates_test.py, cirq/google/xmon_gates_test.py, cirq/ops/common_gates_test.py, cirq/ops/three_qubit_gates_test.py, cirq/testing/__init__.py, cirq/testing/circuit_compare.py, cirq/testing/circuit_compare_test.py, python2.7-generate.sh
Fixes https://github.com/quantumlib/Cirq/issues/830.
=> Add cirq.testing.assert_same_diagram.

cirq/circuits/circuit.py, cirq/circuits/circuit_test.py, cirq/google/eject_full_w_test.py
- shift was not increasing by enough when inserting an OP_TREE instead of an individual operation
- inserts at an index were being shifted by previous inserts at the same index even if they didn't create a new moment
- inserts at the same index were ending up in the reverse order of what you'd get if doing separate inserts
Fixes https://github.com/quantumlib/Cirq/issues/795
=> Fix several bugs in batch_insert

cirq/__init__.py, cirq/contrib/paulistring/pauli_string_phasor.py, cirq/decompositions.py, cirq/google/decompositions.py, cirq/ops/__init__.py, cirq/ops/reversible_composite_gate.py, cirq/protocols/__init__.py, cirq/protocols/inverse.py, cirq/protocols/inverse_test.py
- Moved cirq.inverse into cirq/protocols
- Include temporary compatibility shim for working with ReversibleEffect
- Will eventually delete ReversibleEffect in favor of this method
Part of https://github.com/quantumlib/Cirq/issues/943
=> Refactor cirq.inverse to work on values that define __pow__ or implement ReversibleEffect

cirq/__init__.py, cirq/contrib/paulistring/__init__.py, cirq/contrib/paulistring/clifford_optimize.py, cirq/contrib/paulistring/convert_gate_set.py, cirq/contrib/paulistring/convert_gate_set_test.py, cirq/contrib/paulistring/convert_to_clifford_gates.py, cirq/contrib/paulistring/convert_to_clifford_gates_test.py, cirq/contrib/paulistring/convert_to_pauli_string_phasors.py, cirq/contrib/paulistring/convert_to_pauli_string_phasors_test.py, cirq/contrib/paulistring/pauli_string_phasor_test.py, cirq/contrib/paulistring/recombine.py, cirq/contrib/paulistring/separate.py, cirq/contrib/paulistring/separate_test.py, cirq/ops/__init__.py, cirq/ops/clifford_gate.py, cirq/ops/clifford_gate_test.py, cirq/ops/pauli_interaction_gate.py, cirq/ops/pauli_string.py, cirq/ops/pauli_string_test.py
Curious. Where is `TwoQubitCliffordGate`?
=> Rename cirq.CliffordGate to cirq.SingleQubitCliffordGate (#964)

cirq/contrib/paulistring/pauli_string_phasor.py, cirq/contrib/paulistring/pauli_string_phasor_test.py, cirq/google/xmon_gates_test.py, cirq/ops/clifford_gate.py, cirq/ops/clifford_gate_test.py, cirq/ops/common_gates_test.py, cirq/ops/controlled_gate.py, cirq/ops/controlled_gate_test.py, cirq/ops/eigen_gate.py, cirq/ops/eigen_gate_test.py, cirq/ops/gate_operation.py, cirq/ops/gate_operation_test.py, cirq/ops/pauli_interaction_gate.py, cirq/ops/pauli_string.py, cirq/ops/reversible_composite_gate.py, cirq/ops/reversible_composite_gate_test.py
- Mostly left class implementations alone (except when needed to make tests pass)
Part of https://github.com/quantumlib/Cirq/issues/943
=> Begin switch from value.inverse() to value**-1 / cirq.inverse(value)

cirq/__init__.py, cirq/protocols/__init__.py, cirq/protocols/circuit_diagram_info.py, cirq/protocols/circuit_diagram_info_test.py
- This will eventually replace cirq.TextDiagrammable
Part of https://github.com/quantumlib/Cirq/issues/946
=> Define circuit_diagram_info magic method protocol

cirq/__init__.py, cirq/circuits/circuit.py, cirq/contrib/paulistring/pauli_string_phasor.py, cirq/contrib/paulistring/pauli_string_phasor_test.py, cirq/google/sim/xmon_simulator_test.py, cirq/google/xmon_gates.py, cirq/google/xmon_gates_test.py, cirq/ops/__init__.py, cirq/ops/common_gates.py, cirq/ops/controlled_gate.py, cirq/ops/controlled_gate_test.py, cirq/ops/eigen_gate.py, cirq/ops/eigen_gate_test.py, cirq/ops/gate_features.py, cirq/ops/gate_features_test.py, cirq/ops/gate_operation.py, cirq/ops/gate_operation_test.py, cirq/ops/three_qubit_gates.py, cirq/protocols/__init__.py, cirq/protocols/resolve_parameters.py, cirq/protocols/resolve_parameters_test.py, docs/api.rst
- Add cirq.is_parameterized() and cirq.resolve_parameters() in Protocols
- Add _is_parameterized_() and _resolve_parameters_() magic methods to
several gate and operation classes
- Remove ParameterizableEffect and its references and a few references
to extensions.
=> Add parameter resolution protocol

cirq/circuits/circuit_test.py, cirq/circuits/qasm_output_test.py, cirq/contrib/jobs/depolarizer_channel_test.py, cirq/contrib/quirk/quirk_gate.py, cirq/google/__init__.py, cirq/google/convert_to_xmon_gates.py, cirq/google/eject_full_w.py, cirq/google/eject_full_w_test.py, cirq/google/eject_z_test.py, cirq/google/merge_rotations.py, cirq/google/optimize_test.py, cirq/google/programs.py, cirq/google/programs_test.py, cirq/google/sim/xmon_simulator.py, cirq/google/sim/xmon_simulator_test.py, cirq/google/xmon_device.py, cirq/google/xmon_device_test.py, cirq/google/xmon_gate_extensions.py, cirq/google/xmon_gates.py, cirq/google/xmon_gates_test.py, dev_tools/profiling/benchmark_simulators.py, docs/schedules.md, docs/simulation.md
- Deleted `cirq.google.Exp11Gate`
- Using `cirq.CZ` as a substitute
- Moved all 'proto serialization' tests from `xmon_gates_test` to `cirq/google/programs_test.py`
- Refactored any code that was assuming a supported gate had to be an XmonGate
Part of https://github.com/quantumlib/Cirq/issues/952
=> Merge cirq.google.Exp11Gate into cirq.Rot11Gate

cirq/testing/equals_tester.py, cirq/testing/order_tester.py, cirq/testing/order_tester_test.py
- Reduced usage of EqualsTester to just verifying hash consistency
- Added clearer error messages when there is a failure
- Add `_EqualToEverything` reference value
=> Refactor OrderTester to detect bad NotImplemented patterns

cirq/linalg/transformations.py, cirq/ops/common_gates_test.py, cirq/protocols/apply_unitary_to_tensor.py
This is 20% faster than using einsum.
Setup:
```
import cirq
import numpy as np
c = cirq.Circuit.from_ops(cirq.X(q)**0.1 for q in cirq.LineQubit.range(24))
```
Before:
```
%time _ = c.apply_unitary_effect_to_state(dtype=np.complex64)
CPU times: user 4.05 s, sys: 611 ms, total: 4.66 s
Wall time: 4.66 s
```
After:
```
%time _ = c.apply_unitary_effect_to_state(dtype=np.complex64)
CPU times: user 3.38 s, sys: 279 ms, total: 3.66 s
Wall time: 3.66 s
```
=> Special case single-qubit unitaries in _apply_unitary_to_tensor_

cirq/ops/three_qubit_gates.py, cirq/ops/three_qubit_gates_test.py, cirq/testing/equivalent_repr_eval.py, cirq/testing/equivalent_repr_eval_test.py
- For example, we want `{!r}.on(a)` to work, but `cirq.CCZ**0.5` doesn't have that property. You need to add parens.
=> Add 'dottable' check to assert_equivalent_repr

cirq/circuits/circuit.py, cirq/circuits/circuit_test.py
- Was returning True when there were non-unitary non-measurement operations in the circuit
- Also did some reformating
- Now using `cirq.decompose` to extract unitary gates from circuits
=> Fix `cirq.Circuit._has_unitary_` false positives

cirq/sim/__init__.py, cirq/sim/simulator.py, cirq/sim/wavefunction.py, cirq/sim/wavefunction_test.py
State is a bad choice because you often want to use state as a variable name.  Only matters for code that uses this (i.e. when importing cirq.sim.state but this does happen in new code for numpy simulator using simulator interface.)
=> Rename state module to wavefunction

cirq/sim/sparse_simulator.py, cirq/sim/sparse_simulator_test.py
Doh: append(*list) works when the list is length one but not really what was wanted.
Fixes https://github.com/quantumlib/Cirq/issues/1152
=> Fix bug when multiple qubits are measured in sparse simulator

dev_tools/packaging/verify-published-package.sh
Also, actually install dev deps, too. We need the dependencies in this environment since all tests (including those for code in contrib/) are run in it.
=> Install contrib dependencies during package verification

cirq/circuits/circuit.py
Fixes: https://github.com/quantumlib/Cirq/issues/1180
=> For circuit diagram exponents equal to 0, output "^0" instead of "^(0)"

.readthedocs.yml, README.rst
Documentation build on readthedocs has been failing for awhile... maybe this badge will help.
=> Add readthedocs build badge and fix requirements file path

cirq/google/sim/xmon_simulator_test.py, cirq/google/sim/xmon_stepper_test.py, cirq/sim/simulator.py, cirq/sim/sparse_simulator.py, cirq/sim/sparse_simulator_test.py, cirq/sim/wave_function.py, cirq/sim/wave_function_test.py, cirq/study/trial_result.py, docs/conf.py
Fixes #1052 
I thought it was confusing that the same concept is being represented in different places as `Dict[str, np.ndarray]`, `Dict[str, List[np.ndarray]]`, and `Dict[str, List[List[bool]]]`. Is there a reason for this?
=> Use same type for measurement results everywhere

cirq/google/convert_to_xmon_gates.py, cirq/optimizers/merge_interactions.py, cirq/optimizers/two_qubit_decompositions.py, cirq/optimizers/two_qubit_decompositions_test.py
_cleanup_operations seems to take up 30-40% of the time in the conversion to Xmon gates.  However, this does optimizations that are all done by later phases of the Xmon optimizer set. 
This changes the default to skip this step and adds an option to allow you to optimize the operation list if you want to anyway.  This should only affect two qubit decomposition and not the full circuit optimization, but this should be verified.
=> Add option to skip cleanup in two qubit decomposition

cirq/linalg/decompositions.py, cirq/linalg/decompositions_test.py, cirq/linalg/diagonalize.py
- Disable verification tasks for decomposition and diagonalization.
- Computation for the code in issue #1071 has decreased by another
10-20% or so.
The cumulative savings of this change, in combination with the previous
fixes has decreased conversion from 2.7 seconds to 1.25 seconds and
optimization from 12.6 seconds to 5.4 seconds.
=> Disable post-computation verification tasks

cirq/sim/simulator.py
ParamResolvers are mutable so they shouldn't be used as default arguments. This was already anticipated by existing lines such as
```
param_resolvers = study.to_resolvers(params or study.ParamResolver({}))
```
which are present even though `params` already defaulted to `study.ParamResolver({})`.
Actually, shouldn't `params` be mandatory when using the `sweep` methods?
=> Make param_resolver and params argument default to None

docs/development.md
If you don't do this then `pytest .` fails due to tensorflow not being installed.
=> Add contrib requirements to dev install

cirq/circuits/circuit.py
Small refactoring for more idiomatic / efficient Python.
=> use itertools.groupby instead of looping in Python

docs/api.rst
OptimizationPass was not removed from the documentation, causing warnings when building the docs.
=> Remove documentation reference to the deleted class OptimizationPass (see #1248)

cirq/testing/consistent_protocols.py, cirq/testing/consistent_protocols_test.py, cirq/testing/equivalent_repr_eval.py
=> Remove implicit imports from tests by adding global_vals argument to test routine

cirq/ops/pauli_gates.py
The change simplifies the signature of `Pauli.__init__()` and makes initialization steps for `_PauliX` and the other private Pauli types more explicit. This is more readable since it makes it immediately clear which initialization parameters are passed to which parent class.
=> Simpify initialization of Pauli gates

cirq/ops/clifford_gate.py, cirq/ops/clifford_gate_test.py, cirq/ops/pauli_gates.py, cirq/ops/pauli_gates_test.py, cirq/ops/pauli_string_test.py
Before this change, Pauli gates used `__add__()` and `__sub__()` for cycling between the three Pauli gates. This wasn't the most intuitive or appropriate use of addition and subtraction magic methods. More importantly, for #1037 and #491 we need the methods for actual addition/subtraction of linear operators represented by the gates. This change frees the magic methods up for their new role.
=> Remove Pauli addition and subtraction

cirq/google/programs.py
Numpy 1.16.0 is now released and raises the following warning:
`cirq/google/programs_test.py::test_pack_results
/home/andbe/Cirq/cirq/google/programs.py:215: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
bits = np.hstack(np.asarray(data, dtype=bool) for _, data in measurements)`
This PR fixes that.
=> Fix FutureWarning from numpy 1.16

cirq/contrib/acquaintance/gates_test.py
randomly generated sequences were occasionally the same
=> [Fixes #1329] fixed flaky gates test

cirq/value/symbol.py, cirq/value/symbol_test.py
Rationale:
- simplification of calculations where result is known without evaluating the symbol,
- consistency with existing magic methods,
- happy mypy.
The last reason is why I do this now. In particular, when writing code like `1j**self._exponent` in various gates, mypy is unhappy about the power operation. OTOH, it does allow things like `2 * self._exponent` and even `1j**(self._exponent + 0)`.
=> pow magic methods for symbols

cirq/contrib/acquaintance/bipartite.py, cirq/ops/common_gates.py, cirq/testing/equals_tester.py, dev_tools/packaging/verify-published-package.sh, dev_tools/python2.7-requirements.txt
- Weaken scipy requirement
- Add pytest-benchmark to verify package script
- Use repr strings when describing hash equivalence failures
- Catch old usage of MeasurementGate
- Add `enum34` python 2.7 requirement (used in acquaintance code)
=> Fix issues found syncing openfermioncirq to cirq dev release

cirq/ops/common_gates.py
#1389 has been merged. That said, `cirq.Symbol` has been replaced with `sympy.Symbol` anyway and the latter doesn't suffer from the issue addressed by `+0`.
=> Clean up TODO

cirq/testing/lin_alg_utils.py, cirq/testing/lin_alg_utils_test.py, cirq/testing/random_superposition.py
Fixes https://github.com/quantumlib/Cirq/issues/1451
- Checked to make sure methods in `cirq.testing.linalg` is sampling from the Haar measure.
- Added a few more simple tests in `cirq.testing.linalg.lin_alg_utils_test.py`
=> Verified and documented methods sampling from Haar measure.

cirq/circuits/circuit.py, cirq/circuits/circuit_test.py, cirq/contrib/paulistring/clifford_optimize.py, cirq/contrib/paulistring/pauli_string_optimize.py, cirq/contrib/paulistring/pauli_string_phasor.py, cirq/contrib/paulistring/pauli_string_phasor_test.py, cirq/contrib/paulistring/pauli_string_raw_types.py, cirq/contrib/paulistring/pauli_string_raw_types_test.py, cirq/ops/display_test.py, cirq/ops/pauli_string.py, cirq/ops/pauli_string_test.py, cirq/protocols/mul.py
- Work around sympy not folding -1.0 * symbol into -symbol
- Don't quote circuit symbol equations like "-a" and "a*2". Just bracket them.
- Drop 'negate' method (redundant with unary negation)
- Leave some TODOs work in contrib
- Fix PauliStringGateOperation avoiding negating sympy expressions
- Add support for multiplying pauli strings by complex coefficients
=> Refactor PauliString.negated into complex PauliString.coefficient

cirq/value/linear_dict.py, cirq/value/linear_dict_test.py
This allows one to use keys that don't define comparison methods, e.g. `cirq.X` and `cirq.H`.
Before this PR, `__format__` (which is invoked e.g. by `_repr_pretty_`) raises this
```
TypeError: '<' not supported between instances of 'HPowGate' and '_PauliX'
```
=> Fix key sorting in LinearDict.__format__

cirq/protocols/pauli_expansion.py
This enables type checker to realize that `None` cannot be returned from `cirq.pauli_expansion` unless default is set to `None`. We do it in some of the other protocols.
=> Capture type of default in Pauli expansion protocol

cirq/linalg/operator_spaces.py, cirq/ops/common_gates.py, cirq/ops/phased_x_gate.py, cirq/ops/three_qubit_gates.py, cirq/protocols/pauli_expansion.py, cirq/protocols/pauli_expansion_test.py, cirq/testing/consistent_pauli_expansion_test.py, cirq/testing/consistent_protocols_test.py
Follow-up to #1439.
Removes cleanup logic duplicated between LinearDict and Pauli expansion protocol and allows Pauli expansions to be added together and multiplied by scalars. This in turn simplifies implementation of linear combinations of gates (coming up next).
=> Use LinearDict for Pauli expansions

cirq/testing/lin_alg_utils.py
Fixed the routine that returns a random orthogonal matrix, making sure the diagonal elements of r are positive (as shown in 'How to generate random matrices from the classical compact groups' http://arxiv.org/abs/math-ph/0609050).
=> Fixed generation of random orthogonal matrices.

cirq/ion/ion_device_test.py
Fixtures shouldn't be called directly.  Here the fixture doesn't really provide any benefit over a global method.  Renamed method to avoid it being a test.
=> Remove fixtures from ion device test

cirq/linalg/diagonalize_test.py
`cirq/linalg/diagonalize_test.py:75: RuntimeWarning: divide by zero encountered in log10
np.log10(np.abs(d))`
Even though the assert string is never used, this value is evaluated and a log10(0) is encountered.  I don't think returning log10 of the term here gives that much more info, than just returning it directly, so got rid of the log10.
=> Avoid warning about log10(0)

cirq/sim/simulator.py
This is, I think the last case of someone calling measurement gates "key" attribute.
=> Use protocol.measurement_key

cirq/protocols/control.py, cirq/protocols/control_test.py
=> Fix `cirq.control` documentation talking about `__control__` instead of `controlled_by`

cirq/ops/common_gates.py, cirq/ops/common_gates_test.py
Fixes: https://github.com/quantumlib/Cirq/issues/1507
=> Fix __str__ methods of X/Y/ZPowGate not printing Rx/Ry/Rz when global shift is -0.5 

cirq/circuits/circuit.py, cirq/google/sim/xmon_simulator.py, docs/api.rst, docs/development.md, docs/noise.md, docs/tutorial.md
This gets rid of all the warnings and
Fixes: https://github.com/quantumlib/Cirq/issues/1535
We've been through the relative vs absolute link wringer before (https://github.com/quantumlib/Cirq/issues/857), but this is a temporary solution until I figure out how to display sourcefiles in readthedocs; if it's possible.
=> Get rid of warnings when building readthedocs

cirq/circuits/text_diagram_drawer_test.py, cirq/google/engine/engine_test.py, cirq/google/engine/env_config_test.py, cirq/google/line/placement/anneal_test.py, cirq/google/line/placement/greedy_test.py, cirq/google/line/placement/line_test.py, cirq/google/line/placement/optimization_test.py, cirq/sim/density_matrix_simulator_test.py, cirq/sim/simulator_test.py, cirq/sim/sparse_simulator_test.py
The mock library was being secretly installed via one of the dev or contrib dependencies. This was causing the package verification, which limits itself to the main dependencies plus pytest, to fail. We want to depend on the builtin one.
=> Remove implicit dependence on mock library

.gitignore, cirq/schedules/schedule_test.py, cirq/type_workarounds.py, cirq/value/duration_test.py, cirq/value/timestamp_test.py
Part of: https://github.com/quantumlib/Cirq/issues/1372
I don't remove the `_cmp_` tests because i think they are nice to have documentation (they don't affect coverage). 
With regards to the circular dependency issue, after tinkering with it, it seems to me like it's not specific to Python 2. Please let me know otherwise.
=> Remove remaining references to 'python 2'

cirq/sim/density_matrix_simulator.py, cirq/sim/density_matrix_simulator_test.py, cirq/sim/wave_function.py
And make it work on operations, not just gate operations.
Fixes https://github.com/quantumlib/Cirq/issues/1630
=> Use apply_channel in DensityMatrixSimulator

cirq/protocols/approximate_equality.py, cirq/protocols/approximate_equality_test.py
We had another instance of a dtype that doesn't exist in windows numpy showing up in some tests. Modified to skip in Windows.
=> Adjust failing Windows tests to make them pass

cirq/contrib/paulistring/convert_to_pauli_string_phasors.py
Fixes #1667. The issue was that a default value of 0 for atol in PauliStringPhasor meant that some machines didn't failed to recognize gate sequence simplifications. @vtomole Feel free to verify in your Windows build PR.
=> Give PauliStringPhasor nonzero default atol (Fixes last broken Windows tests)

cirq/api/google/v2/BUILD
This is so external libraries (e.g., TFQuantum) can depend on them when depending on Cirq via a remote archive in blaze.
=> Adds default public visibility to the Cirq V2 protos.

requirements.txt
This fixes a deprecation warning in python 3.7 that shows up everytime you import cirq.
=> Bump matplotlib version

cirq/ops/pauli_string.py, cirq/ops/pauli_string_test.py
Matches the behavior of other collections: empty is false, non-empty is true.
=> Add __bool__ to cirq.PauliString

examples/qaoa.py
- removes function annotations for Python 2 compatibility
- puts factor of 2 on betas to match the paper convention
=> Minor polish to QAOA example

cirq/google/sim/xmon_simulator.py, cirq/sim/density_matrix_simulator.py, cirq/sim/density_matrix_simulator_test.py, cirq/sim/simulator.py, cirq/sim/simulator_test.py, cirq/sim/sparse_simulator.py, cirq/sim/sparse_simulator_test.py, cirq/sim/wave_function_simulator.py
The simulator state for simulators is an internal state used by the implementations for simulating state when stepping through a simulation.  It shouldn't be exposed "publically".  See #1658 for where callers where using this state instead of going to the public methods on step result or trial result.
=> Hide simulator_state

cirq/testing/lin_alg_utils.py
The re-scaling of d by (d/abs(d)) undoes the effect of this multiplication so there is no use in having it.
=> Remove redundant multiplication in random_unitary

cirq/experiments/qubit_characterizations.py, cirq/experiments/qubit_characterizations_test.py, examples/qubit_characterizations_example.py
Currently we generate the matrices for all 11520 elements of the 2 qubit Clifford group and in order to identify the inverse of a specific element we multiply it by all 11520 elements to find a candidate for the inverse. We have cirq.inverse() and should be using that instead. This shaved ~35 seconds off my pytest runs. Fixes #1476
=> Speed up randomized bench-marking

cirq/ops/phased_x_gate.py, cirq/ops/phased_x_gate_test.py, cirq/value/periodic_value.py
Fixes #1713 and moves periodic_value over to use protocol method to future proof it.
=> Fix bug in PhaseXPowGate is_parameterized protocol

cirq/api/google/v2/run_context.proto, cirq/api/google/v2/run_context_pb2.py
This aligns with the actual [Points](https://github.com/quantumlib/Cirq/blob/master/cirq/study/sweeps.py#L275) object, which can only have float values.
Before merging, we'd need to regenerate the `_pb2.py` files. @dabacon, are there instructions somewhere on how to do that?
=> Store float values in v2 Points proto

cirq/devices/grid_qubit.py, cirq/google/gate_sets_test.py, cirq/google/op_deserializer.py, cirq/google/op_deserializer_test.py, cirq/google/op_serializer.py, cirq/google/op_serializer_test.py, cirq/google/serializable_gate_set.py, cirq/google/serializable_gate_set_test.py
Related to the discussion in #1156, this would switch the v2 (de)serializers to use proto message classes, with translation to/from json-compatible dicts using the standard `google.protobuf.json_format` package if desired. This way we can center the discussion around real code. A few notes:
- The protobuf semantics around missing vs. empty fields do not always align with what we've been doing in hand-written code. For example, there's no way to serialize an empty schedule to a protobuf and then deserialize it as an empty schedule, because the protobuf will contain neither a circuit nor schedule field, so we can't tell if this was intended to be an empty schedule or if neither circuit nor schedule was set (which should be an error). I've put in code to assume an empty schedule in this case …
=> Support converting to/from proto messages directly in v2 api.

check/bazel, check/format-incremental, check/mypy, check/performance, check/pylint, check/pytest, check/pytest-and-incremental-coverage, check/pytest-changed-files, continuous-integration/check.sh, continuous-integration/simple_check.sh, dev_tools/auto_merge.sh, dev_tools/build-docs.sh, dev_tools/build-protos.sh, dev_tools/packaging/produce-package.sh
@fvkg mentioned this tool [shellcheck](https://www.shellcheck.net/). It produces a lot of useful warnings about our scripts, mostly related to undesired word splitting if strings happen to contain spaces.
=> Fix some shellcheck warnings in 'get to repo root' script code

cirq/_compat.py, cirq/circuits/circuit.py, cirq/circuits/circuit_dag_test.py, cirq/circuits/circuit_test.py, cirq/circuits/qasm_output_test.py, cirq/contrib/acquaintance/executor_test.py, cirq/contrib/paulistring/clifford_optimize_test.py, cirq/contrib/paulistring/convert_gate_set_test.py, cirq/contrib/paulistring/convert_to_clifford_gates_test.py, cirq/contrib/paulistring/convert_to_pauli_string_phasors_test.py, cirq/contrib/paulistring/optimize_test.py, cirq/contrib/paulistring/pauli_string_dag_test.py, cirq/contrib/paulistring/pauli_string_optimize_test.py, cirq/contrib/paulistring/separate_test.py, cirq/google/sim/xmon_simulator_test.py, cirq/ion/ion_decomposition_test.py, cirq/ops/clifford_gate_test.py, cirq/ops/display_test.py, cirq/ops/pauli_interaction_gate_test.py, cirq/ops/pauli_string_phasor_test.py, cirq/optimizers/convert_to_cz_and_single_gates_test.py, cirq/optimizers/merge_interactions_test.py, cirq/optimizers/two_qubit_decompositions_test.py, cirq/sim/sparse_simulator_test.py, cirq/testing/circuit_compare.py, cirq/testing/circuit_compare_test.py, cirq/testing/consistent_decomposition.py, cirq/testing/sample_circuits_test.py
This makes the circuit method consistent with the global `cirq.unitary` method name.
=> Deprecate-rename Circuit.to_unitary_matrix to Circuit.unitary

cirq/contrib/qasm_import/_parser.py, cirq/contrib/qasm_import/_parser_test.py
Adds mathematical expressions that are supported by Quantum Experience. 
Also fixes the cirq imports: instead of directly importing cirq, we import `cirq.ops` now.
This is PR number 6 for the piecemeal reimplementation of #1602.
=> [QASM import] mathematical expressions for parameters

cirq/contrib/qasm_import/_parser.py, cirq/contrib/qasm_import/_parser_test.py
Adds support for `rx`, `ry` and `rz` gates in QASM import and as such, the first gates that are defined as part of the "qelib1.inc" file. 
This is PR number 7 for the piecemeal reimplementation of #1602.
4 more PRs are planned: 
- "special" - u3(=`U`), u2, u1 and id gates
- single qubit gates - x,y,z,h,t,tdg,s,sdg
- two qubit gates - cx (=`CX`),cy,cz,ch, swap
- three qubit gates - ccx, cswap
=> [Qasm import] rotation gates

cirq/circuits/circuit.py, cirq/circuits/circuit_test.py
The method now delegates to `__iadd__` and `__init__` for validation of moments.
Fixes https://github.com/quantumlib/Cirq/issues/1698
=> Allow adding OP_TREEs into Circuit

cirq/google/api/v2/results.py, cirq/google/api/v2/results_test.py, cirq/google/engine/engine.py, cirq/sim/simulator.py, cirq/sim/simulator_test.py, cirq/study/compute_displays_result_test.py, cirq/study/trial_result.py, cirq/study/trial_result_test.py
- The goal here is to gradually refactor TrialResult into something that can also represent sweep results.
=> Add static TrialResult.from_single_parameter_set factory method

cirq/__init__.py, cirq/study/trial_result.py, cirq/study/trial_result_test.py, cirq/value/__init__.py, cirq/value/digits.py, cirq/value/digits_test.py
- Lazily compute the dataframe when it is needed
- Flatten bits into ints, instead of a series
=> Optimize TrialResult.data

.travis.yml, check/pytest, dev_tools/check_pytest_with_coverage.py
- This fixes an annoyance where error output is hidden waaaay down at the bottom of travis-ci logs
=> Add --actually-quiet parameter to check/pytest and use it in continuous integration runs

.travis.yml, check/doctest, cirq/devices/grid_qubit.py, cirq/line/line_qubit.py, cirq/value/digits.py, dev_tools/output_capture.py, dev_tools/run_doctest.py
This was a problem in https://github.com/quantumlib/Cirq/pull/1836#discussion_r305040210.
Before this PR you had to write this:
```python
>>> GridQubit(2, 3) + (3, 1)
cirq.GridQubit(5, 4)
```
Now you can only write this:
```python
>>> cirq.GridQubit(2, 3) + (3, 1)
cirq.GridQubit(5, 4)
```
./check/doctest now has useful pretty output too (with color).  The dots don't show on Travis.
```
Loading tests   ........................................................................................................................................................................................................................................................................................................................................................................................................... …
```
=> Allow cirq.* in docstring code snippets

cirq/work/sampler.py
`async` methods should be annotated with the type you get when `await`-ing the coroutine; mypy knows to wrap this with `Awaitable` when checking callsites. See https://mypy.readthedocs.io/en/stable/more_types.html#async-and-await.
=> Fix types on Sampler.run_async

cirq/circuits/qasm_output_test.py, cirq/contrib/qasm_import/_parser.py, cirq/contrib/qasm_import/_parser_test.py, cirq/contrib/qasm_import/qasm_test.py, cirq/testing/consistent_qasm.py, dev_tools/auto_merge.py
Adds support for two and three qubit gates in QASM import.
This is PR number 10 for the piecemeal reimplementation of #1602.
Next PR will add docs.
=> [QASM import] two and three qubit gates

cirq/ops/common_gates.py
Modified the `YPowGate` docstring to:
> 
> [[g·c, -g·s],
>  [g·s, g·c]]
> 
> where:
> 
> c = cos(π·t/2)
> s = sin(π·t/2)
> g = exp(i·π·t/2).
For t=1, g= i and s = 1 so this matrix evaluates to:
[[0, -i],
[i, 0]]
which is consistent with `cirq.unitary(cirq.YPowGate(exponent=1)).
=> YPowGate docstring fix

cirq/circuits/circuit.py, cirq/circuits/circuit_test.py
Prior implementation double-counted operations because it iterated over qubits rather than moments.
=> fixes bug in Circuit.findall_operations_until_blocked

docs/development.md, docs/install.md, setup.py
Fixes #843.
This allows users to easily install Cirq with the contrib dependencies:
```
$ pip install cirq[contrib]
```
To install Cirq in editable mode for development:
```
$ pip install -e .[dev,contrib]
```
=> Add pip package configurations for contrib and dev tools

cirq/contrib/paulistring/recombine.py
Before optimization: 
```bash
2019-07-16 09:16:20,584 - INFO - reading qasm file...
2019-07-16 09:16:25,140 - INFO - parsed qasm file: 13392 ops
2019-07-16 09:18:24,564 - INFO - optimized circuit: 1854 ops in 119.42398381233215 
2019-07-16 09:18:24,654 - INFO - stats: misses 74115, dupes: 6505723
```
which means that 98.87% of comparisons has been done at least twice.
Insight: we can  just sort the nodes of the frontier _once_, based on the best placement possible for a given paulistring instead of repeatedly reevaluating them. Why? 
1.) because the nodes of the frontier (rightmost nodes in the DAG) are commuting with each other, so they can be sorted independently of each other and each other's predecessors in the DAG and we can insert all the nodes in the frontier first.
2.)  sorting …
=> Optimize recombination step in paulistring optimizer

apt-system-requirements.txt
- I needed to install this to get matplotlib working
=> Restore python3-tk as an apt requirement

cirq/work/sampler.py
- Streamline type annotations to only use 'cirq.'
- Extracted run_on_thread_async
=> Add cirq.Sampler.run_sweep_async

check/all, check/format-incremental, check/mypy, check/pytest-and-incremental-coverage, check/pytest-changed-files, dev_tools/build-docs.sh, dev_tools/build-protos.sh, dev_tools/packaging/produce-package.sh, dev_tools/packaging/publish-dev-package.sh, dev_tools/packaging/verify-published-package.sh
Replace `'\e'` with `'\033'` in all uses of `echo -e`.
The `echo` builtin on Mac bash doesn't support the `'\e'` escape sequence used to set ANSI colors.  This was causing one of the dev tool tests to fail and many of the scripts to output `\e[##m` everywhere.  `'\033'` is equivalent to `'\e'` but has more support.
=> Fix dev tool terminal colors on Mac

cirq/ops/linear_combinations.py, cirq/ops/linear_combinations_test.py
This is analogous to a similar property on PauliString and other gates. It's useful on the commandline and simplifies some conditions (e.g. checking whether the PauliString is single-qubit).
=> Add qubits property

cirq/sim/density_matrix_simulator.py, cirq/sim/sparse_simulator.py, docs/api.rst
I found some old references to `SupportsApplyUnitary` after #1790.
=> Change old references to SupportsApplyUnitary

cirq/sim/density_matrix_simulator_test.py
- Numpy does not have a consistent whitespace across
versions, so this test can fail in other contexts
=> Remove whitespace in density simulator test

cirq/contrib/contrib-requirements.txt, dev_tools/conf/pip-list-dev-tools.txt, docs/development.md, docs/install.md, setup.py
Instead of using `==v.w.*` this uses `~=v.w` the compatibility operator.  Compatibility is `==v.* >=v.w`.  This is nearly the same thing with some sublties about prelease versions that shouldn't hit us.
I've tested this by pushing to test pypi and prod pypi and it works.
=> Add back in extras_require by using compatible versions

cirq/contrib/acquaintance/executor.py, cirq/ops/raw_types.py, cirq/study/sweeps.py
@abstractproperty is deprecated after python 3.3
=> Cleanup: remove instances of abstractmethod for properties

setup.py
Deploy failed.  Printing the long description out gives
```**This is a development version of Cirq and may be unstable.**
**For the latest stable release of Cirq see ** `here <https://pypi.org/project/cirq>`__.
.. image:: https://raw.githubusercontent.com/quantumlib/Cirq/master/docs/Cirq_logo_color.png
:target: https://github.com/quantumlib/cirq
:alt: Cirq
:width: 500px
```
Which I believe has a problem because of the lack of newline before the image.
=> Add spaces to dev string

dev_tools/conf/apt-list-dev-tools.txt
Fixes #1920 
Tested that removing pandoc mails buid-docs.sh fail and that installing after made it succeed.
=> Add pandoc to dev apt-list

cirq/google/engine/engine.py, cirq/google/engine/engine_sampler.py, cirq/google/engine/engine_sampler_test.py
Note that I chose not to validate that the `EngineProgram` was created from the same `Engine` as the sampler.  We could add this.
Alternatively we could add another type of `Sampler`.
=> Add EngineProgram to QuantumEngineSampler

cirq/ops/pauli_gates.py, cirq/optimizers/decompositions.py, cirq/optimizers/decompositions_test.py, cirq/optimizers/eject_phased_paulis.py, cirq/optimizers/eject_phased_paulis_test.py, cirq/value/angle.py, cirq/value/angle_test.py
For #1930.  Independent of #1963.
=> Support symbols in EjectPhasedPaulis optimizer

cirq/vis/heatmap.py, cirq/vis/heatmap_test.py
The default annotation is `format(float(value), '.2g')` where `value` is the value in the `value_map` passed to `Heatmap.__init__`. It should work if the value is always `SupportsFloat` specified by the `ValueMap` type.
To remove the annotation, the user can call `unset_annotation()` method afterwards.
```python
cirq.Heatmap(value_map).unset_annotation().plot(ax)
```
Demo:
=> Add default annotation to heatmap.

dev_tools/packaging/generate-dev-version-id.sh, dev_tools/packaging/publish-dev-package.sh, dev_tools/packaging/set-dev-version.sh
I'm keeping the set-dev-version script in the case that we can go back to using travis's deploy.
=> Update publish dev pypi script to use cirq-dev

dev_tools/packaging/publish-dev-package.sh, dev_tools/packaging/verify-published-package.sh
- publish-dev-package had a missed script rename
- verify-published-package was using cirq instead of cirq-dev
=> Fix bugs in publish-dev-package and verify-published-package

cirq/__init__.py, cirq/protocols/decompose.py, cirq/protocols/equal_up_to_global_phase.py, cirq/protocols/has_unitary.py, cirq/protocols/inverse.py, cirq/protocols/qasm.py, cirq/protocols/qid_shape_protocol.py, cirq/protocols/resolve_parameters.py
Closes #2055 
Moved lazy imports to module level.
Moved the imports of `study` and `device` so that they can be imported at module level  in `protocols`.
I also found one `import cirq` at module level which I turned into a lazy import in ` cirq/protocols/equal_up_to_global_phase.py`.
=> Remove lazy imports from protocols

cirq/protocols/apply_unitary.py, cirq/protocols/decompose.py, cirq/protocols/has_unitary.py, cirq/protocols/unitary.py
Follow-up to #2059 
By moving `_try_decompose_into_operations_and_qubits` to `decompose`, the cycling dependence in `unitary/has_unitary/apply_unitary` can be removed.
@cduck PTAL
=> Break cyclic dependence and remove remaining lazy imports from protocols

cirq/__init__.py, cirq/ops/__init__.py, cirq/ops/common_gates.py, cirq/ops/common_gates_test.py, cirq/protocols/apply_channel.py, cirq/protocols/apply_channel_test.py, cirq/protocols/json_test.py, cirq/protocols/pauli_expansion.py, cirq/protocols/pauli_expansion_test.py, cirq/testing/circuit_compare.py, cirq/testing/circuit_compare_test.py, cirq/testing/consistent_pauli_expansion.py, cirq/testing/consistent_phase_by.py, cirq/testing/consistent_phase_by_test.py, cirq/testing/consistent_qasm.py, cirq/testing/consistent_qasm_test.py
Part of #933.
Support added:
- IdentityGate and Measurement can be applied to qudits.
- Protocols apply_channel, pauli_expansion, phase_by, and qasm either support qudits or don't crash when given qudit values.
- `testing.assert_implements_consistent_protocols()` correctly tests qudit values.
=> [Qudits] Add support to IdentityGate, MeasurementGate, several protocols

cirq/sim/density_matrix_simulator.py, cirq/sim/density_matrix_simulator_test.py, cirq/sim/simulator.py, cirq/sim/simulator_test.py, cirq/study/trial_result.py, cirq/study/trial_result_test.py
Part of #933.
Where the invert mask is True, switches the measurements of |0> and |1> without modifying |2> and above.
Also fix `str(TrialResult)` for qudits.
=> [Qudits] Fix qudit result with invert mask in simulators

check/bazel, cirq/google/api/v2/results.py, cirq/google/api/v2/results_test.py, cirq/google/api/v2/sweeps.py, cirq/google/api/v2/sweeps_test.py, cirq/google/engine/calibration_test.py, cirq/google/engine/engine.py, cirq/google/engine/engine_test.py, cirq/google/op_deserializer.py, cirq/google/op_serializer.py, cirq/google/serializable_gate_set.py
- Exterminate all cirq.api.google references
- Welcome to our new cirq.google.api
=> cirq.google.api is the new cirq.api.google

cirq/google/api/v1/programs.py, cirq/google/api/v1/programs_test.py
- Currently, the json serializer for v1 protos only accepts strings.  If you pass a naked bool, the serializer crashes.  This allows it to handle both.
=> Allow bools to be parsed by the serializer

cirq/protocols/decompose.py, cirq/protocols/decompose_test.py
Part of #933.
This is a minor API change.
- `def _decompose_(self, qids):` will now work.
- `def _decompose_(self, **kwargs):` will no longer work.
- `def _decompose_(self, something_else=5, qubits=None):` will no longer work.
=> [Qudits] Allow argument of Gate._decompose_ to not just be 'qubits'

cirq/sim/sparse_simulator.py, cirq/sim/sparse_simulator_test.py
This is a somewhat temporary solution until a more general protocol is added that allows for a measurement followed by a conditional operation.
=> Add qubit reset support to the wave function simulator

cirq/sim/density_matrix_utils.py
if the input is known to be Hermitian, eigvalsh is generally higher precision (e.g. see http://www.netlib.org/lapack/lug/node89.html vs. http://www.netlib.org/lapack/lug/node91.html) and more performant:
```
>>> timeit.timeit('np.linalg.eigvalsh(b)', setup='import numpy as np; a = np.random.random((128,128)).astype(np.complex6
4); b = (a + a.T); b = b / np.trace(b)', number=1000)
6.555085600004531
>>> timeit.timeit('np.linalg.eigvals(b)', setup='import numpy as np; a = np.random.random((128,128)).astype(np.complex64
); b = (a + a.T); b = b / np.trace(b)', number=1000)
61.79538379999576
>>>
```
=> eigvals -> eigvalsh

setup.py
- Needed so that we can start pulling them for cirq-dev packages
and transition over to the new packages.
=> Add google.api protos to packages.

cirq/__init__.py, cirq/linalg/__init__.py, cirq/linalg/decompositions.py, cirq/linalg/decompositions_test.py, cirq/ops/pauli_string.py, dev_tools/incremental_coverage.py, dev_tools/run_doctest.py
This PR also:
- Marks `plt.show()` lines as not needing to be covered
- Fixes a deprecation warning w.r.t. `np.asscalar`
- Allows `plt.show()` to be called in doctested example code
- Allows `cirq.kak_decompose` to be called on objects with a `_unitary_` method, such as `cirq.Circuit`.
Plotting KAK interaction coefficients visually is something I've found really handy for understanding two qubit operation decomposition. I put together this flexible method for doing so.
Example:
```python
import cirq
import numpy as np
import matplotlib.pyplot as plt
ax = None
for y in np.linspace(0, 0.5, 10):
a, b = cirq.LineQubit.range(2)
circuits = [
cirq.Circuit.from_ops(
cirq.CZ(a, b)**0.5,
cirq.X(a)**y, cirq.X(b)**x,
cirq.CZ(a, b)**0.5,
cirq.X(a)**x, cirq.X(b)**y,
cirq.CZ(a, b) ** 0.5,
)
for x in …
```
=> Add `cirq.scatter_plot_normalized_kak_interaction_coefficients`

cirq/__init__.py, cirq/ops/__init__.py, cirq/ops/arithmetic_operation.py, cirq/ops/arithmetic_operation_test.py, cirq/protocols/apply_unitary.py, cirq/protocols/apply_unitary_test.py
This is a helper class to make it easier to implement arithmetic operations. These operations are not NISQ-y, but people have asked if cirq can do them efficiently a few times in the past. The answer was that it's *possible*, by implementing an `_apply_unitary_` operation, but it's not so convenient to write that method. Now we have a convenient way to do it.
Here is how you would implement an adder using this class:
```python
class Add(cirq.ArithmeticOperation):
def __init__(self, target_register, input_register):
self.target_register = target_register
self.input_register = input_register
def registers(self):
return self.target_register, self.input_register
def with_registers(self, *new_registers):
return Add(*new_registers)
def apply(self, target_value, input_value):
return target_value …
```
=> Add cirq.ArithmeticOperation helper class

cirq/study/__init__.py
Remove a repeated import for the `Product` class defined in `study/sweeps.py`.
=> Delete repeated `Product` import in `study/__init__.py`

cirq/__init__.py, cirq/circuits/circuit.py, cirq/experiments/qubit_characterizations.py, cirq/ops/__init__.py, cirq/ops/op_tree.py, cirq/ops/op_tree_test.py
Defining OP_TREE using a protocol lets us create a recursive type, which is not possible with type aliases alone. This means downstream operations can preserve more type information, which is good but reveals a problem with `flatten_op_tree` returning a Union type due to the `preserve_moments` option. To work around this I've split it up into two functions instead. Another possibility would be to remove the `preserve_moments` option on `flatten_op_tree` and just add a second function for the non-default case (which is a tiny minority of callsites).
=> Add OpTree protocol

cirq/experiments/fidelity_estimation.py, cirq/experiments/fidelity_estimation_test.py
A tuple doesn't behave as desired when used as an index into a numpy array.
=> Handle tuple input in cross entropy fidelity estimator

cirq/aqt/aqt_sampler.py, cirq/circuits/circuit.py, cirq/circuits/circuit_test.py, cirq/contrib/graph_device/graph_device_test.py, cirq/google/api/v2/results.py, cirq/google/serializable_gate_set.py, cirq/google/serializable_gate_set_test.py, cirq/sim/density_matrix_simulator.py, cirq/sim/mux.py, cirq/sim/simulator.py, cirq/sim/wave_function_simulator.py
- Deprecate the moments= keyword and the positional device parameter
- Add a strategy= keyword
To check for deprecated usage within the library, I ran the tests once without the `@deprecated` annotations, which would cause exceptions instead of printed warnings when it was used wrong.
Part of #1787
Will follow up with PRs switching usage of `from_ops` to `Circuit`, then deprecating `from_ops`
=>  Refactor Circuit.__init__ to accept an OP_TREE 

cirq/ops/common_gates.py, cirq/ops/common_gates_test.py
There was a special case that was applied in error to ISWAP that has now been removed. Added tests to verify that problem this fixes #2172.
=> Fix ISWAP trace_distance_bound

check/format-incremental
- This makes it clearer at a glance that something happened instead of nothing (shown in green)
=> Show yellow text when lines had to be reformatted

.travis.yml, style.md
This reorders the travis tests from longest to shortest in duration.  Because travis runs with 5 concurrent jobs that pick up test in this order putting a long test like build docs or windows later can lead to slower overall testing time.
=> Reorder travis tests

cirq/contrib/contrib-requirements.txt
`pip install tensorflow` now gives tensorflow 2.0 which will break us.
=> Fix tensorflow version since tensorflow 2.0 was just released

cirq/ops/arithmetic_operation.py
- There was a lot of "FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result."
=> Fix deprecation warning in arithmetic_operation.py

cirq/circuits/circuit.py, cirq/circuits/circuit_test.py, cirq/ops/moment.py
- Matches behavior of the method on Operation and Moment
- Includes an optional new_device parameter, since changing qubits is the sort of thing that would be associated with switching devices
- Happens to do the same thing as `with_device`, but with a different flavor. I think it's worth including this variant because of the `transform_qubits` methods on other types.
=> Add transform_qubits to Circuit

.travis.yml
I'm going to temporarily comment the line in the travis.yml file causing the problem. We can later re-enable it when whatever is causing the breakage is actually fixed. The line relates to turning off antivirus slowdown.
Part of https://github.com/quantumlib/Cirq/issues/2283
=> Workaround windows builds suddenly failing

cirq/linalg/decompositions.py
- cirq only requires matplotlib 3.0
- add_subplot() with no positional arguments was not added until 3.1
See:
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.add_subplot
https://matplotlib.org/3.0.3/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.add_subplot
=> Add default parameters for add_subplot

cirq/experiments/google_v2_supremacy_circuit.py
=> Require n_rows > 1 in generate_boixo_2018_supremacy_circuits_v2_bristlecone

cirq/_compat.py, cirq/_compat_test.py, cirq/protocols/json.py, cirq/protocols/json_test.py
- Fix json serialization tests allowing accidentally unused TEST_OBJECTS entries
- Prefix non-cirq TEST_OBJECTS entries with a tag, so they group together at the start
- Remove GivensRotation entry, because it's not a serializable object
- Fix _QubitAsQid entry not being checked
=> Add pandas.DataFrame support to proper_repr and json serialization

cirq/contrib/quirk/url_to_circuit.py, cirq/contrib/quirk/url_to_circuit_test.py
- If the user specifies a dictionary from strings to gates, wrap it in the obvious way
=> Add simplified `extra_cell_makers` argument option to `quirk_url_to_circuit`

cirq/py.typed, setup.py
Works from local testing.
Fixes #2373
=> Add py.typed for type checkers

setup.py
This allows typechecking of protos in code that depends on cirq now that we ship a `py.typed` file.
=> Include mypy stubs for protos in cirq packages.

cirq/circuits/circuit.py, cirq/contrib/acquaintance/mutation_utils.py, cirq/ops/moment.py, cirq/protocols/inverse_protocol.py
Also had to fix up a few type errors in other places resulting from this change. I find dealing with `cirq.Operation` versus `cirq.GateOperation` to be a persistent source of annoyance; is there some way we can make this simpler? For example have a `gate` field on all operations but type it as `Optional[cirq.Gate]`?
=> Add type annotations for Circuit.__iter__ and Moment.__iter__

cirq/study/resolver.py, cirq/study/resolver_test.py
For common cases (sympy.Symbols and strings), directly look up the
value in the parameter dictionary, using sympy resolution as a
fallback.
This increases performance for large param resolvers, since sympy.sub()
sorts the parameter dictionary and iterates through it, causing a
huge slowdown.
Also, this PR tries to catch various cases technically supported by
the mypy function definition (for instance, having symbols or formulas
as keys of the parameter dictionary) and handles them correctly.
This speeds a param resolver of 400 parameters from 25 seconds to 0.04
seconds.  It speeds the example in issue  #1899 from 7.11 seconds to
0.32 seconds (which includes simulation).
=> Speed up param resolution

cirq/circuits/circuit.py, cirq/contrib/tpu/circuit_to_tensorflow.py, cirq/protocols/decompose_protocol.py
Also ensure that intercepting and fallback decomposers, which are
documented as taking cirq.Operation, are in fact only called with
Operations and not other op trees.
=> Improve types in decompose protocol

cirq/ops/linear_combinations.py
Makes the signatures identical to the corresponding methods in PauliString.
=> Add atol parameter to PauliSum expectation methods

cirq/ops/controlled_gate.py, cirq/ops/controlled_operation.py, cirq/ops/controlled_operation_test.py, cirq/protocols/json.py, cirq/protocols/json_test.py
- Also override 'gate' property of ControlledOperation
- Also fix overly-specific type annotation of control_qid_shape
Fixes https://github.com/quantumlib/Cirq/issues/2422
=> Json serialization of ControlledGate and ControlledOperation

.travis.yml, dev_tools/packaging/publish-dev-package.sh, dev_tools/packaging/verify-published-package.sh, setup.py
- Refactor verify-published-package to have an --unstable flag.
- Refactor verify-published-package to require --prod/--test/--unstable be specified
- Rename various CIRQ_DEV type things to CIRQ_UNSTABLE type things
Fixes https://github.com/quantumlib/Cirq/issues/2431
=> Rename cirq-dev to cirq-unstable

cirq/contrib/quirk/cells/arithmetic_cells.py, cirq/contrib/quirk/cells/input_cells_test.py, cirq/devices/unconstrained_device.py, cirq/ops/moment.py
- Reorganize qubit check so that containment is checked on a set.
- Moment.with_operation() cheats and uses private variables so that it
changes from O(n) to O(1).
- Overload validate_moment in unconstrained device so we don't iterate
over all moments.
- Perf improvement is like 100x for example code listed in comments
below.
=> Speed up circuit creation

cirq/protocols/json.py, cirq/protocols/json_test.py
Fixes https://github.com/quantumlib/Cirq/issues/2422
Example serialize:
```python
cirq.to_json(cirq.X)
```
```
'{\n  "cirq_type": "_PauliX",\n  "exponent": 1.0,\n  "global_shift": 0.0\n}'
```
Example deserialize:
```python
cirq.read_json(json_text='{\n  "cirq_type": "_PauliX",\n  "exponent": 1.0,\n  "global_shift": 0.0\n}')
```
```
cirq.X
```
=> Generalize read/to_json to work with pathlib.Path and raw json text

requirements.txt
Python 3.7 has a built-in dataclasses module. This was causing a failure when verifying v0.6.0's package, because the dataclasses shim package was accessing private properties from typing that no longer existed in 3.7.
=> Fix dataclasses package being installed for python 3.7+

cirq/__init__.py, cirq/google/__init__.py, cirq/google/gate_sets_test.py, cirq/google/ops/__init__.py, cirq/google/ops/sycamore_gate.py, cirq/google/ops/sycamore_gate_test.py, cirq/ops/__init__.py, cirq/protocols/json.py, cirq/protocols/json_test.py
- This gate is hardware-specific, so moving it to cirq.google.
=> Move SycamoreGate to cirq.google

cirq/protocols/json.py, cirq/protocols/json_test.py
=> Implement JSON serialization for numpy dtypes

cirq/sim/wave_function.py
Gives ~1.5x speedup by using vectorized operations.
Benchmark script:
```
import timeit
import numpy as np
import cirq
def random_superposition(dim: int, seed: int) -> np.ndarray:
random_state = np.random.RandomState(seed)
state_vector = random_state.randn(dim).astype(complex)
state_vector += 1j * random_state.randn(dim)
state_vector /= np.linalg.norm(state_vector)
return state_vector
for n in range(8, 22, 2):
state = random_superposition(1 << n, seed=1234)
t0 = timeit.default_timer()
_ = cirq.sample_state_vector(state, range(n), repetitions=1000)
t1 = timeit.default_timer()
print(f"n={n}: {t1-t0} secs")
```
Output before:
```
n=8: 0.01701263594441116 secs
n=10: 0.03182271297555417 secs
n=12: 0.101432592025958 secs
n=14: 0.47042544500436634 secs
n=16: 1.6910279580624774 secs
n=18: …
```
=> Speed up wavefunction sampling

cirq/sim/density_matrix_utils.py
Gives a ~1.5x using the same method as #2460 .
=> Speed up density matrix sampling

cirq/sim/density_matrix_utils.py, cirq/sim/wave_function.py
When all qudits are being measured we can avoid looping over measurement outcomes and computing array indices which is very slow. At large qubit numbers this gives over 100x speedup.
Benchmark script:
```
import timeit
import cirq
for n in range(8, 22, 2):
state = cirq.testing.random_superposition(1 << n, random_state=1234)
t0 = timeit.default_timer()
_ = cirq.sample_state_vector(state, range(n), repetitions=1000)
t1 = timeit.default_timer()
print(f"n={n}: {t1-t0} secs")
```
Output before:
```
n=8: 0.014439163962379098 secs
n=10: 0.024910022970288992 secs
n=12: 0.07276041503064334 secs
n=14: 0.3017184369964525 secs
n=16: 1.0823597890557721 secs
n=18: 4.320284072891809 secs
n=20: 17.91134182305541 secs
```
Output after:
```
n=8: 0.00962069199886173 secs
n=10: 0.01253505703061819 secs
n=12: …
```
=> Speed up sampling in the case of measuring all qudits

cirq/ops/raw_types.py, cirq/ops/raw_types_test.py
=> Gate.controlled(0) return self

cirq/ops/linear_combinations_test.py, cirq/ops/pauli_string_test.py
This fixes 2 of the test failures listed at #2455 . I couldn't fix the third one this way though; that seems to be a separate issue.
=> Loosen precision requirement on some tests

cirq/sim/clifford/clifford_simulator.py, cirq/sim/clifford/clifford_simulator_test.py, cirq/sim/clifford/clifford_tableau.py
=> CliffordTableau stabilizers and destabilizers methods return list of DensePauliString

cirq/__init__.py, cirq/_doc.py, cirq/devices/noise_model.py, cirq/devices/unconstrained_device.py, cirq/google/devices/known_devices.py, cirq/google/gate_sets.py, cirq/google/ops/sycamore_gate.py, cirq/linalg/combinators.py, cirq/linalg/operator_spaces.py, cirq/ops/common_gates.py, cirq/ops/identity.py, cirq/ops/linear_combinations.py, cirq/ops/op_tree.py, cirq/ops/parity_gates.py, cirq/ops/pauli_gates.py, cirq/ops/pauli_string.py, cirq/ops/qubit_order_or_list.py, cirq/ops/swap_gates.py, cirq/ops/three_qubit_gates.py, cirq/study/resolver.py, cirq/study/sweepable.py, cirq/study/sweeps.py, cirq/value/duration.py, cirq/value/type_alias.py, docs/conf.py
- Add `cirq/_doc.py` with a `document` function
- Pass public constants into `document` when they are initialized
- Fixes the fact that e.g. [`cirq.OP_TREE` was being documented using `typing.Union`'s docstring](https://cirq.readthedocs.io/en/stable/generated/cirq.OP_TREE.html)
=> Associate docstrings with public constants

cirq/circuits/optimization_pass.py
This isn't actually enough as the point optimizer will flatten it (again). But this *does* make it so I can write my own PointOptimizer replacement that can respect it
xref #2406
=> PointOptimizerSummary option to avoid flattening

cirq/__init__.py, cirq/ops/__init__.py, cirq/ops/swap_gates.py, cirq/ops/swap_gates_test.py
Many gates in cirq and OpenFermion-Cirq have utilities associated with them that take the rotation angle associated with the gate and convert it to the parameters needed to instantiate the gate.
In particular, XXYY and YXXY in OpenFermion-Cirq have such utilities: Rxxyy and Ryxxy. When PhasedISwapPowGate was added to cirq in order to eventually replace OpenFermion-Cirq's YXXY it was added together with GivensRotation to replace Ryxxy. However, cirq's replacement for XXYY, i.e. ISwapPowGate, lacks a corresponding utility to replace Rxxyy. This PR implements the missing function.
=> ISwapRotation

cirq/circuits/text_diagram_drawer.py, cirq/devices/noise_model.py, cirq/google/ops/sycamore_gate.py, cirq/linalg/transformations.py, cirq/study/flatten_expressions.py, cirq/study/resolver.py, cirq/testing/lin_alg_utils.py, cirq/value/digits.py, cirq/vis/heatmap.py, cirq/work/pauli_sum_collector.py
- Add a few missing doc strings
- Fix some example sections coming before args/results
- Fix a few missing Args
- Change some type annotations to refer to exposed 'cirq.XXX' instead of local cirq.YYY.ZZZ.XXXX
=> Various doc fixes

cirq/testing/consistent_qasm.py, dev_tools/conf/pip-list-dev-tools.txt
Fixes https://github.com/quantumlib/Cirq/issues/2509
=> Bump qiskit version used during qasm compatibility test

cirq/ops/identity.py
Sometime before the v06 release the `gate` property of `IdentityOperation` was removed. This leads to a sort of confusing interface with operations
```
cirq.X(qubit).gate 
>>> cirq.X
cirq.I(qubit).gate
>>> None
```
was there a reason for this change?
=> identity operation -> gate property

cirq/ops/phased_iswap_gate.py, cirq/ops/phased_iswap_gate_test.py
Before:
```
In [3]: cirq.Circuit([cirq.PhasedXPowGate(phase_exponent=0.1, exponent=0.2).on(q0), cirq.ISWAP(q0, q1)**0.3, cirq.PhasedISwapPowGate(phase_exponent=0.4, exponent=0.5).on(q0, q1)])
Out[3]: 
0: ───PhX(0.1)^0.2───iSwap───────PhasedISWAP**0.5───
│           │
1: ──────────────────iSwap^0.3───#2─────────────────
```
After:
```
In [3]: cirq.Circuit([cirq.PhasedXPowGate(phase_exponent=0.1, exponent=0.2).on(q0), cirq.ISWAP(q0, q1)**0.3, cirq.PhasedISwapPowGate(phase_exponent=0.4, exponent=0.5).on(q0, q1)])
Out[3]: 
0: ───PhX(0.1)^0.2───iSwap───────PhISwap(0.4)───────
│           │
1: ──────────────────iSwap^0.3───PhISwap(0.4)^0.5───
```
=> Make circuit rendering of PhasedISwapPowGate consistent with other gates

cirq/google/devices/known_devices.py, cirq/google/devices/known_devices_test.py
- 1000ns is just for read-out.  If we want to use this timing for
non-terminal measurements, there is also a 3000ns "ring down" for
signals to depopulate.
=> Fix timings for Google devices

cirq/study/resolver.py
Is this correct? The new type allows keys that are sympy.Basic, not just sympy.Symbol.
=> Fix ParamResolver.param_dict type

cirq/ops/matrix_gates.py, cirq/ops/matrix_gates_test.py
- Was not specifying the `qid_shape` correctly.
=> Fix MatrixGate __pow__ and __repr__ failing for non-qubit shapes

cirq/__init__.py, cirq/ops/__init__.py, cirq/ops/dense_pauli_string.py, cirq/ops/dense_pauli_string_test.py, cirq/ops/pauli_string.py, cirq/ops/pauli_string_test.py, cirq/protocols/json_test.py, docs/api.rst
- Use in `cirq.PauliString` and `cirq.DensePauliString`
- Generalize to allow lower case "ixyz"
- Make it consistent to allow integers 0=I, 1=X, 2=Y, 3=Z
Example:
```python
cirq.PauliString({
cirq.GridQubit(0, 0): 0,
cirq.GridQubit(0, 1): 1,
cirq.GridQubit(0, 2): 2,
cirq.GridQubit(0, 3): 3,
})
```
```
X((0, 1))*Y((0, 2))*Z((0, 3))
```
=> Define cirq.PAULI_GATE_LIKE

cirq/experiments/single_qubit_readout_calibration_test.py
The test class was written incorrectly in that it  only flips the first bit of each measurement. This didn't matter for how it was used, but still the test class should be correct.
=> Fix NoisySingleQubitReadoutSampler test class

cirq/google/engine/engine_sampler.py, cirq/google/engine/engine_sampler_test.py
Sometimes you want to get engine information such as the calibration.
=> Make QuantumEngineSampler engine accessible through property

cirq/google/devices/known_devices_test.py, cirq/google/serializable_gate_set_test.py
I wasn't sure what would happen if you added a gate to a gate set multiple times, so I decided to add tests to make sure it worked.  Also, made a fix to a test for with_added_gates() as there was a typo and it didn't cause the tests to fail.
This PR does not change functionality.  It only adds tests.
=> Test gate being added multiple times.

check/pytest-changed-files, check/pytest-changed-files-and-incremental-coverage, dev_tools/bash_scripts_test.py
Fixes https://github.com/quantumlib/Cirq/issues/2506
=> Make pytest-changed-files include api tests when an __init__ file is changed

check/pytest-changed-files
- check/pytest-changed-files is broken
- The list of fils to test is put in quotes so it is considered to
be one file by pytest rather than a list of files.
=> Fix pytest

cirq/_compat.py, cirq/_compat_test.py, cirq/circuits/circuit.py, cirq/circuits/circuit_test.py, cirq/contrib/quantum_volume/quantum_volume.py, cirq/ops/identity.py, cirq/ops/matrix_gates.py, cirq/ops/matrix_gates_test.py, cirq/protocols/trace_distance_bound_test.py, cirq/value/duration.py
- @mpharrigan was right, this is way better
- warnings now show up when running pytest even when tests succeed
- warning text will now include the offending line, and will show only once for each offending line
- Fix deprecated usage of SingleQubit/TwoQubitMatrixGate
- Fix deprecated usage case of np.nonzero
=> Use warnings.warn for deprecation warnings

cirq/google/__init__.py, cirq/google/optimizers/__init__.py, cirq/google/optimizers/convert_to_sycamore_gates.py, cirq/protocols/json_test.py, docs/api.rst
Adding these to __init__ will make this similar to ConvertToXmonGates and also allow an easier transition from cirq-internal.
=> Add Conversion optimizers to cirq.google __init__

cirq/optimizers/decompositions_test.py
See #2468. This doesn't fix the bug, obviously, but the flaky test causes failures in unrelated PRs and I think we should try to avoid that.
=> Mark test that sometimes fails on windows as xfail.

cirq/google/engine/engine.py, cirq/google/engine/engine_test.py
- Tried to retrieve historical calibration and it was broken.
- Fixed docs to my understanding and fixed key error.
- Please verify that this is correct now per the API.
=> Fix documentation and key error in calibration

cirq/google/devices/serializable_device.py, cirq/google/devices/serializable_device_test.py
- Fix row/col typo
- Also, modify it so that there's not a bunch of extra new lines
if the grid doesn't start at (0,0) [e.g. Sycamore23]
=> Fix typo in SerializableDevice print out

cirq/ops/phased_iswap_gate_test.py
- In sympy 1.2, print(1 - sympy.Symbol('t')) outputs "-t + 1"
- While the requirements do require sympy 1.4, the actual symbols used
in this test are not important to the testing of phased iswap, and this
change will simplify people who are forced to use older versions of
sympy (i.e. me).
=> Change symbols in phased_iswap_test

cirq/protocols/json_test_data/__init__.py, setup.py
- json_test_data is *.json and *.repr files (not *.py) so will not be
automatically included in the package
- Add these as package_files in setup.py
- Also, add a blank __init__.py file to add cirq.protocols.json_test_data as a package so it gets picked up.
=> Add json_test_data to cirq package

.travis.yml
- Currently, only master runs CI tests.
- This change should add version release branches as well.
=> Add versioned branches to the travis file

.travis.yml, dev_tools/conf/pip-list-dev-tools.txt
The latest release of pip (https://pypi.org/project/pip/20.0.1/) breaks the installation of our qiskit dependency. This commit pins our Windows pip version until https://github.com/pypa/pip/issues/7626 is fixed.
Fixes: https://github.com/quantumlib/Cirq/issues/2692
=> Remove pip upgrade on Windows check in Travis

cirq/experiments/__init__.py, cirq/experiments/n_qubit_tomography.py, cirq/experiments/n_qubit_tomography_test.py, docs/api.rst
Also updates tests to access the symbols under cirq instead of cirq.experiments.n_qubit_tomography. This forces n_qubit_tomography to import individual modules (which is also consistent with how we do this elsewhere).
=> Make n-qubit tomography code available under cirq.experiments

cirq/contrib/acquaintance/executor_test.py, cirq/contrib/acquaintance/inspection_utils_test.py, cirq/contrib/acquaintance/strategies/cubic_test.py, cirq/contrib/quantum_volume/quantum_volume_test.py, cirq/contrib/routing/router_test.py, cirq/experiments/cross_entropy_benchmarking_test.py, cirq/experiments/n_qubit_tomography_test.py, cirq/experiments/qubit_characterizations_test.py, cirq/google/optimizers/convert_to_sqrt_iswap_test.py, cirq/google/optimizers/optimize_for_sycamore_test.py, cirq/google/optimizers/optimize_for_xmon_test.py, cirq/ops/clifford_gate_test.py, cirq/ops/pauli_interaction_gate_test.py, cirq/ops/pauli_string_test.py, cirq/ops/phased_iswap_gate_test.py, cirq/sim/clifford/clifford_simulator.py, cirq/sim/clifford/clifford_simulator_test.py, cirq/testing/consistent_protocols.py, cirq/testing/random_circuit_test.py, examples/advanced/quantum_volume.py, examples/advanced/quantum_volume_test.py, examples/examples_test.py, examples/qubit_characterizations_example.py
- Amend a bunch of the tests to use simpler values so as to speed
up testing.
- Combine a few places where itertools.product results in a huge
number of tests.
- On my machine, these changes speed up "pytest ." from 2m33s to 1m55s.
- Also added additional parameters to vary the number of gates for qubit characterization and added appropriate docstring
Fixes #1339
=> Fix slow tests

requirements.txt
Our tests now pass with networkx 2.4 (context for the original pin: #2368).
=> Unpin networkx

requirements.txt
Sympy v1.5.1 is now available, fixes https://github.com/sympy/sympy/issues/18056.
See https://github.com/sympy/sympy/releases/tag/sympy-1.5.1 & changelog: https://github.com/sympy/sympy/wiki/Release-Notes-for-1.5.1
Ref: #2648 #2655
=> requirements: remove sympy pin

.travis.yml
This was already not working due to https://github.com/quantumlib/Cirq/issues/1826 and now it's causing our Windows builds to fail. See: https://github.com/quantumlib/Cirq/pull/2706
=> Turn off --actually-quiet for Windows

cirq/experiments/random_quantum_circuit_generation.py, cirq/experiments/random_quantum_circuit_generation_test.py
This method is much faster when the set of single qubit gates is large since it avoids generating a new list of gates to choose from. For instance, I was using a set of 64 gates and got around a 15x speedup.
I also modified the code to handle the case of when only one choice of single-qubit gate is given. In that case, the condition of no repeating single-qubit gates is simply not enforced.
=> Speed up single qubit gate layer generation for random quantum circuit

cirq/experiments/cross_entropy_benchmarking.py, cirq/experiments/cross_entropy_benchmarking_test.py, cirq/protocols/json_serialization.py, cirq/protocols/json_test_data/CrossEntropyResult.json, cirq/protocols/json_test_data/CrossEntropyResult.repr
=> Save repetitions in CrossEntropyResult and make it into a JSON serializable dataclass

cirq/sim/density_matrix_simulator.py, cirq/sim/density_matrix_simulator_test.py
Fixes #2567 .
The strategy is to add a flag to `_base_iterator` indicating whether all measurements are terminal. If so, then the iterator ignores operations on qubits that have already been measured.
For review, it may be more convenient to look at the first commit, with message "fix noise simulation". The second commit includes unrelated changes to the file that resulted from running the formatter.
This does not fix the second bug raised by @Ashalynd at #2567 . I will open a separate issue for that.
=> Fix density matrix simulation of noise

cirq/experiments/random_quantum_circuit_generation.py, cirq/experiments/random_quantum_circuit_generation_test.py, cirq/protocols/json_serialization.py, cirq/protocols/json_test_data/GridInteractionLayer.json, cirq/protocols/json_test_data/GridInteractionLayer.repr
I refrained from using `json_serializable_dataclass` because it caused mypy errors in the definition of the grid patterns (see #2769), and fixing those errors would have made the code much less readable because the grid patterns have comments I want to preserve.
=> Make GridInteractionLayer a JSON serializable dataclass

cirq/circuits/circuit.py, cirq/google/common_serializers.py, cirq/ops/raw_types.py
These allow handling tagged operations without isinstance checks:
- `tags` allows getting tags on any operation.
- `untagged` allows getting the underlying op with no tags.
=> Add tags and untagged properties on cirq.Operation

cirq/google/optimizers/convert_to_sycamore_gates.py, cirq/google/optimizers/convert_to_sycamore_gates_test.py
Currently the optimizer accepts the `SycamoreGate` specifically, but fails on an equivalent `FSimGate`. This adds support for fsim gates with sycamore parameters (theta = pi/2, phi = ph/6).
Also adds support for PhasedXZGate as a native gate that will be passed through when optimizing for sycamore.
=> Accept FSim(pi/2, pi/6) in ConvertToSycamoreGates

cirq/__init__.py, cirq/linalg/__init__.py, cirq/linalg/decompositions.py, cirq/linalg/predicates.py, cirq/linalg/predicates_test.py, docs/api.rst
They are _pre_-conditions after all.
Also defines `cirq.is_normal`.
=> In unitary_eig, check preconditions before performing computing eigenvalues

cirq/google/__init__.py, cirq/google/common_serializers.py, cirq/google/common_serializers_test.py, cirq/google/gate_sets.py, cirq/protocols/json_serialization_test.py, docs/api.rst
- This will be equivalent to combining the sqrt iswap and syc gatesets.
- Combining these two gatesets will have the following advantages:
--  This can allow for parameterization of the ISWAP**0 gate
--  That allows circuits to drop out iSwaps and batch efficiently
--  Also allows for expansion if other FSim variants become available
=> Add a limited FSIM gateset

cirq/devices/grid_qubit.py
Similar to the PR speeding hashes, directly defining eq is about 5 times faster. 
One wrinkle is the `__eq__` for Qid doesn't actually check that the two things have the same type, only that they have the same name and repr. We can preserve that behavior if we think it's important for some reason.
=> Speed up GridQubit __eq__

cirq/contrib/noise_models/__init__.py, cirq/contrib/noise_models/noise_models.py, cirq/contrib/noise_models/noise_models_test.py
As noted in #2826, it won't be possible to use single-noise-type models to implement these aggregate models until the noise model composition story is solidified. For now, I've restored the models removed in #2734 (and associated tests) and marked them as deprecated.
=> Restore deprecated noise models.

cirq/google/engine/client/quantum_v1alpha1/proto/engine_pb2_grpc.py
- gRPC path was incorrectly changed to the cirq proto path (cirq.google.engine...)
- It should be using the cloud path (google.cloud...)
=> Fix quantum engine gRPC path

cirq/sim/mux.py
Error message changes for  cirq/sim/mux.py
From:-
"Maybe you wanted `cirq.final_wavefunction`
To:-
"Maybe you wanted `cirq.final_density_matrix`? "
Fixes: https://github.com/quantumlib/Cirq/issues/2778
=> Fix error message from cirq.final_wavefunction to cirq.final_density_matrix #2778

check/pytest-changed-files-and-incremental-coverage
Fixes an error on Mac, as soon more than 1 file changes: 
```
Comparing against revision 'upstream/master'.
usage: dirname path
```
=> fix pytest changed files script for mac

docs/dev/gates.md, docs/gates.ipynb, docs/tutorial.ipynb
- Change .md links to .ipynb links.
- From local building the docs, this _should_ work in readthedocs as well.
Closes: https://github.com/quantumlib/Cirq/issues/2887
=> Fix links in github view

dev_tools/conf/pip-list-dev-tools.txt
We just did this at OpenFermion-Cirq and it's a good idea to keep in sync.
=> Upgrade pytest to version 5.4.1

cirq/google/engine/engine_client.py, cirq/google/engine/engine_client_test.py
Calling `engine.list_processors` currently fails, as in the grpc client the second argument must be a number. This fixes the issue, but does not fully test for it, as that would require an integration test.
=> Fix invalid argument in list_processors.

docs/studies/Quantum_Walk.ipynb, docs/studies/variational_algorithm.ipynb
- The top-level title e.g. "# Title" is what shows on the
table of contents in read the docs.
- Shortened two of the titles to make them show up better.
=> Shortening titles of tutorials

docs/examples.md
- This throws off the readthedocs header.
=> Intermediate examples had the wrong header

cirq/interop/quirk/cells/arithmetic_cells.py, cirq/interop/quirk/cells/control_cells.py, cirq/interop/quirk/cells/input_rotation_cells.py, cirq/interop/quirk/cells/qubit_permutation_cells.py, cirq/interop/quirk/cells/swap_cell.py, cirq/ion/ion_device.py, cirq/linalg/decompositions.py, cirq/pasqal/pasqal_device.py, cirq/pasqal/pasqal_qubits.py, cirq/protocols/circuit_diagram_info_protocol.py, cirq/testing/order_tester.py, cirq/value/duration.py, cirq/value/linear_dict.py, cirq/value/periodic_value.py, cirq/value/timestamp.py, cirq/value/timestamp_test.py, cirq/work/collector.py
Follow-up to #2906. As before, also replaced calls to `format` with format strings.
=> Add more missing type annotations

cirq/study/sweeps_test.py
At present, `test_zip_duplicate_keys` just repeats `test_product_duplicate_keys`.
=> Actually test zip sweep with duplicate keys

cirq/google/common_serializers.py, cirq/google/common_serializers_test.py
- It looks like serialization and deserialization of
floats can have an error up to around 5e-8, so loosening the
restriction to 1e-6 to be safe, since this is only used to determine
gates close to the desired gates.
=> Loosen tolerance restrictions in Quantum Engine

cirq/protocols/has_stabilizer_effect_protocol.py, cirq/protocols/has_stabilizer_effect_protocol_test.py
If everything else fails (i.e. op and its gate don't declare has_stabilizer effect), and op has unitary, 2hich is 2x2 unitary, explicilty check if that unitary has stabilizer effect.
After this change has_stabilizer_effect returns True exactly for those gates which are supported by CliffordSimulator.
This is follow-up to PR #2803.
This is copy of PR #2885 which ended up in urepairable state because of CLA.
=> Check 2x2 unitary in has_stabilizer_effect

cirq/google/engine/engine_client.py, cirq/google/engine/engine_client_test.py
Check that whitelisted_users is actually None to accept updates where input is an empty list (i.e. clearing all users).
=> Accept empty list of whitelisted_users when updating reservations.

cirq/sim/clifford/clifford_simulator_test.py, cirq/sim/clifford/clifford_tableau.py
I found a bug in the Y gate for the tableau circuit simulator. Here is a fix and a test
=> Fix Problem with Y gates in Clifford Simulator

cirq/linalg/transformations_test.py, cirq/protocols/inverse_protocol.py, cirq/sim/density_matrix_utils_test.py, dev_tools/conf/pip-list-dev-tools.txt
Previously we were blocked on upgrading asteroid due to a bug
https://github.com/PyCQA/astroid/issues/650
However the bug now says this is fixed, so verifying that our tests pass.
...and it turns out they don't pass.
Fixes:
* `ndarray.reshape` technically takes lists of arguments like `a.reshape(1, 3, 4)`.  However sometimes lint gets mad about this.  Fixed this and changed other uses in this test to use same pattern for consistency.
* Found a missing assertion right nearby and fixed this.  Needed to fix order bug in test.
* Didn't fix a lint error about the result of getattr not being callable.  I don't think there is any fix besides this as there are lots of bugs about pylint messing this up.  So added a disable.
=> Update asteroid version

cirq/__init__.py, cirq/optimizers/__init__.py, cirq/optimizers/cphase_to_fsim.py, cirq/optimizers/cphase_to_fsim_test.py, docs/api.rst
This implements the decomposition described in section VII F I of the [supplement](https://arxiv.org/abs/1910.11333) to the quantum supremacy paper.
=> Decompose cphase to two fSim gates

cirq/contrib/routing/device.py
Adds the fix prescribed in #2925.
=>  Clear plot state in `nx_qubit_layout()` to prevent issues with pyplot dimensionality to fix Doctest issue.

cirq/google/engine/engine.py, cirq/google/engine/engine_job.py, cirq/google/engine/engine_job_test.py, cirq/google/engine/engine_program.py, cirq/google/engine/engine_test.py
- Adds timeout to Engine object and makes it configurable
- This plumbs the timeout down to results object so that the
amount of polling is configurable.
Solves #2817
=> Add timeout to engine object

release.md
- Adds the new release procedure to markdown in cirq.
=> Add the release procedure to the markdown file in cirq

cirq/google/engine/engine.py, docs/google/calibration.md, docs/google/engine.md, docs/google/specification.md
* Clarified that not specifying the proto version gives you version 2
* Removed protoversion defaults from example code
* Fixed remaining use of `get_latest_calibration` in docs, which no longer exists.
=> Fix some documentation for engine

docs/tutorials/variational_algorithm.ipynb
The extra space causes the equation not to be displayed properly in readthedocs:
The equation displays correctly when viewed in a Jupyter notebook:
=> Fix an equation which does not display correctly in nbsphinx.

cirq/contrib/svg/svg.py, cirq/contrib/svg/svg_test.py
`MatrixGate` tries to print its whole matrix which is just huge. This PR hacks in a check that uses `?` for any gate whose label includes a newline. I will quickly remind reviewers that this functionality is in contrib, xref #2313 if anyone wants to "productionize" this functionality.
=> [SVG Circuits] Give up gracefully on gates with big labels

dev_tools/conf/pip-list-dev-tools.txt
Removes warning that appears in coverage tests.
=> Bump pytest-asyncio version to remove warning

.github/workflows/ci.yml
After #2974 we not longer need to include asteriod when installing pylint.
=> No longer need to install asteroid in CI

cirq/_compat_test.py, cirq/linalg/states_test.py, cirq/ops/moment.py, cirq/ops/moment_test.py, cirq/ops/parity_gates.py, cirq/sim/density_matrix_utils_test.py, cirq/sim/wave_function_test.py, cirq/testing/__init__.py, cirq/testing/logs.py, cirq/testing/logs_test.py, docs/api.rst
Adds a helper for testing logs.
```
with cirq.testing.assert_logs('bacon', 'eggs', 'celery', count=2):
logging.error('bacon and eggs is not available')
logging.error('only celery is available')
```
This removes capture code from `cirq._compat_test` which was used to test deprecation warnings across our codebase.
Features:
* Ability to set log level.
* Ability to capture or not capture from python's `warnings` module.
PR also cleans up two things encountered while using:
* Use `import cirq` pattern in `moments_test.py`
* Fix unused type annotations in parity_gates.py.
=> ContextManager for testing logs

cirq/ops/random_gate_channel.py
#3026 deprecated `has_mixture_channel`
=> Heed deprecation notice for has_mixture_channel

cirq/testing/__init__.py, cirq/testing/random_circuit.py, cirq/testing/random_circuit_test.py, docs/api.rst
Fixes #3033 
Fixes a bug where an empty gate domain occurs due to there not being any gates that operate on the proper number of qubits and the circuit has fewer number of qubits.
Also cleans up random circuit tests
* Adds `DEFAULT_GATE_DOMAIN` to `cirq.testing`, users might want to use it for the circuits they generate
* Allows for an `op_density` of 1.0.
* Correct an incorrect documentation assertion about what `op_density` means and added a test that demonstrates why that document assertion was incorrect.
* Moved to standard style for importing modules and not methods.
=> Fix empty gate domain problem in random_circuit

cirq/testing/random_circuit.py, docs/api.rst
This was breaking my doc build for reasons I have not been able to track down.
=> Add a docstring to testing default gate domain constant

.gitattributes
This will cause generated code to be folded by default when viewing
diffs in PRs that touch protobuf definitions. We have automated checks
to ensure that the generated code is updated, so there's typically no
need to look at it.
=> Add .gitattributes file to hide proto generated code in PRs

cirq/sim/sparse_simulator.py, cirq/sim/sparse_simulator_test.py
This was such a dumb mistake for me to make.
=> Fix split_into_unitary_then_general not spreading blocks across operation

requirements.txt
The numpy 1.19 release broke our tests.  Putting this in while we fix the tests.
#3105 and #3103 for the currently known broken tests.
=> Reduce numpy version

cirq/ops/arithmetic_operation.py, cirq/ops/gate_operation.py, cirq/ops/raw_types.py, examples/shor.py
Also change the return type of `transform_qubits` in the same way. AFAICT this should always be correct, but it's sometimes tricky to convince mypy of this (have to cast in `GateOperation.with_qubits`, for example).
=> Change Operation.with_qubits return type to match self type

cirq/qis/states.py, cirq/qis/states_test.py, cirq/sim/density_matrix_simulator.py, cirq/sim/density_matrix_simulator_test.py
This makes it so that by default when you access the density matrix during simulation, it makes a copy of the matrix.  This can be overridden if one wants to get the speed benefits of not copying.
=> Defensively copy density matrices in simulator

cirq/ops/common_gates.py, cirq/ops/common_gates_test.py
Fixes #3111 
Presently the control override on XPowGate results in copying over the global phase shift of the XPowGate to the CXPowGate (similar for other control constuctions).  This is inconsistent with most people's notion of "control" where the identity component has no phase. 
This makes this override occur only when the global phase is zero.
=> Only override control when global phase is zero

cirq/sim/sparse_simulator.py, cirq/sim/sparse_simulator_test.py, cirq/sim/state_vector_simulator.py, cirq/sim/state_vector_simulator_test.py
The state vector simulator version of #3109  One difference is that the code process the initial state already make a copy of the state.
=> Defensively copy state vector in simulator

cirq/ops/common_gates.py
Follow up to #3113 to improve the docstrings.
=> Improve docstrings for controlled common gate overrides

cirq/google/api/v2/results.py, cirq/ops/measurement_gate.py, cirq/ops/measurement_gate_test.py
The "rekey" operation is useful for some circuit transformations we want to implement; defining it on the MeasurementGate ensures that all the gate properties get copied properly when rekeying.
=> Add MeasurementGate.with_key to change measurement key

cirq/linalg/decompositions.py, cirq/linalg/decompositions_test.py, cirq/ops/pauli_string.py, cirq/ops/pauli_string_phasor.py, cirq/ops/pauli_string_phasor_test.py, cirq/ops/pauli_string_test.py, cirq/sim/density_matrix_simulator_test.py, cirq/sim/sparse_simulator_test.py
- I compared against results from WolframAlpha to make sure the modified tests are now correct
=> Add KakDecomposition._decompose_ by fixing factor of 2 error in exp(PauliString)

cirq/google/engine/engine.py, cirq/google/engine/engine_test.py
- Engine now raises ValueError if you don't specify gate_set.
- While technically backwards incompatible, I don't think anyone
will have working code that doesn't specify a gate_set here.
Solves #2957
=> Remove XMON as engine default

cirq/pasqal/__init__.py, cirq/pasqal/pasqal_qubits.py, cirq/pasqal/pasqal_qubits_test.py, cirq/protocols/json_serialization.py, cirq/protocols/json_test_data/ThreeDQubit.json, cirq/protocols/json_test_data/ThreeDQubit.repr, cirq/protocols/json_test_data/TwoDQubit.json, cirq/protocols/json_test_data/TwoDQubit.repr
This the first child-PR of #3126 .
- Introduces new Pasqal qubit classes: `ThreeDQubit`and `TwoDQubit` (a subclass of `ThreeDQubit`)
- These new classes are intended to replace the original `ThreeDGridQubit`, which will be deleted on the next PR (where other classes' dependencies will be resolved).
- In comparison with `ThreeDGridQubit`, these new classes allow for arbitrary placement of qubits in 3D or 2D space, instead of restricting them to a grid. This more closely resembles the capabilities of Pasqal devices.
=> [Pasqal updates] New qubit classes

.github/workflows/ci.yml
Upgrading Github workflows checkout action from v1 to [v2](https://github.com/actions/checkout). This should speed up the jobs a little bit.
=> checkout@v1 to v2

docs/google/calibration.md
The two qubit metrics had extra "cycle" in them.  
I confirmed these names with those currently returned from a device.  I also double checked it with the name on the internal spreadsheet.
=> Fix calibration metric names in docs

examples/examples_test.py
Just noticed that `test_example_shor_find_factor_with_composite_n_and_quantum_order_finder` actually tests the naive order finder instead of testing the quantum order finder.
Note that the naive order finder is already tested by `test_example_shor_find_factor_with_composite_n_and_naive_order_finder`. Looks like a copy-paste error.
=> Test the right order finder

cirq/sim/clifford/clifford_simulator_test.py
Unit test to prevent reoccurrence of #3164. Goes along with #3165.
=> Unit test for Clifford check skipping multi-qubit unitaries

cirq/ops/raw_types.py, cirq/ops/raw_types_test.py
Previously, tags would get dropped from tagged ops when resolving parameters. Instead, we would like to preserve these tags. In addition, we allow tags themselves to be parameterized and resolve them as well when resolving the tagged op.
=> Preserve (and resolve) tags when resolving TaggedOperation

cirq/_compat_test.py, cirq/linalg/transformations.py, cirq/ops/fourier_transform.py, cirq/sim/density_matrix_utils.py, cirq/sim/mux.py, cirq/sim/state_vector.py
Fixes #3170. 
The deprecated decorator should not be used in a way it was directly used. 
The pattern was: 
```
old_function = deprecated(
deadline='v0.9', fix='Use cirq.new_func instead.')(
cirq.new_func)
```
The main problem is that we pass in the _new_ function into the deprecated decorator...now it does return a new function instance that is a decorated one and hence the old function gets a good wrapper around it. However, the name calculation in case `name` arg is not defined cannot determine what the name of `old_function` is. 
There are two ways to fix this AFAICT (unless I'm missing some python magic that can tell what the name of the variable is that is calling the current function - which I found to be not possible): 
1.) set `name` and duplicate the variable (function) name …
=> fixing broken deprecation namings

README.rst
I'm not sure if this will fix the cirq-unstable upload (#3175), but it does say in the [reStructuredTest spec](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#sections) that
> An underline/overline is a single repeated punctuation character that begins in column 1 and forms a line extending at least as far as the right edge of the title text.
I also added an extra blank line before section headers which improves readability of the plain text file, at least to my eyes.
=> Fix readme section headers

.github/workflows/ci.yml, README.rst, dev_tools/conf/pip-list-dev-tools.txt
Adds rstcheck to the doc tests CI step.
This is to avoid accidentally breaking pypi publishing with syntactically incorrect. See https://github.com/quantumlib/Cirq/issues/3175 for when this happened.
=> adding rstcheck for rst files

cirq/google/gate_sets.py, dev_tools/build-docs.sh, dev_tools/conf/pip-list-dev-tools.txt
Fixes #3200.
As we will deprecate Sphinx soon anyway, and I wanted to have this situation resolved asap, I decided to pin to 3.1.* version of sphinx instead of fighting the new warnings from 3.2.0.
=> Fix docs build

cirq/ops/parity_gates.py
Fixes #2806.
This is covered by tests, but I ran these checks to be sure:
```
In [1]: import cirq, numpy as np
In [2]: def mxx(t): 
...:     f = np.e**(1j*np.pi*t/2) 
...:     c = f * np.cos(np.pi*t/2) 
...:     s = -1j * f * np.sin(np.pi*t/2) 
...:     return np.array([[c, 0, 0, s], [0, c, s, 0], [0, s, c, 0], [s, 0, 0, c]]) 
...:     
In [3]: def myy(t): 
...:     f = np.e**(1j*np.pi*t/2) 
...:     c = f * np.cos(np.pi*t/2) 
...:     s = -1j * f * np.sin(np.pi*t/2) 
...:     return np.array([[c, 0, 0, -s], [0, c, s, 0], [0, s, c, 0], [-s, 0, 0, c]]) 
...:     
In [4]: np.allclose(cirq.unitary(cirq.XX**0.1), mxx(0.1))
Out[4]: True
In [5]: np.allclose(cirq.unitary(cirq.YY**0.1), myy(0.1))
Out[5]: True
```
NB: Global phase factors complicate documentation. I think we should prefer SU(n) …
=> Document matrices for parity gates

cirq/google/__init__.py, cirq/google/api/v1/programs_test.py, cirq/google/devices/xmon_device.py, cirq/google/optimizers/convert_to_xmon_gates.py, docs/api.rst
- Cirq v1 protos are deprecated.
- No one should have been actively using these functions for over a year.
=> Remove cirq v1 programs from namespace

.gitignore, cirq/circuits/quil_output_test.py, cirq/ops/common_gates.py, cirq/ops/parity_gates.py, cirq/ops/swap_gates.py, dev_tools/conf/pip-list-dev-tools.txt
This PR addresses a bug in Quil output.
The current code doesn't distinguish between Cirq's `PowGate` exponents and the angle parameters for Quil gates, but they differ by a factor of pi. This is verified by comparing program unitaries before and after conversion to Quil (see below).
Adds a test for this change that depends on pyQuil, so `pyquil` is added to `pip-list-dev-tools.txt`, but in the event that pyQuil is not available for import, the test is [skipped](https://docs.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency).
Additionally sneaks in a change to Quil output for `ISwapPowGate` -- uses the native `XY` Quil gate when the exponent of the `ISwapPowGate` does not equal 1.
```python
In [1]: import numpy as np
...: from pyquil import Program
...: from …
```
=> Add missing factor of pi to parameterized Quil gate output

cirq/google/devices/serializable_device.py, cirq/google/devices/serializable_device_test.py
Makes working with SerializableDevice in ipython or jupyter a bit nicer.
Before:
```
In [1]: import cirq                                                                                      
In [2]: cirq.google.Sycamore                                                                             
Out[2]: <cirq.google.devices.serializable_device.SerializableDevice at 0x7fa7e2840b50>
```
After:
```
In [1]: import cirq                                                                                      
In [2]: cirq.google.Sycamore                                                                             
Out[2]: 
(0, 5)───(0, 6)
│        │
│        │
(1, 4)───(1, 5)───(1, 6)───(1, 7)
│        │        │        │
│        │        │        │
(2, 3)───(2, 4)───(2, 5)───(2, 6)───(2, 7)───(2, …
```
=> Add jupyter-compatible repr for SerializableDevice

cirq/circuits/quil_output.py, cirq/circuits/quil_output_test.py, cirq/contrib/contrib-requirements.txt, cirq/contrib/quil_import/__init__.py, cirq/contrib/quil_import/quil.py, cirq/contrib/quil_import/quil_test.py, cirq/ops/swap_gates.py, cirq/ops/two_qubit_diagonal_gate.py, dev_tools/conf/mypy.ini, docs/api.rst
This PR adds Quil import support in a way analogous to the existing QASM import functionality, by leveraging the Quil parser that already exists in pyQuil.
By using `circuit_from_quil` from the `cirq.contrib.quil_import` module, all Quil standard gates, measurements, and simple (non-parameterized) DEFGATEs can be converted to Cirq operations (see below).
Additionally adds Quil output for special cases of `TwoQubitDiagonalGate`, and fixes a bug in the way DEFGATE blocks were being generated by the Quil outputter.
```python
In [1]: from cirq.contrib.quil_import import circuit_from_quil
In [2]: circuit_from_quil("""
...: DECLARE ro BIT[3]
...: I 0
...: I 1
...: I 2
...: X 0
...: Y 1
...: Z 2
...: H 0
...: S 1
...: T 2
...: PHASE(pi/8) 0
...: PHASE(pi/8) 1
...: PHASE(pi/8) 2
...: RX(pi/2) 0 …
```
=> Add initial support for converting Quil programs into Cirq circuits

dev_tools/docs/build_api_docs.py
- It's deprecated and no one should be using it.
=> Disable cirq v1 api docs

docs/dev/development.md
The Developer Documentation had the two lines below which needed change.
```bash
git clone git@github.com:quantumlib/cirq.git
cd cirq
```
and 
```bash
git clone git@github.com:USERNAME/cirq.git
cd cirq
```
The directory name after cloning is ```Cirq``` and not ```cirq```. Changed the casing to match the directory name.
=> Minor Correction to Dev Docs.

cirq/contrib/qcircuit/qcircuit_diagram_info.py, cirq/devices/grid_qubit.py, cirq/devices/line_qubit.py, cirq/ops/moment.py, cirq/ops/moment_test.py, cirq/protocols/channel.py, cirq/sim/act_on_state_vector_args.py, cirq/study/trial_result.py, cirq/value/__init__.py, cirq/value/linear_dict.py, cirq/value/value_equality_attr.py, cirq/value/value_equality_attr_test.py, dev_tools/auto_merge.py, dev_tools/conf/pip-list-dev-tools.txt, dev_tools/prepared_env.py
- `Moment.__add__` now accepts any `OP_TREE`
- `Moment.__sub__` takes an `OP_TREE` and returns a moment with those operations removed
- If there is an operation-to-remove that was not present, an error is raised
- Also bump mypy version to fix an incompatibility with python 3.8 and fix new warnings
- Add explicit !r to format statements touching bytes
- Rename `value_equality.py` to avoid name collision with the decorator it defines
- Ignore false positives related to abstract base type bounds
=> Add Moment.__sub__ and generalize Moment.__add__

cirq/__init__.py, cirq/protocols/__init__.py, cirq/protocols/json_serialization.py, cirq/protocols/json_serialization_test.py, dev_tools/incremental_coverage.py, docs/api.rst
This is easier to use than `Callable[[str], Union[None, Type]]` and can be used by clients who want to write, and typecheck, their own custom resolvers.
=> Add JsonResolver mypy type for custom json resolvers

cirq/circuits/circuit.py, cirq/circuits/circuit_test.py
This PR fixes #3196 by using the ```html``` module for escaping characters when the circuit diagram is produced. The escaping allows easy and correct rendering of the diagram when it is used as a cell output of a Jupyter Notebook instead of using ```print(circuit)```.
Previsouly, the special characters like ```< >``` were not being rendered after the circuit was flattened as they were being interpreted as part of HTML tags. Using ```html.escape( )``` in ```circuit._repr_html(self)``` prevents that from happening.
=> Escape special characters in Jupyter circuit diagram

cirq/google/__init__.py, cirq/google/engine/__init__.py, cirq/google/engine/engine.py, cirq/google/engine/engine_test.py, docs/api.rst
- Adds a function to get a device from a device specification without having to initialize an Engine object.
Addresses half of #3150
=> Add get_engine_device shortcut

cirq/google/gate_sets.py, cirq/google/line/placement/greedy.py, dev_tools/build-docs.sh, dev_tools/conf/pip-list-dev-tools.txt, docs/conf.py
Upgrades to Sphinx 3.2.* that gives us the ability to discern between cirq.qft and cirq.QFT rst files generated by autodoc which generated a warning on Mac. 
Also adding documentation to NAMED_GATESETS and fixed an indentation warning that came from the new Sphinx. 
Fixes #3202.
=> Upgrade to sphinx 3.2.* and fix warnings

cirq/google/arg_func_langs.py, cirq/google/arg_func_langs_test.py
- Add exponentiation to symbol serialization support.
This will make a new Arg func type called 'poly' that supports
exponents (polynomials).
Fixes #3078
=> Add pow function to arg_func_lang

AUTHORS, cirq/contrib/quirk/export_to_quirk_test.py, cirq/google/engine/client/quantum.py, cirq/google/engine/client/quantum_v1alpha1/__init__.py, cirq/google/engine/client/quantum_v1alpha1/gapic/enums.py, cirq/google/engine/client/quantum_v1alpha1/gapic/quantum_engine_service_client.py, cirq/google/engine/client/quantum_v1alpha1/gapic/transports/quantum_engine_service_grpc_transport.py, cirq/google/engine/client/quantum_v1alpha1/proto/engine.proto, cirq/google/engine/client/quantum_v1alpha1/proto/quantum.proto, cirq/google/engine/client/quantum_v1alpha1/types/__init__.py, cirq/google/line/__init__.py, cirq/google/line/placement/__init__.py, cirq/google/line/placement/anneal.py, cirq/google/line/placement/anneal_test.py, cirq/google/line/placement/chip.py, cirq/google/line/placement/chip_test.py, cirq/google/line/placement/greedy.py, cirq/google/line/placement/greedy_test.py, cirq/google/line/placement/optimization.py, cirq/google/line/placement/optimization_test.py, dev_tools/check.py, dev_tools/check_incremental_coverage_annotations.py, dev_tools/docs/run_doctest.py, dev_tools/incremental_coverage.py, docs/_book.yaml, docs/_index.yaml
As we have the AUTHORS file we should use "The Cirq Developers" type copyright notice.
=> Fix copyright notes: Google LLC -> The Cirq Developers

cirq/_doc.py, cirq/google/gate_sets.py
The devsite API docs generation script doesn't pick up docstrings for our type aliases currently. This fixes it. 
Inspired by https://github.com/tensorflow/tensorflow/blob/40a314cab8d6c7afbc62456433a033c1cab8d74f/tensorflow/python/types/doc_typealias.py#L24:5
=> docstrings for type aliases in devsite API docs

cirq/contrib/contrib-requirements.txt, cirq/contrib/quimb/state_vector.py
Alternatively, you can comment out `state_vector.py` line 150.
Fixes gh-3263
=> Minimum required version of quimb.

dev_tools/conf/pip-list-dev-tools.txt, docs/dev/development.md, docs/dev/nomenclature.md, docs/devices.md, docs/install.md, docs/tutorials/examples.md, docs/tutorials/variational_algorithm.ipynb, rtd_docs/conf.py
We should not refer to readthedocs.io from our docs for content, unless it's absolutely necessary. 
This removes the last readthedocs.io references.
=> removing readthedocs.io references

docs/google/calibration.md, docs/tutorials/google/colab.ipynb, docs/tutorials/google/reservations.ipynb, docs/tutorials/google/start.ipynb
- Add links to the files in github for colabs that are
primarily meant to be downloaded.
- Add link to GCP console for retrieving calibration
metrics.
=> Add a few extra links to documentation

cirq/qis/states.py, cirq/qis/states_test.py
Could potentially cause out of bounds access for `one_hot`
=> Fix a bug in validating computational basis limits

docs/tutorials/google/colab.ipynb, docs/tutorials/google/start.ipynb
- Minor issues found through walk-through
- Google colabs are meant to be downloaded,
so image links need to be absolute
- Rearrange text so that project creation/selection
happens before trying to enable the API
- Add link to reservation colab on getting started guide.
=> Adjust docs for Getting started guide

cirq/google/engine/engine_client.py
Cleanup of method docstrings in the Engine API. 
* some places we had Params instead of Args
* some places we had filter strings for timestamps referring to the long string format which is actually not supported, only epoch timestamps
=> cleanup engine docstrings

cirq/google/engine/engine.py, cirq/google/engine/engine_client.py, cirq/google/engine/engine_client_test.py, cirq/google/engine/engine_program.py, cirq/google/engine/engine_program_test.py, cirq/google/engine/engine_test.py
Adds Engine.list_jobs() and EngineProgram.list_jobs(). 
Adds Engine.list_jobs(), EngineProgram.list_jobs() (which call the newly added EngineClient.list_jobs()) with filtering capabilities: 
* created_after, created_before, has_labels
* execution states to filter for a set of states
Related #3302. Next PR will be to update the docs and that will close it.
=> List Engine jobs

docs/_book.yaml, docs/dev/style.md, rtd_docs/dev/index.rst
Moving style.md to the developer documentation. 
Fixes #2787.
=> Moving style.md to the developer documentation

dev_tools/conf/pip-list-dev-tools.txt
Pinning Pygment==2.6.1 for readthedocs.
See https://github.com/sphinx-doc/sphinx/issues/8198#issuecomment-692525937. 
Fixes #3315.
Test run of this branch on my fork using readthedocs itself succeeds: https://readthedocs.org/projects/balopat-cirq-rtd/builds/11906952/
=> pygment 2.6.1 to fix readthedocs

cirq/__init__.py, cirq/study/__init__.py, cirq/study/sweepable.py, cirq/study/sweepable_test.py, cirq/study/sweeps.py, cirq/study/sweeps_test.py, rtd_docs/api.rst
=> Add methods for converting dict to product or zip sweep and deprecate implicit cartesian product

docs/google/engine.md
More explanation around the Engine API.
=> Explaining Engine API access

cirq/sim/simulator_test.py, cirq/study/sweepable.py
This seems logical. Note, however, that since `to_sweeps` currently contains deprecated code, this introduces deprecated behavior into `to_resolvers`. To avoid that we could wait for the next release before merging this.
=> Refactor to_resolvers to use to_sweeps

.github/workflows/ci.yml, requirements.txt
To cover all python runtimes that we support, adding coverage for 3.7 besides 3.6.
With #3194 we can add 3.8 as well, and soon 3.9 hopefully to the mix. 
If we agree on #3347, then we can drop 3.6 as well.
=> adding 3.7 to the tests

docs/_book.yaml
Adds pasqal pages to devsite configuration.
This was lost in the sphinx / devsite shuffle.
=> adds pasqal pages to devsite

Dockerfile, cirq/ion/convert_to_ion_gates_test.py, cirq/optimizers/decompositions.py, cirq/optimizers/decompositions_test.py, requirements.txt
Remove the upper bound on numpy and fixes the broken tests.
Fixes #3103.
- it [turns out](https://github.com/quantumlib/Cirq/issues/3103#issuecomment-698562537) that the decomposition test needed to be removed
- also switching to use cirq.linalg.unitary_eig that works better for cases when the unitary has close eigenvalues (added extra test for it) and it is faster
Fixes #3105.
- though I cannot reproduce the issue, I added approx_eq in the ion gate conversion tests to be on the safe side
Fixes #3210. 
- finally these two above were the blockers for removing the upper bound of numpy 0.19 which is now removed.
=> Fix NumPy 0.19 related issues

cirq/google/api/v2/program.py, cirq/google/api/v2/program_test.py
Extending the protocol to cater for some older pieces of the infrastructure that mark gridqubits with `q1_2` instead of `1_2`. 
Fixes #3219.
=> ignore q in gridqubit ids

cirq/study/resolver.py, cirq/study/resolver_test.py, docs/google/engine.md
Extends ParamResolver's logic to circumvent sympy's slowness to members of numbers.Number. 
It also generalizes sympy constants instead of only handling pi and NegativeOne.
Fixes #3359.
=> Extending types for symbol resolution fast pass-through

cirq/__init__.py, cirq/optimizers/__init__.py, cirq/optimizers/two_qubit_to_fsim.py, cirq/optimizers/two_qubit_to_fsim_test.py, rtd_docs/api.rst
=> Do not perform extra optimizations in "via B" decomposition

cirq/devices/grid_qubit.py
According to the following profiling code, this change decreases the dictionary lookup time from 2100ns to 600ns on my machine.
```
import time
import cirq
d = {q: 5 for q in cirq.GridQubit.rect(3, 3)}
q = cirq.GridQubit(0, 0)
total = 0
t0 = time.monotonic()
n = 100000
for _ in range(n):
total += d[q]
t1 = time.monotonic()
print(total)
print((t1 - t0) / n * 10**9, "nanoseconds per hash")
```
=> Improve GridQubit dictionary lookup performance 3x

cirq/experiments/grid_parallel_two_qubit_xeb.py
Cirq minimum requirement for numpy is 1.16.
In 1.16, the mode parameter for np.pad is required.
(It was changed to optional in numpy 1.17).
Add this parameter in with the default value to support numpy 1.16.
=> Fix np.pad issue in numpy 1.16

cirq/contrib/quimb/state_vector.py, cirq/study/resolver.py
Making quimb version check more robust.
In some systems the version might not be parseable as (int,int), e.g `0+unknown`. 
This PR fixes these scenarios.
Fixes #3263.
=> Fix quimb version checking

cirq/_compat.py
Removes accidental print statement. 
(cherry pick to v0.9.1)
=> remove accidental print

check/pylint-changed-files, cirq/google/engine/engine.py, cirq/sim/clifford/stabilizer_sampler_test.py, dev_tools/bash_scripts_test.py, dev_tools/conf/.pylintrc, dev_tools/conf/pip-list-dev-tools.txt
Upgrades pylint to 2.6.*
Also: 
* I noticed that the pylintrc file was not properly setup - there was no `[MASTER]` section. 
* `check/pylint-changed-files` passed to pylint not only python files but requirements.txt and pylintrc for example - now it is filtering to .py files only 
* there was a missing licenese header in a recently added file
Fixes #1986.
=> upgrade to pylint 2.6

.github/workflows/stale.yml
Adding stale issue workflow as per http://bit.do/cirq-triage. 
Issues that are exempt from the stale check are the ones that have any of these labels: 
- triage/accepted
- triage/discuss
- kind/design-issue
- kind/health 
- kind/roadmap-item
- kind/task 
PRs are not subject to stale check yet.
=> Adds the stale issue Github Actions workflow

cirq/google/engine/env_config_test.py
- Add mock to env_config_test deprecation test.
- Without the mock, the environment calls the engine, which
fails in certain environments.
=> Add mock to env_config_test

cirq/google/arg_func_langs_test.py
Fix protobuf serialization test issue - as in some environments protobuf might not truncate to 4 bytes the test should cater for approximate equality.
=> fix protobuf serialization test issue

rtd_docs/conf.py
Strips license info for readthedocs generation. 
Fixes #3402.
=> strip license info for RTD pages

cirq/google/serializable_gate_set.py, cirq/google/serializable_gate_set_test.py
This method checks if a given object containing operations (a circuit, moment, or other arbitrary op tree) is supported by a gateset. Note that this does not address separating the notions of belonging to a gateset from serializability, but at it provides a way to check if a circuit is supported without actually serializing, which can be expensive.
=> Add SerializableGateSet.is_supported

cirq/experiments/qubit_characterizations.py, cirq/experiments/qubit_characterizations_test.py
Also adds a test to ensure we are building the full group with either
decomposition, and use ZXZ to ensure that the XZ decomposition uses only
a single microwave gate per clifford.
Fixes #3411
=> Update single-qubit cliffords to fix XZ decomposition.

cirq/circuits/circuit.py, cirq/devices/grid_qubit.py, cirq/devices/grid_qubit_test.py, cirq/devices/line_qubit.py, cirq/devices/line_qubit_test.py, cirq/ops/moment.py, cirq/ops/moment_test.py, cirq/ops/raw_types_test.py, cirq/protocols/circuit_diagram_info_protocol.py, cirq/testing/circuit_compare.py
- Creates a 2d view of the moment
- `Moment.__str__` now produces a text diagram
- Moved several diagram utilities out of circuit and into private methods inside the diagram info protocol file
- Added `__complex__`/`__float__`/`__int__` to GridQubit/LineQubit as appropriate
This was motivated by being confused by a large circuit on a grid, and wanting to see some of the 2d structure more directly.
Example diagram:
```
import cirq
a, b, c, d = cirq.GridQubit.rect(2, 2)
print(cirq.Moment(cirq.S(c), cirq.ISWAP(a, d))
```
```
╷ 0     1
╶─┼─────────────
0 │ iSwap─┐
│       │
1 │ S     iSwap
│
```
=> Add Moment.to_text_diagram

docs/_book.yaml, docs/google/access.md, rtd_docs/index.rst
- Access and Authentication page that describes projects
and users and gives some hints for potential issues.
This is needed for the new website where all vendors will
have an access and auth page to clarify access requirements.
=> Add access and authentication page for Google doc

cirq/google/__init__.py, cirq/google/ops/__init__.py, cirq/google/ops/calibration_tag.py, cirq/google/ops/calibration_tag_test.py, cirq/protocols/json_serialization.py, cirq/protocols/json_test_data/CalibrationTag.json, cirq/protocols/json_test_data/CalibrationTag.repr, rtd_docs/api.rst
- Adds a tag to designate a token on a tag to use a specific
calibration.
- Since we are adjusting the name from Focused Calibration to
Calibration API, I have changed this from the formerly named
FocusedCalibrationTag to CalibrationTag
=> Add CalibrationTag

cirq/experiments/qubit_characterizations.py, cirq/google/optimizers/two_qubit_gates/gate_compilation.py, cirq/google/optimizers/two_qubit_gates/math_utils.py, cirq/linalg/decompositions_test.py, cirq/linalg/transformations.py, cirq/ops/common_channels.py, cirq/ops/parity_gates.py, cirq/protocols/channel.py, cirq/protocols/measurement_key_protocol.py, examples/bcs_mean_field.py
Fix all latex expressions without the enclosing $ signs. Fixes issue #3286
Approach: I searched for all the raw strings in the repository, and went these strings one by one to check for missing latex expressions.
Some comments regarding specific changes to make sure they are correct:
* For file `cirq/linalg/transformations.py`: The changes would look like [this](https://hackmd.io/0UK6Na6mQ1aY2tkcEFSlxg?view).
* For file `examples/bcs_mean_field.py`: The changes would look like [this](https://hackmd.io/ZpqO-TdnQbajFo_TSRBiCA?view). I have changed the command `\dag` to `\dagger` as `\dag` wasn't being rendered properly in HackMd.
* For file `cirq/ops/common_channels.py`: Changed `$ \sum_i p_i Pi \rho Pi $` to  `$\sum_i p_i Pi \rho Pi$`, as the first expression isn't being rendered correctly …
=> Fix all latex expressions without enclosing $ signs

docs/simulation.ipynb
From what I can tell, the nearest equivalent to the old concept of "Study" is a sweep. Strangely, the example code seems to be up-to-date for this.
=> Replace `Study` with `sweep` in docs

cirq/ops/global_phase_op.py, cirq/ops/global_phase_op_test.py
=>  Add _act_on_ for StabilizerStateChForm to GlobalPhaseOp

docs/_book.yaml
Fix educators links in book.yaml. 
This breaks devsite staging currently.
=> fix educators links in book.yaml

docs/custom_gates.ipynb
@balopat I found a small typo when checking that the matrix equations rendered correctly (which they indeed do now).
=> Fix typo in custom gates guide

cirq/google/engine/engine_client.py, cirq/google/engine/engine_client_test.py
Code says initial backoff is 0.1 seconds, but code multiplied this by 2 before sleeping
- Made it match the comment.  
- Added a test.
- Decreased time in nearby test to speed overall tests, tests that two sleeps are called not four now.
=> Change initial backoff in engine client.

cirq/__init__.py, cirq/circuits/circuit.py, cirq/circuits/circuit_test.py, cirq/circuits/frozen_circuit.py, cirq/ops/gate_operation.py, cirq/ops/gate_operation_test.py, cirq/ops/measurement_gate.py, cirq/ops/measurement_gate_test.py, cirq/ops/moment.py, cirq/ops/moment_test.py, cirq/ops/raw_types.py, cirq/ops/raw_types_test.py, cirq/protocols/__init__.py, cirq/protocols/measurement_key_protocol.py, cirq/protocols/measurement_key_protocol_test.py, rtd_docs/api.rst
Related to #3235. This is necessary for encapsulating FrozenCircuits in Gates; if a FrozenCircuit contains a measurement, any Gate that contains that FrozenCircuit cannot be reused in the same Circuit without remapping its measurement keys.
=> Add measurement key remapping protocol.

cirq/__init__.py, cirq/experiments/qubit_characterizations.py, cirq/experiments/t1_decay_experiment.py, cirq/experiments/t2_decay_experiment.py, rtd_docs/api.rst
These should accept any cirq.Qid, not just cirq.GridQubit. Similarly, for tomography experiments we can take AbstractCircuit instead of Circuit. I've also updated type definitions to use the preferred convention of `'cirq.Foo'` for types that are exported on the main `cirq` namespace.
=> Generalize types for basic qubit experiments

cirq/__init__.py, cirq/circuits/quil_output_test.py, cirq/experiments/t1_decay_experiment.py, cirq/experiments/t2_decay_experiment.py, cirq/experiments/t2_decay_experiment_test.py, cirq/google/common_serializers_test.py, cirq/google/devices/known_devices_test.py, cirq/google/gate_sets_test.py, cirq/ops/__init__.py, cirq/ops/wait_gate.py, cirq/ops/wait_gate_test.py, cirq/sim/density_matrix_simulator_test.py, cirq/sim/sparse_simulator_test.py, rtd_docs/api.rst
In some cases we want a wait gate that applies to multiple qubits, to
creates a "barrier" that other gates cannot be moved past even while
a circuit is being manipulated in other ways. This makes the wait gate
variadic and adds a helper function to create WaitGate instances and
deal with qid_shape, similar to MeasurementGate/measure.
=> Make WaitGate variadic and add wait helper function

.github/CODEOWNERS, .github/workflows/ci.yml, dev_tools/codeowners_test.py, dev_tools/conf/mypy.ini, dev_tools/conf/pip-install-minimal-for-pytest-changed-files.sh, dev_tools/conf/pip-list-dev-tools.txt
Adds CODEOWNERS file. 
This will enable the following behavior: 
- @cirq-maintainers, @cduck and @vtomole  are the default codeowners for the content of the repo. This has been decided based on levels of contributions in the last 6 months on Cirq Cynque, PR approvals and issue conversations. 
- @wcourtney is added as an owner to the google related code and docs
- Owners are going to be pinged on every PR
- I will turn on "owner approval required" - which means that no one can merge a PR unless an owner has approved the given PR. 
Eventually this will enable the definition of codeowners for vendors, e.g. AQT, IonQ, Pasqal and experimental modules - so that these modules can move faster without the overhead of waiting on Cirq maintainer approval
@cduck, @vtomole, let me know if you want to …
=> codeowners file

.github/CODEOWNERS, dev_tools/codeowners_test.py
To enable faster iterator for our vendor modules, we are adding quantum platform vendor owners to our repo as collaborators and codeowners for their particular modules.
=> aqt, pasqal, ionq owners

cirq/ops/qubit_order_test.py, cirq/testing/consistent_pauli_expansion_test.py, dev_tools/incremental_coverage.py, dev_tools/incremental_coverage_test.py, examples/examples_perf_test.py
These changes came out of #3516 when trying to switch to using black for formatting.
- Add qubit_order test to cover exception case
- Remove `_unitary_` method on a test class which is not covered by tests
- Ignore coverage check for performance tests which are not run in a standard pytest run
- Modify the coverage script to ignore `if TYPE_CHECKING` blocks which don't run during tests (this resulted in unrelated formatting changes on `incremental_coverage.py` which apparently had never been formatted by yapf)
=> Tweak coverage to prepare for switching to black

cirq/contrib/qasm_import/_parser_test.py, cirq/interop/quirk/url_to_circuit_test.py, cirq/ops/measurement_gate_test.py, cirq/ops/pauli_string_test.py, cirq/pasqal/pasqal_device.py, cirq/sim/density_matrix_simulator_test.py, cirq/value/product_state.py, dev_tools/incremental_coverage_test.py, dev_tools/shell_tools_test.py
Switching the formatting to black in #3516 brought up a few issues. Black has an edge case that requires inserting trailing commas in some constructs (https://github.com/psf/black/issues/1629), which I've done here. Also removes trailing whitespace in a few places that pylint complains about when the files are reformatted (those lint errors are latent since we only lint changed files on PRs).
=> Tweak formatting to prepare for switching to black

cirq/ops/common_gates.py
There was a type error due to the fact that the common superclass `EigenGate`  does not define `_act_on_`. We can act on each gate instead of looping over them, which avoids the type error.
=> Fix type error in (X/Y)PowGate._act_on_

cirq/protocols/json_serialization.py, cirq/protocols/json_serialization_test.py
This came out of #3516; removing two levels of indentation makes the formatting change less drastic, but IMO also makes the code more understandable by removing the singleton `_ResolverCache` class.
=> Refactor how we generate default json resolver

dev_tools/docs/build_api_docs.py
Removes CircuitDag methods from API doc that are inherited from networkx.
=> [doc] remove CircuitDag methods from API doc that are inherited from networkx

docs/tutorials/google/start.ipynb
Fixes a newline in the Google Getting started tutorial.
=> [doc] Fix a newline in the Google Getting started tutorial.

.github/workflows/ci.yml, .readthedocs.yml, pyproject.toml, setup.py
Drop support (CI tests) for python 3.6.
Following #3347 we can safely drop python 3.6 support. This is also motivated by current breakages in Mac 3.6 and RTD #3554. This will not finalize #3347, we'll need to add some more documentation around the python support to close it fully.
Fixes #3554. See the successful build from my fork: https://readthedocs.org/projects/balopat-cirq-rtd/builds/12481463/
=> Drop python 3.6 support

cirq/study/resolver.py, cirq/study/resolver_test.py
This is convenient to have for subcircuits (#3235), since nested circuits must be able to resolve their parameters based on the parent's parameter mapping.
=> ParamResolver composition.

check/format-incremental
Fix formatter on deleted or moved files. 
Fixes #3573.
=> Fix formatter on deleted or moved files

cirq/protocols/resolve_parameters.py
Can't see in the diff, but there was an errant delete character in the docstring causing an unicode issue when rendering the API reference page.
=> Remove bad delete char from docstring

check/pytest-changed-files, check/pytest-changed-files-and-incremental-coverage, dev_tools/bash_scripts_test.py
rtd_docs/docs_coverage_test.py file was deleted in PR3587 but some references to the file were left in check/* scripts because of which the scripts now fail. This PR removes those stale references.
=> Remove stale rtd_docs/docs_coverage_test.py references from check/* scripts

cirq/circuits/frozen_circuit.py
Amusing story.  `pylint` has a flag `-j` which allows for parallel linting.  When I ran it in this mode it entered an infinite loops stuck on this.  Normal `pylint` did not seem to uncover it.  ¯\\\_(ツ)\_/¯
=> Remove unused dependency

docs/simulation.ipynb
Some links on the site are not rendering well for the [simulation docs](https://quantumai.google/cirq/simulation):
This PR fixes this by changing to one tick for inline code instead of two which renders well for other docs (e.g., [noise](https://quantumai.google/cirq/noise)).  Also removes extra Cirq install and fixes small typo.
=> Format links in simulation docs

cirq/ionq/ionq_client.py, cirq/ionq/ionq_client_test.py, cirq/ionq/job.py, cirq/ionq/job_test.py, cirq/ionq/results.py, cirq/ionq/results_test.py, cirq/ionq/service.py, cirq/ionq/service_test.py
This returns `cirq.Result` objects in contrast to `create_job` which returns ionq bespoke result objects.  Note that this involves creating measurement results whose order is not the order in which the circuit was run (technically even over in engine land such a contract is not enforced).
A couple of other changes of note:
* Instead of enforcing no repetitions in creating a job for a simulator, these are passed along through the metadata.  This then makes the interface for the user less complicated, though the user may end up with the false impression that the sample occurs server side.
* For simulations you can override the repetitions to obtain a new sample.
=> Add run method to IonQ service

docs/noise.ipynb
This PR addresses remaining comments from #3569 which was merged due to time constraints.
- Adds link to protocols guide (and custom gates guide) to address comment from @balopat.
- Adds example using `cirq.NoiseModel` and addresses other remaining comments from @obriente.
Also adds section headers to density matrix simulation and monte carlo simulation to make them more apparent in the nav.
=> Update noise docs

README.rst
the tutorial link was prefixed with https://https://. This update fixes the link issue
=> Update tutorial links on readme

cirq/protocols/json_serialization.py, cirq/protocols/json_serialization_test.py
Part of #3235. Also contributes to #3438.
This PR adds a `SerializableByKey` interface which any Cirq object can implement to enable more concise JSON serialization of repeated objects. Enabling this behavior for various types is left to future PRs.
For comparison, consider MatrixGate:
```
a, b, c = cirq.LineQubit.range(3)
op = cirq.MatrixGate(some_big_matrix)
circuit = cirq.Circuit(op.on(a), op.on(b), op.on(c))
cirq.to_json(circuit)
```
Without concise serialization for MatrixGate:
<details>
```
{
"cirq_type": "Circuit",
"moments": [
{
"cirq_type": "GateOperation",
"gate": {
"cirq_type": "MatrixGate",
"matrix": some_big_matrix
}
"qubits": a
}
{
"cirq_type": "GateOperation",
"gate": {
"cirq_type": "MatrixGate",
"matrix": some_big_matrix
}
"qubits": b
}
{
"cirq_type": "GateOperation", …
```
=> Add concise serialization tools.

cirq/google/engine/engine_program.py, cirq/google/engine/engine_test.py
- No longer needed by validation and is meaningless.
=> Remove repetition number in calibration calls

check/format-incremental, cirq/ops/common_gates_test.py, cirq/ops/global_phase_op_test.py, cirq/ops/measurement_gate.py, cirq/ops/measurement_gate_test.py, cirq/sim/clifford/act_on_stabilizer_ch_form_args.py, cirq/sim/clifford/act_on_stabilizer_ch_form_args_test.py, cirq/sim/clifford/clifford_simulator.py, cirq/sim/clifford/stabilizer_state_ch_form.py, cirq/testing/consistent_act_on.py
=> Add measurement support to `ActOnStabilizerChFormArgs` and use it in `MeasurementGate`

cirq/experiments/fidelity_estimation.py
There is a small typo in cirq/experiments/fidelity_estimation.py.
Should read `significant` rather than `sigificant`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, sigificant -> significant

cirq/ops/common_channels.py, cirq/ops/common_channels_test.py, cirq/ops/swap_gates.py, cirq/sim/clifford/clifford_simulator.py, cirq/sim/clifford/clifford_simulator_test.py, cirq/testing/consistent_act_on.py
- Just call `act_on` instead of doing type inspection in CliffordSimulator's _base_iterator
- Add ActOnStabilizerCHFormArgs case to ResetChannel
- Add ActOnStabilizerCHFormArgs case to SwapPowGate
- Remove unit test asserting swap gate doesn't work (!)
=> Fix SWAP and ResetChannel not working with CliffordSimulator

cirq/sim/clifford/clifford_simulator.py, cirq/sim/clifford/clifford_simulator_test.py
During the (ongoing) review of #3630 95-martin-orion@ found a bug in my draft code. He said that I should copy state like in #3109. I changed my code and added a test in that PR.
However, I had inspired myself from the Clifford code which could have the same issue (I think), and so I am fixing the code in the present PR.
=> Copy states in Clifford simulator

cirq/sim/mps_simulator.py, cirq/sim/mps_simulator_test.py
My unit testing didn't test the case when the order of qubits is inverted. I added a test and this causes an error that this PRs attempts to fix.
The error isn't too bad I think, because I had added some asserts (so no bad results), but it should be fixed nonetheless. I apologize for this mistake.
=> Fix assumption about order in MPSSimulator

cirq/sim/clifford/clifford_tableau.py, cirq/sim/clifford/stabilizer_state_ch_form.py
Not doing this caused an issue where the JSON was parsed without issue but when using the object, certain methods would break since they expected an np.array and got a list.
Example: https://github.com/quantumlib/Cirq/pull/3645#discussion_r557795288
Dynamic typing strikes again!
=> Wrap input json_dict entries in np.array to avoid wrong type deduction

cirq/sim/clifford/stabilizer_state_ch_form.py
As pointed out in https://github.com/quantumlib/Cirq/pull/3679#discussion_r558495240
=> Remove extraneous copies in StabilizerStateChForm JSON parsing

cirq/experiments/random_quantum_circuit_generation.py, cirq/work/observable_measurement_data.py, cirq/work/observable_measurement_data_test.py
This is part 3.5 or 4.5 of #2781 
It comes either before or after #3647 
This extends the vanilla `BitstringAccumulator` to handle readout calibrations which can be used to correct observables and mitigate the effect of readout error. However, users should probably never use this functionality directly; instead passing the appropriate configuration options to the functions defined in #3647. It would make git dependencies if this is merged first.
More sophisticated readout mitigation schemes would be implemented by subclassing `BitstringAccumulator`. Subclasses would (1) modify the constructor to accept the relevant calibration info, if different than this simple scheme and (2) modify the `mean()` and `variance()` functions to correct those quantities using the new scheme.
=> Observable Measurement - 3.5 - Readout Correction

cirq/circuits/circuit.py, cirq/circuits/circuit_operation_test.py, cirq/circuits/circuit_test.py
Exactly what it says in the title. This is the "any" analog to `Circuit.are_all_matches_terminal()`; it will be used for the expectation value API ([RFC](https://tinyurl.com/cirq-expectation-value-api)).
=> Add Circuit.are_any_matches_terminal()

cirq/google/api/v2/results.py, cirq/google/api/v2/results_test.py
- When we call cirq.google.api.v2.find_measurements, we need a way
to retrieve tags that were originally on the circuit.
- This adds tags to the NamedTuple that is returned by this function
that includes tags.
This does change the output of this function, but, since it is an
additive change, it should be minimally breaking.
=> Add tags to MeasureInfo

.github/workflows/ci.yml, dev_tools/conf/pip-install-minimal-for-pytest-changed-files.sh
Fixes https://github.com/quantumlib/Cirq/issues/3702. 
This is urgent as it blocks PRs.
=> Pin codeowners to 0.1.2

cirq/google/ops/calibration_tag.py, cirq/google/ops/calibration_tag_test.py, cirq/google/ops/physical_z_tag.py, cirq/google/ops/physical_z_tag_test.py
- By mypy definitions, tags should be hashable.
- Add __hash__ fucntions so they actually are hashable.
=> Add hash values to tags in cirq.google

docs/_book.yaml
Index does not match content on tutorials page. This fixes that. I haven't worked the examples myself, so whether this is the correct fix or whether the content should be changed to match the index, is beyond my ability to judge.
=> Fix: tutorial index headings do not match tutorial content page

.zenodo.json, README.rst
Updated zenodo metadata to reflect Cirq Developers as the authors. I also updated the latest versions on Zenodo too accordingly. I also removed the bibtex from the readme as it was incorrect - it is simplest to rely on the zenodo link for the different formats.
Fixes #3490.
=> update the zenodo metadata + removing confusing bibtex

dev_tools/auto_merge.py
Reverts quantumlib/Cirq#3762
We have to do more testing on this (maybe write actual tests for automerge!)
Currently automerge is down because of this: 
```
File "dev_tools/auto_merge.py", line 937, in <module> main() File "dev_tools/auto_merge.py", line 919, in main response = client.access_secret_version(request={"name": secret_version_name}) TypeError: access_secret_version() got an unexpected keyword argument 'request'
```
=> Revert "Updated secretmanager ref to v1"

dev_tools/notebooks/isolated_notebook_test.py, docs/qcvv/isolated_xeb.ipynb, docs/qcvv/parallel_xeb.ipynb, docs/qcvv/xeb_coherent_noise.ipynb, docs/qcvv/xeb_theory.ipynb
Also moved them to the qcvv folder. 
They were failing on the devsite pipeline, this fixes them.
=> adding standard header to characterization notebooks

cirq/experiments/qubit_characterizations.py, cirq/linalg/decompositions.py, cirq/testing/random_circuit.py
These are failing on older envs, so adding them here for now. 
1. importing mpl_toolkits plot3d: Old matplotlib versions cause failures: `ValueError: Unknown projection '3d'`
2. older numpy versions didn't have `random()` on `RandomState` only `rand()`, otherwise the failure is: `AttributeError: 'mtrand.RandomState' object has no attribute 'random'`
=> Fixes for older envs

cirq/experiments/xeb_fitting.py, cirq/experiments/xeb_fitting_test.py, docs/qcvv/isolated_xeb.ipynb, docs/qcvv/parallel_xeb.ipynb, docs/qcvv/xeb_coherent_noise.ipynb
We don't provide sensible defaults for anything other than sqrt(iswap) but with these changes, you can write your own XEBCalibrationOptions subclass to characterize whatever you want.
=> [XEB] Enable characterizing other gates

cirq/sim/sparse_simulator.py
The `perform_measurements` argument of private method `Simulator._base_iterator` defaults to True (yes, perform the measurements please), and is only set to False in one place: when iterating the unitary prefix of the circuit. However, this prefix will never have a measurement anyway by definition, so setting this argument here has no effect on the iteration of the unitary prefix. Thus this argument and the conditional around it is unnecessary and can be removed. This PR removes it.
=> Remove unused perform_measurements argument from sparse simulator

dev_tools/conf/pip-list-dev-tools.txt, dev_tools/packaging/verify-published-package.sh, setup.py
- Updates pytest version because existing version has a bug where --ignore= doesn't work. 
- Fixed verify-published-package script to install pip dev dependencies. 
- Updated setup.py to include `cirq.google.json_test_data`
=> Fix release scripts

cirq/google/engine/calibration.py, cirq/google/engine/calibration_test.py, cirq/vis/heatmap.py, cirq/vis/heatmap_test.py
- Adds a default title in calibration heatmaps.
- Return self from update_config to support chaining of operations. Eg: heatmap.update_config(title='a').plot()
=> Minor improvements in calibration heatmap api

dev_tools/conf/pip-list-dev-tools.txt
Narrows qiskit dependency for dev tools. 
We don't need the whole qiskit suite for testing, quiskit-aer (and terra transitively) is sufficient.
=> narrow qiskit dependency

cirq/circuits/circuit.py
Since `Operation` provides a canonical way to get the untagged version of itself, we should use it instead of writing a new method to do the same thing.
Using `op.untagged` in #3634 removes any residual blocking effects from #3678, although I'm still in favor of finding a proper resolution to #3678.
=> Replace _get_op_circuit with op.untagged

docs/tutorials/google/floquet.ipynb
I moved the tutorial in #3826 but forgot to update the header links, so they're currently broken on the site. This fixes it.
=> [Docs] Fix links in Floquet tutorial

cirq/_compat.py, cirq/_compat_test.py, cirq/protocols/json_serialization_test.py, cirq/testing/deprecation.py, cirq/testing/deprecation_test.py
Deprecates the `allow_multiple_warnings` parameter for explicit `count`. 
Context: this is split out from https://github.com/quantumlib/Cirq/pull/3917.
===== Release note ======
- `cirq.testing.assert_deprecate` parameter `allow_multiple_warnings` is now deprecated and will be removed in Cirq v0.12. Please use instead `count`. For `allow_multiple_warnings` `True`, you can just use `count=None`, for `False`, `count=1` which is the default value.
======================
=> assert_deprecated improvements

cirq/testing/deprecation.py, cirq/testing/logs.py, cirq/testing/logs_test.py
Renames cirq.testing.assert_logs parameter `level` -> `min_level` and adds a new parameter `max_level`. 
This is to enable more sophisticated logs assertions based on multiple levels.
===== Release note ======
- `cirq.testing.assert_logs` parameter `level` is now deprecated and will be removed in Cirq v0.12. Please use instead `min_level`.
======================
=> Make assert_logs levels interval based

cirq/ops/diagonal_gate.py, cirq/ops/two_qubit_diagonal_gate.py, cirq/protocols/resolve_parameters.py
Fixes #3390
Only had to modify a couple of places where mypy complained about types in `DiagonalGate` and `TwoQubitDiagonalGate`, which accepted `List` but stored a tuple internally. Also had to add a couple of casts in `resolve_parameters`, but I've tried to document what's going on there.
=> Change type signature of cirq.resolve_parameters to preserve types

cirq/__init__.py, cirq/sim/__init__.py
I forgot to make the `SimulatesExpectationValues` interface visible at the top level of Cirq :(
You can still use this type in Cirq v0.10, but it must be referenced as `cirq.sim.simulator.SimulatesExpectationValues`.
=> Make SimulatesExpectationValues public

cirq/contrib/quimb/mps_simulator.py
These give me type errors when running mypy locally. It seems to happen on intermittently, for reasons I haven't full understood, but in any event it seems better to just simplify them since these refer to types defined in the same module.
=> Simplify type annotations in mps_simulator.py

cirq/_compat.py, cirq/_compat_test.py
Adds `__dict__` to the wrapped module to ensure its member attributes stay on it.
=> Fix a bug in module deprecator

.git-blame-ignore-revs, docs/dev/development.md
Adds git-blame-ignore-rev and instructions.
This sets up git blame, PyCharm and other clients that integrate with git well to ignore large scale refactoring revisions. Note that unfortunately this is not yet supported by Github (https://github.community/t/support-ignore-revs-file-in-githubs-blame-view/3256/21).
=> Adds git-blame-ignore-rev and instructions

cirq/__init__.py, cirq/google/engine/calibration.py, cirq/google/engine/calibration_test.py, cirq/vis/__init__.py, cirq/vis/histogram.py, cirq/vis/histogram_test.py
This PR adds integrated histogram visualizations support to Cirq. Closes #3941
See https://tinyurl.com/cirq-visualizations for the larger roadmap item. 
**Usage:**
- `calibration.plot('single_qubit_errors')` now produces the following image: 
**Next steps**
- The `visualizing_calibration_metrics` tutorial will be updated in a follow up PR once this is checked in.
=> Add integrated histogram visualizations

cirq/_compat_test.py
Adds support for pytest.skip() in subprocess tests in _compat_test.py.
Also adding a conditional skip for the g3 env, where importlib_metadata doesn't exist. 
Note: while using strings might seem wonky, pickling exceptions to get over the subprocess boundary is a bit more complicated - especially for pytest's internal types over which we don't have too much control.
=> support pytest.skip() in subprocess tests in _compat_test.py

.github/workflows/release-master.yml
Filter pre-release job to only run in the main repo (quantumlib/Cirq). 
This avoids noise in forks who use the master branch.
=> filter pre-release job for only main repo

cirq/_compat.py, cirq/_compat_test.py
For old type (g3) module loaders, the resolution wasn't working, breaking internal par tests. 
This makes `DeprecatedModuleLoader.load_module` work similarly to `exec_module` that it ensures that when the old module is loaded, both the new and old names are pointing to the same module in the module cache.
cc @cduck - this should be straightforward. The reason it didn't come up earlier, as I haven't tested on g3 since my change in https://github.com/quantumlib/Cirq/pull/3917#discussion_r597349479 - I think that more principled rewiring surfaced this bug :)
=> Fix load_module wrapping

check/format-incremental, cirq/ops/pauli_string.py
Changes the remaining format string to `f-string` using Flynt:
```
$ pip install flynt
$ flynt .
```
Fixes #3804.
=> Change the remaining format string to f-string

cirq/circuits/circuit_operation.py, cirq/circuits/circuit_operation_test.py
=> Disallow qubit_map with conflicting dimensions in subcircuits

cirq/ops/parity_gates.py
=> Update `XXPowGate` docstring to fix href to `MSGate`

cirq/google/optimizers/optimize_for_sycamore_test.py, cirq/optimizers/drop_negligible.py
Fixes #3732
This is a simple approach to fixing `optimized_for_sycamore`, which currently barfs on large measurement gates when `DropNegligible` tries to compute their trace distance bound. There may be other approaches that are more general, but as @mpharrigan said it's somewhat embarrassing that this doesn't work currently, so I think a quick fix is warranted and we can generalize later.
=> Skip measurement gates in DropNegligible optimizer

cirq/ops/common_channels.py, cirq/ops/controlled_operation.py, cirq/ops/dense_pauli_string.py, cirq/ops/diagonal_gate.py, cirq/ops/eigen_gate.py, cirq/ops/identity.py, cirq/ops/pauli_interaction_gate.py, cirq/ops/pauli_sum_exponential.py, cirq/ops/phased_x_z_gate.py, cirq/ops/raw_types.py, cirq/ops/two_qubit_diagonal_gate.py, cirq/qis/states.py
Using `check/mypy --next | grep cirq/ops` this fixes almost all of the issues raised with simple modifications.
There is a looming problem with places where we use `numbers.Complex`, which is a nice generalization for Union[int, float, complex] but does not play nice with numpy type information.
Towards #3767
=> Fix most numpy type errors in cirq/ops

cirq/interop/quirk/cells/parse.py, cirq/qis/measures.py, cirq/qis/states.py, cirq/qis/states_test.py, cirq/sim/density_matrix_simulator.py, cirq/study/result.py, cirq/testing/consistent_qasm.py, cirq/value/product_state.py, cirq/vis/vis_utils.py
=> Fix most numpy errors in cirq/qis and friends

cirq/linalg/combinators.py, cirq/linalg/decompositions.py, cirq/linalg/decompositions_test.py, cirq/linalg/diagonalize.py, cirq/linalg/diagonalize_test.py, cirq/linalg/operator_spaces.py, cirq/linalg/predicates.py, cirq/linalg/tolerance.py, cirq/linalg/transformations.py
Using `check/mypy --next | grep cirq/linalg` this fixes all the
problems.
#3767
=> Fix most numpy type errors in cirq/linalg

cirq/ops/common_channels.py
In commit fa995853b6902eaa48afe6eab1058f9e9bae2ef6 the formula for `DepolarizingChannel` got changed, and I'm pretty sure it should be ` p / (4**n - 1) \sum _i P_i \rho P_i` instead, given that's what the ` AsymmetricDepolarizingChannel` does.
=> Fix DepolarizingChannel documentation

dev_tools/notebooks/__init__.py, dev_tools/notebooks/isolated_notebook_test.py, dev_tools/notebooks/notebook_test.py, dev_tools/notebooks/utils.py
Fixes https://github.com/quantumlib/Cirq/issues/4012 which was caused by https://github.com/networkx/networkx/issues/4718. 
Also ensures that isolated notebook test runs for all notebooks (not just changed ones) if the test itself changes.
=> fix networkx / decorator dependency issue

cirq-core/setup.py, cirq-google/cirq_google/py.typed, cirq-google/setup.py
These are needed to enable type-checking for users who install cirq-core and cirq-google.
=> Include py.typed files in cirq-core and cirq-google

cirq-google/cirq_google/_version.py, dev_tools/version_test.py
Fixes a bug in the version test and the actual _version.py for cirq-google.
=> fix versioning of new modules

dev_tools/notebooks/isolated_notebook_test.py, docs/qcvv/xeb_coherent_noise.ipynb, docs/qcvv/xeb_theory.ipynb, docs/tutorials/google/floquet.ipynb
Makes notebooks using cirq_google install pre-release cirq. 
These notebooks were failing in the devsite pipeline as they were just installing cirq, not `cirq --pre`.
=> Fix cirq_google notebooks

check/pytest-and-incremental-coverage, dev_tools/bash_scripts_test.py
Ensures that `pytest-and-incremental-coverage` runs all code in the repo.
Code lines outside of cirq-google and cirq-core were not tested, so coverage check was failing. See https://github.com/quantumlib/Cirq/runs/2387098464 as an example that modifies the examples directory.
=> Fix omitted coverage

dev_tools/bash_scripts_test.py
Re-adding the mistakenly removed fix for a mypy error. 
Thanks for noticing @mpharrigan https://github.com/quantumlib/Cirq/commit/fd257e6c228a0b4c8839ad6ac3d30467476f195e#r49819445
=> fix bad import

cirq-core/cirq/ionq/service.py, cirq-core/cirq/ionq/service_test.py, docs/ionq/access.md, docs/ionq/service.md, docs/tutorials/ionq/getting_started.ipynb
The remote host is now public information, so setting the default to be this url.  
Also updates the documentation around this.
=> Set default remote host for IonQ API

check/pylint, cirq-google/cirq_google/calibration/engine_simulator.py, dev_tools/conf/.pylintrc
Fixes three things: 
* check/pylint was pointing to the wrong folders (platform -> cirq-google/cirq_google)
* pylint (and the underlying isort) needs to know about cirq_google and cirq as not third_party libraries for import sorting to work properly
* there was an unused import in cirq_google that is now removed
=> pylint recognizes cirq_google as known third_party

docs/google/calibration.md
- Updating documentation on parallel readout errors
to clarify the methodology of sampling many different input
bitstrings and measuring appropriately.
- Documentation content provided by bfoxen@.
=> Update documentation on parallel readout errors

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py
- The docstring was still talking about the arg that was removed months ago
- FIRST alignment is useful when performing bulk operations
=> Fix tetris_concat docstring align arg and restore FIRST alignment option

check/misc
Fixes an error message from grep. Before:
```
$ ./check/all
Running misc
grep: cirq: No such file or directory
No issues.
Running pylint
...
```
After:
```
$ ./check/all
Running misc
No issues.
Running pylint
...
```
=> Fix pathname in misc check tool

cirq-core/cirq/__init__.py, cirq-core/cirq/qis/__init__.py, cirq-core/cirq/qis/channels.py, cirq-core/cirq/qis/channels_test.py
This implements a simple utility for computing the Choi matrix of a channel from its Kraus representation.
Choi representation is more compact than Kraus representations and - unlike the Kraus representation - it is unique for every channel, so we can use this to e.g. compare channels.
The PR is a small step towards #3248. In particular, it does not introduce any new protocols. As discussed on the issue, we might at some point want a protocol to enable channel classes to implement something like `__choi__` if there are cases where folks would prefer to specify channels using their Choi matrix rather than the Kraus operators. If we end up doing this, I suppose the protocol will use the utility in this PR to handle channels that provide Kraus operators.
=> Choi representation

README.rst
The reStructured Text parameters for image directives are indented inconsistently in README.rst. All directives (`image` and `code-block`) aside from two cases have indentation of two spaces. The inconsistent cases currently have four spaces. This PR applies consistent two space indentation.
=> Consistent parameter indentation in README.rst

cirq-core/setup.py
cirq-core/setup.py was referring to the old version of contrib requirements.
This currently causes the cirq pre-release job to fail. 
Fixes https://github.com/quantumlib/Cirq/issues/4154.
=> Fix contrib-requirements

cirq-core/cirq/__init__.py, cirq-core/cirq/qis/__init__.py, cirq-core/cirq/qis/measures.py, cirq-core/cirq/qis/measures_test.py
This computes entanglement fidelity of a channel directly from its Kraus representation.
=> Entanglement fidelity of a quantum channel

.github/workflows/ci.yml, dev_tools/notebooks/isolated_notebook_test.py
Adds sharding for isolated notebook tests.
These tests only test notebooks against the stable cirq releases. Hence they depend on 4 things: stable cirq release (which does not change), the notebooks, the dev environment and the notebook test itself. 
In case the dev environment changes we want to run all the notebooks to ensure everything is still running. However this can take a long time and has been causing issues already on PRs causing timeout in Github Actions. 
Sharding the tests to 4 partitions avoids the timeout. This PR also adds the ability to easily modify the number of partitions from the ci.yml directly.
Fixes #4190.
=> Shard isolated notebook tests

docs/qcvv/parallel_xeb.ipynb
=> Add two-qubit interaction heatmap to parallel xeb tutorial

docs/_book.yaml
Adding cirq_aqt reference API while it doesn't exist broke the devsite publishing, so removing it for now, we'll have to add it after the release of v0.12.
=> fix aqt ref in book.yaml

cirq-core/cirq/optimizers/eject_phased_paulis.py, cirq-core/cirq/optimizers/eject_phased_paulis_test.py
Fixes #4218 and adds a test for the previously failing case.
The code treated the half-turns (exponent) value as whole-turns so both X**1 and X**0 were treated as whole X gates.
=> Fix EjectPhasedPaulis incorrectly treating X**0 as X**1

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/protocols/circuit_diagram_info_protocol.py, cirq-core/cirq/testing/circuit_compare.py
Also fix a couple testing assert methods not hiding themselves from the traceback.
This can change the diagrams of existing circuits, which will potentially break some downstream tests that assert the diagrams are something specific. However, I think having the information missing from the diagrams was more problematic.
Fixes https://github.com/quantumlib/Cirq/issues/4232
Fixes https://github.com/quantumlib/Cirq/issues/4233
=> Draw zero-target operations below circuit text diagrams as annotations

.github/workflows/ci.yml, MANIFEST.in, dev_tools/modules.py, dev_tools/modules_test.py, dev_tools/packaging/packaging_test.sh, dev_tools/requirements/deps/dev-tools.txt, dev_tools/requirements/deps/packaging.txt, dev_tools/requirements/deps/tensorflow-docs.txt, setup.py
The tensorflow-docs requirement was in the wrong format (worked for pip install but not for extras_require).
It also adds testing to avoid these kind of failures: `dev_tools/packaging/packaging_test.sh` is now executed as part of the CI test suite.
Fixes #4222.
=> Fix extras_require for the cirq metapackage setup.py

.github/workflows/ci.yml, .github/workflows/release-master.yml
resolves #4191 
@balopat was this what you had in mind when opening the linked issue?
=> update python version to 3.8

cirq-core/cirq/ops/moment.py, cirq-core/cirq/ops/moment_test.py
This also enables other protocols on Moment, such as the measurement keys protocol, which currently does not work.
=> Support decompose protocol on `cirq.Moment`

setup.py
Removes direct URL requirements from cirq[dev-env].
Fixes #4222.
This is hard to test automatically as it would need to involve uploading to test pypi which in turn requires secrets on Github Actions (see https://github.com/quantumlib/Cirq/pull/4247).
=> Removes direct URL requirements from cirq[dev-env]

cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/gate_operation_test.py
=> Propagate _channel_ from GateOperation to its Gate

docs/support.md
The TFQ link was pointing to OpenFermion, oops. Also changes all links to land on the /about page which gives more details.
=> [Docs] Fix dev group link on support page

cirq-core/cirq/ion/ion_device.py, cirq-core/cirq/ion/ion_device_test.py
Removes `cirq.IonDevice.can_add_operation_into_moment` as it doesn't add any value. 
I noticed that `cirq.IonDevice.can_add_operation_into_moment` implementation was doing a complicated version of a simple qubit overlap testing.
=> Remove cirq.IonDevice.can_add_operation_into_moment

cirq-core/cirq/optimizers/merge_interactions.py, cirq-core/cirq/optimizers/merge_interactions_test.py
Fixes #4287.
`MergeInteractions` skips merging CZ gates if there are already equal or fewer in a sequence than the synthesized result (to prevent increasing the gate count).  Previously, a tagged partial CZ gate could slip through and not be optimized even if `allow_partial_czs=False`.
=> Fix behavior of MergeInteractions for tagged partial CZ gates

cirq-core/cirq/__init__.py, cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/optimizers/__init__.py, cirq-core/cirq/optimizers/merge_interactions.py, cirq-core/cirq/optimizers/merge_interactions_test.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap_test.py, cirq-core/cirq/protocols/json_test_data/spec.py
Follow up to #4213.  Fixes #4083.  (Also contains a one-line change to fix #4225.)
I'm open to name suggestions for `MergeInteractionsToSqrtIswap`.
=> Add Circuit Optimizer for sqrt-iSWAP

.github/workflows/ci.yml, cirq-core/cirq/contrib/requirements.txt
Adds py39 to windows, mac and linux pytest matrices.
Fixes #3772 
Fixes #3769
=> Add py39 testing to CI test matrix.

dev_tools/auto_merge.py
=> Fix automerge checks

cirq-core/cirq/ops/common_channels.py, cirq-core/cirq/ops/gate_features.py, cirq-core/cirq/ops/gate_features_test.py, cirq-core/cirq/ops/identity.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py
Part of #4034. (See https://github.com/quantumlib/Cirq/issues/4034#issuecomment-832913708), moves the on_each functionality to cirq.Gate, and deprecates SupportsOnEachGate.
Note the tests that are deleted here had already been duplicated in raw_types_test.py by https://github.com/quantumlib/Cirq/pull/4281/files.
=> Move on_each to Gate, and deprecate SupportsOnEachGate

cirq-google/cirq_google/serializable_gate_set_test.py
Fixes #4304.
To be precise, this was already working: because the deserializer does not append constants to the `deserialized_constants` map until it finishes deserializing them, it is naturally unable to deserialize a recursive subcircuit. This PR just adds the test.
Note that the _serializer_ will still happily attempt (and fail) to serialize CircuitOperations that exhibit infinite recursion. We allow this because `CircuitOperation` is an immutable type; unless you intentionally circumvent the safeguards that prevent mutation (as shown in the test), it is not possible to define a `CircuitOperation` that contains itself.
=> Test deserializer on infinite recursion.

docs/tutorials/google/visualizing_calibration_metrics.ipynb
`cirq_google` is used to get calibrations in line 181 but never imported, leading to `NameError: name cirq_google is not defined` (189945709).
=> Fix `NameError` in visualizing calibration metrics tutorial

cirq-core/cirq/work/pauli_sum_collector.py, cirq-core/cirq/work/pauli_sum_collector_test.py
For chemistry hamiltonians generated via `openfermion.qubit_operator_to_pauli_sum(qubit_hamiltonian)`, even though the pauli sum has only real terms (complex with imag == 0), using `p.estimated_energy()` returns a complex (with imag  == 0) and hence cannot be directly used with scipy optimizers which expect a flaot (eg: `Nelder-Mead`, `SLSQP` etc.)
See https://github.com/quantumlib/OpenFermion/issues/732 for an example.
=> pauli_sum_collector.estimate_energy() should return float when energy.imag == 0

docs/tutorials/google/floquet_calibration_example.ipynb
The Floquet calibration notebook's connection to our research needed more explanation. There is connection to both the quantum ring paper and the Fermi Hubbard paper. I also explained the motivation behind using segments on the line and added a quirk circuit to demonstrate the evolution of the charge density on a 5 qubit segment.
=> Fix citation and explanation in Floquet calibration example

cirq-google/cirq_google/calibration/workflow.py, cirq-google/cirq_google/calibration/workflow_test.py
This change allows to mix single-qubit and two-qubit operations during calibration. This might be especially useful for creating circuits with spin-echo for example.
=> Complete implementation of the permit_mixed_moments option

cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py, cirq-google/cirq_google/optimizers/convert_to_sycamore_gates_test.py, docs/google/best_practices.md, docs/google/devices.md
_EDIT: This description is outdated - see discussion below for details._
This PR enables serialization of `CircuitOperation`s in the default serializers. Additional changes to make this work smoothly:
* Added `preserve_structure=True` to the Sycamore optimizer. This ensures that the contents of `CircuitOperation`s are converted to a Sycamore-friendly format, but the `CircuitOperation` itself is preserved.
* Updated `cirq.decompose` to support intercepting decomposers alongside `preserve_structure=True`, and removed redundant overloads.
* Documented usage of subcircuits in the context of reducing serialization size of circuits.
#3634 is mostly resolved by this issue, although further optimizations remain possible.
=> Allow CircuitOperations in cirq.optimized_for_sycamore

cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py, cirq-google/cirq_google/optimizers/convert_to_sycamore_gates_test.py, docs/google/best_practices.md, docs/google/devices.md
Reverts #4336.
Enabling CircuitOp serialization is causing errors in QCS.
=> Revert "Allow CircuitOperations in cirq.optimized_for_sycamore"

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/experiments/fidelity_estimation.py, cirq-core/cirq/experiments/fidelity_estimation_test.py, cirq-core/cirq/interop/quirk/cells/input_rotation_cells.py, cirq-core/cirq/ops/arithmetic_operation.py, cirq-core/cirq/ops/controlled_operation.py, cirq-core/cirq/ops/fourier_transform.py, cirq-core/cirq/ops/identity.py, cirq-core/cirq/ops/matrix_gates.py, cirq-core/cirq/ops/measurement_gate.py, cirq-core/cirq/ops/projector.py, cirq-core/cirq/ops/random_gate_channel.py, cirq-core/cirq/ops/random_gate_channel_test.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/unitary_protocol.py, cirq-core/cirq/qis/channels.py, cirq-core/cirq/qis/measures.py, cirq-core/cirq/qis/states.py, cirq-core/cirq/sim/density_matrix_simulator.py, cirq-core/cirq/sim/density_matrix_utils.py, cirq-core/cirq/sim/sparse_simulator.py, cirq-core/cirq/sim/state_vector.py, cirq-core/cirq/testing/circuit_compare.py
Fixes #4346 .
Liberally upgraded a lot of the calls to `np.prod` to use ~~`dtype=int`~~ `dtype=np.int64` that didn't already have it. I opted to keep the calls to `np.prod` instead of doing something like `reduce(mul, <stuff>)` because using basic numpy, we can only really comfortably create and index arrays with sizes up to the max value of a C type `long`.
~~Confirmed `dtype=int` will give us that:~~
~~https://numpy.org/doc/stable/reference/arrays.dtypes.html#specifying-and-constructing-data-types~~
~~https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.int_~~
=> Updated calls to np.prod to use dtype=np.int64.

cirq-core/cirq/__init__.py, cirq-core/cirq/linalg/__init__.py, cirq-core/cirq/linalg/predicates.py, cirq-core/cirq/linalg/predicates_test.py
As requested in #4194. Can be used for #2271.
This predicate is meant to be invoked when constructing a channel to verify that the provided Kraus operators actually describe a valid quantum channel. Recommendations for cleaner `is_cptp` behavior or additional test cases are welcome.
=> Add is_cptp predicate

docs/noise.ipynb
Fix notebook, this is failing in the site import pipeline.
=> Add missing `import cirq`

cirq-core/cirq/ops/boolean_hamiltonian.py, cirq-core/cirq/ops/boolean_hamiltonian_test.py
The current code at head does not implement BooleanHamiltonian.with_qubits() correctly. It assumes that the qubits are named and then maps them to the variable name.
This is restrictive, does not follow the other classes' with_qubits(). It is also incorrect because it silently accepts a list of qubits with missing entries (e.g. there is a variable name 'a' but we don't provide a qubit named 'a'), and the error is thrown only when decompose_once() is called.
Instead, here the code accepts a list of qubits and replaces them in the map. It requires that there are as many qubits provided as there were when building the object. Also, it relies on the order of the qubit keys when building the BooleanHamiltonian object, but that is currently a restriction of the API.
Fixes #4390.
=> Fix BooleanHamiltonian.with_qubits() to work with not only NamedQubits

cirq-aqt/cirq_aqt/json_resolver_cache.py, cirq-core/cirq/__init__.py, cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/protocols/json_serialization.py, cirq-core/cirq/protocols/json_serialization_test.py, cirq-google/cirq_google/__init__.py, cirq-google/cirq_google/json_resolver_cache.py, cirq-ionq/cirq_ionq/json_resolver_cache.py, cirq-pasqal/cirq_pasqal/__init__.py, cirq-pasqal/cirq_pasqal/json_resolver_cache.py, cirq-rigetti/cirq_rigetti/json_resolver_cache.py, docs/_book.yaml, docs/dev/modules.md, docs/dev/serialization.md
Adds docs for modules and updates the JSON serialization documentation.
Also removes the need for modifying the `imports` dict in the repr eval test, instead it automates the creation of it.
Hat tip to @erichulburd for starting the new version of the JSON serialization docs in https://github.com/quantumlib/Cirq/pull/4378/files. 
Fixes #4376.
=> update json serialization docs + add module docs

dev_tools/docs/Dockerfile, dev_tools/docs/build_api_docs.py, docs/_book.yaml
Add new cirq modules to `_book.yaml`, and `cirq_pasqal`, `cirq_web` to the reference doc generation.
This is one of the post v0.12 release cleanup activities.
=> Add modules to book yaml

cirq-core/cirq/experiments/random_quantum_circuit_generation.py
=> Revert "Improve speed of random circuit generation"

cirq-core/cirq/__init__.py, cirq-core/cirq/protocols/json_test_data/spec.py
Fixes: https://github.com/quantumlib/Cirq/issues/4425
=> Add `SupportsKraus` to `cirq/__init__.py`

cirq-core/cirq/protocols/json_test_data/MeasurementKey.repr, cirq-core/cirq/value/measurement_key.py, cirq-core/cirq/value/measurement_key_test.py
=> Fix MeasurementKey repr s.t. `eval(repr(k)) == k`

cirq-core/cirq/contrib/acquaintance/gates_test.py, dev_tools/conf/mypy.ini
Fixes: https://github.com/quantumlib/Cirq/issues/4448
=> Replace `from numpy.random import poisson` with `import numpy as np` in `cirq-core/cirq/contrib/acquaintance/gates_test.py`

cirq-core/cirq/ops/pauli_string.py, cirq-core/cirq/ops/pauli_string_test.py
Fixes #4270
Note that the fix relies on the fact that python dicts maintain insertion order from python 3.6+ [[link](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6)]
=> Do not sort qubits by default in pauli_string to fix inconsistencies with pauli_string.gate

cirq-core/cirq/contrib/acquaintance/gates_test.py
Fixes mypy's complaint:
```
$ ./check/mypy 
cirq-core/cirq/contrib/acquaintance/gates_test.py:20: error: Module 'numpy.random' has no attribute 'poisson'
Found 1 error in 1 file (checked 925 source files)
```
See the code snippet in [this document](https://numpy.org/doc/stable/reference/random/index.html#random-quick-start) for background on this change.
=> Fix reference to np.random.poisson

cirq-core/cirq/ops/linear_combinations.py, cirq-core/cirq/ops/linear_combinations_test.py, cirq-core/cirq/ops/projector.py
For issue #3288 I noticed that some code was missing when working on integrating with TFQ:
https://github.com/tensorflow/quantum/pull/623
=> Add missing code for ProjectorSum serialization in TFQ

cirq-core/cirq/__init__.py, cirq-core/cirq/experiments/xeb_fitting.py, cirq-core/cirq/protocols/__init__.py, cirq-core/cirq/protocols/json_serialization.py, cirq-core/cirq/protocols/json_serialization_test.py
Dataclasses keep track of their relevant fields, so we can automatically generate these.
Dataclasses are implemented with somewhat complex metaprogramming, and tooling (PyCharm, mypy)
have special cases for dealing with classes decorated with `@dataclass`. There is very little
support (and no plans for support) for decorators that wrap `@dataclass` (like
`@cirq.json_serializable_dataclass`) or combining additional decorators with `@dataclass`.
Although not as elegant, you may want to consider explicitly defining `_json_dict_` on your
dataclasses which simply `return dataclass_json_dict(self)`.
=> dataclass_json_dict

cirq-core/cirq/contrib/qasm_import/_parser.py, cirq-core/cirq/contrib/qasm_import/_parser_test.py
As requested in #3415.
Made changes in `_parser.py` and added `r` gate under. I have replicated the format of `u3` and set params to `QasmUGate` according to `r(theta, phi) = u3(theta, phi - pi/2, -phi + pi/2)`. 
Also wrote a test for the same.
=> Added r(theta, phi) gate

docs/tutorials/google/floquet_calibration_example.ipynb
https://quantumai.google/cirq/tutorials/google/floquet_calibration_example broke after #4286 (because it was missing a `--pre` flag).
Without the `--pre` flag this tutorial wouldn't pull in the latest changes and broke.
Added the `--pre` to fix this.
=> Fix broken Floquet tutorial

cirq-google/cirq_google/engine/qcs_notebook.py, cirq-google/cirq_google/engine/qcs_notebook_test.py, dev_tools/notebooks/isolated_notebook_test.py, docs/tutorials/google/calibration_api.ipynb, docs/tutorials/google/colab.ipynb, docs/tutorials/google/compare_to_calibration.ipynb, docs/tutorials/google/echoes.ipynb, docs/tutorials/google/floquet_calibration_example.ipynb, docs/tutorials/google/reservations.ipynb, docs/tutorials/google/spin_echoes.ipynb, docs/tutorials/google/start.ipynb, docs/tutorials/google/visualizing_calibration_metrics.ipynb, docs/tutorials/google/xeb_calibration_example.ipynb
#4286 introduced a new module (`qcs_notebook`) and utility method (`get_qcs_objects_for_notebook`) to abstract out boilerplate code for notebooks. 
However, all notebooks using the new method now depend on the pre-released version and should `pip install --pre cirq` instead of `pip install cirq` to work correctly. Right now, all these notebooks are broken and this PR fixes it. 
Note: In some notebooks, already existing `--pre` and `--quiet` is reordered because of recent tests which assert that pre released notebooks have the pip install statement: https://github.com/quantumlib/Cirq/blob/6ecaf0793c0d0865b09603e50fcfbc11ce567273/dev_tools/notebooks/isolated_notebook_test.py#L206 
Even though vendor notebooks (`"**/google/*.ipynb",`) are skipped from testing against cirq, I think it's good …
=> Fix broken tutorials depending on cirq pre-release

cirq-core/cirq/__init__.py, cirq-core/cirq/ops/__init__.py, cirq-core/cirq/ops/common_gate_families.py, cirq-core/cirq/ops/common_gate_families_test.py, cirq-core/cirq/protocols/json_test_data/spec.py
This PR introduces new common gate families which will be useful to adopt the usage of Gatesets across Cirq. This is split off the larger PR #4513 and follow up PRs will use these new gate families. 
Part of the roadmap item #3243
=> Add common gate families as part of adopting gatesets across Cirq. 

cirq-core/cirq/optimizers/convert_to_cz_and_single_gates.py, cirq-core/cirq/optimizers/merge_interactions.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap.py
This PR adopts the use of `cirq.Gateset` in cirq/optimizers/*. Part of the roadmap item #3243
=> Use Gatesets in cirq/optimizers/*

cirq-core/cirq/devices/named_topologies.py, cirq-core/cirq/devices/named_topologies_test.py
This little helper function makes explicit the conversion between topology graphs and line qubits. This is analogous to `TiltedSquareLattice.nodes_as_gridqubits()`
=> [Named Topologies] LineTopology nodes_as_linequbits

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py
It was erroneously removed in #4403 without deprecating.
Part of #4040.
=> Re-add `all_measurement_keys` and deprecate it

cirq-core/cirq/protocols/json_serialization.py
This change addresses issue #4453: `cirq.to_json` now accepts separators argument, which is forwarded to `json.dump` function.
=> Add separators argument to to_json function.

cirq-core/cirq/sim/clifford/clifford_simulator_test.py
This PR is a followup to Issue #4263 (@95-martin-orion). 
`test_clifford_circuit_3` in `Cirq/cirq-core/cirq/sim/clifford/clifford_simulator_test.py` also appears to be flaky when all seed-setting code is removed. In commit 8cef3d9dc16b27e3b10184e1b72afa764efe590d (version 0.11.0), `test_clifford_circuit_3` fails ~12% of the time (out of 500 runs) compared to 0% of the time (out of 500 runs) when no seed-setting code is removed.
One method of reducing the flakiness of tests is to adjust how strict the assertions are. We reduced the precision of the assertion in `test_clifford_circuit_3` from 7 decimal places (the default precision of `np.testing.assert_almost_equal`) to 6 decimal places. We also removed the seed-setting code (this will allow more paths of execution to be tested). 
We ran …
=> Fixed test_clifford_circuit_3

cirq-core/cirq/protocols/kraus_protocol.py, cirq-core/cirq/protocols/kraus_protocol_test.py
Fix ineffective test in kraus_protocol_test.py by replacing `np.allclose` with `np.testing.assert_equal`. Also, some minor naming improvements and updates.
=> Acctually assert in kraus_protocol_test.py

cirq-core/cirq/__init__.py, cirq-core/cirq/qis/__init__.py, cirq-core/cirq/qis/channels.py, cirq-core/cirq/qis/channels_test.py
The new `cirq.choi_to_kraus` function is like the existing `cirq.kraus_to_choi` but in the opposite direction.
Note that the former chooses one of many admissible Kraus representations while the latter maps all valid Kraus representations to the Choi. Therefore, `cirq.kraus_to_choi(cirq.choi_to_kraus(c)) == c`, but it is not necessarily the case that `cirq.choi_to_kraus(cirq.kraus_to_choi(ks)) == ks`. Check out [section and retraction](https://en.wikipedia.org/wiki/Section_(category_theory)) if you like this sort of thing.
Example future use-cases: channel comparisons, obtaining Kraus representation of a noisy circuit.
Some context: #3248.
=> Compute a Kraus representation from the Choi matrix

cirq-core/cirq/__init__.py, cirq-core/cirq/qis/__init__.py, cirq-core/cirq/qis/channels.py, cirq-core/cirq/qis/channels_test.py
After this PR one can convert between any two representations from among: Kraus, Choi and superoperator.
=> More channel representation conversion tools

cirq-core/cirq/ops/phased_x_z_gate.py, cirq-core/cirq/ops/phased_x_z_gate_test.py
=> Implement PhasedXZGate._unitary_

cirq-core/cirq/circuits/circuit_operation_test.py, cirq-core/cirq/sim/act_on_args_container_test.py, cirq-core/cirq/sim/clifford/clifford_simulator_test.py, cirq-core/cirq/sim/simulator_base_test.py, cirq-google/cirq_google/engine/engine_sampler.py
We have an ongoing issue about lint not being consistent.  I tried to track down what is occurring but did not find anything except some more missing lint.
Lint being silly is tracked in #3716
=> Fix lint errors

cirq-core/cirq/linalg/operator_spaces_test.py
See #4379 for failure which occurs only on some architectures.
=> Fix operator spaces test which fails due to precision 

cirq-core/cirq/_import.py
Fixes #4637 and also removes `ModuleType = Any` in `_import.py`.  This removal exposed some mislabeled types and some missing defense.
=> Fix importlib.abc and type madness in _import

cirq-google/cirq_google/serialization/circuit_serializer.py, cirq-google/cirq_google/serialization/circuit_serializer_test.py
- Conversion of float args changes 0.0 to a int of 0,
so this fails validation, since the current code
checks isinstance float.
- This PR adds ints to the type checking to fix this.
=> Fix FSim serialization for zeros and ints

docs/install.md
Very minor fix.  The install guide at https://quantumai.google/cirq/install has a validation step that references `cirq.google` which is a deprecated usage on new installs, example:
```
[amcnamara] > python -c 'import cirq; print(cirq.google.Foxtail)'
<string>:1: DeprecationWarning: cirq.google was used but is deprecated.
it will be removed in cirq v0.14.
Use cirq_google instead.
(0, 0)───(0, 1)───(0, 2)───(0, 3)───(0, 4)───(0, 5)───(0, 6)───(0, 7)───(0, 8)───(0, 9)───(0, 10)
│        │        │        │        │        │        │        │        │        │        │
│        │        │        │        │        │        │        │        │        │        │
(1, 0)───(1, 1)───(1, 2)───(1, 3)───(1, 4)───(1, 5)───(1, 6)───(1, 7)───(1, 8)───(1, 9)───(1, 10)
[amcnamara] > python -c 'import …
```
=> Remove deprecated use of `cirq.google` in install guide

cirq-core/cirq/experiments/t1_decay_experiment.py, cirq-core/cirq/experiments/xeb_fitting.py, cirq-core/cirq/linalg/decompositions.py, cirq-google/cirq_google/calibration/xeb_wrapper_test.py, dev_tools/packaging/isolated_packages_test.py, docs/tutorials/quantum_walks.ipynb
This speeds up top level import.
Note that we had previously done this for another use of scipy.stats, but this one got added.  Also doing it for scipy.optimize.  Both of these can slow down the resulting experiments, probably a case for moving experiments out of cirq-core?
=> Delay import of scipy stats and optimize

docs/dev/development.md, docs/dev/notebooks.md, docs/google/calibration.md, docs/google/devices.md, docs/google/engine.md, docs/google/specification.md, docs/install.md
Follow up from #4647 replacing the rest of the uses of `cirq.google` in the `docs`.
=> Remove remaining uses of cirq.google in docs/ .

cirq-core/cirq/ops/common_channels.py, cirq-core/cirq/ops/common_channels_test.py
`num_qubits` was mistakenly added as a property to AsymetricDepolarizingChannel See #4185
I don't believe there is an easy way to deprecate this because one cannot have both a property and a method on the class, the last one define is called.  
I propose that we just hard break this, but if someone has a better idea, I'm all ears.  I kept the code commented out in case someone goes looking for this, and we can remove this after v0.15.
#4215 which also fixes this seems to have stalled.
=> Fix num_qubits property on AsymetricDepolarizing Channel

cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py
Fixes #4655
This PR adds functionality to `_InverseCompositeGate` to forward requests like `resolve_parameters`, `is_parameterized` and `parameter_names` to the underlying `original_gate`.
=> Add parameter resolution and other utility methods to _InverseCompositeGate

dev_tools/requirements/deps/dev-tools.txt
On a clean install and older version of this was burping on parsing qasm.  This seems to fix it.
This is just for dev-tools which is what is recommended to install for developers.
=> Bump version of qiskit-aer in dev-tools

dev_tools/conf/apt-list-dev-tools.txt, docs/dev/development.md
We have docker tests and rigetti requires docker. This adds these to the dev apt-get list and explains that you need to install docker.
=> Add docker and docker compose to dev install

cirq-core/cirq/contrib/quimb/mps_simulator.py, cirq-core/cirq/contrib/quimb/mps_simulator_test.py, cirq-core/cirq/ion/ion_device.py, cirq-core/cirq/ion/ion_device_test.py, cirq-core/cirq/neutral_atoms/neutral_atom_devices.py, cirq-core/cirq/neutral_atoms/neutral_atom_devices_test.py, cirq-core/cirq/sim/clifford/clifford_simulator.py, cirq-core/cirq/sim/clifford/clifford_simulator_test.py, cirq-core/cirq/sim/density_matrix_simulator.py, cirq-core/cirq/sim/density_matrix_simulator_test.py, cirq-core/cirq/sim/state_vector_simulator.py, cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/deprecation.py, cirq-core/cirq/testing/repr_pertty_tester_test.py, cirq-core/cirq/testing/repr_pretty_tester.py, cirq-google/cirq_google/devices/xmon_device.py, cirq-google/cirq_google/devices/xmon_device_test.py
Implements `_repr_pretty_` which pretty prints in iPython (jupyter notebooks)
Addresses #682
=> Add pretty repr to devices and result types

cirq-core/cirq/contrib/quantum_volume/quantum_volume_test.py, cirq-core/cirq/sim/simulator.py, cirq-core/cirq/sim/simulator_test.py, cirq-core/cirq/study/result.py, cirq-core/cirq/study/result_test.py, cirq-google/cirq_google/api/v2/results.py, cirq-google/cirq_google/api/v2/results_test.py, cirq-google/cirq_google/engine/engine_job.py
=> Deprecate from_single_parameter_set on Result

cirq-core/cirq/_compat.py, cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/contrib/qasm_import/_parser.py, cirq-core/cirq/contrib/quantum_volume/quantum_volume.py, cirq-core/cirq/contrib/routing/greedy.py, cirq-core/cirq/devices/grid_qubit.py, cirq-core/cirq/experiments/cross_entropy_benchmarking.py, cirq-core/cirq/experiments/xeb_fitting.py, cirq-core/cirq/linalg/predicates.py, cirq-core/cirq/ops/eigen_gate.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/circuit_diagram_info_protocol.py, cirq-core/cirq/qis/clifford_tableau.py, cirq-core/cirq/sim/state_vector.py, cirq-core/cirq/study/result.py, cirq-core/cirq/study/sweeps.py, cirq-core/cirq/testing/circuit_compare.py, cirq-core/cirq/work/observable_measurement.py, cirq-core/cirq/work/sampler.py, cirq-google/cirq_google/api/v1/programs.py, cirq-google/cirq_google/calibration/phased_fsim.py, cirq-google/cirq_google/engine/calibration.py, cirq-google/cirq_google/engine/client/quantum_v1alpha1/gapic/transports/quantum_engine_service_grpc_transport.py, cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/optimizers/two_qubit_gates/gate_compilation.py, cirq-google/cirq_google/serialization/op_serializer.py, cirq-ionq/cirq_ionq/ionq_client.py
Believe this is the last of the lint.
* Note that `GridQid` needed to use a raw string due to the `\n` in the text.
Fixes: #3388
=> Fix remaining documentation lint

cirq-core/cirq/ion/ion_device.py, cirq-core/cirq/ion/ion_device_test.py
=> Enforce LineQubit type for IonDevices

cirq-core/cirq/__init__.py, cirq-core/cirq/optimizers/__init__.py, cirq-core/cirq/optimizers/transformer_primitives.py, cirq-core/cirq/optimizers/transformer_primitives_test.py
The PR introduces new transformer primitives -- `map_operations` and `map_moments`, as proposed in https://tinyurl.com/moment-preserving-transformers.
Part of roadmap item #3237 and #4483
=> Add `map_operations` and `map_moments` transformer primitives

cirq-core/cirq/protocols/json_serialization.py, cirq-core/cirq/protocols/json_serialization_test.py
Fixes a backwards-incompatibility in #4704.
This alternate return path is necessary until the deprecation cycle for this change is complete.
=> Don't invoke json_cirq_type if cirq_type is defined...for now.

cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/circuit_operation_test.py, cirq-core/cirq/contrib/routing/router.py, cirq-core/cirq/interop/quirk/cells/input_rotation_cells.py, cirq-core/cirq/linalg/decompositions_test.py, cirq-core/cirq/ops/common_gate_families_test.py, cirq-core/cirq/ops/state_preparation_channel_test.py, cirq-core/cirq/optimizers/clifford_decomposition.py, cirq-core/cirq/protocols/json_serialization_test.py, cirq-core/cirq/testing/consistent_controlled_gate_op.py, cirq-core/cirq/testing/no_identifier_qubit.py, cirq-core/cirq/value/measurement_key_test.py, cirq-google/cirq_google/calibration/phased_fsim.py, cirq-google/cirq_google/calibration/workflow.py, cirq-ionq/cirq_ionq/service.py, cirq-rigetti/cirq_rigetti/aspen_device.py, dev_tools/conf/.pylintrc, dev_tools/modules_test.py
Use plain strings when brace expansion is not needed.
=> pylint - enable check for f-string-without-interpolation

check/pylint-changed-files, check/pytest-changed-files, check/pytest-changed-files-and-incremental-coverage
Store changed paths in bash arrays by splitting diff output at newlines.
Avoid scalars that need to be split and may perform wildcard expansion.
Ref: https://www.baeldung.com/linux/reading-output-into-array#using-theread-command
=> Always use bash arrays for changed files and directories

cirq-core/cirq/linalg/operator_spaces.py, cirq-core/cirq/linalg/operator_spaces_test.py
Fix dimensionality of initial array in kron_bases.
This was causing failures when working with zero-qubit gates: empty pauli strings, Identity(0), and the new GlobalPhaseGate.
cc @viathor to review
=> Fix operator_spaces.py::kron_bases initial value

check/format-incremental
Split diff output at newlines and avoid storing files in a scalar that
needs to be split and may do wildcard expansion.  Simplify diff output
processing.  When formatting all files include only git-known sources.
=> format-incremental - store modified files in bash array

cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/ops/gateset.py, cirq-core/cirq/protocols/json_test_data/Gateset.json, cirq-core/cirq/protocols/json_test_data/Gateset.repr, cirq-core/cirq/protocols/json_test_data/spec.py
This PR adds json serialization to `cirq.Gateset` objects. This is made possible after the recent #4715 which adds serialization support for `cirq.GateFamily`'s.
=> Support serialization of Gatesets

cirq-google/cirq_google/engine/engine.py, cirq-google/cirq_google/engine/engine_sampler.py, cirq-google/cirq_google/engine/engine_sampler_test.py, cirq-google/cirq_google/engine/engine_test.py, cirq-google/cirq_google/serialization/serializable_gate_set.py, cirq-google/cirq_google/serialization/serializable_gate_set_test.py
=> Support FrozenCircuit in`cg.Engine`

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_test.py, cirq-core/cirq/ops/moment.py, cirq-core/cirq/ops/moment_test.py
=> Add missing `_has_*_` methods

cirq-core/cirq/ops/swap_gates_test.py
Fix scipy.linalg import that broke pytest-changed-files in github.
=> Fix scipy.linalg import in swap_gates_test

dev_tools/requirements/deps/format.txt
The old version of `black` started producing the following error when calling `check/format-incremental --apply`:
```
ImportError: {...}/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so:
undefined symbol: _PyUnicode_DecodeUnicodeEscape
```
Upgrading resolves the issue.
=> Upgrade pinned `black` version

cirq-core/cirq/circuits/circuit.py, cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/frozen_circuit.py, cirq-core/cirq/contrib/qcircuit/qcircuit_diagram.py, cirq-core/cirq/contrib/quimb/mps_simulator.py, cirq-core/cirq/ops/classically_controlled_operation.py, cirq-core/cirq/ops/gate_operation.py, cirq-core/cirq/ops/kraus_channel.py, cirq-core/cirq/ops/measure_util.py, cirq-core/cirq/ops/measurement_gate.py, cirq-core/cirq/ops/mixed_unitary_channel.py, cirq-core/cirq/ops/moment.py, cirq-core/cirq/ops/pauli_measurement_gate.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/measurement_key_protocol.py, cirq-core/cirq/sim/act_on_args.py, cirq-core/cirq/sim/act_on_args_container.py, cirq-core/cirq/sim/act_on_density_matrix_args.py, cirq-core/cirq/sim/act_on_state_vector_args.py, cirq-core/cirq/sim/clifford/act_on_clifford_tableau_args.py, cirq-core/cirq/sim/clifford/act_on_stabilizer_ch_form_args.py, cirq-core/cirq/sim/clifford/clifford_simulator.py, cirq-core/cirq/sim/clifford/stabilizer_sampler.py, cirq-core/cirq/sim/density_matrix_simulator.py, cirq-core/cirq/sim/mux.py, cirq-core/cirq/sim/simulator.py, cirq-core/cirq/sim/simulator_base.py, cirq-core/cirq/sim/sparse_simulator.py, cirq-core/cirq/sim/state_vector.py, cirq-core/cirq/sim/state_vector_simulator.py
There was an issue where docs were not showing types if they were not annotated in the 'cirq.MyType' style. I went through cirq.sim and fixed all the ones I noticed.
I also went ahead and fixed `value.MeasurementKey` across the whole project, since that was a very common one.
=> Sanitize type annotations in cirq.sim

cirq-core/cirq/ops/classically_controlled_operation.py, docs/dev/serialization.md
The `_json_dict_` method of `ClassicallyControlledOperation` contains a `cirq_type` key, which causes a deprecation warning:
https://github.com/quantumlib/Cirq/blob/01ae51eebf3b18a5cbee9fc0c697d4e1511c07f2/cirq-core/cirq/protocols/json_serialization.py#L281-L288
It is easy to fix by removing this item. Nevertheless, the real problem is in the manual for serialization, which says:
https://github.com/quantumlib/Cirq/blob/01ae51eebf3b18a5cbee9fc0c697d4e1511c07f2/docs/dev/serialization.md?plain=1#L91-L95
It says a `cirq_type` is required, which contradicts the code. To avoid confusing developers in the future, I have modified it.
close #4763
=> Fix the deprecation warning for `ClassicallyControlledOperation`

cirq-google/cirq_google/devices/specifications/__init__.py, cirq-google/cirq_google/engine/__init__.py, cirq-google/setup.py
- Add virtual_engine_factory to cirq_google.engine namespace
- Add device/specifications to package_files so that device templates
are packaged.
=> Adding files for virtual emulation

cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py
This makes the implementation of `_unitary_` method on `TaggedOperation` consistent with other protocols like `_mixture_` and `_kraus_`.
=> Use `NotImplemented` instead of `None` as default value for `TaggedOperation._unitary_`

cirq-core/cirq/ops/boolean_hamiltonian_test.py, cirq-core/cirq/transformers/transformer_primitives_test.py
Avoid conversion of ragged nested sequences to numpy array.
Use simple equality check to compare lists of tuples.
Use RandomState.choice to get item index instead of the item itself
which implies conversion to numpy.array.
Fixes  check/pytest -Werror:'Creating an ndarray from ragged'
=> Fix warning on array creation from ragged sequences

cirq-aqt/cirq_aqt/aqt_sampler.py, cirq-core/cirq/experiments/single_qubit_readout_calibration_test.py, cirq-core/cirq/sim/clifford/stabilizer_sampler.py, cirq-core/cirq/sim/mux.py, cirq-core/cirq/sim/simulator.py, cirq-core/cirq/work/sampler.py, cirq-core/cirq/work/sampler_test.py, cirq-google/cirq_google/api/v2/results.py, cirq-google/cirq_google/engine/abstract_job.py, cirq-google/cirq_google/engine/abstract_local_job_test.py, cirq-google/cirq_google/engine/engine_job.py, cirq-google/cirq_google/engine/engine_sampler.py, cirq-google/cirq_google/engine/simulated_local_job.py, cirq-google/cirq_google/engine/validating_sampler.py, cirq-ionq/cirq_ionq/sampler.py, cirq-rigetti/cirq_rigetti/circuit_sweep_executors.py, cirq-rigetti/cirq_rigetti/qcs_sampler_and_service_test.py, cirq-rigetti/cirq_rigetti/sampler.py
`Sequence` is a covariant type (`Sequence[A]` is a subclass of `Sequence[B]` when `A` is a subclass of `B`) while `List`, because it is mutable, is invariant (`List[A]` is not a subclass of `List[B]` even if `A` is a subclass of `B`). Returning `Sequence[cirq.Result]` thus allows returning subtypes of `cirq.Result`, while `List[cirq.Result]` does not.
We change `cirq.Sampler` methods `run_sweep` and `run_batch` to return `Sequence[cirq.Result]` and `Sequence[Sequence[cirq.Result]]`, respectively, which makes it possible to return result subtypes if desired, as needed in #4806.
=> Change Sampler methods to return Sequence instead of List

cirq-core/cirq/__init__.py, cirq-core/cirq/neutral_atoms/convert_to_neutral_atom_gates.py, cirq-core/cirq/optimizers/__init__.py, cirq-core/cirq/optimizers/convert_to_cz_and_single_gates.py, cirq-core/cirq/optimizers/merge_interactions.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/analytical_decompositions/__init__.py, cirq-core/cirq/transformers/analytical_decompositions/three_qubit_decomposition.py, cirq-core/cirq/transformers/analytical_decompositions/three_qubit_decomposition_test.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_cz.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_cz_test.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_fsim_test.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_sqrt_iswap.py, cirq-core/cirq/transformers/analytical_decompositions/two_qubit_to_sqrt_iswap_test.py
Moves the following files from `cirq/optimizers/` to `cirq/transformers/analytical_decompositions/` using `deprecated_submodule`:
- two_qubit_decompositions.py --> two_qubit_to_cz.py
- two_qubit_to_fsim.py
- two_qubit_to_sqrt_iswap.py
- three_qubit_decomposition.py
Part of #4722
=> Move two/three qubit decompositions from `optimizers/` to `transformers/analytical_decompositions`

cirq-core/cirq/vis/density_matrix.py, cirq-core/cirq/vis/density_matrix_test.py
The plotting positions were dividing by cell size instead of multiplying, fixed that.
Closes #4804.
=> Density Matrix plotting is being fixed

cirq-core/cirq/optimizers/__init__.py
After the recent migration of decompositions from `optimizers/*` to `transformers/analytical_decompositions/*`, the following user code breaks despite deprecating the moved submodules. 
```python
from cirq import optimizers
from cirq.optimizers import two_qubit_decompositions
_ = two_qubit_decompositions.two_qubit_matrix_to_operations(mat) # This is deprecated correctly and will emit a deprecation warning but work as expected.
_ = optimizers.two_qubit_matrix_to_operations(mat) # This would currently break since the optimizers module is neither deprecated nor has these top-level objects available
```
This PR adds a fix to temporarily unbreak the above user code by importing top-level objects from `transformers/analytical_decompositions/*` to `optimizers/*`. Once all files from …
=> Import `transformers/analytical_decompositions/*` methods in `optimizers/*`

cirq-core/cirq/experiments/cross_entropy_benchmarking_test.py, cirq-core/cirq/experiments/qubit_characterizations_test.py, cirq-core/cirq/experiments/t1_decay_experiment_test.py, cirq-core/cirq/experiments/t2_decay_experiment_test.py, cirq-core/cirq/linalg/decompositions_test.py, cirq-core/cirq/vis/density_matrix_test.py, cirq-core/cirq/vis/heatmap_test.py, cirq-core/cirq/vis/histogram_test.py, cirq-core/cirq/vis/state_histogram_test.py, cirq-google/cirq_google/engine/calibration_test.py, cirq-google/cirq_google/optimizers/two_qubit_gates/example_test.py, conftest.py, examples/examples_test.py
Add test fixture that cleans up any open matplotlib figures and
plug it in the tests that open new figures.
Fix RuntimeWarning: More than 20 figures have been opened.
=> Close matplotlib figures after testing

cirq-core/cirq/ops/pauli_measurement_gate.py, cirq-core/cirq/ops/pauli_measurement_gate_test.py, cirq-core/cirq/protocols/json_test_data/PauliMeasurementGate.json, cirq-core/cirq/protocols/json_test_data/PauliMeasurementGate.json_inward, cirq-core/cirq/protocols/json_test_data/PauliMeasurementGate.repr, cirq-core/cirq/protocols/json_test_data/PauliMeasurementGate.repr_inward
Fixes #4814 
Note that this is a breaking change because:
- Serialization of the `PauliMeasurementGate` is now different -- the serialized observable is `DensePauliString` instead of a tuple of Pauli's.
-  A DensePauliString with coefficient != +1/-1 will now raise a `ValueError` whereas earlier the coefficient was simply ignored.
=> Make `PauliMeasurementGate` respect sign of the pauli observable.

cirq-core/cirq/devices/device.py, cirq-core/cirq/devices/device_test.py
=> Update equalstester in DeviceMetadata.

CONTRIBUTING.md
Might be helpful to add a section in CONTRIBUTING.md to describe dev environment setup as it could be one of the first docs contributors look at. WDYT?
edit: Just found links to development.md elsewhere in the doc. Do you think it makes sense to have a dedicated section, to make it obvious where to look for dev environment setup?
=> Add link to dev environment page in CONTRIBUTING.md

cirq-core/cirq/experiments/cross_entropy_benchmarking.py
Closes #2757.
The "exp" suffix may be interpreted as either "experimental" or "expected" (as in "theoretically expected") which causes confusion that led to #2757. This PR changes the suffix to "th" (for "theoretical") which happens to be what is already used in the docstring. Also, added some missing docstrings.
=> Improve consistency between code and docstrings for XEB

cirq-google/cirq_google/engine/abstract_processor.py, cirq-google/cirq_google/engine/engine_processor.py, cirq-google/cirq_google/engine/engine_processor_test.py, cirq-google/cirq_google/engine/simulated_local_processor.py
- mypy and pycharm need a default value in the abstract interface
in order to be truly optional.
- Also, add a copy of the inherited arguments in
SimulatedLocalProcessor.
=> Make gate_sets actually optional

cirq-core/cirq/value/value_equality_attr.py, cirq-core/cirq/value/value_equality_attr_test.py
Fixes https://github.com/quantumlib/Cirq/issues/4834
=> Fix `_value_equality_values_cls_` handling in `_value_equality_approx_eq`

cirq-core/cirq/ops/dense_pauli_string.py, cirq-core/cirq/ops/dense_pauli_string_test.py
Fixes https://github.com/quantumlib/Cirq/issues/4837
=> Make `BaseDensePauliString` an iterable class.

cirq-core/cirq/ops/parity_gates.py
Part of https://github.com/quantumlib/Cirq/issues/4858
Decompositions are tested as part of `assert_eigengate_implements_consistent_protocols`, which is already tested for both gates.
=> Add default decompositions for `XXPowGate` and `YYPowGate` which terminate in `CZPowGate`.

dev_tools/requirements/deps/notebook.txt, dev_tools/requirements/deps/pytest.txt
It looks like there is some weird interactions involving `coverage==6.2` -> 6.3 and `notebook==6.4.7` -> 6.4.8. This pins them back.
Opened: https://github.com/quantumlib/Cirq/issues/4897
=> Fix coverage CI break.

cirq-core/cirq/linalg/transformations.py, cirq-core/cirq/linalg/transformations_test.py
=> Increase atol for sub_state_vector()

cirq-core/cirq/__init__.py, cirq-core/cirq/circuits/__init__.py, cirq-core/cirq/contrib/__init__.py, cirq-core/cirq/devices/__init__.py, cirq-core/cirq/experiments/__init__.py, cirq-core/cirq/interop/__init__.py, cirq-core/cirq/ion/__init__.py, cirq-core/cirq/json_resolver_cache.py, cirq-core/cirq/linalg/__init__.py, cirq-core/cirq/neutral_atoms/__init__.py, cirq-core/cirq/ops/__init__.py, cirq-core/cirq/optimizers/__init__.py, cirq-core/cirq/protocols/__init__.py, cirq-core/cirq/qis/__init__.py, cirq-core/cirq/sim/__init__.py, cirq-core/cirq/study/__init__.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/type_workarounds.py, cirq-core/cirq/value/__init__.py, cirq-core/cirq/vis/__init__.py
* Trying to avoid "types and methods" and be more descriptive.  
* Updated top level doc string.
* See go/q-stage for how this renders.
=> Update top level module documentation

cirq-google/cirq_google/engine/engine_validator_test.py
Uses a generated big circuit instead of a random big circuit.
This should remove the 0.4% flakes of the original test.
=> Change engine_validator_test to be deterministic.

cirq-core/cirq/transformers/transformer_primitives.py, cirq-core/cirq/transformers/transformer_primitives_test.py
- Add support for deleting an operation 
- Add support for adding operations which act on qubits outside of `op.qubits` -- This requires passing an explicit flag for use cases like https://github.com/quantumlib/Cirq/pull/4849
- Fixes type annotation for `map_moments` to accept a single modified moment or a sequence of moments.
=> Support adding qubits and deleting operations in `cirq.map_operations`.

cirq-core/cirq/sim/density_matrix_simulator.py, cirq-core/cirq/sim/density_matrix_simulator_test.py, cirq-core/cirq/sim/sparse_simulator.py, cirq-core/cirq/sim/sparse_simulator_test.py
It was accepted at cirq sync that these are vestigial functions from a time when we didn't have initial_state or custom gates or classical controls that could be used for this. Now that we have all these, we can remove this function.
Fixes #4830
=> Deprecate set_state_vector and set_density_matrix

cirq-core/cirq/sim/__init__.py
`deprecate_attributes` replaces standard Python module with a wrapper
that modifies attribute access.  Avoid unless truly needed.
=> Clean up redundant use of `_deprecate_attributes`

cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py
Fixes: https://github.com/quantumlib/Cirq/issues/4914
=> Change `TaggedOperation`'s `__pow__` from returning `Operation` to returning `TaggedOperation` 

cirq-core/cirq/__init__.py, cirq-core/cirq/optimizers/synchronize_terminal_measurements.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/synchronize_terminal_measurements.py, cirq-core/cirq/transformers/synchronize_terminal_measurements_test.py, docs/tutorials/google/spin_echoes.ipynb
- Part of https://github.com/quantumlib/Cirq/issues/4722
- Follows the new Transformer API https://github.com/quantumlib/Cirq/issues/4483
- Supports no compile tags NoCompile Tag for optimizers #4253
- Fixes #4907
=> Add `synchronize_terminal_measurements` transformer to replace `SynchronizeTerminalMeasurements`

cirq-core/cirq/__init__.py, cirq-core/cirq/contrib/paulistring/convert_gate_set.py, cirq-core/cirq/contrib/quimb/Cirq-to-Tensor-Networks.ipynb, cirq-core/cirq/contrib/quimb/Contract-a-Grid-Circuit.ipynb, cirq-core/cirq/contrib/quimb/density_matrix_test.py, cirq-core/cirq/contrib/quimb/grid_circuits.py, cirq-core/cirq/ops/pauli_string_phasor_test.py, cirq-core/cirq/optimizers/drop_empty_moments.py, cirq-core/cirq/optimizers/drop_negligible.py, cirq-core/cirq/optimizers/eject_z_test.py, cirq-core/cirq/optimizers/expand_composite_test.py, cirq-core/cirq/optimizers/merge_interactions_test.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap_test.py, cirq-core/cirq/optimizers/merge_single_qubit_gates_test.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/analytical_decompositions/three_qubit_decomposition.py, cirq-core/cirq/transformers/drop_empty_moments.py, cirq-core/cirq/transformers/drop_empty_moments_test.py, cirq-core/cirq/transformers/drop_negligible_operations.py, cirq-core/cirq/transformers/drop_negligible_operations_test.py, cirq-google/cirq_google/optimizers/optimize_for_sycamore.py, dev_tools/notebooks/isolated_notebook_test.py, docs/tutorials/google/spin_echoes.ipynb
- Replaces `DropEmptyMoments` and `DropNegligible` optimizers.
- Part of Organization (and deprecation) of cirq-core/optimizers in cirq-core/transformers #4722
- Follows the new Transformer API Compiling: Circuit Transformers API #4483
- Supports no compile tags NoCompile Tag for optimizers NoCompile Tag for optimizers #4253
=> Add `drop_empty_moments` and `drop_negligible_operations` transformers.

docs/tutorials/google/start.ipynb
=> Missing cirq_google import in command line QCS example

cirq-core/cirq/ops/gate_operation.py
Fix for issue #4766 
Also, Introduced more idiomatic code for group_interchangeable_qubits implementation.
=> Use group_interchangeable_qubits for qubit comparison in GateOperation

cirq-pasqal/cirq_pasqal/pasqal_device.py, cirq-pasqal/cirq_pasqal/pasqal_device_test.py
Also adds the metadata field to devices. More of #4744 .
=> deprecate device.qubit_set in cirq_pasqal.

cirq-core/cirq/__init__.py, cirq-core/cirq/contrib/acquaintance/bipartite_test.py, cirq-core/cirq/contrib/acquaintance/gates_test.py, cirq-core/cirq/contrib/acquaintance/mutation_utils.py, cirq-core/cirq/contrib/acquaintance/mutation_utils_test.py, cirq-core/cirq/contrib/acquaintance/optimizers_test.py, cirq-core/cirq/contrib/acquaintance/permutation.py, cirq-core/cirq/contrib/acquaintance/permutation_test.py, cirq-core/cirq/contrib/acquaintance/shift_test.py, cirq-core/cirq/ops/pauli_string_phasor_test.py, cirq-core/cirq/optimizers/expand_composite.py, cirq-core/cirq/transformers/__init__.py, cirq-core/cirq/transformers/expand_composite.py, cirq-core/cirq/transformers/expand_composite_test.py
- Part of https://github.com/quantumlib/Cirq/issues/4722
- Follows the new Transformer API https://github.com/quantumlib/Cirq/issues/4483
- Supports no compile tags NoCompile Tag for optimizers https://github.com/quantumlib/Cirq/issues/4253
=> Add `expand_composite` transformer to replace `ExpandComposite` optimizer

cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py
=> Revert "Change `TaggedOperation`'s `__pow__` from returning `Operation` to returning `TaggedOperation` "

dev_tools/notebooks/isolated_notebook_test.py, docs/tutorials/google/start.ipynb
This significantly speeds up the startup experience because we don't have to install all the other packages in the cirq metapackage. In testing just now installing `cirq-google` took about 7 seconds in colab, whereas installing `cirq` took about 30 seconds.
=> In QCS getting started, only install cirq-google

.github/CODEOWNERS, dev_tools/codeowners_test.py, docs/dev/development.md
Getting ready for docs work by making a quick update to the dev instructions and codeowners.
=> Update documentation development instructions and codeowners

cirq-core/cirq/sim/act_on_args.py, cirq-core/cirq/sim/act_on_args_container.py, cirq-core/cirq/sim/act_on_args_container_test.py, cirq-core/cirq/sim/act_on_args_test.py
=> Replace fields with properties in ActOnArgs

cirq-core/cirq/transformers/transformer_primitives.py, cirq-core/cirq/transformers/transformer_primitives_test.py
Fixes a bug where `cirq.merge_moments` would treat a newly merged empty `cirq.Moment()` as the case where we return `None` to indicate that two moments cannot be merged.
=> BugFix in `cirq.merge_moments` to correctly handle new empty moments.

cirq-core/cirq/testing/circuit_compare.py, cirq-core/cirq/testing/circuit_compare_test.py
=> Sets tolerance to 1.0e-8 by default in equivalence assertion

cirq-google/cirq_google/engine/client/quantum_v1alpha1/gapic/quantum_engine_service_client.py
Prefetching doesn't work because the service does not send any messages until after the user has sent at least one request. It seems prefetching was added in gapic 1.17.0 and broke some other streaming APIs such as pubsub (https://github.com/googleapis/python-api-core/issues/25). This changes follows the official workaround, which is unfortunately pretty hacky (https://github.com/googleapis/python-api-core/pull/30).
@wcourtney, @verult
=> Update quantum_run_stream to not prefetch first result

cirq-google/cirq_google/engine/engine_client.py
Other helpers had already been converted to use f-strings.
=> Use f-strings consistently in engine_client.py helpers

cirq-core/cirq/optimizers/merge_interactions.py, cirq-core/cirq/optimizers/merge_interactions_test.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap.py, cirq-core/cirq/optimizers/merge_interactions_to_sqrt_iswap_test.py, cirq-google/cirq_google/optimizers/convert_to_sqrt_iswap.py, cirq-google/cirq_google/optimizers/convert_to_sqrt_iswap_test.py, cirq-google/cirq_google/optimizers/optimize_for_sycamore.py
- Deprecates `cirq_google.ConvertToSqrtIswapGates` and `cirq.MergeInteractionsToSqrtIswap` and replaces them with `cirq.SqrtIswapTargetGateset` introduced in https://github.com/quantumlib/Cirq/pull/5025
- Part of https://github.com/quantumlib/Cirq/issues/4722
- Part of https://github.com/quantumlib/Cirq/issues/5028
- Follows the new Transformer API https://github.com/quantumlib/Cirq/issues/4483
- Supports no compile tags NoCompile Tag for optimizers https://github.com/quantumlib/Cirq/issues/4253
=> Deprecate `cirq_google.ConvertToSqrtIswapGates` and `cirq.MergeInteractionsToSqrtIswap`

cirq-google/cirq_google/__init__.py, cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py, cirq-google/cirq_google/optimizers/convert_to_sycamore_gates_test.py, cirq-google/cirq_google/transformers/__init__.py, cirq-google/cirq_google/transformers/analytical_decompositions/__init__.py, cirq-google/cirq_google/transformers/analytical_decompositions/two_qubit_to_sycamore.py, cirq-google/cirq_google/transformers/analytical_decompositions/two_qubit_to_sycamore_test.py
- Refactors `cirq_google.optimizers.convert_to_sycamore_gates` to abstract out analytical decomposition methods in a separate module `cirq_google.transformers.analytical_decompositions.two_qubit_to_sycamore_gates`.
- Also added new tests, improved docstrings etc.
- This is consistent with the new organization and naming structure in cirq-core, as introduced in https://github.com/quantumlib/Cirq/issues/4722
- Part-1 of migrating `cirq_google.ConvertToSycamoreGates` to the new transformer infrastructure, as part of https://github.com/quantumlib/Cirq/issues/5028
=> Refactors `convert_to_sycamore_gates` to abstract out analytical decomposition methods in `cirq_google.two_qubit_to_sycamore`

cirq-core/cirq/study/sweeps.py, cirq-core/cirq/value/abc_alt_test.py, dev_tools/check.py
Fixes: https://github.com/quantumlib/Cirq/issues/554
=> Add type annotations to method overrides in child classes

cirq-core/requirements.txt
Part of #5058. The latest sympy release (v1.10) appears to have broken our mypy tests: #4936, #4964, #5030
Pinning until we can bring ourselves up to date (assuming that's what we want to do here)
=> Pin sympy version to <1.10

cirq-core/cirq/contrib/paulistring/clifford_optimize.py
Fixes #2962
@dabacon hunch was correct. The coefficient is initialized at 1, and can only be negated. Changed the error to an assertion accordingly,
https://github.com/quantumlib/Cirq/blob/9cefed8c384dc8a6751e4fe114873bf349160721/cirq-core/cirq/ops/pauli_string.py#L946
Update: Removed the assertion entirely since that assertion already exists in `PauliStringPhasor.__init__`
=> Change ValueError to assertion in clifford_optimize

docs/tutorials/google/start.ipynb
- Use Circuit.transform_qubits instead of cg.optimize_for_sycamore, since all we need to do is change qubits.
- Don't specify a gate_set, which will use CircuitSerializer by default.
- Use standard string representation of cirq.Result.
- Remove unused imports.
=> Update getting started notebook

cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/protocols/decompose_protocol_test.py
This is an attempt to fix #5052
=> Call decompose_once in TaggedOperation

cirq-core/cirq/ops/controlled_gate.py, cirq-core/cirq/ops/controlled_gate_test.py, cirq-core/cirq/ops/controlled_operation.py, cirq-core/cirq/ops/controlled_operation_test.py, cirq-core/cirq/ops/measurement_gate.py, cirq-core/cirq/ops/measurement_gate_test.py
Change public fields to private, and encapsulate with getters and deprecated setters.
xref #4851
=> Remove public fields for measurement and controlled ops

cirq-core/cirq/ops/fourier_transform.py, cirq-core/cirq/ops/fourier_transform_test.py, cirq-core/cirq/ops/permutation_gate.py, cirq-core/cirq/ops/permutation_gate_test.py, cirq-core/cirq/ops/random_gate_channel.py, cirq-core/cirq/ops/random_gate_channel_test.py, cirq-core/cirq/ops/raw_types.py, cirq-core/cirq/ops/raw_types_test.py, cirq-core/cirq/ops/wait_gate.py, cirq-core/cirq/ops/wait_gate_test.py
Change public fields to private, and encapsulate with getters and deprecated setters.
xref #4851
=> Remove public fields from subop gates and ops

cirq-core/cirq/_compat.py, cirq-core/cirq/ops/clifford_gate.py, cirq-core/cirq/ops/dense_pauli_string.py, cirq-core/cirq/ops/dense_pauli_string_test.py, cirq-core/cirq/testing/deprecation.py
https://github.com/quantumlib/Cirq/issues/4851 for `DensePauliString`. This was *slightly* less straightforward than others.
* Required moving `ALLOW_DEPRECATION_IN_TEST` or else a circular dependency was created.
* One place externally where setting the field still was necessary. (A factory method in `CliffordGate`).
* One member is of type `ndarray`, which is mutable, so we set `flags.writeable = False`
=> Wrap private fields for DensePauliString

cirq-core/cirq/ops/pauli_interaction_gate.py, cirq-core/cirq/ops/pauli_interaction_gate_test.py, cirq-core/cirq/ops/pauli_measurement_gate.py, cirq-core/cirq/ops/pauli_measurement_gate_test.py, cirq-core/cirq/ops/pauli_string_raw_types.py, cirq-core/cirq/ops/pauli_string_raw_types_test.py
https://github.com/quantumlib/Cirq/issues/4851 for all the pauli stuff.
I skipped BaseDensePauliString because including `cirq._compat` there makes a weird circular dependency.
=> Remove public fields for pauli ops

cirq-core/cirq/ops/fsim_gate.py, cirq-core/cirq/ops/fsim_gate_test.py
Change public fields to private, and encapsulate with getters and deprecated setters.
Closes #4851
=> Remove public fields from fsim

cirq-core/cirq/linalg/transformations.py, cirq-core/cirq/sim/state_vector_test.py
The `validate` block here did not account for the possibility of a phase shift. It was just luck that `H(q0), I(q1)` factorization in the test did not cause one. Also there's no need to transpose the axes here, just compare `t1` and `t2` directly.
=> Fix state vector factorization validation

cirq-google/cirq_google/__init__.py, cirq-google/cirq_google/json_test_data/spec.py, cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py, cirq-google/cirq_google/optimizers/convert_to_sycamore_gates_test.py, cirq-google/cirq_google/optimizers/optimize_for_sycamore.py, cirq-google/cirq_google/transformers/__init__.py, cirq-google/cirq_google/transformers/target_gatesets/__init__.py, cirq-google/cirq_google/transformers/target_gatesets/sycamore_gateset.py, cirq-google/cirq_google/transformers/target_gatesets/sycamore_gateset_test.py
- Part of https://github.com/quantumlib/Cirq/issues/5028
- Follows the new Transformer API https://github.com/quantumlib/Cirq/issues/4483
- Supports no compile tags NoCompile Tag for optimizers https://github.com/quantumlib/Cirq/issues/4253
=> Add `cg.SycamoreTargetGateset` and deprecate `cg.ConvertToSycamoreGates`

cirq-core/cirq/linalg/transformations.py, cirq-core/cirq/linalg/transformations_test.py, cirq-core/cirq/sim/state_vector_test.py
Add handling for qudits within `partial_trace_of_state_vector_as_mixture`
Fixes #3003
=> Allow partial state vector function to handle qudits

cirq-core/cirq/circuits/circuit_operation.py, cirq-core/cirq/circuits/circuit_operation_test.py, cirq-core/cirq/sim/density_matrix_simulator_test.py, cirq-core/cirq/transformers/measurement_transformers_test.py, cirq-google/cirq_google/serialization/op_serializer.py, cirq-google/cirq_google/serialization/op_serializer_test.py
Since recursive parameter resolution is now working (#5033) we can do this now.
The biggest caveat with this code is that params are floats, and repetitions must be an integer. I added a new type IntParam for the `repetitions` field itself, but it's still possible for the resolver to put a float value there. I added a runtime check for that. It may make sense to allow floats if they're really close to an integer, but I didn't do that here yet.
Closes #3266
=> Allow repetitions to be parameterized

cirq-core/cirq/ops/measurement_gate.py
Add a return type annotation on `MeasurementGate.full_invert_mask`, which returns a tuple of the same length as the number of qubits. This is in contrast to the invert mask itself, which can be specified as a partial mask for just some of the qubits.
=> Add return type annotation on MeasurementGate.full_invert_mask

cirq-core/cirq/protocols/decompose_protocol.py, cirq-core/cirq/testing/__init__.py, cirq-core/cirq/testing/consistent_decomposition.py, cirq-core/cirq/testing/consistent_decomposition_test.py
- Part-1 of https://github.com/quantumlib/Cirq/pull/5057
- The PR adds ` cirq.testing.assert_decompose_ends_at_default_gateset` which checks that if the given object (gate / operation) has a _decompose_ method defined, then it should always end up decomposing to the cirq default gateset.
- In subsequent PRs, this method will also be added to `cirq.testing.assert_implements_consistent_protocols` to extend the coverage of this test across all cirq objects. 
cc @MichaelBroughton
=> Add assert_decompose_ends_at_default_gateset consistency test

cirq-core/cirq/ops/phased_x_gate.py, cirq-core/cirq/ops/phased_x_gate_test.py
- Adds support for decomposing parameterized `cirq.PhasedXPowGate`s.
- Also modifies the decomposition to respect global phase, so that the decomposition is valid for controlled variants as well. 
=> Support decomposition of parameterized gates in cirq.PhasedXPowGate

cirq-core/cirq/circuits/quil_output_test.py, cirq-core/cirq/ops/two_qubit_diagonal_gate.py, cirq-core/cirq/ops/two_qubit_diagonal_gate_test.py
- Adds a default decomposition for `cirq.TwoQubitDiagonalGate` in terms of `X/Z/CZ`s
- Also supports parameterized gates. 
- Note that adding a decomposition changes pyquil output to X/Z/CZs instead of a custom DEFGATE USERGATE1, but this should be fine since both the outputs represent the same unitary action. 
- Part of #4858
=> Add default decomposition for cirq.TwoQubitDiagonalGate

cirq-core/cirq/ops/diagonal_gate.py, cirq-core/cirq/ops/diagonal_gate_test.py
- Adds support for decomposing parameterized `cirq.DiagonalGate`.
- Global phase is ignored for parameterized version because `cirq.GlobalPhaseGate` doesn't yet support symbols. 
=> Add support for decompositions of parameterized `cirq.DiagonalGate`

cirq-core/cirq/ops/controlled_gate.py, cirq-core/cirq/ops/matrix_gates.py, cirq-core/cirq/ops/matrix_gates_test.py, cirq-core/cirq/testing/consistent_decomposition.py
- Uses known analytical decompositions for matrix gates on 1/2/3 qubits. 
- Adds `cirq.MatrixGate` acting on > 3 qubits or on a qudit to set of known gates with no analytical decomposition in the `cirq.testing.assert_decompose_ends_at_default_gateset` test suite. 
=> Adds default decompositions for `cirq.MatrixGate` into X/Y/Z/CZ target gateset.

cirq-core/cirq/ops/three_qubit_gates.py, cirq-core/cirq/ops/three_qubit_gates_test.py
- The decomposition of cirq.CCZPowGate is generic enough already to support parameterized gates.
- This PR removes an unnecessary if condition to not decompose parameterized gates.
=> Add support for decompositions of parameterized `cirq.CCZPowGate`

cirq-google/cirq_google/workflow/quantum_executable.py, cirq-google/cirq_google/workflow/quantum_executable_test.py
For issue #4734. It was discussed there that the order of the keys should not matter.
=> Order of keys shouldn't matter when comparing cirq.google.KeyValueExecutableSpec

cirq-core/cirq/ops/controlled_gate.py, cirq-core/cirq/ops/controlled_gate_test.py, cirq-core/cirq/ops/controlled_operation.py, cirq-core/cirq/ops/controlled_operation_test.py, cirq-core/cirq/testing/consistent_decomposition.py
When decomposed, controlled gates and operations simply fall back on the decomposition of underlying sub_gate / sub_operation and return apply appropriate controls to each decomposed operation. 
If we can ensure that all underlying gates / operations decompose to X/Y/Z/CZ target gateset, then their controlled versions will decompose to:
- Multi controlled single qubit rotations (corresponding to (X/Y/Z).controlled_by(...)) OR
- Multi controlled CZs, which is also equivalent to a multi controlled single qubit rotation (Z.controlled_by(...))
In Cirq, we have an analytical method to decompose a multi controlled rotation into X/Y/Z/CZ - `cirq.decompose_multi_controlled_rotation`, which is now used in the `_decompose_` method of controlled gates. 
However, there are many corner cases and …
=> Extend default decomposition of `cirq.ControlledGate` and `cirq.ControlledOperation` to end in X/Y/Z/CZ target gateset

cirq-core/cirq/ops/permutation_gate.py, cirq-core/cirq/ops/permutation_gate_test.py
- Adds decomposition to `cirq.QubitPermutationGate` in terms of minimum number of adjacent swap operations on qubits. 
Closes https://github.com/quantumlib/Cirq/issues/5090
=> Add default decomposition for cirq.QubitPermutationGate in terms of adjacent swaps

cirq-core/cirq/transformers/transformer_primitives.py, cirq-core/cirq/transformers/transformer_primitives_test.py
- Part of fixing https://github.com/quantumlib/Cirq/issues/5039
- Fixes multiple bugs and improves support for `deep=True` flag in transformer primitives.
=> Improve support for recursively applying transformer primitives on circuit operations using `deep=True`

cirq-core/cirq/transformers/transformer_primitives.py, cirq-core/cirq/transformers/transformer_primitives_test.py
* Part of fixing https://github.com/quantumlib/Cirq/issues/5039
* Adds support for running transformer primitives inside subcircuits using `deep=True` to the following remaining transformer primitives:
* `cirq.merge_operations`
* `cirq.merge_operations_to_circuit_op`
* `cirq.merge_k_qubit_unitaries_to_circuit_op`
* `cirq.map_moments`
* `cirq.merge_moments`
=> Add support for `deep=True` flag to remaining transformer primitives

cirq-core/cirq/transformers/transformer_primitives.py, cirq-core/cirq/transformers/transformer_primitives_test.py
- Fixes a few more bugs in the handling of deep=True flag and nested operations to ignore using `tags_to_ignore` in `cirq.map_operations` and `cirq.map_moments` transformer primitives. Also added more tests. 
- Step towards fixing https://github.com/quantumlib/Cirq/issues/5039
=> Bugfixes in handling nested tags_to_ignore + deep=True in `cirq.map_moments` and `cirq.map_operations` transformer primitives

cirq-core/cirq/transformers/drop_empty_moments.py, cirq-core/cirq/transformers/drop_empty_moments_test.py
- Adds support to recursively run `cirq.drop_empty_moments` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
=> Add support for deep=True to `cirq.drop_empty_moments` transformer

cirq-core/cirq/transformers/drop_negligible_operations.py, cirq-core/cirq/transformers/drop_negligible_operations_test.py
- Adds support to recursively run `cirq.drop_negligible_operations` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
=> Add support for deep=True to `cirq.drop_negligible_operations` transformer

cirq-core/cirq/transformers/stratify.py, cirq-core/cirq/transformers/stratify_test.py
- Adds support to recursively run `cirq.stratified_circuit` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
=> Add support for deep=True to `cirq.stratified_circuit` transformer

cirq-core/cirq/transformers/synchronize_terminal_measurements.py, cirq-core/cirq/transformers/synchronize_terminal_measurements_test.py
- Adds support to recursively run `cirq.synchronize_terminal_measurements` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
=> Add support for deep=True to `cirq.synchronize_terminal_measurements` transformer

cirq-core/cirq/transformers/expand_composite.py, cirq-core/cirq/transformers/expand_composite_test.py
- Adds support to recursively run `cirq.expand_composite` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
- Note that this does not rely on `preserve_structure` argument of `protocols.decompose` because the latter does not support handling nested circuit operations tagged with a no-compile tag (the added tests would fail if we rely on protocols.decompose(preserve_structure=True) instead transformer primitives). Hence, I would argue that we should deprecate the preserve_structure=True flag in protocols.decompose in-favour of this transformer. cc @95-martin-orion 
=> Add support for deep=True to `cirq.expand_composite` transformer

cirq-core/cirq/transformers/eject_phased_paulis.py, cirq-core/cirq/transformers/eject_phased_paulis_test.py
- Adds support to recursively run `cirq.eject_phased_paulis` transformer on circuits wrapped inside a circuit operation by setting deep=True in transformer context.
=> Add support for deep=True to `cirq.eject_phased_paulis` transformer
